java_library(
    name = "exception",
    srcs = [
        "ErrorMessage.java",
        "GraknException.java",
        "Validator.java"
    ],
    deps = [
        "//dependencies/maven/artifacts/com/google/code/findbugs:annotations",
    ],
    visibility = ["//common:__subpackages__"],
)