java_library(
    name = "opencensus-api",
    exports = [
        "//external:jar/io/opencensus/opencensus-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


