java_library(
    name = "commons-httpclient",
    exports = [
        "//external:jar/commons-httpclient/commons-httpclient"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/commons-codec:commons-codec",
        "//dependencies/maven/artifacts/commons-logging:commons-logging"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


