java_library(
    name = "thrift_server",
    exports = [
        "//external:jar/com/thinkaurelius/thrift/thrift_server"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/lmax:disruptor",
        "//dependencies/maven/artifacts/org/apache/thrift:libthrift",
        "//dependencies/maven/artifacts/org/slf4j:slf4j_api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


