define

pokemon sub entity
    plays pokemon-with-type
    has pokedex-no
    has description
    has height
    has weight;

type-id sub attribute datatype long;
pokedex-no sub attribute datatype long;
description sub attribute datatype string;
height sub attribute datatype long;
weight sub attribute datatype long;

pokemon-type sub entity
    has description
    has type-id
    plays type-of-pokemon;

has-type sub relationship
    relates pokemon-with-type
    relates type-of-pokemon;
pokemon-with-type sub role;
type-of-pokemon sub role;
