java_library(
    name = "concurrentlinkedhashmap-lru",
    exports = [
        "//external:jar/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


