java_library(
    name = "concurrent-trees",
    exports = [
        "//external:jar/com/googlecode/concurrent-trees/concurrent-trees"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


