define

general-entity sub entity
	has resource
	has boolean-resource;

sub-entity sub general-entity;

#Resources
resource sub attribute datatype long;
boolean-resource sub attribute datatype boolean;

#Rules

rule-1 sub rule
when {
    $x isa general-entity, has resource > 0;
}
then {
    $x has boolean-resource true;
};

insert

#Data
$x isa sub-entity has resource 1;