define

#Roles

# Entity hierarchy
#
#                             role
#         role1       role2           role3          role4
#                       |
#                    subRole2

role1 sub role;
role2 sub role;
role3 sub role;
role4 sub role;

subRole2 sub role2;

#Entities

# Entity hierarchy
#
#                  entity
#                     |
#               noRoleEntity
#              /            \                                   \
#  singleRoleEntity(R3)   anotherSingleRoleEntity(R2)    yetAnotherSingleRoleEntity(R1)
#           |                   |
#   twoRoleEntity(R4)     anotherTwoRoleEntity(R3)
#                               |
#                         threeRoleEntity(R4)

noRoleEntity sub entity;

#plays in rel2, rel3
singleRoleEntity sub noRoleEntity
	plays role3;
#plays in rel2, rel3
twoRoleEntity sub singleRoleEntity
    plays role4;

#plays in rel1, rel2
anotherSingleRoleEntity sub noRoleEntity
    plays role2;
#plays in rel1, rel2, rel3
anotherTwoRoleEntity sub anotherSingleRoleEntity
    plays role3;
#plays in rel1, rel2, rel3
threeRoleEntity sub anotherTwoRoleEntity
    plays role4;

#plays in rel1
yetAnotherSingleRoleEntity sub noRoleEntity
	plays role1;


#Relations

relation1 sub relationship
	relates role1
	relates role2;

relation2 sub relationship
    relates role2
    relates role3;

relation3 sub relationship
    relates subRole2
    relates role3
    relates role4;

insert
$e isa noRoleEntity;
$x isa singleRoleEntity;
$y isa twoRoleEntity;
$z isa anotherTwoRoleEntity;
$u isa threeRoleEntity;
$v isa anotherSingleRoleEntity;
$q isa yetAnotherSingleRoleEntity;


