insert
  thing sub entity
    has-resource a-int
    has-resource a-boolean
    has-resource a-number
    has-resource a-string
    has-resource a-null;

a-int sub resource datatype long;
a-boolean sub resource datatype boolean;
a-number sub resource datatype double;
a-string sub resource datatype string;
a-null sub resource datatype string;