insert
  thing sub entity
    has a-int
    has a-boolean
    has a-number
    has a-string
    has a-null;

a-int sub resource datatype long;
a-boolean sub resource datatype boolean;
a-number sub resource datatype double;
a-string sub resource datatype string;
a-null sub resource datatype string;