const SchemaConceptMethods = require("./methods/SchemaConcept");
const RelationshipTypeMethods = require("./methods/RelationshipType");
const ConceptMethods = require("./methods/Concept");
const TypeMethods = require("./methods/Type");
const ThingMethods = require("./methods/Thing");
const AttributeMethods = require("./methods/Attribute");
const RelationshipMethods = require("./methods/Relationship");
const RuleMethods = require("./methods/Rule");
const RoleMethods = require("./methods/Role");
const AttributeTypeMethods = require("./methods/AttributeType");
const EntityTypeMethods = require("./methods/EntityType");
const ConceptProto = require("../service/Session/autogenerated/Concept_pb");

/**
 * This creates Concepts as Javascipt objects from GrpcConcept provided
 * @param {Object} txService Object implementing all the functionalities of gRPC Tx service as defined in grakn.proto
 */
function ConceptFactory(txService) {
  this.txService = txService;
}

ConceptFactory.prototype.createConcept = function createConcept(grpcConcept) {
  const conceptId = grpcConcept.getId();
  let state;
  switch (grpcConcept.getBasetype()) {
    case ConceptProto.Concept.BASE_TYPE.ENTITY:
      state = buildState(conceptId, ConceptMethods.ENTITY, this.txService);
      return Object.create(entityProto, state);
    case ConceptProto.Concept.BASE_TYPE.RELATION:
      state = buildState(conceptId, ConceptMethods.RELATIONSHIP, this.txService);
      return Object.create(relationshipProto, state);
    case ConceptProto.Concept.BASE_TYPE.ATTRIBUTE:
      state = buildState(conceptId, ConceptMethods.ATTRIBUTE, this.txService);
      return Object.create(attributeProto, state);
    case ConceptProto.Concept.BASE_TYPE.ENTITY_TYPE:
      state = buildState(conceptId, ConceptMethods.ENTITY_TYPE, this.txService);
      return Object.create(entityTypeProto, state);
    case ConceptProto.Concept.BASE_TYPE.RELATION_TYPE:
      state = buildState(conceptId, ConceptMethods.RELATIONSHIP_TYPE, this.txService);
      return Object.create(relationshipTypeProto, state);
    case ConceptProto.Concept.BASE_TYPE.ATTRIBUTE_TYPE:
      state = buildState(conceptId, ConceptMethods.ATTRIBUTE_TYPE, this.txService);
      return Object.create(attributeTypeProto, state);
    case ConceptProto.Concept.BASE_TYPE.ROLE:
      state = buildState(conceptId, ConceptMethods.ROLE, this.txService);
      return Object.create(roleProto, state);
    case ConceptProto.Concept.BASE_TYPE.RULE:
      state = buildState(conceptId, ConceptMethods.RULE, this.txService);
      return Object.create(ruleProto, state);
    case ConceptProto.Concept.BASE_TYPE.META_TYPE:
      state = buildState(conceptId, ConceptMethods.META_TYPE, this.txService);
      return Object.create(metaschemaProto, state);
    default:
      throw "BaseType not recognised.";
  }
}

function buildState(conceptId, baseType, txService) {
  return {
    id: { value: conceptId, enumerable: true },
    baseType: { value: baseType, enumerable: true },
    txService: { value: txService, enumerable: true }
  };
}

const attributeTypeProto = Object.assign(
  ConceptMethods.get(),
  SchemaConceptMethods.get(),
  TypeMethods.get(),
  AttributeTypeMethods.get()
);

const relationshipTypeProto = Object.assign(
  ConceptMethods.get(),
  SchemaConceptMethods.get(),
  TypeMethods.get(),
  RelationshipTypeMethods.get()
);

const entityTypeProto = Object.assign(
  ConceptMethods.get(),
  SchemaConceptMethods.get(),
  TypeMethods.get(),
  EntityTypeMethods.get()
);

const relationshipProto = Object.assign(
  ConceptMethods.get(),
  ThingMethods.get(),
  RelationshipMethods.get()
);

const attributeProto = Object.assign(
  ConceptMethods.get(),
  ThingMethods.get(),
  AttributeMethods.get()
);

const entityProto = Object.assign(
  ConceptMethods.get(),
  ThingMethods.get()
);

const roleProto = Object.assign(
  ConceptMethods.get(),
  SchemaConceptMethods.get(),
  RoleMethods.get()
);

const ruleProto = Object.assign(
  ConceptMethods.get(),
  SchemaConceptMethods.get(),
  RuleMethods.get()
);

const metaschemaProto = Object.assign(
  ConceptMethods.get(),
  SchemaConceptMethods.get(),
);

module.exports = ConceptFactory;
