java_library(
    name = "proto_google_common_protos",
    exports = [
        "//external:jar/com/google/api/grpc/proto_google_common_protos"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


