java_library(
    name = "proto-google-common-protos",
    exports = [
        "//external:jar/com/google/api/grpc/proto-google-common-protos"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


