java_library(
    name = "tagsoup",
    exports = [
        "//external:jar/org/ccil/cowan/tagsoup/tagsoup"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


