filegroup(
    name = "cassandra-embedded",
    srcs = ["cassandra-embedded.yaml"],
    visibility = ["//visibility:public"]
)

filegroup(
    name = "logback-test",
    srcs = ["logback.xml"],
    visibility = ["//visibility:public"]
)