filegroup(
    name = "cassandra-embedded",
    srcs = ["cassandra-embedded.yaml"],
    visibility = ["//test-integration:__subpackages__"]
)

filegroup(
    name = "logback-test",
    srcs = ["logback.xml"],
    visibility = ["//test-integration:__subpackages__"]
)