filegroup(
    name = "cassandra-embedded",
    srcs = ["cassandra-embedded.yaml"],
    visibility = ["//visibility:public"]
)

filegroup(
    name = "logback-test",
    srcs = ["logback.xml"],
    visibility = ["//visibility:public"]
)

filegroup(
    name = "cassandra-embedded-no-caches",
    srcs = ["cassandra-embedded-no-caches.yaml"],
    visibility = ["//visibility:public"]
)

filegroup(
    name = "grakn-properties-no-caches",
    srcs = ["grakn-no-caches.properties"],
    visibility = ["//visibility:public"]
)
