java_library(
    name = "bigtable-hbase-1-0",
    exports = [
        "//external:jar/com/google/cloud/bigtable/bigtable-hbase-1-0"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/appengine:appengine-api-1-0-sdk",
        "//dependencies/maven/artifacts/com/google/code/findbugs:jsr305",
        "//dependencies/maven/artifacts/com/google/code/gson:gson",
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/com/google/protobuf:protobuf-java",
        "//dependencies/maven/artifacts/commons-cli:commons-cli",
        "//dependencies/maven/artifacts/commons-codec:commons-codec",
        "//dependencies/maven/artifacts/commons-collections:commons-collections",
        "//dependencies/maven/artifacts/commons-lang:commons-lang",
        "//dependencies/maven/artifacts/commons-logging:commons-logging",
        "//dependencies/maven/artifacts/org/apache/hbase:hbase-annotations",
        "//dependencies/maven/artifacts/org/apache/hbase:hbase-client",
        "//dependencies/maven/artifacts/org/apache/hbase:hbase-common",
        "//dependencies/maven/artifacts/org/apache/hbase:hbase-protocol",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpcore",
        "//dependencies/maven/artifacts/org/slf4j:slf4j-api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


