insert

isa inference-rule,
lhs {
(production-with-genre: $x, genre-of-production: $y) isa has-genre;
$y has description 'Sci-Fi';
$z isa genre;
$z has description 'science fiction';},
rhs {(production-with-genre: $x, genre-of-production: $z) isa has-genre;};

isa inference-rule,
lhs {
$x isa movie;$x has rotten-tomatoes-user-total-votes > 25000;},
rhs {$x has status 'popular movie';};

isa inference-rule,
lhs {
$x isa movie; $x has tmdb-vote-count > 1000.0;},
rhs {$x has status 'popular movie';};

isa inference-rule,
lhs {
$x isa movie;$x has rotten-tomatoes-user-rating >= 3.0;},
rhs {$x has status 'decent movie';};

isa inference-rule,
lhs {
$x isa movie;$x has tmdb-vote-average < 4.0;},
rhs {$x has status 'bad movie';};

isa inference-rule,
lhs {
$x isa movie;
$x has status 'popular movie';
$x has status 'decent movie';},
rhs {$x has status 'decent popular movie';};

isa inference-rule,
lhs {
$x isa movie;
$x has status 'popular movie';
$x has status 'bad movie';},
rhs {$x has status 'bad popular movie';};

isa inference-rule,
lhs {
(actor: $x, production-with-cast: $y) isa has-cast;
$y has status "popular movie";},
rhs {$x has status 'popular actor';};

isa inference-rule,
lhs {
(actor: $x) isa has-cast;
(director: $x) isa production-crew;},
rhs {$x has status 'actor-director';};
