java_library(
    name = "commons-codec",
    exports = [
        "//external:jar/commons-codec/commons-codec"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


