java_library(
    name = "ecj",
    exports = [
        "//external:jar/org/eclipse/jdt/core/compiler/ecj"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


