java_library(
    name = "apiguardian-api",
    exports = [
        "//external:jar/org/apiguardian/apiguardian-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


