#!/bin/bash

if [ -z "${GRAKN_HOME}" ]; then
    [[ $(readlink $0) ]] && path=$(readlink $0) || path=$0
    GRAKN_BIN=$(cd "$(dirname "${path}")" && pwd -P)
    GRAKN_HOME=$(cd "${GRAKN_BIN}" && pwd -P)
fi

case "$1" in
  server)
    case "$2" in
      start)
        "${GRAKN_HOME}/services/grakn.sh" start
        ;;
      stop)
        "${GRAKN_HOME}/services/grakn.sh" stop
      ;;
      status)
        "${GRAKN_HOME}/services/grakn.sh" status
        ;;
      *)
        echo "Usage: grakn server (start|stop|status)"
        ;;
    esac
    ;;

  graql)
    "${GRAKN_HOME}/services/graql.sh"
    ;;

  *|help)
    case "$2" in
      server)
        echo "
Starts, stops or monitors grakn running on this machine.

Usage: grakn server (start|stop|status)"
        ;;
      graql)
        echo "
Starts a REPL console for running Graql queries on Grakn.

Usage: grakn graql
"
        ;;
      *)
        echo "
Usage: grakn <command>

command:
  server  start a new grakn server
  graql   start a graql console
  help    print this message

tips:
  Start grakn with 'grakn server start' (by default the dashboard will be on http://localhost:4567)
  You can then perform queries by opening a REPL console with 'grakn graql' (defaults to connecting to a local server)"
        ;;
    esac
    ;;
esac
