#!/bin/bash

#
# Grakn - A Distributed Semantic Database
# Copyright (C) 2016  Grakn Labs Limited
#
# Grakn is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Grakn is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# <http://www.gnu.org/licenses/gpl.txt>.

if [ -z "${GRAKN_HOME}" ]; then
    [[ $(readlink $0) ]] && path=$(readlink $0) || path=$0
    GRAKN_BIN=$(cd "$(dirname "${path}")" && pwd -P)
    GRAKN_HOME=$(cd "${GRAKN_BIN}" && pwd -P)
fi

case "$1" in
  console)
    "${GRAKN_HOME}/services/graql.sh" ${1+"${@:2}"}
    ;;
  migrate)
    "${GRAKN_HOME}/services/migration.sh" "${@:2}"
    ;;

  *|help)
    case "$2" in
      migrate)
        "${GRAKN_HOME}/services/migration.sh" help
        ;;

      *)
        echo "
Usage:
  graql COMMAND

COMMAND:
  console  Starts a REPL console for running Graql queries. Defaults to connecting to http://localhost:4567
  migrate  Runs migration from a file
  help     Prints this message"
        ;;
    esac
    ;;
esac
