# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

artifacts = [
    "ch.qos.logback:logback-classic",
    "ch.qos.logback:logback-core",
    "com.eclipsesource.minimal-json:minimal-json",
    "com.github.ben-manes.caffeine:caffeine",
    "com.google.code.findbugs:jsr305",
    "com.google.errorprone:error_prone_annotations",
    "com.google.guava:guava",
    "com.google.ortools:ortools-java",
    "com.google.ortools:ortools-darwin-x86-64",
    "com.google.ortools:ortools-darwin-aarch64",
    "com.google.ortools:ortools-linux-x86-64",
    "com.google.ortools:ortools-linux-aarch64",
    "com.google.ortools:ortools-win32-x86-64",
    "com.google.protobuf:protobuf-java",
    "commons-io:commons-io",
    "io.cucumber:cucumber-java",
    "io.cucumber:cucumber-junit",
    "io.github.speedb-io:speedbjni",
    "io.grpc:grpc-api",
    "io.grpc:grpc-core",
    "io.grpc:grpc-netty",
    "io.grpc:grpc-protobuf",
    "io.grpc:grpc-stub",
    "io.netty:netty-all",
    "io.netty:netty-transport",
    "io.sentry:sentry",
    "javax.annotation:javax.annotation-api",
    "junit:junit",
    "org.slf4j:slf4j-api",
    "org.zeroturnaround:zt-exec",
]
