java_library(
    name = "hamcrest_all",
    exports = [
        "//external:jar/org/hamcrest/hamcrest_all"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "hamcrest_core",
    exports = [
        "//external:jar/org/hamcrest/hamcrest_core"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "hamcrest_library",
    exports = [
        "//external:jar/org/hamcrest/hamcrest_library"
    ],
    runtime_deps = [
        ":hamcrest_core"
    ],
    visibility = [
        "//visibility:public"
    ]
)


