java_library(
    name = "hamcrest-core",
    exports = [
        "//external:jar/org/hamcrest/hamcrest-core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


