define

# Entities

person sub entity,
    plays parent,
    plays child,
    plays spouse,
    plays sibling,
    plays cousin,

    has identifier,
    has firstname,
    has surname,
    has middlename,
    has picture,
    has age,
    has birth-date,
    has death-date,
    has gender;

# Resources

identifier sub attribute, datatype string;
firstname sub attribute, datatype string;
surname sub attribute, datatype string;
middlename sub attribute, datatype string;
picture sub attribute, datatype string;
age sub attribute, datatype long;
birth-date sub attribute, datatype date;
death-date sub attribute, datatype date;
gender sub attribute, datatype string;

# Roles and Relations

marriage sub relation,
    relates spouse,
    has picture;

spouse sub role;

parentship sub relation,
    relates parent,
    relates child;

parent sub role;
child sub role;

## INFERRED

person
    plays wife,
    plays husband,
    plays granddaughter,
    plays grandson,
    plays father-in-law,
    plays mother-in-law,
    plays daughter-in-law,
    plays son-in-law,
    plays son,
    plays daughter,
    plays grandparent,
    plays grandchild,
    plays child-in-law,
    plays parent-in-law,
    plays mother,
    plays father,
    plays grandmother,
    plays grandfather;

marriage sub relation,
    relates husband,
    relates wife;

husband sub role;
wife sub role;

parentship sub relation,
    relates mother,
    relates father,
    relates son,
    relates daughter;

mother sub parent;
father sub parent;
son sub child;
daughter sub child;

siblings sub relation,
    relates sibling;

sibling sub role;

grandparentship sub relation,
    relates grandparent,
    relates grandfather,
    relates grandmother,
    relates grandchild,
    relates granddaughter,
    relates grandson;

grandparent sub role;
grandfather sub grandparent;
grandmother sub grandparent;
grandchild sub role;
grandson sub grandchild;
granddaughter sub grandchild;

cousins sub relation,
    relates cousin;

cousin sub role;

in-laws sub relation,
    relates child-in-law,
    relates son-in-law,
    relates daughter-in-law,
    relates parent-in-law,
    relates mother-in-law,
    relates father-in-law;

child-in-law sub role;
son-in-law sub child-in-law;
daughter-in-law sub child-in-law;

parent-in-law sub role;
mother-in-law sub parent-in-law;
father-in-law sub parent-in-law;

insert

# DATA

$57472      isa person, has firstname "Mary", has identifier "Mary Guthrie", has surname "Guthrie", has gender "female";
$86144      isa person, has surname "Dudley", has identifier "Susan Josephine Dudley", has gender "female", has firstname "Susan", has middlename "Josephine";
$118912     isa person, has age 74, has firstname "Margaret", has surname "Newman", has gender "female", has identifier "Margaret Newman";
$188544     isa person, has firstname "Barbara", has birth-date 1833-04-08, has age 52, has identifier "Barbara Ellen Niesz", has gender "female", has middlename "Ellen", has surname "Niesz";
$32904      isa person, has birth-date 1774-08-02, has identifier "John Newman", has surname "Newman", has death-date 1862-12-26, has firstname "John", has gender "male", has age 88;
$41096      isa person, has surname "Newman", has gender "male", has firstname "Peter", has identifier "Peter Newman";
$41095248   isa person, has age 90, has middlename "S.", has gender "male", has firstname "Samuel", has identifier "Samuel S. Bard", has surname "Bard";
$41168976   isa person, has identifier "Elizabeth Shafner", has gender "female", has surname "Shafner", has firstname "Elizabeth";
$41185360   isa person, has birth-date 1840-01-19, has firstname "Sarah", has age 78, has middlename "Ann", has gender "female", has surname "Niesz", has identifier "Sarah Ann Niesz";
$41209936   isa person, has firstname "Rosalie", has gender "female", has identifier "Rosalie";
$41291856   isa person, has surname "Roush", has firstname "Delilah", has gender "female", has identifier "Delilah Roush";
$41324624   isa person, has age 76, has identifier "William Sanford Titus", has firstname "William", has surname "Titus", has gender "male", has birth-date 1818-03-23, has death-date 1905-01-01, has middlename "Sanford";
$41349200   isa person, has firstname "Byron", has surname "Culbertson", has identifier "Byron Culbertson", has gender "male";
$41361488   isa person, has death-date 1872-03-06, has age 74, has identifier "John Niesz", has birth-date 1798-01-02, has firstname "John", has gender "male", has surname "Niesz";
$28840      isa person, has identifier "Barbara E. Newman", has middlename "E.", has firstname "Barbara", has surname "Newman", has gender "female";
$49320      isa person, has firstname "Ron", has identifier "Ron Newman", has surname "Newman", has gender "male";
$8248       isa person, has firstname "Barbara", has gender "female", has surname "Shafner", has identifier "Barbara Shafner";
$81976      isa person, has identifier "Elizabeth", has gender "female", has firstname "Elizabeth";
$118840     isa person, has identifier "Barbara Herchelroth", has firstname "Barbara", has age 93, has birth-date 1773-06-06, has gender "female", has death-date 1868-03-15, has surname "Herchelroth";
$41013448   isa person, has identifier "Eliza Newman", has surname "Newman", has gender "female", has firstname "Eliza";
$184376     isa person, has firstname "Jacob", has death-date 1798-10-01, has identifier "Jacob Young", has gender "male", has surname "Young";
$41025736   isa person, has identifier "Stephen Newman", has firstname "Stephen", has surname "Newman", has gender "male";
$344120     isa person, has identifier "Frederick Shafner", has gender "male", has firstname "Frederick", has surname "Shafner";
$458808     isa person, has identifier "Elizabeth Weaver", has surname "Weaver", has gender "female", has firstname "Elizabeth";
$49344      isa person, has surname "Newman", has identifier "Robert Newman", has gender "male", has birth-date 1803-02-21, has firstname "Robert";
$53440      isa person, has identifier "Ann Eliza Niesz", has firstname "Ann", has gender "female", has surname "Niesz", has middlename "Eliza";
$188608     isa person, has surname "Billings", has firstname "Maggie", has identifier "Maggie Billings", has gender "female";
$319680     isa person, has age 74, has birth-date 1829-09-12, has death-date 1904-03-26, has gender "male", has firstname "George", has surname "Niesz", has middlename "W.", has identifier "George W. Niesz";
$356544     isa person, has firstname "John", has gender "male", has identifier "John Shafner", has surname "Shafner", has age 22;
$4168       isa person, has surname "Newman", has firstname "Lucinda", has gender "female", has identifier "Lucinda Newman";
$20552      isa person, has firstname "Sarah", has identifier "Sarah Hane", has surname "Hane", has gender "female";
$40980536   isa person, has firstname "Catherine", has surname "Newman", has gender "female", has identifier "Catherine Newman";
$40968224   isa person, has identifier "Amanda Newman", has surname "Newman", has gender "female", has firstname "Amanda";
$40988704   isa person, has identifier "John L. Newman", has surname "Newman", has firstname "John", has gender "male", has middlename "L.";
$41025568   isa person, has birth-date 1811-03-06, has surname "Newman", has gender "male", has death-date 1898-09-10, has identifier "Henry Newman", has age 87, has firstname "Henry";
$119000     isa person, has death-date 1891-12-08, has gender "female", has surname "Niesz", has age 71, has identifier "Elizabeth Niesz", has birth-date 1820-08-27, has firstname "Elizabeth";
$143576     isa person, has firstname "Mary", has death-date 1946-05-10, has surname "Titus", has age 98, has gender "female", has middlename "Melissa", has identifier "Mary Melissa Titus", has birth-date 1847-08-12;
$237784     isa person, has firstname "Mary", has age 83, has gender "female", has surname "Niesz", has birth-date 1824-05-29, has identifier "Mary Niesz";
$307416     isa person, has identifier "George Niesz", has gender "male", has firstname "George", has surname "Niesz";
$8288       isa person, has identifier "Hermione Newman", has firstname "Hermione", has surname "Newman", has gender "female";
$114784     isa person, has firstname "Barbara", has identifier "Barbara Newman", has surname "Newman", has gender "female";
$233568     isa person, has birth-date 1798-04-09, has identifier "Mary Young", has firstname "Mary", has death-date 1868-10-28, has gender "female", has surname "Young", has age 70;
$250080     isa person, has surname "Newman", has identifier "Lawrence Newman", has gender "male", has age 82, has birth-date 1804-09-12, has firstname "Lawrence";
$266336     isa person, has identifier "Josephine", has gender "female", has firstname "Josephine";
$282848     isa person, has birth-date 1842-11-16, has identifier "Benjamin Franklin Niesz", has gender "male", has firstname "Benjamin", has middlename "Franklin", has surname "Niesz";
$389216     isa person, has birth-date 1822-05-28, has age 91, has identifier "William Niesz", has firstname "William", has gender "male", has death-date 1913-04-12, has surname "Niesz";
$40964120   isa person, has firstname "Jacob", has birth-date 1825-11-18, has death-date 1891-08-02, has gender "male", has age 65, has middlename "J.", has identifier "Jacob J. Niesz", has surname "Niesz";
$41119768   isa person, has surname "Newman", has identifier "Harry Newman", has gender "male", has firstname "Harry";
$41127960   isa person, has identifier "Haman Newman", has firstname "Haman", has surname "Newman", has gender "male";
$41316376   isa person, has age 76, has birth-date 1824-10-20, has firstname "Catherine", has identifier "Catherine Niesz", has death-date 1900-12-09, has gender "female", has surname "Niesz", has picture "http:\/\/www.christliebfamilyassociation.com\/images\/CatherineNieszChristlieb.jpg";
$41320472   isa person, has identifier "Andrew Shafner", has firstname "Andrew", has gender "male", has surname "Shafner";
$41340952   isa person, has firstname "Barbara", has surname "Titus", has age 82, has identifier "Barbara Ellen Titus", has gender "female", has middlename "Ellen", has birth-date 1850-09-18, has death-date 1933-01-10;
$41406488   isa person, has surname "Titus", has firstname "Timothy", has gender "male", has identifier "Timothy Titus";
$82040      isa person, has firstname "Catherine", has identifier "Catherine Young", has surname "Young", has gender "female", has birth-date 1798-12-01;
$102520     isa person, has firstname "Elam", has surname "Smith", has gender "male", has identifier "Elam G. Smith", has middlename "G.";
$135288     isa person, has identifier "John Meyers", has surname "Meyers", has firstname "John", has gender "male";
$196728     isa person, has middlename "Kossuth", has firstname "John", has birth-date 1836-11-22, has gender "male", has identifier "John Kossuth Niesz", has surname "Niesz";
$249976     isa person, has death-date 1942-04-08, has age 96, has surname "Titus", has identifier "Amanda Ann Titus", has middlename "Ann", has gender "female", has birth-date 1845-09-10, has firstname "Amanda";
$295032     isa person, has surname "McGaughey", has gender "female", has identifier "Isabelle McGaughey", has firstname "Isabelle";
$299128     isa person, has birth-date 1857-12-24, has death-date 1957-03-28, has firstname "William", has surname "Titus", has age 99, has gender "male", has identifier "William Sanford Titus Jr.", has middlename "Sanford";
$122888272  (parent: $41361488, child: $188544) isa parentship;
$122896464  (parent: $41361488, child: $319680) isa parentship;
$122908752  (parent: $119000, child: $249976) isa parentship;
$40984672   (parent: $233568, child: $188544) isa parentship;
$40964192   (parent: $344120, child: $8248) isa parentship;
$40964320   (parent: $41361488, child: $40964120) isa parentship;
$40980704   (parent: $233568, child: $389216) isa parentship;
$40984800   (parent: $41324624, child: $41340952) isa parentship;
$40992864   (parent: $184376, child: $82040) isa parentship;
$40997088   (parent: $41361488, child: $389216) isa parentship;
$41001056   (parent: $118840, child: $49344) isa parentship;
$41009248   (parent: $295032, child: $4168) isa parentship;
$41013344   (parent: $81976, child: $118912) isa parentship;
$41017440   (parent: $41025568, child: $40988704) isa parentship;
$41021664   (parent: $41406488, child: $41324624) isa parentship;
$163848272  (parent: $250080, child: $41025736) isa parentship;
$163856464  (parent: $49344, child: $118912) isa parentship;
$163901520  (parent: $184376, child: $233568) isa parentship;
$163905616  (parent: $41025568, child: $40980536) isa parentship;
$163909712  (parent: $81976, child: $114784) isa parentship;
$163922000  (parent: $20552, child: $40980536) isa parentship;
$163926096  (parent: $344120, child: $356544) isa parentship;
$8344       (parent: $233568, child: $119000) isa parentship;
$20632      (parent: $458808, child: $41361488) isa parentship;
$81924216   (parent: $119000, child: $143576) isa parentship;
$81944696   (parent: $233568, child: $319680) isa parentship;
$81948792   (parent: $41361488, child: $119000) isa parentship;
$40980696   (parent: $233568, child: $237784) isa parentship;
$40984792   (parent: $233568, child: $41316376) isa parentship;
$40988888   (parent: $41361488, child: $41316376) isa parentship;
$40992984   (parent: $41324624, child: $299128) isa parentship;
$40997080   (parent: $41324624, child: $249976) isa parentship;
$41029848   (parent: $233568, child: $40964120) isa parentship;
$32944      (parent: $233568, child: $41185360) isa parentship;
$53424      (parent: $41361488, child: $196728) isa parentship;
$61616      (parent: $233568, child: $196728) isa parentship;
$40964288   (parent: $233568, child: $282848) isa parentship;
$40968384   (parent: $344120, child: $41168976) isa parentship;
$40972480   (parent: $20552, child: $28840) isa parentship;
$40976576   (parent: $295032, child: $41025736) isa parentship;
$41005248   (parent: $118840, child: $250080) isa parentship;
$41025728   (parent: $82040, child: $41320472) isa parentship;
$4280       (parent: $41361488, child: $237784) isa parentship;
$16568      (parent: $41324624, child: $143576) isa parentship;
$32952      (parent: $119000, child: $41340952) isa parentship;
$81932320   (parent: $41361488, child: $282848) isa parentship;
$81944608   (parent: $32904, child: $49344) isa parentship;
$81948704   (parent: $81976, child: $41127960) isa parentship;
$81965088   (parent: $118840, child: $41025568) isa parentship;
$82010144   (parent: $295032, child: $49320) isa parentship;
$82014240   (parent: $41361488, child: $41185360) isa parentship;
$82026528   (parent: $250080, child: $49320) isa parentship;
$81932336   (parent: $118840, child: $233568) isa parentship;
$81940528   (parent: $82040, child: $41168976) isa parentship;
$81965104   (parent: $41025568, child: $28840) isa parentship;
$40964136   (parent: $32904, child: $41025568) isa parentship;
$40968232   (parent: $81976, child: $41119768) isa parentship;
$40972328   (parent: $82040, child: $8248) isa parentship;
$40984616   (parent: $49344, child: $114784) isa parentship;
$40988712   (parent: $32904, child: $250080) isa parentship;
$40992808   (parent: $20552, child: $40968224) isa parentship;
$41001000   (parent: $49344, child: $41119768) isa parentship;
$41009192   (parent: $118840, child: $82040) isa parentship;
$41025576   (parent: $295032, child: $41013448) isa parentship;
$41029672   (parent: $250080, child: $41013448) isa parentship;
$28912      (parent: $344120, child: $41320472) isa parentship;
$4208       (parent: $119000, child: $299128) isa parentship;
$8304       (parent: $57472, child: $41324624) isa parentship;
$24816      (parent: $81976, child: $41096) isa parentship;
$37104      (parent: $49344, child: $41127960) isa parentship;
$41200      (parent: $250080, child: $4168) isa parentship;
$53488      (parent: $82040, child: $356544) isa parentship;
$61680      (parent: $250080, child: $8288) isa parentship;
$102640     (parent: $49344, child: $41096) isa parentship;
$78064      (parent: $295032, child: $8288) isa parentship;
$86256      (parent: $20552, child: $40988704) isa parentship;
$94448      (parent: $41025568, child: $40968224) isa parentship;
$24824      (parent: $307416, child: $41361488) isa parentship;
$4096       (spouse: $295032, spouse: $250080) isa marriage;
$12288      (spouse: $266336, spouse: $319680) isa marriage;
$32768      (spouse: $86144, spouse: $299128) isa marriage;
$204816464  (spouse: $356544, spouse: $41316376) isa marriage;
$204824656  (spouse: $41095248, spouse: $237784) isa marriage;
$204828752  (spouse: $41291856, spouse: $389216) isa marriage;
$40980728   (spouse: $81976, spouse: $49344) isa marriage;
$40984728   (spouse: $53440, spouse: $389216) isa marriage;
$40992920   (spouse: $344120, spouse: $82040) isa marriage;
$40997016   (spouse: $41127960, spouse: $40980536) isa marriage;
$81924296   (spouse: $118840, spouse: $184376) isa marriage;
$81932328   (spouse: $41324624, spouse: $119000) isa marriage;
$81952808   (spouse: $188608, spouse: $196728) isa marriage;
$81957064   (spouse: $20552, spouse: $41025568) isa marriage;
$122884216  (spouse: $57472, spouse: $41406488) isa marriage;
$40972456   (spouse: $40964120, spouse: $8248) isa marriage;
$40976552   (spouse: $102520, spouse: $41185360) isa marriage;
$40980648   (spouse: $40968224, spouse: $41096) isa marriage;
$40988840   (spouse: $41349200, spouse: $249976) isa marriage;
$81924152   (spouse: $135288, spouse: $41340952) isa marriage;
$81936440   (spouse: $41209936, spouse: $282848) isa marriage;

$20480      (spouse: $118840, spouse: $32904) isa marriage, has picture "http:\/\/2.bp.blogspot.com\/-AT7bLradHgU\/TsfF8VuBpaI\/AAAAAAAAADA\/uodQOYjQikE\/s1600\/willsusieanothercouplesm.jpg";
$81940536   (spouse: $233568, spouse: $41361488) isa marriage, has picture "http:\/\/1.bp.blogspot.com\/-Ty9Ox8v7LUw\/VKoGzIlsMII\/AAAAAAAAAZw\/UtkUvrujvBQ\/s1600\/johnandmary.jpg";

define

## RULES
#############################################################################
#                                                                           #
#     			Rules to add genderized basic relations		   		        #
#                                                                           #
#############################################################################

genderizeMarriages sub rule,
when { (spouse: $s1, spouse: $s2) isa marriage; $s1 has gender "male"; },
then { (husband: $s1, wife: $s2) isa marriage; };

genderizeMarriages2 sub rule,
when { (spouse: $s1, spouse: $s2) isa marriage; $s1 has gender "female"; },
then { (husband: $s2, wife: $s1) isa marriage; };


genderizeParentships1 sub rule,
when { (parent: $p, child: $c) isa parentship; $p has gender "male"; $c has gender "male"; },
then { (father: $p, son: $c) isa parentship; };

genderizeParentships2 sub rule,
when { (parent: $p, child: $c) isa parentship; $p has gender "male"; $c has gender "female"; },
then { (father: $p, daughter: $c) isa parentship; };

genderizeParentships3 sub rule,
when { (parent: $p, child: $c) isa parentship; $p has gender "female"; $c has gender "male"; },
then { (mother: $p, son: $c) isa parentship; };

genderizeParentships4 sub rule,
when { (parent: $p, child: $c) isa parentship; $p has gender "female"; $c has gender "female"; },
then { (mother: $p, daughter: $c) isa parentship; };


#############################################################################
#                                                                           #
#     				Rules to add inferred  relations		   		        #
#                                                                           #
#############################################################################


grandParents1 sub rule,
when { ($p, son: $gc) isa parentship; (father: $gp, $p) isa parentship; },
then { (grandfather: $gp, grandson: $gc) isa grandparentship; };

grandParents2 sub rule,
when { ($p, daughter: $gc) isa parentship; (father: $gp, $p) isa parentship; },
then { (grandfather: $gp, granddaughter: $gc) isa grandparentship; };

grandParents3 sub rule,
when { ($p, daughter: $gc) isa parentship; (mother: $gp, $p) isa parentship; },
then { (grandmother: $gp, granddaughter: $gc) isa grandparentship; };

grandParents4 sub rule,
when { ($p, son: $gc) isa parentship; (mother: $gp, $p) isa parentship; },
then { (grandmother: $gp, grandson: $gc) isa grandparentship; };


peopleWithSameParentsAreSiblings sub rule,
when { (mother: $m, $x) isa parentship; (mother: $m, $y) isa parentship;
       (father: $f, $x) isa parentship; (father: $f, $y) isa parentship; $x != $y; },
then { (sibling: $x, sibling: $y) isa siblings; };

peopleWithSiblingsParentsAreCousins sub rule,
when { (parent: $p, child: $c1) isa parentship; ($p, $p2) isa siblings; (parent: $p2, child: $c2) isa parentship; },
then { (cousin: $c1, cousin: $c2) isa cousins; };

inLaws1 sub rule,
when { (husband: $x, wife: $y) isa marriage; (mother: $il, $y) isa parentship; },
then { (mother-in-law: $il, son-in-law: $x) isa in-laws; };

inLaws2 sub rule,
when { (husband: $x, wife: $y) isa marriage; (father: $il, $y) isa parentship; },
then { (father-in-law: $il, son-in-law: $x) isa in-laws; };

inLaws3 sub rule,
when { (husband: $x, wife: $y) isa marriage; (father: $il, child: $x) isa parentship; },
then { (father-in-law: $il, daughter-in-law: $y) isa in-laws; };

inLaws4 sub rule,
when { (husband: $x, wife: $y) isa marriage; (mother: $il, child: $x) isa parentship; },
then { (mother-in-law: $il, daughter-in-law: $y) isa in-laws; };
