java_test(
    name = "boolean-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.BooleanMacroTest",
    srcs = ["BooleanMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)
java_test(
    name = "concat-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.ConcatMacroTest",
    srcs = ["ConcatMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)
java_test(
    name = "date-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.DateMacroTest",
    srcs = ["DateMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)
java_test(
    name = "double-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.DoubleMacroTest",
    srcs = ["DoubleMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)
java_test(
    name = "equals-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.EqualsMacroTest",
    srcs = ["EqualsMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)
java_test(
    name = "int-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.IntMacroTest",
    srcs = ["IntMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)
java_test(
    name = "long-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.LongMacroTest",
    srcs = ["LongMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)
java_test(
    name = "lower-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.LowerMacroTest",
    srcs = ["LowerMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)
java_test(
    name = "no-escp-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.NoescpMacroTest",
    srcs = ["NoescpMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)
java_test(
    name = "split-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.SplitMacroTest",
    srcs = ["SplitMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)
java_test(
    name = "string-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.StringMacroTest",
    srcs = ["StringMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)
java_test(
    name = "upper-macro-test",
    test_class = "ai.grakn.graql.internal.template.macro.UpperMacroTest",
    srcs = ["UpperMacroTest.java", "MacroTestUtilities.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)