java_library(
    name = "zt_exec",
    exports = [
        "//external:jar/org/zeroturnaround/zt_exec"
    ],
    runtime_deps = [
        "//dependencies/maven/org/slf4j:slf4j_api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


