java_library(
    name = "high_scale_lib",
    exports = [
        "//external:jar/com/github/stephenc/high_scale_lib/high_scale_lib"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


