java_library(
    name = "cassandra_unit",
    exports = [
        "//external:jar/org/cassandraunit/cassandra_unit"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/io/netty:netty_handler",
        "//dependencies/maven/artifacts/junit:junit",
        "//dependencies/maven/artifacts/net/java/dev/jna:jna",
        "//dependencies/maven/artifacts/org/apache/cassandra:cassandra_all",
        "//dependencies/maven/artifacts/org/apache/commons:commons_lang3",
        "//dependencies/maven/artifacts/org/apache/thrift:libthrift",
        "//dependencies/maven/artifacts/org/hamcrest:hamcrest_core",
        "//dependencies/maven/artifacts/org/hamcrest:hamcrest_library"
    ],
    visibility = [
        "//visibility:public"
    ]
)


