java_library(
    name = "cassandra-unit",
    exports = [
        "//external:jar/org/cassandraunit/cassandra-unit"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/io/netty:netty-handler",
        "//dependencies/maven/artifacts/junit:junit",
        "//dependencies/maven/artifacts/net/java/dev/jna:jna",
        "//dependencies/maven/artifacts/org/apache/cassandra:cassandra-all",
        "//dependencies/maven/artifacts/org/apache/commons:commons-lang3",
        "//dependencies/maven/artifacts/org/apache/thrift:libthrift",
        "//dependencies/maven/artifacts/org/hamcrest:hamcrest-core",
        "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library"
    ],
    visibility = [
        "//visibility:public"
    ]
)


