java_library(
    name = "commons_pool",
    exports = [
        "//external:jar/commons_pool/commons_pool"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


