#
# Copyright (C) 2020 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

package(default_visibility = ["//test-integration/graql/reasoner:__subpackages__"])

filegroup(
    name = "reasoning-stubs",
    srcs = [
        "appendingRPs.gql",
        "duplicateMaterialisation.gql",
        "explanations.gql",
        "freshEntityDerivation.gql",
        "freshEntityDerivationFromRelations.gql",
        "freshRelationDerivation.gql",
        "negation.gql",
        "recipeTest.gql",
        "reflexiveRelation.gql",
        "reflexiveSymmetricRelation.gql",
        "resourceAttachment.gql",
        "resourceDirectionality.gql",
        "resourceHierarchy.gql",
        "resourceOwnership.gql",
        "resourcesAsRolePlayers.gql",
        "testSet10.gql",
        "testSet11.gql",
        "testSet12.gql",
        "testSet13.gql",
        "testSet19.gql",
        "testSet19-recursive.gql",
        "testSet20.gql",
        "testSet21.gql",
        "testSet22.gql",
        "testSet23.gql",
        "testSet24.gql",
        "testSet25.gql",
        "testSet26.gql",
        "testSet27.gql",
        "testSet28.gql",
        "testSet28b.gql",
        "testSet29.gql",
        "testSet30.gql",
        "testSet7.gql",
        "testSet8.gql",
        "testSet9.gql",
        "typeDerivation.gql",
        "typeDerivationFromAttribute.gql",
        "typeDerivationFromRelations.gql",
        "typeDerivationRelationsWithDirect.gql",
        "typeDerivationWithDirect.gql",
    ],
)
