define

baseType sub entity,
    has resource-string,
    has resource-long,
    has derived-resource-string,
    has derived-resource-boolean,
    plays someRole,
    plays anotherRole,
    plays otherRole;

type sub baseType;
anotherType sub baseType;
derived-type sub baseType;

someRole sub role;
anotherRole sub role;
otherRole sub role;

binary sub relationship,
    relates someRole,
    relates otherRole;

ternary sub relationship,
    relates someRole,
    relates otherRole,
    relates anotherRole;

derived-binary sub relationship,
    relates someRole,
    relates otherRole;
derived-ternary sub relationship,
    relates someRole,
    relates otherRole,
    relates anotherRole;

#Resources
resource-string sub attribute, datatype string;
resource-long sub attribute, datatype long;

derived-resource-string sub attribute, datatype string;
derived-resource-boolean sub attribute, datatype boolean;

#Rules

attachUnattachedResourceToEntity sub rule,
    when {
        $x isa resource-string;
        $x == 'unattached';
        $y isa type;
    },
    then {
        $y has derived-resource-string 'attached';
    };

setResourceFlagBasedOnOtherResourceValue sub rule,
    when {
        $x isa anotherType, has resource-long > 0;
    },
    then {
        $x has derived-resource-boolean true;
    };

binaryEquivalence sub rule,
    when {
        (someRole:$x, otherRole:$z) isa binary;
    },
    then {
        (someRole:$x, otherRole:$z) isa derived-binary;
    };

binaryTransitivity sub rule,
    when {
        (someRole:$x, otherRole:$z) isa derived-binary;
        (someRole:$z, otherRole:$y) isa derived-binary;
    },
    then {
        (someRole:$x, otherRole:$y) isa derived-binary;
    };



ternaryDefinition sub rule,
    when {
        (someRole:$x, otherRole:$z) isa binary;
        (someRole:$z, otherRole:$y) isa binary;
    },
    then {
        (someRole:$x, otherRole:$y, anotherRole: $z) isa ternary;
    };

ternaryEquivalence sub rule,
    when {
        (someRole:$x, otherRole:$y, anotherRole: $z) isa ternary;
    },
    then {
        (someRole:$x, otherRole:$y, anotherRole: $z) isa derived-ternary;
    };

typeDerivation sub rule,
    when {
        $x isa type;
        ($x, $y) isa binary;
    },
    then {
        $x isa derived-type;
    };

insert

#Data

$x isa type, has resource-string "value";
$y isa type;
$z isa type;
$v isa type, has resource-string "someString";
(someRole: $x, otherRole: $y) isa binary;
(someRole: $x, otherRole: $z) isa binary;
(someRole: $y, otherRole: $q) isa binary;
(someRole: $z, otherRole: $v) isa binary;
(someRole: $y, otherRole: $v) isa binary;

$q isa anotherType, has resource-long 1;

$r "unattached" isa resource-string;