define

named-entity sub entity,
    abstract,
    has name;

ingredientBase sub named-entity,
    abstract,
    plays contained-ingredient,
    plays required-ingredient;

recipeBase sub named-entity,
    abstract,
    plays requiring-recipe;

pantry sub entity,
    plays containing-pantry;
recipe sub recipeBase;
ingredient sub ingredientBase;
allergenic-ingredient sub ingredientBase;

requires sub relation,
    relates required-ingredient,
    relates requiring-recipe;

containes sub relation,
    relates contained-ingredient,
    relates containing-pantry;

name sub attribute, datatype string;


available-ingredient-occuring-in-recipe sub ingredientBase;
available-ingredient sub ingredientBase;
recipe-with-unavailable-ingredient sub recipeBase;

rule-1 sub rule,
    when {
        $r isa recipe;
        $i isa ingredient;
        ($r, $i) isa requires;
        ($i) isa containes;
    },
    then {
        $i isa available-ingredient-occuring-in-recipe;
    };

rule-2 sub rule,
    when {
       $i isa ingredient;
       ($i) isa containes;
    },
    then {
        $i isa available-ingredient;
    };

rule-3 sub rule,
    when {
        $r isa recipe;
        ($r, $i) isa requires;
        not {$i isa available-ingredient;};
    },
    then {
        $r isa recipe-with-unavailable-ingredient;
    };

insert
$n isa allergenic-ingredient, has name 'nuts';
$l isa allergenic-ingredient, has name 'milk';
$f isa ingredient, has name 'flour';
$w isa ingredient, has name 'water';
$m isa ingredient, has name 'malt';
$h isa ingredient, has name 'hops';
$y isa ingredient, has name 'yeast';
$c isa allergenic-ingredient, has name 'cocoa';

$p isa pantry;

(contained-ingredient: $f, containing-pantry: $p) isa containes;
(contained-ingredient: $w, containing-pantry: $p) isa containes;
(contained-ingredient: $m, containing-pantry: $p) isa containes;
(contained-ingredient: $h, containing-pantry: $p) isa containes;
(contained-ingredient: $y, containing-pantry: $p) isa containes;

$r1 isa recipe, has name 'lager';
$r2 isa recipe, has name 'stout';
$r3 isa recipe, has name 'kakao';
$r4 isa recipe, has name 'pie';
$r5 isa recipe, has name 'cheesecake';

(required-ingredient: $w, requiring-recipe: $r1) isa requires;
(required-ingredient: $m, requiring-recipe: $r1) isa requires;
(required-ingredient: $h, requiring-recipe: $r1) isa requires;
(required-ingredient: $y, requiring-recipe: $r1) isa requires;

(required-ingredient: $w, requiring-recipe: $r2) isa requires;
(required-ingredient: $m, requiring-recipe: $r2) isa requires;
(required-ingredient: $h, requiring-recipe: $r2) isa requires;
(required-ingredient: $y, requiring-recipe: $r2) isa requires;
(required-ingredient: $c, requiring-recipe: $r2) isa requires;

(required-ingredient: $m, requiring-recipe: $r3) isa requires;
(required-ingredient: $c, requiring-recipe: $r3) isa requires;

(required-ingredient: $f, requiring-recipe: $r4) isa requires;
(required-ingredient: $w, requiring-recipe: $r4) isa requires;
(required-ingredient: $y, requiring-recipe: $r4) isa requires;

(required-ingredient: $f, requiring-recipe: $r5) isa requires;
(required-ingredient: $m, requiring-recipe: $r5) isa requires;
(required-ingredient: $y, requiring-recipe: $r5) isa requires;


