define

genericEntity sub entity,
    has extendedResource,
    has anotherExtendedResource,
    has furtherExtendedResource,
    has simpleResource;

genericRole sub role;

relation0 sub relation,
    relates genericRole;

baseResource sub attribute, valuetype string,
    plays genericRole;

extendedResource sub baseResource, valuetype string;
anotherExtendedResource sub baseResource, valuetype string;

furtherExtendedResource sub extendedResource, valuetype string;

simpleResource sub attribute, valuetype string;


insert
$x 'value' isa baseResource;
$y 'pupa' isa extendedResource;
