define

name sub attribute, datatype string;

indicator sub attribute, datatype string,
  plays action;

specific-indicator sub indicator;

model-name sub name,
  plays action,
  has specific-indicator;

diagnosis sub relation,
  relates subject,
  relates action;

router sub entity,
  has model-name,
  has specific-indicator,
  plays subject;

define
indicator-name sub name;
@has-indicator has indicator-name;
@has-specific-indicator has indicator-name;

insert
$r isa router, has specific-indicator $w, has model-name $rmn;
$rmn "someName" isa model-name, has specific-indicator $w;
$w "someIndicator";
$d(subject: $r, action: $w) isa diagnosis;

