define

#Roles

role1 sub role;
role2 sub role;
role3 sub role1;
role4 sub role2;

#Entities

entity1 sub entity,
    plays role1,
    plays role2,
    plays role3,
    plays role4;

#Relations

relation1 sub relation,
    relates role1,
    relates role2;

relation2 sub relation,
    relates role1,
    relates role2;

relation3 sub relation2,
    relates role3,
    relates role4;

#Rules

rule-1 sub rule,
    when {
    	(role1:$x, role2:$y) isa relation1;
    },
    then {
    	(role3:$x, role4:$y) isa relation3;
    };

insert

#Data

$x isa entity1;
$y isa entity1;

(role1:$x, role2:$y) isa relation1;