define

#Roles

friend1 sub role;
friend2 sub role;

#Entities

person sub entity,
    plays friend1,
    plays friend2;

#Relations

knows-trans sub relation,
    relates friend1,
    relates friend2;
knows sub knows-trans,
    relates friend1,
    relates friend2;

#Rules

rule0 sub rule,
    when {
        (friend1:$x, friend2:$y);
        (friend1:$y, friend2:$z);
    },
    then {
        (friend1:$x, friend2:$z) isa knows-trans;
    };

insert

#Data

$p1 isa person;
$p2 isa person;
$p3 isa person;
$p4 isa person;

(friend1:$p1, friend2:$p2) isa knows;
(friend1:$p2, friend2:$p3) isa knows;
(friend1:$p3, friend2:$p4) isa knows;