define

#Roles

related-state sub role;

#Entities

state sub entity,
    plays related-state,
    has name;

#Relations

achieved sub relation,
    relates related-state;

prior sub relation,
    relates related-state;

holds sub relation,
    relates related-state;

name sub attribute, datatype string;

rule-1 sub rule,
    when {
        $st isa state;
        (related-state: $st) isa achieved;
        (related-state: $st2) isa prior;
        $st != $st2;
    },
    then{
        (related-state: $st) isa holds;
    };

insert

$s1 isa state, has name 's1';
$s2 isa state, has name 's2';

(related-state: $s1) isa prior;
(related-state: $s1) isa achieved;
(related-state: $s2) isa achieved;