define

#Roles

contained sub role;
container sub role;
role1 sub role;
role2 sub role;

#Entities

entity1 sub entity,
    has name,
    plays contained;

entity2 sub entity,
    plays contained,
    plays container;

entity3 sub entity,
    plays contained,
    plays container,
    plays role1,
    plays role2;

#Relations

containment sub relation,
    relates contained,
    relates container;

relation1 sub relation,
    relates role1,
    relates role2;

name sub attribute, datatype string;

#Rules

rule-1 sub rule,
    when {
    	(contained:$x, container: $z) isa containment;
    	(contained:$z, container: $y) isa containment;
    },
    then {
    	(contained: $x, container: $y) isa containment;
    };

insert

#Data

$x isa entity1, has name 'a';
$y isa entity2;
$z isa entity3;
$z1 isa entity3;
$z2 isa entity3;

(contained:$x, container: $y) isa containment;
(contained:$y, container: $z) isa containment;

(role1: $z, role2: $z1) isa relation1;
(role1: $z, role2: $z2) isa relation1;

