define

#Roles

original sub role;
reply sub role;
predecessor sub role;
successor sub role;

#Entities

post sub entity,
    plays original,
    plays reply,
    plays predecessor,
    plays successor,
    has creation-date;

#Relations

reply-of sub relation,
    relates original,
    relates reply;

message-succession sub relation,
    relates predecessor,
    relates successor;

creation-date sub attribute, datatype long;

#Rules

rule2 sub rule,
    when{
        (original:$p, reply:$s) isa reply-of;
        $s has creation-date $d1;
        $d1 < $d2;
        (original:$p, reply:$r) isa reply-of;
        $r has creation-date $d2;
    },
    then {
        (predecessor:$s, successor:$r) isa message-succession;
    };

insert

#Data

$x isa post, has creation-date 0;
$x1 isa post, has creation-date 1;
$x2 isa post, has creation-date 2;
$x3 isa post, has creation-date 3;
$x4 isa post, has creation-date 4;
$x5 isa post, has creation-date 5;

(original:$x, reply:$x1) isa reply-of;
(original:$x, reply:$x2) isa reply-of;
(original:$x, reply:$x3) isa reply-of;
(original:$x, reply:$x4) isa reply-of;
(original:$x, reply:$x5) isa reply-of;
