define

##################################################################
# Schema
##################################################################

word sub entity,
    plays subtype,
    plays supertype,
    plays prep,
    plays pobj,
    has name;

f sub word;
o sub word;

pobj sub role;
prep sub role;
subtype sub role;
supertype sub role;

inheritance sub relation,
    relates supertype,
    relates subtype;

pair sub relation,
    relates prep,
    relates pobj,
    has typ,
    has name;

name sub attribute, datatype string;
typ sub attribute, datatype string;

##################################################################
# Inference: all pairs;
##################################################################

rule-1 sub rule,
    when {
        $x isa word;
        $y isa word;
        $x has name !== 'f';
        $y has name !== 'o';
    },
    then {
        (prep: $x, pobj: $y) isa pair;
    };

##################################################################
# Inference: pairs FF
##################################################################

rule-2 sub rule,
    when {
        $f isa f;
        (subtype: $prep, supertype: $f) isa inheritance;
        (subtype: $pobj, supertype: $f) isa inheritance;
        $p (prep: $prep, pobj: $pobj) isa pair;
    },
    then {
        $p has name 'ff';
    };

##################################################################
# Inference: pairs FO
##################################################################

rule-3 sub rule,
    when {
        $f isa f;
        $o isa o;
        (subtype: $prep, supertype: $f) isa inheritance;
        (subtype: $pobj, supertype: $o) isa inheritance;
        $p (prep: $prep, pobj: $pobj) isa pair;
    },
    then {
        $p has name 'fo';
    };

##################################################################
# Data
##################################################################

insert

$f isa f, has name "f";
$o isa o, has name "o";

$aa isa word, has name "aa";
$bb isa word, has name "bb";
$cc isa word, has name "cc";

(supertype: $o, subtype: $aa) isa inheritance;
(supertype: $o, subtype: $bb) isa inheritance;
(supertype: $o, subtype: $cc) isa inheritance;

$pp isa word, has name "pp";
$qq isa word, has name "qq";
$rr isa word, has name "rr";
$rr2 isa word, has name "rr";

(supertype: $f, subtype: $pp) isa inheritance;
(supertype: $f, subtype: $qq) isa inheritance;
(supertype: $f, subtype: $rr) isa inheritance;
(supertype: $f, subtype: $rr2) isa inheritance;

