define

baseEntity sub entity,
    has baseAttribute;

derivedEntity sub entity,
    has baseAttribute;

baseAttribute sub attribute, datatype string;

rule1
    when {
        $x has baseAttribute "derived";
    },
    then {
        $x isa derivedEntity;
    };

insert

$x isa baseEntity, has baseAttribute "derived";
