java_library(
    name = "vavr",
    exports = [
        "//external:jar/io/vavr/vavr"
    ],
    runtime_deps = [
        ":vavr-match"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "vavr-match",
    exports = [
        "//external:jar/io/vavr/vavr-match"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


