java_library(
    name = "HdrHistogram",
    exports = [
        "//external:jar/org/hdrhistogram/HdrHistogram"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


