insert

#########################################
##########Language requirement###########
#########################################

isa inference-rule,
lhs {$x isa applicant;
$x has degreeOrigin 'US';
$x has TOEFL >499;},
rhs {$x has languageRequirement 'satisfied';};

isa inference-rule,
lhs {$x isa applicant;
$x has degreeOrigin 'nonUS';},
rhs {$x has languageRequirement 'unsatisfied';};

isa inference-rule,
lhs {$x isa applicant;
$x has TOEFL <500;},
rhs {$x has languageRequirement 'unsatisfied';};


#########################################
##########Consider GPR###########
#########################################

isa inference-rule,
lhs {$x isa applicant;
$x has priorGraduateWork 'none';},
rhs {$x has considerGPR 'true';};

isa inference-rule,
lhs {$x isa applicant;
$x has priorGraduateWork 'completed';
$x has GPR >2.99;},
rhs {$x has considerGPR 'true';};

#########################################
##################Decision###############
#########################################

isa inference-rule,
lhs {$x isa applicant;
$x has languageRequirement 'satisfied';
$x has transcript 'available';},
rhs {$x has decisionType 'full';};

isa inference-rule,
lhs {$x isa applicant;
$x has languageRequirement 'satisfied';
$x has transcript 'unavailable';},
rhs {$x has decisionType 'conditional';};

#########################################
#############Conditional evaluation######
#########################################

isa inference-rule,
lhs {$x isa applicant;
$x has GPR >3.29;
$x has specialHonours 'honour student';},
rhs {$x has admissionStatus 'conditional';};

isa inference-rule,
lhs {$x isa applicant;
$x has decisionType 'conditional';
$x has specialHonours 'none';
$x has GRE >1099;},
rhs {$x has admissionStatus 'conditional';};


##########################################
##############Admission accepted##############
##########################################

isa inference-rule,
lhs {$x isa applicant;
$x has decisionType 'full';
$x has considerGPR 'true';
$x has GPR >2.49;
$x has specialHonours 'none';
$x has GRE >1099;
$x has vGRE >399;},
rhs {$x has admissionStatus 'full';};

isa inference-rule,
lhs {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.99;
$x has specialHonours !='none';},
rhs {$x has admissionStatus 'full';};

isa inference-rule,
lhs {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.99;
$x has specialHonours 'none';
$x has GRE >1099;
$x has vGRE <400;},
rhs {$x has admissionStatus 'admit at department\'s discretion';};

#########################################
#############Wait for transcript######
#########################################

isa inference-rule,
lhs {$x isa applicant;
$x has decisionType 'conditional';
$x has specialHonours 'none';
$x has GRE <1100;},
rhs {$x has admissionStatus 'wait for transcript';};

isa inference-rule,
lhs {$x isa applicant;
$x has decisionType 'conditional';
$x has GPR <3.3;},
rhs {$x has admissionStatus 'wait for transcript';};


#########################################
#########Admission denied#########
#########################################

isa inference-rule,
lhs {$x isa applicant;
$x has languageRequirement 'unsatisfied';},
rhs {$x has admissionStatus 'denied';};

isa inference-rule,
lhs {$x isa applicant;
$x has considerGPR 'true';$x has GPR <2.5;},
rhs {$x has admissionStatus 'denied';};

isa inference-rule,
lhs {$x isa applicant;
$x has priorGraduateWork 'completed';
$x has GPR <3.0;},
rhs {$x has admissionStatus 'denied';};

isa inference-rule,
lhs {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has GRE <900;},
rhs {$x has admissionStatus 'denied';};

isa inference-rule,
lhs {$x isa applicant;
$x has considerGPR 'true';
$x has specialHonours 'none';
$x has GPR >2.49;
$x has GRE <900;},
rhs {$x has admissionStatus 'denied';};

#########################################
##############Provisional admission##############
#########################################

isa inference-rule,
lhs {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has specialHonours 'none';
$x has GRE >899;
$x has GRE <1100;
$x has vGRE <400;},
rhs {$x has admissionStatus 'provisional with English remediation';};

isa inference-rule,
lhs {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.99;
$x has specialHonours 'none';
$x has GRE >899;
$x has GRE <1100;
$x has vGRE >399;},
rhs {$x has admissionStatus 'provisional';};

isa inference-rule,
lhs {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has GPR <3.0;
$x has specialHonours 'none';
$x has GRE >899;
$x has vGRE <400;},
rhs {$x has admissionStatus 'provisional with English remediation';};

isa inference-rule,
lhs {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has GPR <3.0;
$x has GRE >899;
$x has vGRE <400;},
rhs {$x has admissionStatus 'provisional';};
