insert


###################################################
####################Ontology######################
#################################################

"Person" sub entity
    has name;

"friendA" sub role;
"friendB" sub role;
"Friend" sub relation, relates friendA, relates friendB;
Person plays friendA, plays friendB;

"parent" sub role;
"child" sub role;
"Parent" sub relation, relates parent, relates child;
Person plays parent, plays child;

"person" sub role;
"ancestor-friend" sub role;
"Ancestor-friend" sub relation, relates person, relates ancestor-friend;
Person plays person, plays ancestor-friend;

"name" sub resource, datatype string;

####################################################
##################DATA#############################
####################################################

$a isa Person, has name "a";
$b isa Person, has name "b";
$c isa Person, has name "c";
$d  isa Person, has name "d";
$g  isa Person, has name "g";

(parent: $a, child: $b) isa Parent;
(parent: $b, child: $c) isa Parent;
(friendA: $a, friendB: $g) isa Friend;
(friendA: $c, friendB: $d) isa Friend;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
(friendA: $x, friendB: $y) isa Friend;},
rhs {
(person: $x, ancestor-friend: $y) isa Ancestor-friend;};

isa inference-rule,
lhs {
(parent: $x, child: $z) isa Parent;
(person: $z, ancestor-friend: $y) isa Ancestor-friend;},
rhs {
(person: $x, ancestor-friend: $y) isa Ancestor-friend;};
