insert


###################################################
####################Ontology######################
#################################################

"Person" sub entity
    has name;

"parent" sub role;
"child" sub role;
"Parent" sub relation, relates parent, relates child;
Person plays parent, plays child;

"ancestor" sub role;
"descendant" sub role;
"Ancestor" sub relation, relates ancestor, relates descendant;
Person plays ancestor, plays descendant;

"name" sub resource, datatype string;

####################################################
##################DATA#############################
####################################################

$a isa Person, has name 'a';
$aa isa Person, has name 'aa';
$aaa isa Person, has name 'aaa';
$aab isa Person, has name 'aab';
$aaaa isa Person, has name 'aaaa';
$ab isa Person, has name 'ab';
$c isa Person, has name 'c';
$ca isa Person, has name 'ca';

(parent: $a, child: $aa) isa Parent;
(parent: $a, child: $ab) isa Parent;
(parent: $aa, child: $aaa) isa Parent;
(parent: $aa, child: $aab) isa Parent;
(parent: $aaa, child: $aaaa) isa Parent;
(parent: $c, child: $ca) isa Parent;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
(parent: $x, child: $z) isa Parent;
(ancestor: $z, descendant: $y) isa Ancestor;},
rhs {
(ancestor: $x, descendant: $y) isa Ancestor;};

isa inference-rule,
lhs {
(parent: $x, child: $y) isa Parent;},
rhs {
(ancestor: $x, descendant: $y) isa Ancestor;};