insert

entity1 sub entity
    plays rel-from
    plays rel-to
    has name;

horizontal sub relation
    relates rel-from
    relates rel-to;

vertical sub relation
    relates rel-from
    relates rel-to;

diagonal sub relation
    relates rel-from
    relates rel-to;

rel-from sub role;
rel-to sub role;
name sub resource datatype string;

isa inference-rule
lhs {
    (rel-from:$x, rel-to:$y) isa horizontal;
    (rel-from:$y, rel-to:$z) isa horizontal;
    (rel-from:$z, rel-to:$u) isa vertical;
    (rel-from:$u, rel-to:$v) isa vertical;
}
rhs{
    (rel-from:$x, rel-to:$v) isa diagonal;
};