insert

#Roles

role1 sub role;
role2 sub role;

#Entities

entity1 sub entity
    has name
	plays role1
	plays role2;

#Relations

relation1 sub relation
	relates role1
	relates role2;

"name" sub resource, datatype string;

$a1 isa entity1, has name "a1";
$a2 isa entity1, has name "a2";
$b isa entity1, has name "b";
$c isa entity1, has name "c";
(role1:$a1, role2:$b) isa relation1;
(role1:$a1, role2:$c) isa relation1;
(role1:$a2, role2:$b) isa relation1;
(role1:$a2, role2:$c) isa relation1;
(role1:$b, role2:$c) isa relation1;