insert

###################################################
####################Ontology######################
#################################################

"entity" sub entity, is-abstract
    has name;

"city" sub entity;
"region" sub entity;
"country" sub entity;
"continent" sub entity;
"university" sub entity;

"geo-entity" sub role;
"entity-location" sub role;
"is-located-in" sub relation, relates geo-entity, relates entity-location;
entity plays geo-entity, plays entity-location;

"role1" sub role;
"role2" sub role;
"role3" sub role;
"ternary-relation-test" sub relation, relates role1, relates role2, relates role3;
entity plays role1, plays role2, plays role3;

"name" sub resource, datatype string;

####################################################
##################DATA#############################
####################################################

$europe isa continent, has name "Europe";
$north-america isa continent, has name "NorthAmerica";

$poland isa country, has name "Poland";
$england isa country, has name "England";
$germany isa country, has name "Germany";
$france isa country, has name "France";
$italy isa country, has name "Italy";

$masovia isa region, has name "Masovia";
$silesia isa region, has name "Silesia";
$greater-london isa region, has name "GreaterLondon";
$bavaria isa region, has name "Bavaria";
$ile-de-france isa region, has name "IleDeFrance";
$lombardy isa region, has name "Lombardy";

$warsaw isa city, has name "Warsaw";
$wroclaw isa city, has name "Wroclaw";
$london isa city, has name "London";
$munich isa city, has name "Munich";
$paris isa city, has name "Paris";
$milan isa city, has name "Milan";

$uni-warsaw isa university, has name "University-of-Warsaw";
$warsaw-poly isa university, has name "Warsaw-Polytechnics";
$imperial isa university, has name "Imperial-College-London";
$ucl isa university, has name "University-College-London";
$uni-munich isa university, has name "University-of-Munich";

(geo-entity: $warsaw-poly, entity-location: $warsaw) isa is-located-in;
(geo-entity: $uni-warsaw, entity-location: $warsaw) isa is-located-in;
(geo-entity: $imperial, entity-location: $london) isa is-located-in;
(geo-entity: $ucl, entity-location: $london) isa is-located-in;

(geo-entity: $warsaw, entity-location: $masovia) isa is-located-in;
(geo-entity: $masovia, entity-location: $poland) isa is-located-in;
(geo-entity: $wroclaw, entity-location: $silesia) isa is-located-in;
(geo-entity: $silesia, entity-location: $poland) isa is-located-in;
(geo-entity: $poland, entity-location: $europe) isa is-located-in;

(geo-entity: $london, entity-location: $greater-london) isa is-located-in;
(geo-entity: $greater-london, entity-location: $england) isa is-located-in;
(geo-entity: $england, entity-location: $europe) isa is-located-in;

(geo-entity: $munich, entity-location: $bavaria) isa is-located-in;
(geo-entity: $bavaria, entity-location: $germany) isa is-located-in;
(geo-entity: $germany, entity-location: $europe) isa is-located-in;

(geo-entity: $milan, entity-location: $lombardy) isa is-located-in;
(geo-entity: $lombardy, entity-location: $italy) isa is-located-in;
(geo-entity: $italy, entity-location: $europe) isa is-located-in;

(geo-entity: $paris, entity-location: $ile-de-france) isa is-located-in;
(geo-entity: $ile-de-france, entity-location: $france) isa is-located-in;
(geo-entity: $france, entity-location: $europe) isa is-located-in;
