insert

#transitivity of resides & sublocate
isa inference-rule,
lhs {(located-subject: $x, subject-location: $y) isa resides;
(member-location: $y, container-location: $z) isa sublocate;
},
rhs {(located-subject: $x, subject-location: $z) isa resides;};

# transitivity of sublocate
isa inference-rule,
lhs {
(member-location: $x, container-location: $y) isa sublocate;
(member-location: $y, container-location: $z) isa sublocate;
},
rhs {(member-location: $x, container-location: $z) isa sublocate;};

isa inference-rule,
lhs {(moderator: $x, moderated: $y) isa moderates;},
rhs {(forum-member: $x, membered-forum: $y) isa membership;};

isa inference-rule,
lhs {$x isa person;
$t1 isa tag;$t1 has name 'Ennio Morricone';
$t2 isa tag;$t2 has name 'John Wayne';
($x, $t1) isa tagging;
($x, $t2) isa tagging;
$y isa product;
$y has name 'The Good the Bad the Ugly';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;{$t has name 'Ozzy Osbourne';} or {$t has name 'Rising Force';};
#($x, $t) isa tagging;
#$y isa product;
#{$y has name 'Blizzard of Ozz';} or {$y has name 'Stratocaster';};
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Ozzy Osbourne';
($x, $t) isa tagging;
$y isa product;
$y has name 'Blizzard of Ozz';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Ozzy Osbourne';
($x, $t) isa tagging;
$y isa product;
$y has name 'Stratocaster';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Rising Force';
($x, $t) isa tagging;
$y isa product;
$y has name 'Blizzard of Ozz';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Rising Force';
($x, $t) isa tagging;
$y isa product;
$y has name 'Stratocaster';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$x has gender 'male';$x has age >=18;
$y isa product;$y has min-age >=18;
$z isa country;$z has name 'Italy';
($y, $z) isa made-in;
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;{$t has name 'Ludwig van Beethoven';} or {$t has name 'Johann Sebastian Bach';} or {$t has name 'Wolfgang Amadeus Mozart';};
#($x, $t) isa tagging;
#$y isa product;$y has name 'Nocturnes';
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Ludwig van Beethoven';
($x, $t) isa tagging;
$y isa product;$y has name 'Nocturnes';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Johann Sebastian Bach';
($x, $t) isa tagging;
$y isa product;$y has name 'Nocturnes';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Wolfgang Amadeus Mozart';
($x, $t) isa tagging;
$y isa product;$y has name 'Nocturnes';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Roger Waters';
($x, $t) isa tagging;
$y isa product;$y has name 'The Wall';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

###########################################
##################Writer->Book######################
#############################################

#isa inference-rule,
#lhs {
#$x isa person;$t isa tag;
#($x, $t) isa tagging;
#$tt isa category;$tt has name 'Writer';
#($t, $tt) isa grouping;
#$y isa product;
#$yt isa category;$yt has name 'book';
#($y, $yt) isa typing;},
#rhs {
#(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'H. G. Wells';
($x, $t) isa tagging;
$y isa product;$y has name 'War of the Worlds';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Fyodor Dostoyevsky';
($x, $t) isa tagging;
$y isa product;$y has name 'Crime and Punishment';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'George Orwell';
($x, $t) isa tagging;
$y isa product;$y has name 'Animal Farm';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Lewis Carroll';
($x, $t) isa tagging;
$y isa product;$y has name 'Adventures in Wonderland';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Agatha Christie';
($x, $t) isa tagging;
$y isa product;$y has name 'Orient Express';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Hans Christian Andersen';
($x, $t) isa tagging;
$y isa product;$y has name 'Fairy Tales';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Terry Pratchett';
($x, $t) isa tagging;
$y isa product;$y has name 'Colour of Magic';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'P. G. Wodehouse';
($x, $t) isa tagging;
$y isa product;$y has name 'My Man Jeeves';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Oscar Wilde';
($x, $t) isa tagging;
$y isa product;$y has name 'Dorian Gray';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'J. R. R. Tolkien';
($x, $t) isa tagging;
$y isa product;$y has name 'Lord of the Rings';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'J. K. Rowling';
($x, $t) isa tagging;
$y isa product;$y has name 'Harry Potter';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Arthur Conan Doyle';
($x, $t) isa tagging;
$y isa product;$y has name 'Sherlock Holmes';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Ernest Hemingway';
($x, $t) isa tagging;
$y isa product;$y has name 'For Whom the Bell Tolls';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'John Steinbeck';
($x, $t) isa tagging;
$y isa product;$y has name 'Of Mice and Men';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Franz Kafka';
($x, $t) isa tagging;
$y isa product;$y has name 'Trial';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Johann Wolfgang von Goethe';
($x, $t) isa tagging;
$y isa product;$y has name 'Faust';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

############################################
##############MusicalArtist->Band############
#############################################

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Ozzy Osbourne';
($x, $t) isa tagging;
$y isa tag;$y has name 'Black Sabbath';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;{$t has name 'Paul McCartney';} or {$t has name 'George Harrison';};
#($x, $t) isa tagging;
#$y isa tag;$y has name 'Beatles';
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Paul McCartney';
($x, $t) isa tagging;
$y isa tag;$y has name 'Beatles';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'George Harrison';
($x, $t) isa tagging;
$y isa tag;$y has name 'Beatles';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Roger Waters';
($x, $t) isa tagging;
$y isa tag;$y has name 'Pink Floyd';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Keith Richards';
($x, $t) isa tagging;
$y isa tag;$y has name 'Rolling Stones';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Paul Simon';
($x, $t) isa tagging;
$y isa tag;$y has name 'Simon and Garfunkel';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;$t has name 'Eric Clapton';
#($x, $t) isa tagging;
#$y isa tag;
#{$y has name 'Cream';} or {$y has name 'Yardbirds';};
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Eric Clapton';
($x, $t) isa tagging;
$y isa tag;
$y has name 'Cream';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Eric Clapton';
($x, $t) isa tagging;
$y isa tag;
$y has name 'Yardbirds';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Bob Marley';
($x, $t) isa tagging;
$y isa tag;$y has name 'Bob Marley and the Wailers';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

############################################
##############Album->Band##################
#############################################

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;$t has name 'Master of Puppets';
#($x, $t) isa tagging;
#$y isa tag;
#{$y has name 'Megadeth';} or {$y has name 'Slayer';};
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;$t has name 'Far Beyond Driven';
#($x, $t) isa tagging;
#$y isa tag;
#{$y has name 'Pantera';} or {$y has name 'Superjoint Ritual';};
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;$t has name 'Hybrhas name Theory';
#($x, $t) isa tagging;
#$y isa tag;
#{$y has name 'Linkin Park';} or {$y has name 'Limp Bizkit';};
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;$t has name 'Powerslave';
#($x, $t) isa tagging;
#$y isa tag;
#{$y has name 'Iron Maiden';} or {$y has name 'Judas Priest';};
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;$t has name 'Enter the Chicken';
#($x, $t) isa tagging;
#$y isa tag;
#{$y has name 'Buckethead';} or {$y has name 'Primus';};
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;$t has name 'Rising Force';
#($x, $t) isa tagging;
#$y isa tag;
#{$y has name 'Yngwie Malmsteen';} or {$y has name 'Steve Vai';} or {$y has name 'Cacophony';};
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Rising Force';
($x, $t) isa tagging;
$y isa tag;
$y has name 'Yngwie Malmsteen';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Rising Force';
($x, $t) isa tagging;
$y isa tag;
$y has name 'Steve Vai';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Rising Force';
($x, $t) isa tagging;
$y isa tag;
$y has name 'Cacophony';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;$t has name 'Led Zeppelin IV';
#($x, $t) isa tagging;
#$y isa tag;
#{$y has name 'Led Zeppelin';} or {$y has name 'Deep Purple';};
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

############################################
##############Song/Single->Band##################
#############################################

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'All_Along_the_Watchtower';
($x, $t) isa tagging;
$y isa tag;$y has name 'Jimi Hendrix';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'These_Are_the_Days_of_Our_Lives';
($x, $t) isa tagging;
$y isa tag;$y has name 'Queen';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Come_Together';
($x, $t) isa tagging;
$y isa tag;$y has name ' Beatles';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Smoke_on_the_Water';
($x, $t) isa tagging;
$y isa tag;$y has name 'Deep Purple';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Immigrant_Song';
($x, $t) isa tagging;
$y isa tag;$y has name 'Led Zeppelin';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

######################################################
##################Artist->Painting####################
#######################################################

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Claude Monet';
($x, $t) isa tagging;
$y isa product;$y has name 'Water Lillies';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Rembrandt';
($x, $t) isa tagging;
$y isa product;$y has name 'The Night Watch';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Leonardo da Vinci';
($x, $t) isa tagging;
$y isa product;$y has name 'Mona Lisa';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Raphael';
($x, $t) isa tagging;
$y isa product;$y has name 'Madonna';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Titian';
($x, $t) isa tagging;
$y isa product;$y has name 'Bacchus and Ariadne';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Vincent van Gogh';
($x, $t) isa tagging;
$y isa product;$y has name 'Sunflowers';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Diego Rivera';
($x, $t) isa tagging;
$y isa product;$y has name 'Controller of the Universe';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Piet Mondrian';
($x, $t) isa tagging;
$y isa product;$y has name 'Gray Tree';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

isa inference-rule,
lhs {$x isa person;$t isa tag;$t has name 'Michelangelo';
($x, $t) isa tagging;
$y isa product;$y has name 'Last Judgement';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};
