insert
#string, long, double, boolean

"entity2" sub entity, is-abstract
    has name;
"recommendable" sub entity2;
"place" sub entity2;
"organization" sub entity2;
"tag" sub recommendable;
"category" sub entity2;
"forum" sub entity2;

"subject-location" sub location;
"located-subject" sub role;
"resides" sub relation, relates subject-location, relates located-subject;

# place
"continent" sub place;
"country" sub place;
"city" sub place;


"location" sub role, is-abstract;

"member-location" sub location;
"container-location" sub location;
"sublocate" sub relation, relates member-location, relates container-location;
place plays member-location, plays container-location, plays subject-location;

# organization
"university" sub organization;
"company" sub organization;
organization plays located-subject;

# person
"person" sub entity2;

person
    has name,
    has firstname,
    has lastname,
    has gender,
    has birthday,
    has email,
    has age;

"name" sub resource, datatype string;
"firstname" sub resource, datatype string;
"lastname" sub resource, datatype string;
"gender" sub resource, datatype string;
"birthday" sub resource, datatype string;
"email" sub resource, datatype string;
"age" sub resource, datatype long;

person plays located-subject;

"acquaintance" sub role, is-abstract;
"acquaintance1" sub acquaintance;
"acquaintance2" sub acquaintance;
"knows" sub relation, relates acquaintance1, relates acquaintance2;
person plays acquaintance1, plays acquaintance2;

"student" sub role;
"enrolled-university" sub role;
"attends" sub relation, relates student, relates enrolled-university;
person plays student;
university plays enrolled-university;

"employee" sub role;
"employer" sub role;
"employment" sub relation, relates employee, relates employer;
person plays employee;
company plays employer;

"class-year" sub resource, datatype string;
"attends-resource-value" sub role;
"attends-resource-owner" sub role;
"attends-resource" sub relation, relates attends-resource-value, relates attends-resource-owner;
attends plays attends-resource-owner;
class-year plays attends-resource-value;

"employment-startdate" sub resource, datatype string;
"employment-resource-value" sub role;
"employment-resource-owner" sub role;
"employment-resource" sub relation, relates employment-resource-value, relates employment-resource-owner;
employment plays employment-resource-owner;
employment-startdate plays employment-resource-value;

# message
"message" sub entity2, is-abstract;

"message-resource-owner" sub role;
"message-resource-value" sub role;
"message-resource" sub relation, relates message-resource-value, relates message-resource-owner;
message plays message-resource-owner;

"content" sub resource, datatype string, plays message-resource-value;
"length" sub resource, datatype string, plays message-resource-value;

"liked" sub role;
"liker" sub role;
"likes" sub relation, relates liked, relates liker;
message plays liked;
person plays liker;

"written" sub role;
"writer" sub role;
"writes" sub relation, relates written, relates writer;
message plays written;
person plays writer;

message plays located-subject;

"comment" sub message;

"reply-owner" sub role;
"reply-content" sub role;
"reply" sub relation, relates reply-content, relates reply-owner;
comment plays reply-content;
message plays reply-owner;

"post" sub message;

"post-resource-owner" sub role;
"post-resource-value" sub role;
"post-resource" sub relation, relates post-resource-owner, relates post-resource-value;
post plays post-resource-owner;

"image-file" sub resource, datatype string, plays post-resource-value;

# forum
"forum-resource-owner" sub role;
"forum-resource-value" sub role;
"forum-resource" sub relation, relates forum-resource-value, relates forum-resource-owner;
forum plays forum-resource-owner;

"moderator" sub role;
"moderated" sub role;
"moderates" sub relation, relates moderator, relates moderated;
person plays moderator;
forum plays moderated;

"forum-member" sub role;
"membered-forum" sub role;
"membership" sub relation, relates forum-member, relates membered-forum;
person plays forum-member;
forum plays membered-forum;

"post-container" sub role;
"contained-post" sub role;
"containing" sub relation, relates post-container, relates contained-post;
post plays contained-post;
forum plays post-container;

# tag
"subject-tag" sub role;
"tagged-subject" sub role;
"tagging" sub relation, relates tagged-subject, relates subject-tag;
tag plays subject-tag;
forum plays tagged-subject;
message plays tagged-subject;
person plays tagged-subject;

# tag class
"group" sub role, is-abstract;
"subgroup" sub group;
"supergroup" sub group;
"subgrouping" sub relation, relates subgroup, relates supergroup;
category plays subgroup, plays supergroup;

"grouped-tag" sub role;
"tag-group" sub role;
"grouping" sub relation, relates grouped-tag, relates tag-group;
tag plays grouped-tag;
category plays tag-group;
