insert

$uni-cambridge isa university, has name "University of Cambridge";
$grakn isa company, has name "Grakn";
$cambridge isa city, has name "Cambridge";
$london isa city, has name "London";
$uk isa country, has name "UK";
$italy isa country, has name "Italy";
$europe isa continent, has name "Europe";

$alice isa person, has name "Alice", has age 19;
$bob isa person, has name "Bob", has age 21, has gender "male";
$charlie isa person, has name "Charlie", has age 23;
$denis isa person, has name "Denis", has age 25;
$frank isa person, has name "Frank", has age 27;
$gary isa person, has name "Gary", has age 29;
$karl isa person, has name "Karl Fischer", has age 31;
$forum1 isa forum, has name "forum1";

(acquaintance1: $bob, acquaintance2: $charlie) isa knows;
(located-subject: $uni-cambridge, subject-location: $cambridge) isa resides;
(located-subject: $grakn, subject-location: $london) isa resides;
(member-location: $cambridge, container-location: $uk) isa sublocate;
(member-location: $london, container-location: $uk) isa sublocate;
(member-location: $uk, container-location: $europe) isa sublocate;
(moderator: $bob, moderated: $forum1) isa moderates;

$ennio isa tag, has name"Ennio Morricone";
$john-wayne isa tag, has name "John Wayne";
$ozzy isa tag, has name "Ozzy Osbourne";
$rising-force isa tag, has name "Rising Force";
$terry isa tag, has name "Terry Pratchett";
$wells isa tag, has name "H. G. Wells";
$oscar-wilde isa tag, has name "Oscar Wilde";
$goethe isa tag, has name "Johann Wolfgang von Goethe";
$writer isa category, has name "Writer";
(grouped-tag: $terry, tag-group: $writer) isa grouping;
(grouped-tag: $wells, tag-group: $writer) isa grouping;
(grouped-tag: $goethe, tag-group: $writer) isa grouping;

$bach isa tag, has name "Johann Sebastian Bach";
$beethoven isa tag, has name "Ludwig van Beethoven";
$mozart isa tag, has name "Wolfgang Amadeus Mozart";

$roger-waters isa tag, has name "Roger Waters";

(tagged-subject: $alice, subject-tag: $wells) isa tagging;
(tagged-subject: $bob, subject-tag: $ennio) isa tagging;
(tagged-subject: $bob, subject-tag: $john-wayne) isa tagging;
(tagged-subject: $denis, subject-tag: $terry) isa tagging;
(tagged-subject: $denis, subject-tag: $oscar-wilde) isa tagging;
(tagged-subject: $frank, subject-tag: $beethoven) isa tagging;

(tagged-subject: $charlie, subject-tag: $ozzy) isa tagging;
(tagged-subject: $charlie, subject-tag: $rising-force) isa tagging;
(tagged-subject: $gary, subject-tag: $roger-waters) isa tagging;

(tagged-subject: $karl, subject-tag: $beethoven) isa tagging;
(tagged-subject: $karl, subject-tag: $mozart) isa tagging;
(tagged-subject: $karl, subject-tag: $goethe) isa tagging;


#####################################################
##################PRODUCT DATA#######################
#####################################################

# motorbike
$motorbike isa category, has name "motorbike";
$ducatti isa product, has name "Ducatti 1299", has min-age 18, has gender "male";
(typed-product: $ducatti, product-type: $motorbike) isa typing;
(product-made: $ducatti, product-origin: $italy) isa made-in;

# music
$cd isa category, has name "cd";
$theWall isa product, has name "The Wall";
(typed-product: $theWall,product-type: $cd) isa typing;
$blizzard isa product, has name "Blizzard of Ozz";
(typed-product: $blizzard, product-type: $cd) isa typing;
$nocturnes isa product, has name "Nocturnes";
(typed-product: $nocturnes, product-type: $cd) isa typing;

# movie
$movie isa category, has name "movie";
$goodBadUgly isa product, has name "The Good the Bad the Ugly";
(typed-product: $goodBadUgly, product-type: $movie) isa typing;
$godfather isa product, has name "Godfather";
(typed-product: $godfather, product-type: $movie) isa typing;
$dumb isa product, has name "Dumb and dumber";
(typed-product: $dumb, product-type: $movie) isa typing;

# book
$book isa category, has name "book";
$dorianGray isa product, has name "Dorian Gray";
(typed-product: $dorianGray, product-type: $book) isa typing;
$colourOfMagic isa product, has name "Colour of Magic";
(typed-product: $colourOfMagic, product-type: $book) isa typing;
$warOfWorlds isa product, has name "War of the Worlds";
(typed-product: $warOfWorlds, product-type: $book) isa typing;
$crime isa product, has name "Crime and Punishment";
(typed-product: $crime, product-type: $book) isa typing;
$farm isa product, has name "Animal Farm";
(typed-product: $farm, product-type: $book) isa typing;
$alice-in-wonderland isa product, has name "Adventures in Wonderland";
(typed-product: $alice-in-wonderland, product-type: $book) isa typing;
$orientExpress isa product, has name "Orient Express";
(typed-product: $orientExpress, product-type: $book) isa typing;
$fairy isa product, has name "Fairy Tales";
(typed-product: $fairy, product-type: $book) isa typing;
$jeeves isa product, has name "My Man Jeeves";
(typed-product: $jeeves, product-type: $book) isa typing;
$rings isa product, has name "Lord of the rings";
(typed-product: $rings, product-type: $book) isa typing;
$harry isa product, has name "Harry Potter";
(typed-product: $harry, product-type: $book) isa typing;
$sherlock isa product, has name "Sherlock Holmes";
(typed-product: $sherlock, product-type: $book) isa typing;
$forWhom isa product, has name "For Whom he Bell Tolls";
(typed-product: $forWhom, product-type: $book) isa typing;
$miceAndMen isa product, has name "Of Mice and Men";
(typed-product: $miceAndMen, product-type: $book) isa typing;
$trial isa product, has name "Trial";
(typed-product: $trial, product-type: $book) isa typing;
$faust isa product, has name "Faust";
(typed-product: $faust, product-type: $book) isa typing;


# paintings
$painting isa category, has name "painting";
$lesElephants isa product, has name "Les Elephants";
(typed-product: $lesElephants, product-type: $painting) isa typing;
$waterLillies isa product, has name "Water Lillies";
(typed-product: $waterLillies, product-type: $painting) isa typing;
$nightWatch isa product, has name "Night Watch";
(typed-product: $nightWatch, product-type: $painting) isa typing;
$monaLisa isa product, has name "Mona Lisa";
(typed-product: $monaLisa, product-type: $painting) isa typing;
$raphael isa product, has name "Madonna of the pinks";
(typed-product: $raphael, product-type: $painting) isa typing;
$bacchus isa product, has name "Bacchus and Ariadne";
(typed-product: $bacchus, product-type: $painting) isa typing;
$sunflowers isa product, has name "Sunflowers";
(typed-product: $sunflowers, product-type: $painting) isa typing;
$universe isa product, has name "Controller of the Universe";
(typed-product: $universe, product-type: $painting) isa typing;
$grayTree isa product, has name "Gray Tree";
(typed-product: $grayTree, product-type: $painting) isa typing;
$lastJudgement isa product, has name "Last Judgement";
(typed-product: $lastJudgement, product-type: $painting) isa typing;

# instrument
$guitar isa category, has name "guitar";
$stratocaster isa product, has name "Stratocaster";
(typed-product: $stratocaster, product-type: $guitar) isa typing;

# bands
$band isa category, has name "Band";
$musical-artist isa category, has name "MusicalArtist";

$beatles isa tag, has name "Beatles";
(grouped-tag: $beatles,tag-group: $band) isa grouping;
$pinkFloyd isa tag, has name "Pink Floyd";
(grouped-tag: $pinkFloyd,tag-group: $band) isa grouping;
$rollingStones isa tag, has name "Rolling Stones";
(grouped-tag: $rollingStones,tag-group: $band) isa grouping;
$cream isa tag, has name "Cream";
(grouped-tag: $cream,tag-group: $band) isa grouping;
$yardbirds isa tag, has name "Yardbirds";
(grouped-tag: $yardbirds,tag-group: $band) isa grouping;
$simonAndGarfunkel isa tag, has name "Simon and Garfunkel";
(grouped-tag: $simonAndGarfunkel,tag-group: $band) isa grouping;
$blackSabbath isa tag, has name "Black Sabbath";
(grouped-tag: $blackSabbath,tag-group: $band) isa grouping;
$wailers isa tag, has name "Bob Marley and the Wailers";
(grouped-tag: $wailers,tag-group: $band) isa grouping;

$buckethead isa tag, has name "Buckethead";
(grouped-tag: $buckethead,tag-group: $band) isa grouping;

$primus isa tag, has name "Primus";
(grouped-tag: $primus, tag-group: $band) isa grouping;

$linkinPark isa tag, has name "Linkin park";
(grouped-tag: $linkinPark, tag-group: $band) isa grouping;

$limpBizkit isa tag, has name "Limp Bizkit";
(grouped-tag: $limpBizkit, tag-group: $band) isa grouping;

$jimiHendrix isa tag, has name "Jimi Hendrix";
(grouped-tag: $jimiHendrix, tag-group: $musical-artist) isa grouping;

$slash isa tag, has name "Slash";
(grouped-tag: $slash, tag-group: $musical-artist) isa grouping;

$yngwie isa tag, has name "Yngwie Malmsteen";
(grouped-tag: $yngwie, tag-group: $musical-artist) isa grouping;

$steveVai isa tag, has name "Steve Vai";
(grouped-tag: $steveVai, tag-group: $musical-artist) isa grouping;

$cacophony isa tag, has name "Cacophony";
(grouped-tag: $cacophony, tag-group: $band) isa grouping;

$vanHalen isa tag, has name "Van Halen";
(grouped-tag: $vanHalen, tag-group: $band) isa grouping;

$metallica isa tag, has name "Metallica";
(grouped-tag: $metallica, tag-group: $band) isa grouping;

$megadeth isa tag, has name "Megadeth";
(grouped-tag: $megadeth, tag-group: $band) isa grouping;

$slayer isa tag, has name "Slayer";
(grouped-tag: $slayer, tag-group: $band) isa grouping;

$pantera isa tag, has name "Pantera";
(grouped-tag: $pantera, tag-group: $band) isa grouping;

$superjoint isa tag, has name "Superjoint Ritual";
(grouped-tag: $superjoint, tag-group: $band) isa grouping;

$ironMaiden isa tag, has name "Iron Maiden";
(grouped-tag: $ironMaiden, tag-group: $band) isa grouping;

$judasPriest isa tag, has name "Judas Priest";
(grouped-tag: $judasPriest, tag-group: $band) isa grouping;

$thinLizzy isa tag, has name "Thin Lizzy";
(grouped-tag: $thinLizzy, tag-group: $band) isa grouping;

$ledZeppelin isa tag, has name "Led Zeppelin";
(grouped-tag: $ledZeppelin, tag-group: $band) isa grouping;

$deepPurple isa tag, has name "Deep Purple";
(grouped-tag: $deepPurple, tag-group: $band) isa grouping;

$queen isa tag, has name "Queen";
(grouped-tag: $queen, tag-group: $band) isa grouping;

tag plays recommended-product;

