insert 

entity isa entity-type, is-abstract;
product sub entity
    has-resource name
    has-resource min-age
    has-resource max-age
    has-resource gender;

# product resources
min-age isa resource-type, datatype long;
max-age isa resource-type, datatype long;
gender isa resource-type, datatype string;

product-made isa role-type;
product-origin isa role-type;
made-in isa relation-type, has-role product-origin, has-role product-made;
product plays-role product-made
    plays-role typed-product;

recommended-product isa role-type;
recommended-customer isa role-type;
recommendation isa relation-type, has-role recommended-product, has-role recommended-customer;
product plays-role recommended-product;

person isa entity-type;
person plays-role recommended-customer;

place sub entity;
place plays-role product-origin;

typed-product isa role-type;
product-type isa role-type;
typing isa relation-type, has-role typed-product, has-role product-type;
category isa entity-type
    has-resource name
    plays-role product-type
    plays-role typed-product;