insert

###################################################
####################Ontology######################
#################################################

"entity2" sub entity
    has-resource index;
"a-entity" sub entity2;

"P-from" sub role;
"P-to" sub role;
"P" sub relation, has-role P-from, has-role P-to;
entity2 plays-role P-from plays-role P-to;

"Q-from" sub role;
"Q-to" sub role;
"Q" sub relation, has-role Q-from, has-role Q-to;
entity2 plays-role Q-from plays-role Q-to;

"S-from" sub role;
"S-to" sub role;
"S" sub relation, has-role S-from, has-role S-to;
entity2 plays-role S-from plays-role S-to;

"index" sub resource, datatype string;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
(Q-from: $x, Q-to: $y) isa Q;},
rhs {
(P-from: $x, P-to: $y) isa P;};

isa inference-rule,
lhs {
(Q-from: $x, Q-to: $z) isa Q;
(P-from: $z, P-to: $y) isa P;},
rhs {
(P-from: $x, P-to: $y) isa P;};

isa inference-rule,
lhs {
(P-from: $x, P-to: $y) isa P;},
rhs {
(S-from: $x, S-to: $y) isa S;};