insert

###################################################
####################Ontology######################
#################################################

"entity2" sub entity
    has index
    plays S-from
    plays S-to;
"a-entity" sub entity2;

"P-from" sub role;
"P-to" sub role;
"P" sub relation, relates P-from, relates P-to;
entity2 plays P-from plays P-to;

"Q-from" sub role;
"Q-to" sub role;
"Q" sub relation, relates Q-from, relates Q-to;
entity2 plays Q-from plays Q-to;

"S-from" sub role;
"S-to" sub role;
"S" sub relation, relates S-from, relates S-to;


"index" sub resource, datatype string;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
(Q-from: $x, Q-to: $y) isa Q;},
rhs {
(P-from: $x, P-to: $y) isa P;};

isa inference-rule,
lhs {
(Q-from: $x, Q-to: $z) isa Q;
(P-from: $z, P-to: $y) isa P;},
rhs {
(P-from: $x, P-to: $y) isa P;};

isa inference-rule,
lhs {
(P-from: $x, P-to: $y) isa P;},
rhs {
(S-from: $x, S-to: $y) isa S;};