insert

###################################################
####################Ontology######################
#################################################


"vertex" sub entity
   has index;
"start-vertex" sub entity
   has index;

"arc-from" sub role;
"arc-to" sub role;
"arc" sub relation, relates arc-from, relates arc-to;
vertex plays arc-from, plays arc-to;
start-vertex plays arc-from;

"path-from" sub role;
"path-to" sub role;
"path" sub relation, relates path-from, relates path-to;
vertex plays path-from, plays path-to;
start-vertex plays path-from;

"index" sub resource, datatype string;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
(arc-from: $x, arc-to: $y) isa arc;},
rhs {
(path-from: $x, path-to: $y) isa path;};

isa inference-rule,
lhs {
(path-from: $x, path-to: $z) isa path;
(path-from: $z, path-to: $y) isa path;},
rhs {
(path-from: $x, path-to: $y) isa path;};
