insert

###################################################
####################Ontology######################
#################################################

"start-vertex" sub entity;
"vertex" sub entity;

"arcA" sub role;
"arcB" sub role;
"arc" sub relation, has-role arcA, has-role arcB;
vertex plays-role arcA, plays-role arcB;
start-vertex plays-role arcA, plays-role arcB;

"pathA" sub role;
"pathB" sub role;
"path" sub relation, has-role pathA, has-role pathB;
vertex plays-role pathA, plays-role pathB;
start-vertex plays-role pathA, plays-role pathB;

####################################################
##################RULES#############################
####################################################

"R1" isa inference-rule,
lhs {
($x, $y) isa arc;},
rhs {
($x, $y) isa path;};

"R2" isa inference-rule,
lhs {
($x, $z) isa path;
($z, y) isa path;},
rhs {
($x, $y) isa path;};
