insert

###################################################
####################Ontology######################
#################################################


"vertex" sub entity
   has-resource index;
"start-vertex" sub entity
   has-resource index;

"arc-from" sub role;
"arc-to" sub role;
"arc" sub relation, has-role arc-from, has-role arc-to;
vertex plays-role arc-from, plays-role arc-to;
start-vertex plays-role arc-from;

"path-from" sub role;
"path-to" sub role;
"path" sub relation, has-role path-from, has-role path-to;
vertex plays-role path-from, plays-role path-to;
start-vertex plays-role path-from;

"index" sub resource, datatype string;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
(arc-from: $x, arc-to: $y) isa arc;},
rhs {
(path-from: $x, path-to: $y) isa path;};

isa inference-rule,
lhs {
(path-from: $x, path-to: $z) isa path;
(path-from: $z, path-to: $y) isa path;},
rhs {
(path-from: $x, path-to: $y) isa path;};
