insert

###################################################
####################Ontology######################
#################################################

"start-vertex" sub entity
has index;
"vertex" sub entity
has index;

"arcA" sub role;
"arcB" sub role;
"arc" sub relation, relates arcA, relates arcB;
vertex plays-role arcA, plays-role arcB;
start-vertex plays-role arcA, plays-role arcB;

"pathA" sub role;
"pathB" sub role;
"path" sub relation, relates pathA, relates pathB;
vertex plays-role pathA, plays-role pathB;
start-vertex plays-role pathA, plays-role pathB;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
($x, $y) isa arc;},
rhs {
($x, $y) isa path;};

isa inference-rule,
lhs {
($x, $z) isa path;
($z, y) isa path;},
rhs {
($x, $y) isa path;};
