insert

######################################################
####################ONTOLOGY##########################
######################################################

"entity2" sub entity;

"P1-role-A" sub role;
"P1-role-B" sub role;
"P1" sub relation, relates P1-role-A, relates P1-role-B;
entity2 plays P1-role-A, plays P1-role-B;

"P2-role-A" sub role;
"P2-role-B" sub role;
"P2" sub relation, relates P2-role-A, relates P2-role-B;
entity2 plays P2-role-A, plays P2-role-B;

"P-role-A" sub role;
"P-role-B" sub role;
"P" sub relation, relates P-role-A, relates P-role-B;
entity2 plays P-role-A, plays P-role-B;

"Q-role-A" sub role;
"Q-role-B" sub role;
"Q" sub relation, relates Q-role-A, relates Q-role-B;
entity2 plays Q-role-A, plays Q-role-B;

"B1-role-A" sub role;
"B1-role-B" sub role;
"B1" sub relation, relates B1-role-A, relates B1-role-B;
entity2 plays B1-role-A, plays B1-role-B;

"B2-role-A" sub role;
"B2-role-B" sub role;
"B2" sub relation, relates B2-role-A, relates B2-role-B;
entity2 plays B2-role-A, plays B2-role-B;

"B3-role-A" sub role;
"B3-role-B" sub role;
"B3" sub relation, relates B3-role-A, relates B3-role-B;
entity2 plays B3-role-A, plays B3-role-B;

"B4-role-A" sub role;
"B4-role-B" sub role;
"B4" sub relation, relates B4-role-A, relates B4-role-B;
entity2 plays B4-role-A, plays B4-role-B;

"B5-role-A" sub role;
"B5-role-B" sub role;
"B5" sub relation, relates B5-role-A, relates B5-role-B;
entity2 plays B5-role-A, plays B5-role-B;

##################################################
####################RULES##########################
##################################################

isa inference-rule,
lhs {
($x, $z) isa P1;
($z, $y) isa Q;},
rhs {
($x, $y) isa P;};

isa inference-rule,
lhs {
($x, $z) isa P;
($z, $y) isa P2;},
rhs {
($x, $y) isa Q;};

isa inference-rule,
lhs {
($x, $y) isa B3;},
rhs {
($x, $y) isa P;};

isa inference-rule,
lhs {
($x, $z) isa B1;
($z, $y) isa P1;},
rhs {
($x, $y) isa P1;};

isa inference-rule,
lhs {
($x, $y) isa B4;}
rhs {
($x, $y) isa P1;};

isa inference-rule,
lhs {
($x, $z) isa B2;
($z, $y) isa P2;},
rhs {
($x, $y) isa P2;};

isa inference-rule,
lhs {
($x, $y) isa B5;},
rhs {
($x, $y) isa P2;};
