insert

###################################################
####################Ontology######################
#################################################

"entity2" sub entity
    has name;
"Human" sub entity2;

"parent" sub role;
"child" sub role;
"Parent" sub relation, relates parent, relates child;
entity2 plays parent, plays child;

"SG-role-A" sub role;
"SG-role-B" sub role;
"SameGen" sub relation, relates SG-role-A, relates SG-role-B;
entity2 plays SG-role-A, plays SG-role-B;

"name" sub resource, datatype string;

####################################################
##################DATA#############################
####################################################

$a isa entity2, has name "a";
$b isa entity2, has name "b";
$c isa entity2, has name "c";
$d isa Human, has name "d";
$e isa entity2, has name "e";
$f isa entity2, has name "f";
$g isa entity2, has name "g";
$h isa entity2, has name "h";

(parent: $a, child: $b) isa Parent;
(parent: $a, child: $c) isa Parent;
(parent: $b, child: $d) isa Parent;
(parent: $c, child: $d) isa Parent;
(parent: $e, child: $d) isa Parent;
(parent: $f, child: $e) isa Parent;

#Extra data
(parent: $g, child: $f) isa Parent;
(parent: $h, child: $g) isa Parent;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
$x isa Human;},
rhs {
($x, $x) isa SameGen;};

isa inference-rule,
lhs {
(parent: $x, child: $u) isa Parent;
($u, $v) isa SameGen;
(parent: $y, child: $v) isa Parent;},
rhs {
($x, $y) isa SameGen;};

