insert

###################################################
####################Ontology######################
#################################################

"entity" isa entity-type
    has-resource index;
"q" sub entity;

"N-TC-roleA" isa role-type;
"N-TC-roleB" isa role-type;
"N-TC" isa relation-type, has-role N-TC-roleB, has-role N-TC-roleA;
entity plays-role N-TC-roleB, plays-role N-TC-roleA;

"TC-roleA" isa role-type;
"TC-roleB" isa role-type;
"TC" isa relation-type, has-role TC-roleA, has-role TC-roleB;
entity plays-role TC-roleA, plays-role TC-roleB;

"P-roleA" isa role-type;
"P-roleB" isa role-type;
"P" isa relation-type, has-role P-roleA, has-role P-roleB;
entity plays-role P-roleA, plays-role P-roleB;

"index" isa resource-type, datatype string;

####################################################
##################DATA#############################
####################################################

$a isa entity, has index "a";
$a1 isa entity, has index "a1";
$a2 isa q, has index "a2";

(P-roleA: $a1, P-roleB: $a) isa P;
(P-roleA: $a2, P-roleB: $a1) isa P;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
$x isa q;
($x, $y) isa TC;},
rhs {
($x, $y) isa N-TC;};

isa inference-rule,
lhs {
($x, $y) isa P;},
rhs {
($x, $y) isa TC;};

isa inference-rule,
lhs {
($x, $z) isa P;
($z, $y) isa TC;},
rhs {
($x, $y) isa TC;};

