insert

#Roles

role1 sub role;
role2 sub role;
role3 sub role;


#Entities

entity1 sub entity
	plays-role role1;

entity2 sub entity
	plays-role role1
	plays-role role2;

entity3 sub entity
    plays-role role1
    plays-role role2
    plays-role role3;

entity4 sub entity
    plays-role role2
    plays-role role3;

entity5 sub entity
    plays-role role1;


#Relations

relation1 sub relation
	has-role role1
	has-role role2
	has-role role3;

relation2 sub relation
    has-role role1
    has-role role2
    has-role role3;

#Rules

isa inference-rule
	lhs {
		$x isa entity1;
		$y isa entity2;
		$z isa entity3;
	}
	rhs {
		(role1:$x, role2:$y, role3: $z) isa relation1;
	};


