insert

###################################################
####################Ontology######################
#################################################

"person" sub entity
      has-resource name;

"parent" sub role;
"child" sub role;
"Parent" sub relation, has-role parent, has-role child;
person plays-role parent, plays-role child;

"sibA" sub role;
"sibB" sub role;
"Sibling" sub relation, has-role sibA, has-role sibB;
person plays-role sibA, plays-role sibB;

"SG-role-A" sub role;
"SG-role-B" sub role;
"SameGen" sub relation, has-role SG-role-A, has-role SG-role-B;
person plays-role SG-role-A, plays-role SG-role-B;

"name" sub resource, datatype string;

####################################################
##################DATA#############################
####################################################

$ann isa person, has name "ann";
$bill isa person, has name "bill";
$john isa person, has name "john";
$peter isa person, has name "peter";

(parent: $john, child: $ann) isa Parent;
(parent: $john, child: $peter) isa Parent;
(parent: $john, child: $bill) isa Parent;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
($x, $y) isa Sibling;},
rhs {
($x, $y) isa SameGen;};

isa inference-rule,
lhs {
(parent: $x, child: $u) isa Parent;
($u, $v) isa SameGen;
(parent: $y, child: $v) isa Parent;},
rhs {
($x, $y) isa SameGen;};

isa inference-rule,
lhs {
(parent: $z, child: $x) isa Parent;
(parent: $z, child: $y) isa Parent;},
rhs {
($x, $y) isa Sibling;};