insert

#Roles

role1 sub role;
role2 sub role;


#Entities

entity1 sub entity
	plays role1
	plays role2;

entity2 sub entity
	plays role1
	plays role2;


#Relations

relation1 sub relation
	relates role1
	relates role2;


#Rules

isa inference-rule 
	lhs {
		$x isa entity1;
	}
	rhs {
		(role1:$x, role2:$x) isa relation1;
	};


#Data

isa entity1;
isa entity2;