insert

entity1 sub entity
	has res1
	has res2;

#Resources
res1 sub resource datatype string;
res2 sub res1;

#Rules

isa inference-rule 
	lhs {
		$x isa entity1 has res1 $r1;
	}
	rhs {
		$x has res2 $r1;
	};

#Data

$x isa entity1 has res1 "value";