insert

general-entity sub entity
	has res1
	has res2;

sub-entity sub general-entity;

#Resources
res1 sub resource datatype long;
res2 sub resource datatype boolean;

#Rules

isa inference-rule
lhs {
$x isa general-entity, has res1 > 0;
}
rhs {
$x has res2 true;
};

#Data
$x isa sub-entity has res1 1;