insert

role1 sub role;
role2 sub role;

entity1 sub entity
	has res1
	plays role2
	plays role1;

relation1 sub relation
	relates role1
	relates role2
	has res1;

#Resources
res1 sub resource datatype string;

#Rules

isa inference-rule
lhs {
    $x isa entity1, has res1 $y;
    $z isa relation1;
}
rhs {
    $z has res1 $y;
};

#Data

$x isa entity1 has res1 "value1";
(role1:$x, role2:$x) isa relation1;