insert

#Roles

role1 sub role;
role2 sub role;


#Entities

entity1 sub entity
	plays-role role1
	plays-role role2;

entity2 sub entity
	plays-role role1
	plays-role role2;


#Relations

relation1 sub relation
	has-role role1
	has-role role2;


#Rules

isa inference-rule 
	lhs {
		$x isa entity1;
	}
	rhs {
		$y isa entity2;
	};


#Data

$x isa entity1;