insert

#######################################################
########################ONTOLOGY######################
#######################################################

"context-preference-owner" sub role;
"context-preference-id" sub role;
"context-preference" sub relation, relates context-preference-owner, relates context-preference-id;

"preferred-context" sub resource, datatype string;

"body-preference-owner" sub role;
"body-preference-id" sub role;
"body-preference" sub relation, relates body-preference-owner, relates body-preference-id;

"preferred-body" sub resource, datatype string;

"dryness-preference-owner" sub role;
"dryness-preference-id" sub role;
"dryness-preference" sub relation, relates dryness-preference-owner, relates dryness-preference-id;

"preferred-dryness" sub resource, datatype string;

"entree-preference-owner" sub role;
"entree-preference-id" sub role;
"entree-preference" sub relation, relates entree-preference-owner, relates entree-preference-id;

"preferred-entree" sub resource, datatype string;

"colour-preference-owner" sub role;
"colour-preference-id" sub role;
"colour-preference" sub relation, relates colour-preference-owner, relates colour-preference-id;

"preferred-colour" sub resource, datatype string;

"sparklingness-preference-owner" sub role;
"sparklingness-preference-id" sub role;
"sparkingness-preference" sub relation, relates sparklingness-preference-owner, relates sparklingness-preference-id;

"preferred-sparklingness" sub resource, datatype string;

"recommended-wine" sub role;
"recommendation-owner" sub role;
"wine-recommendation" sub relation, relates recommended-wine, relates recommendation-owner;

"recommended-generic-wine-type" sub resource, datatype string;

"person" sub entity
    has name;
person plays recommendation-owner;
person has preferred-context;
person has preferred-body;
person has preferred-dryness;
person has preferred-entree;
person has preferred-colour;
person has preferred-sparklingness;
person has recommended-generic-wine-type;

"name" sub resource, datatype string;

"wine" sub entity
    has name;
wine plays recommended-wine;

#######################################################
######################DATA########################
#######################################################

#recommend Cabernet Sauvignion
$Alice isa person, has name "Alice";
$Alice has preferred-context "aperitif";
$Alice has preferred-sparklingness "non-sparkling";
$Alice has preferred-body "full";
$Alice has preferred-colour "red";

#recommend White Champagne
$Bob isa person, has name "Bob";
$Bob has preferred-context "aperitif";
$Bob has preferred-sparklingness "sparkling";
$Bob has preferred-body "full";
$Bob has preferred-colour "white";

#recommend Pinot Grigio
$Charlie isa person, has name "Charlie";
$Charlie has preferred-context "entree";
$Charlie has preferred-entree "white meat";
$Charlie has preferred-colour "rose";

#recommend Busuioaca Romaneasca
$Denis isa person, has name "Denis";
$Denis has preferred-context "entree";
$Denis has preferred-entree "steak";
$Denis has preferred-colour "rose";

#recommend Tamaioasa Romaneasca
$Eva isa person, has name "Eva";
$Eva has preferred-context "aperitif";
$Eva has preferred-body "full";
$Eva has preferred-sparklingness "non-sparkling";
$Eva has preferred-colour "white";

#recommend Riojo Blanco
$Frank isa person, has name "Frank";
$Frank has preferred-context "entree";
$Frank has preferred-entree "barbecue";
$Frank has preferred-body "full";
$Frank has preferred-sparklingness "non-sparkling";
$Frank has preferred-colour "white";

#wines
$white-champagne isa wine, has name "White Champagne";
$cabernet-sauvignion isa wine, has name "Cabernet Sauvignion";
$tamaioasa-romaneasca isa wine, has name "Tamaioasa Romaneasca";
$busuioaca-romaneasca isa wine, has name "Busuioaca Romaneasca";
$pinot-noir isa wine, has name "Pinot Noir";
$muscat-sec isa wine, has name "Muscat Sec";
$pinot-grigio-rose isa wine, has name "Pinot Grigio Rose";
$corbieres isa wine, has name "Corbieres 2003";
$chateu isa wine, has name "Chateau Agnel 2000";
$rosso isa wine, has name "Rosso di Sicilia 2004";
$riojo-blanco isa wine, has name "Riojo Blanco CVNE 2003";
$tamaioasa-regala isa wine, has name "Tamaioasa Regala";
$riojo-tempranillo isa wine, has name "Riojo Tempranillo";
$chianti isa wine, has name "Chianti";
$white-riesling isa wine, has name "White Riesling";
$burgundy isa wine, has name "Burgundy";
$chardonnay isa wine, has name "Chardonnay";
$bordeaux isa wine, has name "Bordeaux Blanc";
$feteasca-regala isa wine, has name "Feteasca Regala";
$feteasca-roz isa wine, has name "Feteasca Roz";
$feteasca-neagra isa wine, has name "Feteasca Neagra";
$sauvignion-blanc isa wine, has name "Sauvignion Blanc";