java_library(
    name = "javax-ws-rs-api",
    exports = [
        "//external:jar/javax/ws/rs/javax-ws-rs-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "jsr311-api",
    exports = [
        "//external:jar/javax/ws/rs/jsr311-api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


