java_library(
    name = "jopt-simple",
    exports = [
        "//external:jar/net/sf/jopt-simple/jopt-simple"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


