java_library(
    name = "resolve",
    srcs = glob([
        "*.java",
        ]
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava",
        "//concept/answer:answer",
        "//graql/reasoner:reasoner",
        "//kb/concept/api:api",
        "//kb/server:server",
        "@graknlabs_graql//java:graql",
    ],
)