java_library(
    name = "generics-resolver",
    exports = [
        "//external:jar/ru/vyarus/generics-resolver"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


