#
# GRAKN.AI - THE KNOWLEDGE GRAPH
# Copyright (C) 2018 Grakn Labs Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

package(default_visibility = ["//test-integration/graql/reasoner:__subpackages__"])

filegroup(
    name = "ancestor",
    srcs = ["ancestor.gql"],
)

filegroup(
    name = "ancestor-friend",
    srcs = ["ancestor-friend.gql"],
)

filegroup(
    name = "nguyen",
    srcs = ["nguyen.gql"],
)

filegroup(
    name = "reachability",
    srcs = ["reachability.gql"],
)

filegroup(
    name = "reachability-symmetric",
    srcs = ["reachability-symmetric.gql"],
)

filegroup(
    name = "recursivity",
    srcs = ["recursivity.gql"],
)

filegroup(
    name = "recursivity-rsg",
    srcs = ["recursivity-rsg.gql"],
)

filegroup(
    name = "recursivity-sg",
    srcs = ["recursivity-sg.gql"],
)

filegroup(
    name = "recursivity-tx",
    srcs = ["recursivity-tc.gql"],
)

filegroup(
    name = "same-generation",
    srcs = ["same-generation.gql"],
)

filegroup(
    name = "tail-recursion",
    srcs = ["tail-recursion.gql"],
)
