define

indexable sub entity,
    has index;

traversable sub indexable,
    plays from,
    plays to;

vertex sub traversable;
node sub traversable;

link sub relation, relates from, relates to;
indirect-link sub relation, relates from, relates to;
reachable sub relation, relates from, relates to;
unreachable sub relation, relates from, relates to;

index sub attribute, datatype string;

reachability-transitivityA
when {
    (from: $x, to: $y) isa link;
},
then {
    (from: $x, to: $y) isa reachable;
};

reachability-transitivityB
when {
    (from: $x, to: $z) isa link;
    (from: $z, to: $y) isa reachable;
},
then {
    (from: $x, to: $y) isa reachable;
};

#node-ruleA
#when {
#    ($x) isa link;
#},
#then {
#    $x isa node;
#};

indirect-link-rule
when {
    (from: $x, to: $y) isa reachable;
    not {(from: $x, to: $y) isa link;};
},
then {
    (from: $x, to: $y) isa indirect-link;
};

unreachability-rule
when {
    $x isa vertex;
    $y isa vertex;
    #$x isa node;
    #$y isa node;
    not {(from: $x, to: $y) isa reachable;};
},
then {
    (from: $x, to: $y) isa unreachable;
};

