define

###################################################
####################Schema######################
#################################################

vertex sub entity,
    has index;

coordinate sub role;
link sub relation, relates coordinate;
vertex plays coordinate;

reachable sub relation, relates coordinate;
vertex plays coordinate;

index sub attribute, datatype string;

####################################################
##################RULES#############################
####################################################

rule-1
when {
($x, $y) isa link;},
then {
($x, $y) isa reachable;};

rule-2
when {
($x, $z) isa link;
($z, $y) isa reachable;},
then {
($x, $y) isa reachable;};

insert

####################################################
##################DATA#############################
####################################################

$a isa vertex, has index "a";
$b isa vertex, has index "b";
$c isa vertex, has index "c";
$d isa vertex, has index "d";

(coordinate: $a, coordinate: $b) isa link;
(coordinate: $b, coordinate: $c) isa link;
(coordinate: $c, coordinate: $c) isa link;
(coordinate: $c, coordinate: $d) isa link;

