define

indexable sub entity,
    has index;

traversable sub indexable,
    plays from,
    plays to;

vertex sub traversable;
node sub traversable;

link sub relationship, relates from, relates to;
indirect-link sub relationship, relates from, relates to;
reachable sub relationship, relates from, relates to;
unreachable sub relationship, relates from, relates to;

index sub attribute, datatype string;

reachability-transitivityA
when {
    (from: $x, to: $y) isa link;
},
then {
    (from: $x, to: $y) isa reachable;
};

reachability-transitivityB
when {
    (from: $x, to: $z) isa link;
    (from: $z, to: $y) isa reachable;
},
then {
    (from: $x, to: $y) isa reachable;
};

node-ruleA
when {
    (from: $x, to: $y) isa link;
},
then {
    $x isa node;
};

node-ruleB
when {
    (from: $x, to: $y) isa link;
},
then {
    $y isa node;
};

node-reachability
when {

    (from: $x, to: $y) isa link;
},
then {
    $y isa node;
};

indirect-link-rule
when {
    (from: $x, to: $y) isa reachable;
    not {(from: $x, to: $y) isa link;};
},
then {
    (from: $x, to: $y) isa indirect-link;
};

unreachability-rule
when {
    $x isa vertex;
    $y isa vertex;
    #$x isa node;
    #$y isa node;
    not {(from: $x, to: $y) isa reachable;};
},
then {
    (from: $x, to: $y) isa unreachable;
};

