define

#######################################################
########################Schema######################
#######################################################

entity2 sub entity,
    has index;

R-role-A sub role;
R-role-B sub role;
R sub relation, relates R-role-A, relates R-role-B;
entity2 plays R-role-A, plays R-role-B;

E-role-A sub role;
E-role-B sub role;
E sub relation, relates E-role-A, relates E-role-B;
entity2 plays E-role-A, plays E-role-B;

F-role-A sub role;
F-role-B sub role;
F sub relation, relates F-role-A, relates F-role-B;
entity2 plays F-role-A, plays F-role-B;

G-role-A sub role;
G-role-B sub role;
G sub relation, relates G-role-A, relates G-role-B;
entity2 plays G-role-A, plays G-role-B;

H-role-A sub role;
H-role-B sub role;
H sub relation, relates H-role-A, relates H-role-B;
entity2 plays H-role-A, plays H-role-B;

index sub attribute, datatype string;

insert

#######################################################
######################DATA########################
#######################################################

$i isa entity2, has index "i";
$j isa entity2, has index "j";
$k isa entity2, has index "k";
$l isa entity2, has index "l";
$m isa entity2, has index "m";
$n isa entity2, has index "n";
$o isa entity2, has index "o";
$p isa entity2, has index "p";
$q isa entity2, has index "q";
$r isa entity2, has index "r";
$s isa entity2, has index "s";
$t isa entity2, has index "t";
$u isa entity2, has index "u";
$v isa entity2, has index "v";

(E-role-A: $i, E-role-B: $j) isa E;
(E-role-A: $l, E-role-B: $m) isa E;
(E-role-A: $n, E-role-B: $o) isa E;
(E-role-A: $q, E-role-B: $r) isa E;
(E-role-A: $t, E-role-B: $u) isa E;

(F-role-A: $i, F-role-B: $i) isa F;
(F-role-A: $i, F-role-B: $k) isa F;
(F-role-A: $k, F-role-B: $l) isa F;

(G-role-A: $m, G-role-B: $n) isa G;
(G-role-A: $p, G-role-B: $q) isa G;
(G-role-A: $s, G-role-B: $t) isa G;

(H-role-A: $o, H-role-B: $p) isa H;
(H-role-A: $r, H-role-B: $s) isa H;
(H-role-A: $u, H-role-B: $v) isa H;

define

################################################################
################################RULES#################################
################################################################

rule-1
when {
(E-role-A: $x, E-role-B: $y) isa E;},
then {
(R-role-A: $x, R-role-B: $y) isa R;};

rule-2
when {
(F-role-A: $x, F-role-B: $t) isa F;
(R-role-A: $t, R-role-B: $u) isa R;
(G-role-A: $u, G-role-B: $v) isa G;
(R-role-A: $v, R-role-B: $w) isa R;
(H-role-A: $w, H-role-B: $y) isa H;},
then {
(R-role-A: $x, R-role-B: $y) isa R;};

