java_library(
    name = "profiler",
    exports = [
        "//external:jar/com/papertrail/profiler"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/joda_time:joda_time"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


