from typing import Type
import grpc

from src import Grakn
from src.Transaction import Transaction
from src.service.Session.TransactionService import TransactionService
from src.service.Session.autogenerated.Session_pb2_grpc import SessionServiceStub


class Session(object):

    def __init__(self, uri: str, keyspace: str):

        self.keyspace = keyspace
        self.uri = uri

        self._channel = grpc.insecure_channel(uri)
        self._stub = SessionServiceStub(self._channel)


    def transaction(self, tx_type):
        # create a transaction service which hides GRPC usage
        transaction_service = TransactionService(self.keyspace, tx_type, self._stub.transaction)
        return Transaction(transaction_service)

    def close(self):
        self._channel.close()

