java_library(
    name = "zookeeper",
    exports = [
        "//external:jar/org/apache/zookeeper/zookeeper"
    ],
    runtime_deps = [
        "//dependencies/maven/io/netty:netty",
        "//dependencies/maven/jline:jline"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


