java_library(
    name = "mail",
    exports = [
        "//external:jar/javax/mail/mail"
    ],
    runtime_deps = [
        "//dependencies/maven/javax/activation:activation"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


