java_library(
    name = "spotbugs-annotations",
    exports = [
        "//external:jar/com/github/spotbugs/spotbugs-annotations"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/code/findbugs:jsr305"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


