java_library(
    name = "zookeeper",
    exports = [
        "//external:jar/org/apache/zookeeper/zookeeper"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/jline:jline",
        "//dependencies/maven/artifacts/log4j:log4j",
        "//dependencies/maven/artifacts/org/slf4j:slf4j-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


