define

#########################################
##########Language requirement###########
#########################################

rule-1
when {$x isa applicant;
$x has degreeOrigin 'US';
$x has TOEFL >499;},
then {$x has languageRequirement 'satisfied';};

rule-2
when {$x isa applicant;
$x has degreeOrigin 'nonUS';},
then {$x has languageRequirement 'unsatisfied';};

rule-3
when {$x isa applicant;
$x has TOEFL <500;},
then {$x has languageRequirement 'unsatisfied';};


#########################################
##########Consider GPR###########
#########################################

rule-4
when {$x isa applicant;
$x has priorGraduateWork 'none';},
then {$x has considerGPR 'true';};

rule-5
when {$x isa applicant;
$x has priorGraduateWork 'completed';
$x has GPR >2.99;},
then {$x has considerGPR 'true';};

#########################################
##################Decision###############
#########################################

rule-6
when {$x isa applicant;
$x has languageRequirement 'satisfied';
$x has transcript 'available';},
then {$x has decisionType 'full';};

rule-7
when {$x isa applicant;
$x has languageRequirement 'satisfied';
$x has transcript 'unavailable';},
then {$x has decisionType 'conditional';};

#########################################
#############Conditional evaluation######
#########################################

rule-8
when {$x isa applicant;
$x has GPR >3.29;
$x has specialHonours 'honour student';},
then {$x has admissionStatus 'conditional';};

rule-9
when {$x isa applicant;
$x has decisionType 'conditional';
$x has specialHonours 'none';
$x has GRE >1099;},
then {$x has admissionStatus 'conditional';};


##########################################
##############Admission accepted##############
##########################################

rule-10
when {$x isa applicant;
$x has decisionType 'full';
$x has considerGPR 'true';
$x has GPR >2.49;
$x has specialHonours 'none';
$x has GRE >1099;
$x has vGRE >399;},
then {$x has admissionStatus 'full';};

rule-11
when {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.99;
$x has specialHonours !== 'none';},
then {$x has admissionStatus 'full';};

rule-12
when {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.99;
$x has specialHonours 'none';
$x has GRE >1099;
$x has vGRE <400;},
then {$x has admissionStatus 'admit at department\'s discretion';};

#########################################
#############Wait for transcript######
#########################################

rule-13
when {$x isa applicant;
$x has decisionType 'conditional';
$x has specialHonours 'none';
$x has GRE <1100;},
then {$x has admissionStatus 'wait for transcript';};

rule-14
when {$x isa applicant;
$x has decisionType 'conditional';
$x has GPR <3.3;},
then {$x has admissionStatus 'wait for transcript';};


#########################################
#########Admission denied#########
#########################################

rule-15
when {$x isa applicant;
$x has languageRequirement 'unsatisfied';},
then {$x has admissionStatus 'denied';};

rule-16
when {$x isa applicant;
$x has considerGPR 'true';$x has GPR <2.5;},
then {$x has admissionStatus 'denied';};

rule-17
when {$x isa applicant;
$x has priorGraduateWork 'completed';
$x has GPR <3.0;},
then {$x has admissionStatus 'denied';};

rule-18
when {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has GRE <900;},
then {$x has admissionStatus 'denied';};

rule-19
when {$x isa applicant;
$x has considerGPR 'true';
$x has specialHonours 'none';
$x has GPR >2.49;
$x has GRE <900;},
then {$x has admissionStatus 'denied';};

#########################################
##############Provisional admission##############
#########################################

rule-20
when {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has specialHonours 'none';
$x has GRE >899;
$x has GRE <1100;
$x has vGRE <400;},
then {$x has admissionStatus 'provisional with English remediation';};

rule-21
when {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.99;
$x has specialHonours 'none';
$x has GRE >899;
$x has GRE <1100;
$x has vGRE >399;},
then {$x has admissionStatus 'provisional';};

rule-22
when {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has GPR <3.0;
$x has specialHonours 'none';
$x has GRE >899;
$x has vGRE <400;},
then {$x has admissionStatus 'provisional with English remediation';};

rule-23
when {$x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has GPR <3.0;
$x has GRE >899;
$x has vGRE <400;},
then {$x has admissionStatus 'provisional';};
