define

#Roles

role1 sub role;
role2 sub role;

#Entities

entity1 sub entity
    has name
    plays role1
    plays role2;

#Relations

relation1 sub relationship
    relates role1
    relates role2;

relation2 sub relationship
    relates role1
    relates role2;

relation3 sub relationship
    relates role1
    relates role2;

inferredRelation sub relationship
    relates role1
    relates role2;

#Resources

"name" sub attribute, datatype string;

insert

$a1 isa entity1, has name "a1";
$a2 isa entity1, has name "a2";
$b isa entity1, has name "b";
$c isa entity1, has name "c";

(role1:$a1, role2:$c) isa relation2;
(role1:$a2, role2:$c) isa relation2;
(role1:$a1, role2:$b) isa relation1;
(role1:$a2, role2:$b) isa relation1;
(role1:$b, role2:$c) isa inferredRelation;


define

rule-1 sub rule
    when {
    	(role1: $x, role2: $y) isa relation1;
    	($y, $z) isa inferredRelation;
    	($z, $u) isa relation2;
    	($u, $v) isa relation1;
    	(role1: $v, role2: $w) isa inferredRelation;
    }
    then {
    	(role1: $x, role2: $w) isa inferredRelation;
    };

object sub role;
subject sub role;
location sub role;
place sub role;
operated sub role;
operator sub role;

geo-location sub entity
    plays location
    plays subject;

asset sub entity
    plays place
    plays operated;

company sub entity
    plays operator
    plays subject;

factor sub entity
    has value
    plays object;

carried-relation sub relationship
    relates object
    relates subject;

coordinates sub relationship
    relates location
    relates place;

operates sub relationship
    relates operated
    relates operator;

value sub attribute, datatype string;

carryRelation sub rule
when {
  $geo isa geo-location;
  $asset isa asset;
  $company isa company;
  (object: $obj, subject: $geo) isa carried-relation;
  (location: $geo, place: $asset) isa coordinates;
  (operated: $asset, operator: $company) isa operates;
}
then {
  (object: $obj, subject: $company) isa carried-relation;
};

insert

$fac isa factor, has value 'high';
$geo isa geo-location;
$asset isa asset;
$company isa company;
(object: $fac, subject: $geo) isa carried-relation;
(location: $geo, place: $asset) isa coordinates;
(operated: $asset, operator: $company) isa operates;

