define

#Roles

role1 sub role;
role2 sub role;

#Entities

genericEntity sub entity
    has name
    plays role1
    plays role2;

#Relations

baseRelation sub relationship
    relates role1
    relates role2;

anotherBaseRelation sub relationship
    relates role1
    relates role2;

inferredRelation sub relationship
    relates role1
    relates role2;

#Resources

"name" sub attribute, datatype string;

rule-1 sub rule
    when {
    	(role1: $x, role2: $y) isa baseRelation;
    	($y, $z) isa inferredRelation;
    	($z, $u) isa anotherBaseRelation;
    	($u, $v) isa baseRelation;
    	(role1: $v, role2: $w) isa inferredRelation;
    }
    then {
    	(role1: $x, role2: $w) isa inferredRelation;
    };

insert

$a1 isa genericEntity, has name "a1";
$a2 isa genericEntity, has name "a2";
$b isa genericEntity, has name "b";
$c isa genericEntity, has name "c";

(role1:$a1, role2:$c) isa anotherBaseRelation;
(role1:$a2, role2:$c) isa anotherBaseRelation;
(role1:$a1, role2:$b) isa baseRelation;
(role1:$a2, role2:$b) isa baseRelation;
(role1:$b, role2:$c) isa inferredRelation;




