define

column sub entity
    plays tagged
    plays linked-column;

tag sub entity
    has tag-type
    plays tagger;

tagging sub relationship
    relates tagged
    relates tagger;

same-tag-column-link sub relationship
    relates linked-column;

tag-type sub attribute, datatype string;

same-tag-column-linking sub rule,
when {
	$col1 isa column;
	$col2 isa column;
	$tag isa tag, has tag-type "dimension";
	(tagged: $col1, tagger: $tag) isa tagging;
	(tagged: $col2, tagger: $tag) isa tagging;
	$col1 != $col2;
},
then {
	(linked-column: $col1, linked-column: $col2) isa same-tag-column-link;
};

insert

$col1 isa column;
$col2 isa column;
$tag isa tag, has tag-type "dimension";
(tagged: $col1, tagger: $tag) isa tagging;
(tagged: $col2, tagger: $tag) isa tagging;