insert 

entity2 sub entity, is-abstract;
product sub recommendable
    has name
    has min-age
    has max-age
    has gender;

# product resources
min-age sub resource, datatype long;
max-age sub resource, datatype long;
gender sub resource, datatype string;

product-made sub role;
product-origin sub role;
made-in sub relation, relates product-origin, relates product-made;
product plays product-made
    plays typed-product;

recommended-product sub role;
recommended-customer sub role;
recommendation sub relation, relates recommended-product, relates recommended-customer;
product plays recommended-product;

person sub entity2;
person plays recommended-customer;

place sub entity2;
place plays product-origin;

typed-product sub role;
product-type sub role;
typing sub relation, relates typed-product, relates product-type;
category sub entity2
    has name
    plays product-type
    plays typed-product;