insert

isa inference-rule,
lhs {$x isa person;
$t isa tag;$t has name 'Ludwig van Beethoven';
($x, $t) isa tagging;
$y isa product;$y has name 'Nocturnes';
},
rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$t isa tag;$t has name 'Roger Waters';
#($x, $t) isa tagging;
#$y isa tag;$y has name 'Pink Floyd';
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

#isa inference-rule,
#lhs {$x isa person;
#$x has gender 'male';$x has age >=18;
#$y isa product;$y has min-age >=18;
#$z isa country;$z has name 'Italy';
#($y, $z) isa made-in;
#},
#rhs {(recommended-customer: $x, recommended-product: $y) isa recommendation;};

