insert

"R1" isa inference-rule,
lhs {
($x, $y) isa resides;
(member-location $y, container-location $z) isa sublocate},
rhs {($x, $z) isa resides};

# transitivity of sublocate
"R2" isa inference-rule,
lhs {
(member-location $x, container-location $y) isa sublocate;
(member-location $y, container-location $z) isa sublocate},
rhs {(member-location $x, container-location $z) isa sublocate};