insert

"R1" isa inference-rule,
when {
($x, $y) isa resides;
(member-location $y, container-location $z) isa sublocate},
then {($x, $z) isa resides};

# transitivity of sublocate
"R2" isa inference-rule,
when {
(member-location $x, container-location $y) isa sublocate;
(member-location $y, container-location $z) isa sublocate},
then {(member-location $x, container-location $z) isa sublocate};