insert

###################################################
####################Ontology######################
#################################################

"vertex" sub entity
    has index;

"link-from" sub role;
"link-to" sub role;
"link" sub relation, relates link-from, relates link-to;
vertex plays link-from, plays link-to;

"reach-from" sub role;
"reach-to" sub role;
"reachable" sub relation, relates reach-from, relates reach-to;
vertex plays reach-from, plays reach-to;

"index" sub resource, datatype string;

####################################################
##################DATA#############################
####################################################

$a isa vertex, has index "a";
$b isa vertex, has index "b";
$c isa vertex, has index "c";
$d isa vertex, has index "d";

(link-from: $a, link-to: $b) isa link;
(link-from: $b, link-to: $c) isa link;
(link-from: $c, link-to: $c) isa link;
(link-from: $c, link-to: $d) isa link;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
(link-from: $x, link-to: $y) isa link;},
rhs {
(reach-from: $x, reach-to: $y) isa reachable;};

isa inference-rule,
lhs {
(link-from: $x, link-to: $z) isa link;
(reach-from: $z, reach-to: $y) isa reachable;},
rhs {
(reach-from: $x, reach-to: $y) isa reachable;};
