insert

###################################################
####################Ontology######################
#################################################

"person" sub entity
     has name;

"parent" sub role;
"child" sub role;
"Parent" sub relation, relates parent, relates child;
person plays parent, plays child;

"RSG-from" sub role;
"RSG-to" sub role;
"RevSG" sub relation, relates RSG-from, relates RSG-to;
person plays RSG-from, plays RSG-to;

"up-from" sub role;
"up-to" sub role;
"up" sub relation, relates up-from, relates up-to;
person plays up-from, plays up-to;

"down-from" sub role;
"down-to" sub role;
"down" sub relation, relates down-from, relates down-to;
person plays down-from, plays down-to;

"flat-from" sub role;
"flat-to" sub role;
"flat" sub relation, relates flat-to, relates flat-from;
person plays flat-from, plays flat-to;

"name" sub resource, datatype string;

####################################################
##################DATA#############################
####################################################

$a isa person, has name "a";
$b isa person, has name "b";
$c isa person, has name "c";
$d isa person, has name "d";
$e isa person, has name "e";
$f isa person, has name "f";
$g isa person, has name "g";
$h isa person, has name "h";
$i isa person, has name "i";
$j isa person, has name "j";
$k isa person, has name "k";
$l isa person, has name "l";
$m isa person, has name "m";
$n isa person, has name "n";
$o isa person, has name "o";
$p isa person, has name "p";

(up-from: $a, up-to: $e) isa up;
(up-from: $a, up-to: $f) isa up;
(up-from: $f, up-to: $m) isa up;
(up-from: $g, up-to: $n) isa up;
(up-from: $h, up-to: $n) isa up;
(up-from: $i, up-to: $o) isa up;
(up-from: $j, up-to: $o) isa up;

(flat-from: $g, flat-to: $f) isa flat;
(flat-from: $m, flat-to: $n) isa flat;
(flat-from: $m, flat-to: $o) isa flat;
(flat-from: $p, flat-to: $m) isa flat;

(down-from: $l, down-to: $f) isa down;
(down-from: $m, down-to: $f) isa down;
(down-from: $g, down-to: $b) isa down;
(down-from: $h, down-to: $c) isa down;
(down-from: $i, down-to: $d) isa down;
(down-from: $p, down-to: $k) isa down;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
(flat-from: $x, flat-to: $y) isa flat;},
rhs {
(RSG-from: $x, RSG-to: $y) isa RevSG;};

isa inference-rule,
lhs {
(up-from: $x, up-to: $x1) isa up;
(RSG-from: $y1, RSG-to: $x1) isa RevSG;
(down-from: $y1, down-to: $y) isa down;},
rhs {
(RSG-from: $x, RSG-to: $y) isa RevSG;};