define

#Roles

role1 sub role;
role2 sub role;

#Entities

baseEntity sub entity
    plays role1
    plays role2
    has resource
    has anotherResource;

entity1 sub baseEntity;
entity2 sub baseEntity;

#Relations

relation sub relationship
    relates role1
    relates role2;

derivedRelation sub relationship
    relates role1
    relates role2;

anotherRelation sub relationship
    relates role1
    relates role2;

yetAnotherRelation sub relationship
    relates role1
    relates role2;

resource sub attribute datatype string;
anotherResource sub attribute datatype string;

simple-rule
when {
(role1: $x, role2: $y) isa relation;
(role1: $y, role2: $z) isa relation;},
then {
(role1: $x, role2: $z) isa derivedRelation;};

insert

$x isa entity1;
$y isa entity2;