insert

entity1 sub entity
	has res-string
	has res-double
	has res-long
	has res-boolean
	has res1;
entity2 sub entity
    has res1;

#Resources
res1 sub resource datatype string;
res-string sub resource datatype string;
res-double sub resource datatype double;
res-long sub resource datatype long;
res-boolean sub resource datatype boolean;

#Rules

isa inference-rule
when {
    $x isa entity1;
}
then {
    $x has res-string 'string';
};

isa inference-rule
when {
    $x isa entity1;
}
then {
    $x has res-double 3.14;
};

isa inference-rule
when {
    $x isa entity1;
}
then {
    $x has res-long 123;
};

isa inference-rule
when {
    $x isa entity1;
}
then {
    $x has res-boolean 'true';
};

isa inference-rule
when {
    $x isa entity1;
}
then {
    $x has res1 'test';
};
