insert

###################################################
####################Ontology######################
#################################################

"entity2" sub entity
    has index
    plays Q-from
    plays Q-to;
"a-entity" sub entity2;

"Q-from" sub role;
"Q-to" sub role;
"Q" sub relation, relates Q-from, relates Q-to;

"index" sub resource, datatype string;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
(Q-from: $x, Q-to: $z) isa Q;
(Q-from: $z, Q-to: $y) isa Q;},
rhs {
(Q-from: $x, Q-to: $y) isa Q;};
