define

#Entities

entity1 sub entity;
sub-entity1 sub entity1;
entity2 sub entity;

#Rules

rule-1 sub rule
	when {
		$x isa entity2;
	}
	then {
		$x isa sub-entity1;
	};

insert

#Data

$x isa entity2;