define

entity1 sub entity
	has resource;

#Resources
resource sub attribute datatype string;

#Rules

rule-1 sub rule
when {
    $x isa entity1;
}
then {
    $x has resource 'value';
};

insert

#Data
$x isa entity1;
$y isa entity1;