insert

entity1 sub entity
	has res1;

#Resources
res1 sub attribute datatype string;

#Rules

isa inference-rule
when {
    $x isa entity1;
}
then {
    $x has res1 'value';
};

#Data
$x isa entity1;
$y isa entity1;