insert

entity1 sub entity
	has res1;

#Resources
res1 sub resource datatype string;

#Rules

isa inference-rule 
	lhs {
		$x isa entity1 has res1 $r1;
		$y isa entity1;
	}
	rhs {
		$y has res1 $r1;
	};

#Data

$x isa entity1 has res1 "value";
$y isa entity1;