define

#Roles

# Entity hierarchy
#
#                             role
#         role1       role2           role3          role4
#                       |
#                    subRole2

role1 sub role;
role2 sub role;
role3 sub role;
role4 sub role;

subRole2 sub role2;

#Entities

# Entity hierarchy
#
#                  entity
#                     |
#               noRoleEntity
#              /            \
#  singleRoleEntity    anotherSingleRoleEntity
#         |                     |
#  twoRoleEntity        anotherTwoRoleEntity
#                               |
#                         threeRoleEntity

#plays in rel1
singleRoleEntity sub entity
	plays role1;

#plays in rel1, rel3
twoRoleEntity sub singleRoleEntity
    plays role4;

#plays in rel1, rel2
anotherTwoRoleEntity sub singleRoleEntity
	plays role2;

#plays in rel1, rel2, rel3
threeRoleEntity sub anotherSingleRoleEntity
    plays role2
    plays role3;

#plays in rel3
anotherSingleRoleEntity sub entity
    plays role4;

#Relations

relation1 sub relationship
	relates role1
	relates role2;

relation2 sub relationship
    relates role2
    relates role3;

relation3 sub relationship
    relates subRole2
    relates role3
    relates role4;

insert
$x isa singleRoleEntity;
$y isa twoRoleEntity;
$z isa anotherTwoRoleEntity;
$u isa threeRoleEntity;
$v isa anotherSingleRoleEntity;


