define
###############APERITIF WINES##################

rule-1
when {
$x isa person;
$x has preferred-context 'aperitif';},
then { $x has recommended-generic-wine-type 'Romanian wine';};

rule-2
when {
$x isa person;
$x has recommended-generic-wine-type 'Romanian wine';
$x has preferred-body 'full';},
then { $x has recommended-generic-wine-type 'Cotnary vineyard wine';};

rule-3
when {
$x isa person;
$x has recommended-generic-wine-type 'Cotnary vineyard wine';
$x has preferred-sparklingness 'sparkling';},
then { $x has recommended-generic-wine-type 'sparkling wine';};

###############Champagne###############
rule-4
when {
$x isa person;
$x has recommended-generic-wine-type 'sparkling wine';},
then { $x has recommended-generic-wine-type 'Champagne';};

rule-5
when {
$x isa person;
$x has recommended-generic-wine-type 'Champagne';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'White Champagne';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-6
when {
$x isa person;
$x has recommended-generic-wine-type 'Champagne';
$x has preferred-colour 'pink';
$y isa wine;
$y has name 'Pink Champagne';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-7
when {
$x isa person;
$x has recommended-generic-wine-type 'Champagne';
$x has preferred-colour 'black';
$y isa wine;
$y has name 'Black Champagne';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

###############Table###############

rule-8
when {
$x isa person;
$x has recommended-generic-wine-type 'Cotnary vineyard wine';
$x has preferred-sparklingness 'non-sparkling';},
then { $x has recommended-generic-wine-type 'table wine';};

rule-9
when {
$x isa person;
$x has recommended-generic-wine-type 'table wine';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Tamaioasa Romaneasca';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-10
when {
$x isa person;
$x has recommended-generic-wine-type 'table wine';
$x has preferred-colour 'pink';
$y isa wine;
$y has name 'Busuioaca Romaneasca';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-11
when {
$x isa person;
$x has recommended-generic-wine-type 'table wine';
$x has preferred-colour 'red';
$y isa wine;
$y has name 'Cabernet Sauvignion';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};


###############DEALU MARE VINEYARD###############

rule-12
when {
$x isa person;
$x has recommended-generic-wine-type 'Romanian wine';
$x has preferred-body 'medium';},
then { $x has recommended-generic-wine-type 'Dealu Mare vineyard wine';};

rule-13
when {
$x isa person;
$x has recommended-generic-wine-type 'Dealu Mare vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Feteasca Regala';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-14
when {
$x isa person;
$x has recommended-generic-wine-type 'Dealu Mare vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'pink';
$y isa wine;
$y has name 'Feteasca Roz';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-15
when {
$x isa person;
$x has recommended-generic-wine-type 'Dealu Mare vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'red';
$y isa wine;
$y has name 'Feteasca Neagra';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

###############Jidvei vineyard###############

rule-16
when {
$x isa person;
$x has recommended-generic-wine-type 'Romanian wine';
$x has preferred-body 'light';},
then { $x has recommended-generic-wine-type 'Jidvei vineyard wine';};

rule-17
when {
$x isa person;
$x has recommended-generic-wine-type 'Jidvei vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Sauvignion Blanc';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-18
when {
$x isa person;
$x has recommended-generic-wine-type 'Jidvei vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'pink';
$y isa wine;
$y has name 'Feteasca Regala';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-19
when {
$x isa person;
$x has recommended-generic-wine-type 'Jidvei vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'red';
$y isa wine;
$y has name 'Pinot Noir';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

###############ENTREE WINES###############

rule-20
when {
$x isa person;
$x has preferred-context 'entree';},
then { $x has recommended-generic-wine-type 'entree wine';};

rule-21
when {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'white meat';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Muscat Sec';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-22
when {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'white meat';
$x has preferred-colour 'rose';
$y isa wine;
$y has name 'Pinot Grigio Rose';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-23
when {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'white meat';
$x has preferred-colour 'red';
$y isa wine;
$y has name 'Corbieres 2003';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-24
when {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'steak';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Chateau Agnel 2000';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-25
when {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'steak';
$x has preferred-colour 'rose';
$y isa wine;
$y has name 'Busuioaca Romaneasca';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-26
when {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'steak';
$x has preferred-colour 'red';
$y isa wine;
$y has name 'Rosso di Sicilia 2004';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

rule-27
when {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'barbecue';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Riojo Blanco CVNE 2003';},
then {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};