insert
###############APERITIF WINES##################

isa inference-rule,
lhs {
$x isa person;
$x has preferred-context 'aperitif';},
rhs { $x has recommended-generic-wine-type 'Romanian wine';};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Romanian wine';
$x has preferred-body 'full';},
rhs { $x has recommended-generic-wine-type 'Cotnary vineyard wine';};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Cotnary vineyard wine';
$x has preferred-sparklingness 'sparkling';},
rhs { $x has recommended-generic-wine-type 'sparkling wine';};

###############Champagne###############
isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'sparkling wine';},
rhs { $x has recommended-generic-wine-type 'Champagne';};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Champagne';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'White Champagne';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Champagne';
$x has preferred-colour 'pink';
$y isa wine;
$y has name 'Pink Champagne';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Champagne';
$x has preferred-colour 'black';
$y isa wine;
$y has name 'Black Champagne';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

###############Table###############

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Cotnary vineyard wine';
$x has preferred-sparklingness 'non-sparkling';},
rhs { $x has recommended-generic-wine-type 'table wine';};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'table wine';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Tamaioasa Romaneasca';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'table wine';
$x has preferred-colour 'pink';
$y isa wine;
$y has name 'Busuioaca Romaneasca';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'table wine';
$x has preferred-colour 'red';
$y isa wine;
$y has name 'Cabernet Sauvignion';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};


###############DEALU MARE VINEYARD###############

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Romanian wine';
$x has preferred-body 'medium';},
rhs { $x has recommended-generic-wine-type 'Dealu Mare vineyard wine';};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Dealu Mare vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Feteasca Regala';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Dealu Mare vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'pink';
$y isa wine;
$y has name 'Feteasca Roz';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Dealu Mare vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'red';
$y isa wine;
$y has name 'Feteasca Neagra';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

###############Jidvei vineyard###############

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Romanian wine';
$x has preferred-body 'light';},
rhs { $x has recommended-generic-wine-type 'Jidvei vineyard wine';};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Jidvei vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Sauvignion Blanc';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Jidvei vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'pink';
$y isa wine;
$y has name 'Feteasca Regala';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'Jidvei vineyard wine';
$x has preferred-sparklingness 'non-sparkling';
$x has preferred-colour 'red';
$y isa wine;
$y has name 'Pinot Noir';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

###############ENTREE WINES###############

isa inference-rule,
lhs {
$x isa person;
$x has preferred-context 'entree';},
rhs { $x has recommended-generic-wine-type 'entree wine';};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'white meat';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Muscat Sec';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'white meat';
$x has preferred-colour 'rose';
$y isa wine;
$y has name 'Pinot Grigio Rose';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'white meat';
$x has preferred-colour 'red';
$y isa wine;
$y has name 'Corbieres 2003';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'steak';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Chateau Agnel 2000';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'steak';
$x has preferred-colour 'rose';
$y isa wine;
$y has name 'Busuioaca Romaneasca';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'steak';
$x has preferred-colour 'red';
$y isa wine;
$y has name 'Rosso di Sicilia 2004';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};

isa inference-rule,
lhs {
$x isa person;
$x has recommended-generic-wine-type 'entree wine';
$x has preferred-entree 'barbecue';
$x has preferred-colour 'white';
$y isa wine;
$y has name 'Riojo Blanco CVNE 2003';},
rhs {(recommendation-owner: $x, recommended-wine: $y)  isa wine-recommendation;};