package(default_visibility = ["//visibility:public"])

# DUMMY

java_library(
    name = "concept",
    srcs = glob(["*.java"]),
    deps = [
    ],
)


checkstyle_test(
     name = "checkstyle",
     targets = [
         ":concept",
     ],
 )
