insert

pet sub entity
    has-resource name
    has-resource owner
    has-resource sex
    has-resource birth
    has-resource death
    is-abstract;

cat sub pet;
dog sub pet;
snake sub pet;
hamster sub pet;
bird sub pet;

name sub resource datatype string;
owner sub resource datatype string;
sex sub resource datatype string;
birth sub resource datatype string;
death sub resource datatype string;