insert

pet sub entity
    has name
    has owner
    has sex
    has birth
    has death
    is-abstract;

cat sub pet;
dog sub pet;
snake sub pet;
hamster sub pet;
bird sub pet;

name sub resource datatype string;
owner sub resource datatype string;
sex sub resource datatype string;
birth sub resource datatype string;
death sub resource datatype string;