insert

$x isa <species>
    has name <name>
    has owner <owner>
    has sex <sex>
    if(<birth> != "") do { has birth @date(<birth>, "yyyy-MM-dd") }
    if(<death> != "") do { has death @date(<death>, "yyyy-MM-dd") };