java_library(
    name = "jts_core",
    exports = [
        "//external:jar/org/locationtech/jts/jts_core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


