java_library(
    name = "jts-core",
    exports = [
        "//external:jar/org/locationtech/jts/jts-core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


