define

# --------------------------------------------------------
# Locations
# --------------------------------------------------------

name sub attribute,
    value string;

location sub entity,
    abstract,
    key name,
    plays location-hierarchy_superior,
    plays location-hierarchy_subordinate;

area sub location;
city sub location;
country sub location;
continent sub location;

location-hierarchy sub relation,
    relates location-hierarchy_superior,
    relates location-hierarchy_subordinate;

location-hierarchy-transitivity sub rule,
when {
    (location-hierarchy_superior: $a, location-hierarchy_subordinate: $b) isa location-hierarchy;
    (location-hierarchy_superior: $b, location-hierarchy_subordinate: $c) isa location-hierarchy;
}, then {
    (location-hierarchy_superior: $a, location-hierarchy_subordinate: $c) isa location-hierarchy;
};