java_library(
    name = "mesos-jar-shaded-protobuf",
    exports = [
        "//external:jar/org/apache/mesos/mesos-jar-shaded-protobuf"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


