java_library(
    name = "snappy-java",
    exports = [
        "//external:jar/org/xerial/snappy/snappy-java"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


