#java_test(
#    name = "analytics-it",
#    test_class = "ai.grakn.test.graql.analytics.AnalyticsIT",
#    srcs = ["AnalyticsIT.java"],
#    deps = [
#        "//server",
#        "//grakn-graql",
#        "//test-integration/rule:grakn-server",
#    ],
#    size = "large",
#    classpath_resources = ["//test-integration/resources:logback-test"]
#)
#
#java_test(
#    name = "connected-component-it",
#    test_class = "ai.grakn.test.graql.analytics.ConnectedComponentIT",
#    srcs = ["ConnectedComponentIT.java"],
#    deps = [
#        "//server",
#        "//grakn-graql",
#        "//test-integration/rule:grakn-server",
#        "//dependencies/maven/artifacts/com/google/guava:guava"
#    ],
#    size = "large",
#    classpath_resources = ["//test-integration/resources:logback-test"]
#)
#
#java_test(
#    name = "coreness-it",
#    test_class = "ai.grakn.test.graql.analytics.CorenessIT",
#    srcs = ["CorenessIT.java"],
#    deps = [
#        "//server",
#        "//grakn-graql",
#        "//test-integration/rule:grakn-server",
#    ],
#    size = "large",
#    classpath_resources = ["//test-integration/resources:logback-test"]
#)
#
#java_test(
#    name = "count-it",
#    test_class = "ai.grakn.test.graql.analytics.CountIT",
#    srcs = ["CountIT.java"],
#    deps = [
#        "//server",
#        "//grakn-graql",
#        "//test-integration/rule:grakn-server",
#    ],
#    size = "large",
#    classpath_resources = ["//test-integration/resources:logback-test"]
#)
#
#java_test(
#    name = "degree-it",
#    test_class = "ai.grakn.test.graql.analytics.DegreeIT",
#    srcs = ["DegreeIT.java"],
#    deps = [
#        "//server",
#        "//grakn-graql",
#        "//test-integration/rule:grakn-server",
#        "//dependencies/maven/artifacts/com/google/guava:guava"
#    ],
#    size = "large",
#    classpath_resources = ["//test-integration/resources:logback-test"]
#)
#
#java_test(
#    name = "graql-it",
#    test_class = "ai.grakn.test.graql.analytics.GraqlIT",
#    srcs = ["GraqlIT.java"],
#    deps = [
#        "//server",
#        "//grakn-graql",
#        "//test-integration/rule:grakn-server",
#        "//dependencies/maven/artifacts/com/google/guava:guava"
#    ],
#    size = "large",
#    classpath_resources = ["//test-integration/resources:logback-test"]
#)
#
#java_test(
#    name = "kcore-it",
#    test_class = "ai.grakn.test.graql.analytics.KCoreIT",
#    srcs = ["KCoreIT.java"],
#    deps = [
#        "//server",
#        "//grakn-graql",
#        "//test-integration/rule:grakn-server",
#    ],
#    size = "large",
#    classpath_resources = ["//test-integration/resources:logback-test"]
#)
#
#java_test(
#    name = "path-it",
#    test_class = "ai.grakn.test.graql.analytics.PathIT",
#    srcs = ["PathIT.java"],
#    deps = [
#        "//server",
#        "//grakn-graql",
#        "//test-integration/rule:grakn-server",
#        "//dependencies/maven/artifacts/com/google/guava:guava"
#    ],
#    size = "large",
#    classpath_resources = ["//test-integration/resources:logback-test"]
#)
#
#java_test(
#    name = "statistics-it",
#    test_class = "ai.grakn.test.graql.analytics.StatisticsIT",
#    srcs = ["StatisticsIT.java"],
#    deps = [
#        "//server",
#        "//grakn-graql",
#        "//test-integration/rule:grakn-server",
#        "//dependencies/maven/artifacts/com/google/guava:guava"
#    ],
#    size = "large",
#    classpath_resources = ["//test-integration/resources:logback-test"]
#)