java_library(
    name = "validation_api",
    exports = [
        "//external:jar/javax/validation/validation_api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


