java_library(
    name = "validation-api",
    exports = [
        "//external:jar/javax/validation/validation-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


