java_library(
    name = "high-scale-lib",
    exports = [
        "//external:jar/com/boundary/high-scale-lib"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


