java_library(
    name = "jersey_guice",
    exports = [
        "//external:jar/com/sun/jersey/contribs/jersey_guice"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/inject:guice",
        "//dependencies/maven/artifacts/com/sun/jersey:jersey_server",
        "//dependencies/maven/artifacts/javax/inject:javax_inject"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


