java_library(
    name = "jersey-guice",
    exports = [
        "//external:jar/com/sun/jersey/contribs/jersey-guice"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/inject/extensions:guice-servlet",
        "//dependencies/maven/artifacts/com/google/inject:guice",
        "//dependencies/maven/artifacts/com/sun/jersey:jersey-server",
        "//dependencies/maven/artifacts/javax/inject:javax-inject"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


