insert $x isa person
	has person-id @long(<id>)
	has first-name <firstName>
	has last-name <lastName>
	has gender <gender>
	has birth-day @date(<birthday>,"yyyy-MM-dd")
	has creation-date @date(<creationDate>,"yyyy-MM-dd'T'HH:mm:ss.SSSZ")
	has location-ip <locationIP>
	has browser-used <browserUsed>;
