java_library(
    name = "annotations",
    exports = [
        "//external:jar/com/google/code/findbugs/annotations"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/net/jcip:jcip-annotations",
        ":jsr305"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "jsr305",
    exports = [
        "//external:jar/com/google/code/findbugs/jsr305"
    ],
    visibility = [
        "//visibility:public"
    ]
)


