java_test(
    name = "template-parser-test",
    test_class = "grakn.core.graql.internal.template.TemplateParserTest",
    srcs = ["TemplateParserTest.java"],
    deps = [
        "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library",
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//server"],
    size = "small"
)