java_test(
     name = "grakn-tx-operation-exception-test",
     srcs = ["TransactionExceptionTest.java"],
     test_class = "grakn.core.exception.TransactionExceptionTest",
     deps = [
         "//grakn-graql",
         "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library",
     ],
     size = "small"
)