filegroup(
    name = "generic-schema",
    srcs = ["genericSchema.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "reified-resource-applicability",
    srcs = ["reifiedResourceApplicabilityTest.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "resource-applicability",
    srcs = ["resourceApplicabilityTest.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "role-inference",
    srcs = ["roleInferenceTest.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "rule-applicability",
    srcs = ["ruleApplicabilityTest.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "type-inference",
    srcs = ["typeInferenceTest.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "materialisation",
    srcs = ["materialisationTest.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "unification-with-types",
    srcs = ["unificationWithTypesTest.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "diagonal-test",
    srcs = ["diagonalTest.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "path-test",
    srcs = ["pathTest.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "linear-transivity",
    srcs = ["linearTransitivity.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "multi-join",
    srcs = ["multiJoin.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "quadratic-transitivity",
    srcs = ["quadraticTransitivity.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)
filegroup(
    name = "resolution-plan",
    srcs = ["resolutionPlanTest.gql"],
    visibility = ["//test-integration/test/graql/reasoner:__subpackages__"]
)