java_library(
    name = "stream",
    exports = [
        "//external:jar/com/clearspring/analytics/stream"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


