java_library(
    name = "stream",
    exports = [
        "//external:jar/com/clearspring/analytics/stream"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/it/unimi/dsi:fastutil"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


