java_test(
    name = "match-base-test",
    test_class = "grakn.core.graql.internal.match.MatchBaseTest",
    srcs = ["MatchBaseTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//server"],
    size = "small"
)