java_library(
    name = "unused",
    exports = [
        "//external:jar/org/spark_project/spark/unused"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


