java_library(
    name = "libthrift",
    exports = [
        "//external:jar/org/apache/thrift/libthrift"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpclient",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpcore",
        "//dependencies/maven/artifacts/org/slf4j:slf4j-api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


