insert
"production" sub entity
	is-abstract
	## Filming details
	plays-role production-with-crew
    plays-role production-with-cast
    plays-role production-with-company

    plays-role production-with-location

    plays-role production-with-language

    ## Reactions
    plays-role production-with-certificate
    plays-role nominee

    plays-role subject-with-review

    ## Indexing details
    plays-role production-with-genre
    plays-role production-with-mood
    plays-role production-with-cluster
    plays-role subject-with-keyword

    plays-role production-with-stream

	has-resource title
    has-resource original-title
    has-resource alternate-titles

    has-resource imdb-vote
    has-resource rotten-tomatoes-critic-rating
    has-resource rotten-tomatoes-critic-fresh-votes
    has-resource rotten-tomatoes-critic-rotten-votes
    has-resource rotten-tomatoes-critic-total-votes
    has-resource rotten-tomatoes-user-rating
    has-resource rotten-tomatoes-user-total-votes
    has-resource rotten-tomatoes-user-meter
    has-resource rotten-tomatoes-total-meter
    has-resource rotten-tomatoes-url
    has-resource free-web-sources
    has-resource free-ios-sources
    has-resource free-android-sources
    has-resource tv-everywhere-web-sources
    has-resource tv-everywhere-ios-sources
    has-resource tv-everywhere-android-sources
    has-resource subscription-web-sources
    has-resource subscription-ios-sources
    has-resource subscription-android-sources
    has-resource purchase-web-sources
    has-resource purchase-ios-sources
    has-resource purchase-android-sources
    has-resource guidebox-web-trailer
    has-resource guidebox-ios-trailer
    has-resource guidebox-android-trailer
    has-resource youtube-trailer
    has-resource tmdb-id
    has-resource guidebox-id
    has-resource imdb-identifier
    has-resource freebase-identifier
    has-resource wikidata-id
    has-resource tagline
    has-resource metacritic-link
    has-resource images
    has-resource alternate-versions
    has-resource backdrops
    has-resource revenue
    has-resource budget
    has-resource soundtracks
    has-resource runtime
    has-resource metascore
    has-resource tmdb-popularity
    has-resource tmdb-vote-count
    has-resource tmdb-vote-average
    has-resource status
    has-resource links
    has-resource overview
    has-resource release-date;

"movie" sub production
    plays-role movie-with-keyword-person;

"tv-series" sub production;

"production-crew" sub relation
    has-role production-with-crew
    has-role director
    has-role production-designer
    has-role composer
    has-role editor
    has-role animator
    has-role writer
    has-role producer
    has-role art-director
    has-role photography-director
    has-role costume-designer;
"production-with-crew" sub role;
"crew-member" sub role is-abstract;
"director" sub crew-member;
"production-designer" sub crew-member;
"composer" sub crew-member;
"editor" sub crew-member;
"animator" sub crew-member;
"writer" sub crew-member;
"costume-designer" sub crew-member;
"producer" sub crew-member;
"photography-director" sub crew-member;
"art-director" sub crew-member;

"has-cast" sub relation
    has-role character-being-played
    has-role actor
    has-role production-with-cast
    has-resource billing-number;
"character-being-played" sub role;
"actor" sub role;
"production-with-cast" sub role;

"has-production-company" sub relation
    has-role production-with-company
    has-role production-company;
"production-with-company" sub role;
"production-company" sub role;

"production-location" sub relation
    has-role production-with-location
    has-role location-of-subject
    has-role filming-location
    has-role narrative-location;
"production-with-location" sub role;
"location-of-subject" sub role;
"narrative-location" sub role;
"filming-location" sub role;

"production-language" sub relation
    has-role production-with-language
    has-role language-of-subject
    has-role original-language
    has-role translation;
"production-with-language" sub role;
"language-of-subject" sub role;
"original-language" sub role;
"translation" sub role;

"has-certificate" sub relation
    has-role production-with-certificate
    has-role certificate-of-production;
"production-with-certificate" sub role;
"certificate-of-production" sub role;


"accolade" sub relation
    has-role nominee
    has-role award-of-subject
    has-role nominated-award;
"nominee" sub role;
"award-of-subject" sub role;
"nominated-award" sub role;

"has-review" sub relation
    has-role subject-with-review
    has-role review-of-subject;
"subject-with-review" sub role;
"review-of-subject" sub role;

"has-genre" sub relation
    has-role production-with-genre
    has-role genre-of-production;
"production-with-genre" sub role;
"genre-of-production" sub role;

"has-mood" sub relation
    has-role production-with-mood
    has-role mood-of-production
    has-resource weight;
"production-with-mood" sub role;
"mood-of-production" sub role;

"has-cluster" sub relation
    has-role production-with-cluster
    has-role cluster-of-production
    has-resource weight;
"production-with-cluster" sub role;
"cluster-of-production" sub role;

"has-keyword" sub relation
    has-role subject-with-keyword
    has-role keyword-of-subject;
"subject-with-keyword" sub role;
"keyword-of-subject" sub role;

"has-streaming-service" sub relation
    has-role streaming-provider
    has-role streaming-url-role
    has-role production-with-stream;
"streaming-provider" sub role;
"streaming-url-role" sub role;
"production-with-stream" sub role;

"person" sub entity
    plays-role crew-member
    plays-role actor
    plays-role board-member
    plays-role character-being-played
    plays-role relative
    plays-role nominee
    plays-role detailed-person
    plays-role keyword-person

    has-resource name
    has-resource imdb-identifier
    has-resource images
    has-resource birthday
    has-resource also-known-as
    has-resource cause-of-death
    has-resource place-of-birth
    has-resource biography
    has-resource child-string
    has-resource gender
    has-resource freebase-identifier
    has-resource residence
    has-resource deathday
    has-resource has-spouse
    has-resource homepage;
"relative" sub role is-abstract;

"marriage" sub relation
    has-role spouse1
    has-role spouse2;
"spouse" sub relative, is-abstract;
"spouse1" sub spouse;
"spouse2" sub spouse;

"has-child" sub relation
    has-role parent
    has-role child;
"parent" sub relative;
"child" sub relative;

"has-partner" sub relation
    has-role person-has-partner
    has-role partner;
"person-has-partner" sub relative;
"partner" sub relative;

"personal-details" sub relation
    has-role detailed-person
    has-role country-of-citizenship
    has-role education-company
    has-role occupation-of-person
    has-role location-of-birth
    has-role location-of-death;
"detailed-person" sub role;
"country-of-citizenship" sub role;
"education-company" sub role;
"occupation-of-person" sub role;
"location-of-birth" sub role;
"location-of-death" sub role;

"person-via-keyword" sub relation
    has-role keyword-person
    has-role movie-with-keyword-person;
"keyword-person" sub role;
"movie-with-keyword-person" sub role;

"company" sub entity
    plays-role production-company
    plays-role streaming-provider
    plays-role education-company

    plays-role company-with-board

    plays-role company-with-headquarters

    plays-role nominee

    has-resource parent-company
    has-resource industry
    has-resource headquarters
    has-resource freebase-identifier
    has-resource inception
    has-resource dissolved
    has-resource owned-by
    has-resource images
    has-resource homepage
    has-resource imdb-identifier
    has-resource name;

"company-board" sub relation
    has-role company-with-board
    has-role ceo
    has-role founder
    has-role chairperson;
"company-with-board" sub role;
"board-member" sub role is-abstract;
"ceo" sub board-member;
"founder" sub board-member;
"chairperson" sub board-member;

"company-has-headquarters-location" sub relation
    has-role company-with-headquarters
    has-role location-of-headquarters;
"company-with-headquarters" sub role;
"location-of-headquarters" sub role;

"location" sub entity
    plays-role parent-of-feature
    plays-role location-of-headquarters
    plays-role location-of-birth
    plays-role location-of-death
    plays-role location-of-subject
    plays-role narrative-location
    plays-role filming-location
    plays-role country-of-citizenship
    has-resource name;

"country" sub location
    has-resource iso-3166;

"language" sub entity
    plays-role language-of-subject
    plays-role original-language
    plays-role translation
    has-resource name
    has-resource iso-639-1
    has-resource iso-639-2
    has-resource iso-639-3
    has-resource wikimedia-language-code;

"award" sub entity
    plays-role award-of-subject
    plays-role nominated-award
    has-resource description
    has-resource name;

"parent-feature" sub relation
    has-role parent-of-feature
    has-role child-of-feature;
"parent-of-feature" sub role;
"child-of-feature" sub role;

"character" sub entity
    plays-role character-being-played
    has-resource name;

"certificate" sub entity
    plays-role certificate-of-production
    has-resource description;

"genre" sub entity
    plays-role genre-of-production
    has-resource weight
    has-resource description;

"keyword" sub entity
    plays-role keyword-of-subject
    has-resource name
    has-resource weight;

"review" sub entity
    plays-role review-of-subject
    has-resource content
    has-resource media-type
    has-resource author;

"occupation" sub entity
    plays-role occupation-of-person
    has-resource description;

"cluster" sub entity
    plays-role cluster-of-production
    has-resource description
    has-resource cluster-id;

"mood" sub entity
    plays-role mood-of-production
    has-resource description;


### RESOURCE TYPES:

"title" sub resource
    datatype string;

"alternate-titles" sub resource
    datatype string;

"original-title" sub resource
    datatype string;

"imdb-vote" sub resource
    datatype long;

"rotten-tomatoes-critic-rating" sub resource
    datatype double;

"rotten-tomatoes-critic-fresh-votes" sub resource
    datatype long;

"rotten-tomatoes-critic-rotten-votes" sub resource
    datatype long;

"rotten-tomatoes-critic-total-votes" sub resource
    datatype long;

"rotten-tomatoes-user-rating" sub resource
    datatype double;

"rotten-tomatoes-user-total-votes" sub resource
    datatype long;

"rotten-tomatoes-user-meter" sub resource
    datatype long;

"rotten-tomatoes-total-meter" sub resource
    datatype long;

"rotten-tomatoes-url" sub resource
    datatype string;

"free-web-sources" sub resource
    datatype string;

"free-ios-sources" sub resource
    datatype string;

"free-android-sources" sub resource
    datatype string;

"tv-everywhere-web-sources" sub resource
    datatype string;

"tv-everywhere-ios-sources" sub resource
    datatype string;

"tv-everywhere-android-sources" sub resource
    datatype string;

"subscription-web-sources" sub resource
    datatype string;

"subscription-ios-sources" sub resource
    datatype string;

"subscription-android-sources" sub resource
    datatype string;

"purchase-web-sources" sub resource
    datatype string;

"purchase-ios-sources" sub resource
    datatype string;

"purchase-android-sources" sub resource
    datatype string;

"guidebox-web-trailer" sub resource
    datatype string;

"guidebox-ios-trailer" sub resource
    datatype string;

"guidebox-android-trailer" sub resource
    datatype string;

"youtube-trailer" sub resource
    datatype string;

"tmdb-id" sub resource
    datatype string;

"guidebox-id" sub resource
    datatype string;

"imdb-identifier" sub resource
    datatype string;

"freebase-identifier" sub resource
    datatype string;

"tagline" sub resource
    datatype string;

"metacritic-link" sub resource
    datatype string;

"wikidata-id" sub resource
    datatype string;

"links" sub resource
    datatype string;

"tmdb-vote-average" sub resource
    datatype double;

"overview" sub resource
    datatype string;

"metascore" sub resource
    datatype double;

"revenue" sub resource
    datatype double;

"tmdb-popularity" sub resource
    datatype double;

"runtime" sub resource
    datatype double;

"tmdb-vote-count" sub resource
    datatype double;

"images" sub resource
    datatype string;

"budget" sub resource
    datatype double;

"soundtracks" sub resource
    datatype string;

"backdrops" sub resource
    datatype string;

"alternate-versions" sub resource
    datatype string;

"release-date" sub resource
    datatype long;

"status" sub resource
    datatype string;

"name" sub resource
    datatype string;

"has-spouse" sub resource
    datatype string;

"also-known-as" sub resource
    datatype string;

"biography" sub resource
    datatype string;

"deathday" sub resource
    datatype long;

"birthday" sub resource
    datatype long;

"place-of-birth" sub resource
    datatype string;

"homepage" sub resource
    datatype string;

"residence" sub resource
    datatype string;

"gender" sub resource
    datatype string;

"cause-of-death" sub resource
    datatype string;

"child-string" sub resource
    datatype string;

"headquarters" sub resource
    datatype string;

"parent-company" sub resource
    datatype string;

"inception" sub resource
    datatype long;

"dissolved" sub resource
    datatype long;

"industry" sub resource
    datatype string;

"owned-by" sub resource
    datatype string;

"description" sub resource
    datatype string;

"weight" sub resource
    datatype double;

"iso-639-1" sub resource
    datatype string;

"iso-639-2" sub resource
    datatype string;

"iso-639-3" sub resource
    datatype string;

"wikimedia-language-code" sub resource
    datatype string;

"author" sub resource
    datatype string;

"media-type" sub resource
    datatype string;

"content" sub resource
    datatype string;

"billing-number" sub resource
    datatype long;

"streaming-url" sub entity
    has-resource url
    plays-role streaming-url-role;

"url" sub resource
    datatype string;

"iso-3166" sub resource
    datatype string;

"cluster-id" sub resource
    datatype string;