java_library(
    name = "org_abego_treelayout_core",
    exports = [
        "//external:jar/org/abego/treelayout/org_abego_treelayout_core"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


