define
  thingy sub entity
    has a-int
    has a-boolean
    has a-number
    has a-string
    has a-null;

a-int sub attribute datatype long;
a-boolean sub attribute datatype boolean;
a-number sub attribute datatype double;
a-string sub attribute datatype string;
a-null sub attribute datatype string;