insert

bond sub entity
  has name
  has risk
  plays issued
  plays affected;

article sub entity
  has subject
  has uri
  has title
  plays information;

company sub entity
  has name
  plays issuer
  plays owner;

oil-platform sub entity
  has distance-from-coast
  has platform-id
  plays owned
  plays located
  plays affected;

country sub entity
  has name
  plays location
  plays located;

region sub entity
  has name
  plays location;


affected sub role; information sub role;
affects sub relation
  relates affected
  relates information;

issuer sub role; issued sub role;
issues sub relation
  relates issuer
  relates issued;

owner sub role; owned sub role;
owns sub relation
  relates owner
  relates owned;


location sub role; located sub role;
located-in sub relation
  relates location
  relates located;


company-id sub attribute datatype string;
platform-id sub attribute datatype string;
title sub attribute datatype string;
uri sub attribute datatype string;
subject sub attribute datatype string;
name sub attribute datatype string;
distance-from-coast sub attribute datatype long;
risk sub attribute datatype double;