java_library(
    name = "guava_retrying",
    exports = [
        "//external:jar/com/github/rholder/guava_retrying"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/code/findbugs:jsr305",
        "//dependencies/maven/artifacts/com/google/guava:guava"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "snowball_stemmer",
    exports = [
        "//external:jar/com/github/rholder/snowball_stemmer"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


