java_library(
    name = "guava-retrying",
    exports = [
        "//external:jar/com/github/rholder/guava-retrying"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/code/findbugs:jsr305",
        "//dependencies/maven/artifacts/com/google/guava:guava"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "snowball-stemmer",
    exports = [
        "//external:jar/com/github/rholder/snowball-stemmer"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


