java_library(
    name = "snowball-stemmer",
    exports = [
        "//external:jar/com/github/rholder/snowball-stemmer"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


