java_library(
    name = "hystrix_core",
    exports = [
        "//external:jar/com/netflix/hystrix/hystrix_core"
    ],
    runtime_deps = [
        "//dependencies/maven/com/netflix/archaius:archaius_core",
        "//dependencies/maven/io/reactivex:rxjava",
        "//dependencies/maven/org/hdrhistogram:HdrHistogram",
        "//dependencies/maven/org/slf4j:slf4j_api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


