java_test(
     name = "attribute-it",
     srcs = ["AttributeIT.java"],
     test_class = "grakn.core.server.kb.internal.concept.AttributeIT",
     deps = [
         "//server",
         "//test-integration/rule:concurrent-grakn-server",
         "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library",
         "//dependencies/maven/artifacts/com/google/guava:guava",
     ],
     classpath_resources = ["//test-integration/resources:logback-test"],
     size = "medium",
)
java_test(
     name = "attribute-type-it",
     srcs = ["AttributeTypeIT.java"],
     test_class = "grakn.core.server.kb.internal.concept.AttributeTypeIT",
     deps = [
         "//server",
         "//test-integration/rule:concurrent-grakn-server",
         "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library"
     ],
     classpath_resources = ["//test-integration/resources:logback-test"],
     size = "medium"
)
java_test(
     name = "concept-it",
     srcs = ["ConceptIT.java"],
     test_class = "grakn.core.server.kb.internal.concept.ConceptIT",
     deps = [
         "//server",
         "//test-integration/rule:concurrent-grakn-server",
         "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library",
         "//dependencies/maven/artifacts/org/apache/tinkerpop:gremlin-core"
     ],
     classpath_resources = ["//test-integration/resources:logback-test"],
     size = "medium"
)
java_test(
     name = "entity-it",
     srcs = ["EntityIT.java"],
     test_class = "grakn.core.server.kb.internal.concept.EntityIT",
     deps = [
         "//server",
         "//test-integration/rule:concurrent-grakn-server",
         "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library"
     ],
     classpath_resources = ["//test-integration/resources:logback-test"],
     size = "medium"
)
java_test(
     name = "entity-type-it",
     srcs = ["EntityTypeIT.java"],
     test_class = "grakn.core.server.kb.internal.concept.EntityTypeIT",
     deps = [
         "//server",
         "//util",
         "//test-integration/rule:concurrent-grakn-server",
         "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library",
         "//dependencies/maven/artifacts/org/apache/tinkerpop:gremlin-core"
     ],
     classpath_resources = ["//test-integration/resources:logback-test"],
     size = "medium"
)
java_test(
     name = "relationship-it",
     srcs = ["RelationshipIT.java"],
     test_class = "grakn.core.server.kb.internal.concept.RelationshipIT",
     deps = [
         "//server",
         "//util",
         "//test-integration/rule:concurrent-grakn-server",
         "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library",
         "//dependencies/maven/artifacts/org/apache/tinkerpop:gremlin-core",
         "//dependencies/maven/artifacts/com/google/guava:guava",
     ],
     classpath_resources = ["//test-integration/resources:logback-test"],
     size = "medium"
)
java_test(
     name = "relationship-type-it",
     srcs = ["RelationshipTypeIT.java"],
     test_class = "grakn.core.server.kb.internal.concept.RelationshipTypeIT",
     deps = [
         "//server",
         "//test-integration/rule:concurrent-grakn-server",
         "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library"
     ],
     classpath_resources = ["//test-integration/resources:logback-test"],
     size = "medium"
)
java_test(
     name = "role-it",
     srcs = ["RoleIT.java"],
     test_class = "grakn.core.server.kb.internal.concept.RoleIT",
     deps = [
         "//server",
         "//test-integration/rule:concurrent-grakn-server",
         "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library"
     ],
     classpath_resources = ["//test-integration/resources:logback-test"],
     size = "medium"
)
java_test(
     name = "schema-concept-it",
     srcs = ["SchemaConceptIT.java"],
     test_class = "grakn.core.server.kb.internal.concept.SchemaConceptIT",
     deps = [
         "//server",
         "//util",
         "//test-integration/rule:concurrent-grakn-server",
         "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library",
         "//dependencies/maven/artifacts/org/apache/tinkerpop:gremlin-core",
     ],
     classpath_resources = ["//test-integration/resources:logback-test"],
     size = "medium"
)
java_test(
     name = "schema-mutation-it",
     srcs = ["SchemaMutationIT.java"],
     test_class = "grakn.core.server.kb.internal.concept.SchemaMutationIT",
     deps = [
         "//server",
         "//util",
         "//test-integration/rule:concurrent-grakn-server",
         "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library",
         "//dependencies/maven/artifacts/com/google/guava:guava",
     ],
     classpath_resources = ["//test-integration/resources:logback-test"],
     size = "large"
)