java_library(
    name = "xercesImpl",
    exports = [
        "//external:jar/xerces/xercesImpl"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/xml-apis:xml-apis"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


