java_library(
    name = "spark-core",
    exports = [
        "//external:jar/com/sparkjava/spark-core"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/eclipse/jetty/websocket:websocket-server",
        "//dependencies/maven/artifacts/org/eclipse/jetty/websocket:websocket-servlet",
        "//dependencies/maven/artifacts/org/eclipse/jetty:jetty-server",
        "//dependencies/maven/artifacts/org/eclipse/jetty:jetty-webapp"
    ],
    visibility = [
        "//visibility:public"
    ]
)


