java_library(
    name = "spark_core",
    exports = [
        "//external:jar/com/sparkjava/spark_core"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/eclipse/jetty/websocket:websocket_server",
        "//dependencies/maven/artifacts/org/eclipse/jetty/websocket:websocket_servlet",
        "//dependencies/maven/artifacts/org/eclipse/jetty:jetty_server",
        "//dependencies/maven/artifacts/org/eclipse/jetty:jetty_webapp"
    ],
    visibility = [
        "//visibility:public"
    ]
)


