java_library(
    name = "jopt_simple",
    exports = [
        "//external:jar/net/sf/jopt_simple/jopt_simple"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


