java_library(
    name = "activation",
    exports = [
        "//external:jar/javax/activation/activation"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


