java_library(
    name = "uncommons_maths",
    exports = [
        "//external:jar/org/uncommons/maths/uncommons_maths"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


