java_test(
    name = "in-plays-fragment-test",
    srcs = ["InPlaysFragmentTest.java"],
    test_class = "grakn.core.graql.internal.gremlin.fragment.InPlaysFragmentTest",
    deps = [
        "//grakn-graql",
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/org/apache/tinkerpop:gremlin-core"
    ],
    size = "small"
)

java_test(
    name = "isa-explicit-test",
    srcs = ["IsaExplicitTest.java"],
    test_class = "grakn.core.graql.internal.gremlin.fragment.IsaExplicitTest",
    deps = ["//grakn-graql"],
    size = "small"
)

java_test(
     name = "out-plays-fragment-test",
     srcs = ["OutPlaysFragmentTest.java"],
     test_class = "grakn.core.graql.internal.gremlin.fragment.OutPlaysFragmentTest",
     deps = [
         "//grakn-graql",
         "//dependencies/maven/artifacts/org/apache/tinkerpop:gremlin-core",
         "//dependencies/maven/artifacts/com/google/guava:guava"
         ],
     size = "small"
)