java_library(
    name = "jflex",
    exports = [
        "//external:jar/de/jflex/jflex"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/apache/ant:ant"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


