const grpc = require("grpc");
const services = require("./autogenerated/SessionServiceProto");
const TxService = require("./TxService");

function Session(uri, keyspace, credentials) {
    this.stub = new services.SessionClient(uri, grpc.credentials.createInsecure());
    debugger;
}

Session.prototype.createRemoteTx = function create(txType) {
    const txService = new TxService(this.stub.tx());
    return txService.openTx(this.keyspace, txType, this.credentials).catch(e => { throw e; });
}

Session.prototype.close = function close() {
    grpc.closeClient(this.stub);
}

module.exports = Session;