java_library(
    name = "cassandra-driver-core",
    exports = [
        "//external:jar/com/datastax/cassandra/cassandra-driver-core"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/github/jnr:jnr-ffi",
        "//dependencies/maven/artifacts/com/github/jnr:jnr-posix",
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/org/slf4j:slf4j-api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


