java_library(
    name = "cassandra_driver_core",
    exports = [
        "//external:jar/com/datastax/cassandra/cassandra_driver_core"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/github/jnr:jnr_ffi",
        "//dependencies/maven/artifacts/com/github/jnr:jnr_posix",
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/org/slf4j:slf4j_api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


