java_library(
    name = "airline",
    exports = [
        "//external:jar/io/airlift/airline"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/javax/inject:javax_inject"
    ],
    visibility = [
        "//visibility:public"
    ]
)


