java_library(
    name = "airline",
    exports = [
        "//external:jar/io/airlift/airline"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/javax/inject:javax-inject"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


