java_library(
    name = "config",
    srcs = ["Config.java", "ConfigKey.java", "SystemProperty.java"],
    deps = [
        "//common/util:util",
        "//common/exception:exception",
        "//dependencies/maven/artifacts/com/google/auto/value:auto-value",
        "//dependencies/maven/artifacts/com/google/code/findbugs:annotations",
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/org/slf4j:slf4j-api",
    ],
    visibility = ["//common:__subpackages__"],
)
