java_library(
    name = "jersey-media-jaxb",
    exports = [
        "//external:jar/org/glassfish/jersey/media/jersey-media-jaxb"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/glassfish/hk2/external:javax-inject",
        "//dependencies/maven/artifacts/org/glassfish/hk2:hk2-api",
        "//dependencies/maven/artifacts/org/glassfish/hk2:hk2-locator",
        "//dependencies/maven/artifacts/org/glassfish/hk2:osgi-resource-locator",
        "//dependencies/maven/artifacts/org/glassfish/jersey/core:jersey-common"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


