java_library(
    name = "byte-buddy",
    exports = [
        "//external:jar/net/bytebuddy/byte-buddy"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "byte-buddy-agent",
    exports = [
        "//external:jar/net/bytebuddy/byte-buddy-agent"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


