java_library(
    name = "byte_buddy",
    exports = [
        "//external:jar/net/bytebuddy/byte_buddy"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "byte_buddy_agent",
    exports = [
        "//external:jar/net/bytebuddy/byte_buddy_agent"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


