java_library(
    name = "jaxb-impl",
    exports = [
        "//external:jar/com/sun/xml/bind/jaxb-impl"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/javax/xml/bind:jaxb-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


