java_library(
    name = "jaxb_impl",
    exports = [
        "//external:jar/com/sun/xml/bind/jaxb_impl"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/javax/xml/bind:jaxb_api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


