java_library(
    name = "guava",
    exports = [
        "//external:jar/com/google/guava/guava"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/code/findbugs:jsr305",
        "//dependencies/maven/artifacts/com/google/errorprone:error-prone-annotations",
        "//dependencies/maven/artifacts/com/google/j2objc:j2objc-annotations",
        "//dependencies/maven/artifacts/org/codehaus/mojo:animal-sniffer-annotations"
    ],
    visibility = [
        "//visibility:public"
    ]
)


