java_library(
    name = "jctools_core",
    exports = [
        "//external:jar/org/jctools/jctools_core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


