java_library(
    name = "jctools-core",
    exports = [
        "//external:jar/org/jctools/jctools-core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


