define

age sub attribute,
    value long;

currency sub attribute,
    value string,
    regex "^(American Dollar|Great British Pound|Euro|Brazilian Real|South African Rand|Renminbi|Australian Dollar)$",
    owns currency-code;

currency-code sub attribute,
    value string,
    regex "^(USD|GBP|EUR|BRL|ZAR|RMB|AUD)$";

date-of-event sub attribute,
    value datetime,
    abstract;

date-of-birth sub date-of-event,
    value datetime;

date-of-marriage sub date-of-event,
    value datetime;

email sub attribute,
    value string;

gender sub attribute,
    value string;

identifier sub attribute,
    value long,
    abstract;

marriage-id sub identifier,
    value long;

language sub attribute,
    value string,
    regex "^(English|German|Portugese|Afrikaans|Mandarin)$";

name sub attribute,
    value string,
    abstract;

forename sub name,
    value string;

location-name sub name,
    value string;

surname sub name,
    value string;

locates sub relation,
    relates located,
    relates location;

born-in sub locates,
    relates child as located,
    relates place-of-birth as location;

location-hierarchy sub relation,
    relates subordinate,
    relates superior;

marriage sub relation,
    owns marriage-id @key,
    owns date-of-marriage,
    relates husband,
    relates wife,
    plays locates:located;

parentship sub relation,
    relates child,
    relates parent;

residency sub relation,
    relates location,
    relates resident;

location sub entity,
    abstract,
    owns location-name @key,
    plays born-in:place-of-birth,
    plays locates:location,
    plays location-hierarchy:subordinate,
    plays location-hierarchy:superior;

city sub location,
    plays residency:location;

continent sub location;

country sub location,
    owns currency,
    owns language;

person sub entity,
    owns email @key,
    owns age,
    owns date-of-birth,
    owns forename,
    owns gender,
    owns surname,
    plays born-in:child,
    plays marriage:husband,
    plays marriage:wife,
    plays parentship:child,
    plays parentship:parent,
    plays residency:resident;

