java_library(
    name = "java-semver",
    exports = [
        "//external:jar/com/github/zafarkhaja/java-semver"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


