java_library(
    name = "java_semver",
    exports = [
        "//external:jar/com/github/zafarkhaja/java_semver"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


