java_library(
    name = "jboss_logging",
    exports = [
        "//external:jar/org/jboss/logging/jboss_logging"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


