java_library(
    name = "jboss-logging",
    exports = [
        "//external:jar/org/jboss/logging/jboss-logging"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


