insert

model sub entity
    has name
    has year
    has description
    has price
    plays model-of-car;
make sub entity
    has name
    plays make-of-car;

name sub resource datatype string;
year sub resource datatype string;
description sub resource datatype string;
price sub resource datatype double;

make-and-model sub relation, relates make-of-car, relates model-of-car;
make-of-car sub role;
model-of-car sub role;

