insert

# motorbike
$motorbike isa category, id "motorbike";
$ducatti isa product, id "Ducatti 1299", has min-age 18, has gender "male";
(typed-product: $ducatti, product-type: $motorbike) isa typing;
(product-made: $ducatti, product-origin: Italy) isa made-in;

# music
$cd isa category, id "cd";
$theWall isa product, id "The Wall";
(typed-product: $theWall,product-type: $cd) isa typing;
$blizzard isa product, id "Blizzard of Ozz";
(typed-product: $blizzard, product-type: $cd) isa typing;
$nocturnes isa product, id "Nocturnes";
(typed-product: $nocturnes, product-type: $cd) isa typing;

# movie
$movie isa category, id "movie";
$goodBadUgly isa product, id "The Good the Bad the Ugly";
(typed-product: $goodBadUgly, product-type: $movie) isa typing;
$godfather isa product, id "Godfather";
(typed-product: $godfather, product-type: $movie) isa typing;
$dumb isa product, id "Dumb and dumber";
(typed-product: $dumb, product-type: $movie) isa typing;

# book
$book isa category, id "book";
$dorianGray isa product, id "Dorian Gray";
(typed-product: $dorianGray, product-type: $book) isa typing;
$colourOfMagic isa product, id "Colour of Magic";
(typed-product: $colourOfMagic, product-type: $book) isa typing;
$warOfWorlds isa product, id "War of the Worlds";
(typed-product: $warOfWorlds, product-type: $book) isa typing;
$crime isa product, id "Crime and Punishment";
(typed-product: $crime, product-type: $book) isa typing;
$farm isa product, id "Animal Farm";
(typed-product: $farm, product-type: $book) isa typing;
$alice isa product, id "Adventures in Wonderland";
(typed-product: $alice, product-type: $book) isa typing;
$orientExpress isa product, id "Orient Express";
(typed-product: $orientExpress, product-type: $book) isa typing;
$fairy isa product, id "Fairy Tales";
(typed-product: $fairy, product-type: $book) isa typing;
$jeeves isa product, id "My Man Jeeves";
(typed-product: $jeeves, product-type: $book) isa typing;
$rings isa product, id "Lord of the rings";
(typed-product: $rings, product-type: $book) isa typing;
$harry isa product, id "Harry Potter";
(typed-product: $harry, product-type: $book) isa typing;
$sherlock isa product, id "Sherlock Holmes";
(typed-product: $sherlock, product-type: $book) isa typing;
$forWhom isa product, id "For Whom he Bell Tolls";
(typed-product: $forWhom, product-type: $book) isa typing;
$miceAndMen isa product, id "Of Mice and Men";
(typed-product: $miceAndMen, product-type: $book) isa typing;
$trial isa product, id "Trial";
(typed-product: $trial, product-type: $book) isa typing;
$faust isa product, id "Faust";
(typed-product: $faust, product-type: $book) isa typing;


# paintings
$painting isa category, id "painting";
$lesElephants isa product, id "Les Elephants";
(typed-product: $lesElephants, product-type: $painting) isa typing;
$waterLillies isa product, id "Water Lillies";
(typed-product: $waterLillies, product-type: $painting) isa typing;
$nightWatch isa product, id "Night Watch";
(typed-product: $nightWatch, product-type: $painting) isa typing;
$monaLisa isa product, id "Mona Lisa";
(typed-product: $monaLisa, product-type: $painting) isa typing;
$raphael isa product, id "Madonna of the pinks";
(typed-product: $raphael, product-type: $painting) isa typing;
$bacchus isa product, id "Bacchus and Ariadne";
(typed-product: $bacchus, product-type: $painting) isa typing;
$sunflowers isa product, id "Sunflowers";
(typed-product: $sunflowers, product-type: $painting) isa typing;
$universe isa product, id "Controller of the Universe";
(typed-product: $universe, product-type: $painting) isa typing;
$grayTree isa product, id "Gray Tree";
(typed-product: $grayTree, product-type: $painting) isa typing;
$lastJudgement isa product, id "Last Judgement";
(typed-product: $lastJudgement, product-type: $painting) isa typing;

# instrument
$guitar isa category, id "guitar";
$stratocaster isa product, id "Stratocaster";
(typed-product: $stratocaster, product-type: $guitar) isa typing;

# bands
"Band" isa category;
"MusicalArtist" isa category;

$beatles isa tag, id "Beatles";
(grouped-tag: $beatles,tag-group: Band) isa grouping;
$pinkFloyd isa tag, id "Pink Floyd";
(grouped-tag: $pinkFloyd,tag-group: Band) isa grouping;
$rollingStones isa tag, id "Rolling Stones";
(grouped-tag: $rollingStones,tag-group: Band) isa grouping;
$cream isa tag, id "Cream";
(grouped-tag: $cream,tag-group: Band) isa grouping;
$yardbirds isa tag, id "Yardbirds";
(grouped-tag: $yardbirds,tag-group: Band) isa grouping;
$simonAndGarfunkel isa tag, id "Simon and Garfunkel";
(grouped-tag: $simonAndGarfunkel,tag-group: Band) isa grouping;
$blackSabbath isa tag, id "Black Sabbath";
(grouped-tag: $blackSabbath,tag-group: Band) isa grouping;
$wailers isa tag, id "Bob Marley and the Wailers";
(grouped-tag: $wailers,tag-group: Band) isa grouping;

$buckethead isa tag, id "Buckethead";
(grouped-tag: $buckethead,tag-group: Band) isa grouping;

$primus isa tag, id "Primus";
(grouped-tag: $primus, tag-group: Band) isa grouping;

$linkinPark isa tag, id "Linkin park";
(grouped-tag: $linkinPark, tag-group: Band) isa grouping;

$limpBizkit isa tag, id "Limp Bizkit";
(grouped-tag: $limpBizkit, tag-group: Band) isa grouping;

$jimiHendrix isa tag, id "Jimi Hendrix";
(grouped-tag: $jimiHendrix, tag-group: MusicalArtist) isa grouping;

$slash isa tag, id "Slash";
(grouped-tag: $slash, tag-group: MusicalArtist) isa grouping;

$yngwie isa tag, id "Yngwie Malmsteen";
(grouped-tag: $yngwie, tag-group: MusicalArtist) isa grouping;

$steveVai isa tag, id "Steve Vai";
(grouped-tag: $steveVai, tag-group: MusicalArtist) isa grouping;

$cacophony isa tag, id "Cacophony";
(grouped-tag: $cacophony, tag-group: Band) isa grouping;

$vanHalen isa tag, id "Van Halen";
(grouped-tag: $vanHalen, tag-group: Band) isa grouping;

$metallica isa tag, id "Metallica";
(grouped-tag: $metallica, tag-group: Band) isa grouping;

$megadeth isa tag, id "Megadeth";
(grouped-tag: $megadeth, tag-group: Band) isa grouping;

$slayer isa tag, id "Slayer";
(grouped-tag: $slayer, tag-group: Band) isa grouping;

$pantera isa tag, id "Pantera";
(grouped-tag: $pantera, tag-group: Band) isa grouping;

$superjoint isa tag, id "Superjoint Ritual";
(grouped-tag: $superjoint, tag-group: Band) isa grouping;

$ironMaiden isa tag, id "Iron Maiden";
(grouped-tag: $ironMaiden, tag-group: Band) isa grouping;

$judasPriest isa tag, id "Judas Priest";
(grouped-tag: $judasPriest, tag-group: Band) isa grouping;

$thinLizzy isa tag, id "Thin Lizzy";
(grouped-tag: $thinLizzy, tag-group: Band) isa grouping;

$ledZeppelin isa tag, id "Led Zeppelin";
(grouped-tag: $ledZeppelin, tag-group: Band) isa grouping;

$deepPurple isa tag, id "Deep Purple";
(grouped-tag: $deepPurple, tag-group: Band) isa grouping;

$queen isa tag, id "Queen";
(grouped-tag: $queen, tag-group: Band) isa grouping;

tag plays-role recommended-product;

