insert

###################################################
####################Ontology######################
#################################################

"entity" isa entity-type
    has-resource index;
"a-entity" sub entity;
"b-entity" sub entity;

"P-from" isa role-type;
"P-to" isa role-type;
"P" isa relation-type, has-role P-from, has-role P-to;
entity plays-role P-from plays-role P-to;

"Q-from" isa role-type;
"Q-to" isa role-type;
"Q" isa relation-type, has-role Q-from, has-role Q-to;
entity plays-role Q-from plays-role Q-to;

"index" isa resource-type, datatype string;

####################################################
##################RULES#############################
####################################################

isa inference-rule,
lhs {
(Q-from: $x, Q-to: $y) isa Q;},
rhs {
(P-from: $x, P-to: $y) isa P;};

isa inference-rule,
lhs {
(Q-from: $x, Q-to: $z) isa Q;
(P-from: $z, P-to: $y) isa P;},
rhs {
(P-from: $x, P-to: $y) isa P;};
