java_library(
    name = "error_prone_annotations",
    exports = [
        "//external:jar/com/google/errorprone/error_prone_annotations"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


