java_library(
    name = "instrumentation-api",
    exports = [
        "//external:jar/com/google/instrumentation/instrumentation-api"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/code/findbugs:jsr305",
        "//dependencies/maven/artifacts/com/google/guava:guava"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


