insert

$471104 isa surname val "Newman";
$40984696 isa surname val "Hane";
$761920 isa surname val "Smith";
$528504 val "" isa surname;
$94384 isa surname val "Niesz";
$114736 isa surname val "Titus";
$704696 isa surname val "McGaughey";
$16504 isa surname val "Dudley";
$32856 isa surname val "Newman";
$37048 isa surname val "Meyers";
$90200 isa surname val "Bard";
$98360 isa surname val "Roush";
$114872 isa surname val "Young";
$192760 isa surname val "Guthrie";
$655376 isa surname val "Shafner";
$258168 isa surname val "Culbertson";
$331864 isa surname val "Weaver";
$405624 val "Herchelroth" isa surname;
$507960 isa surname val "Billings";
$61504 isa middlename val "S.";
$106592 val "Sanford" isa middlename;
$40996912 val "L." isa middlename;
$37040 val "" isa middlename;
$708728 val "Franklin" isa middlename;
$204816 val "Melissa" isa middlename;
$241840 val "Ann" isa middlename;
$794808 val "Kossuth" isa middlename;
$847960 isa middlename val "W.";
$340144 val "Ellen" isa middlename;
$389136 val "J." isa middlename;
$868440 isa middlename val "G.";
$12344 isa middlename val "Josephine";
$41144360 isa middlename val "E.";
$311352 isa middlename val "Eliza";
$467064 val "" isa middlename;
$40968440 has death-date "" has confidence "high" isa death;
$40976632 has death-date "" has confidence "high" isa death;
$41029880 has death-date "" has confidence "high" isa death;
$41091192 has death-date "" has confidence "high" isa death;
$45072 has confidence "high" has death-date "1862-12-26" isa death;
$110608 has death-date "1900" has confidence "high" isa death;
$192528 has death-date "before 1798-10" has confidence "high" isa death;
$229392 has death-date "" has confidence "high" isa death;
$393232 has confidence "high" has death-date "1891-08" isa death;
$516112 has death-date "" has confidence "high" isa death;
$761872 has death-date "" has confidence "high" isa death;
$909328 has death-date "" has confidence "high" isa death;
$933904 has death-date "" has confidence "high" isa death;
$41017432 has death-date "" has confidence "high" isa death;
$151720 has death-date "" has confidence "high" isa death;
$610488 has death-date "" has confidence "high" isa death;
$147632 has death-date "" has confidence "high" isa death;
$446640 has death-date "" has confidence "high" isa death;
$966712 has death-date "" has confidence "high" isa death;
$483504 has death-date "" has confidence "high" isa death;
$77880 has death-date "1957-03-28" has confidence "high" isa death;
$610352 has death-date "" has confidence "high" isa death;
$139448 has death-date "1946-05-10" has confidence "high" isa death;
$655408 has death-date "" has confidence "high" isa death;
$663728 has death-date "" has confidence "high" isa death;
$708656 has death-date "" has confidence "high" isa death;
$41046088 has death-date "" has confidence "high" isa death;
$208952 has death-date "" has confidence "high" isa death;
$237624 has death-date "1942-04-08" has confidence "high" isa death;
$41099336 has confidence "high" has death-date "1898-09-10" isa death;
$909360 has death-date "1904-03-26" has confidence "high" isa death;
$491704 has death-date "" has confidence "high" isa death;
$69696 has death-date "" has confidence "high" isa death;
$286784 has death-date "1872-03-06" has confidence "high" isa death;
$426048 has confidence "high" has death-date "1868-03-15" isa death;
$442432 has confidence "high" has death-date "1868-10-28" isa death;
$811072 has death-date "" has confidence "high" isa death;
$696408 has death-date "" has confidence "high" isa death;
$770136 has death-date "" has confidence "high" isa death;
$802904 has death-date "" has confidence "high" isa death;
$962648 has death-date "" has confidence "high" isa death;
$311384 has death-date "1891-12-08" has confidence "high" isa death;
$450648 has confidence "high" has death-date "1913" isa death;
$258144 has death-date "" has confidence "high" isa death;
$417888 has confidence "high" isa death has death-date "1933-01-10";
$110696 has death-date "" has confidence "high" isa death;
$589920 has death-date "" has confidence "high" isa death;
$618592 has death-date "" has confidence "high" isa death;
$159976 has death-date "" has confidence "high" isa death;
$729184 has death-date "" has confidence "high" isa death;
$798816 has death-date "" has confidence "high" isa death;
$590072 has death-date "" has confidence "high" isa death;
$618744 has death-date "" has confidence "high" isa death;
$839800 has death-date "" has confidence "high" isa death;
$12536 has death-date "" has confidence "high" isa death;
$53496 has death-date "" has confidence "high" isa death;
$233720 has death-date "" has confidence "high" isa death;
$299128 has death-date "" has confidence "high" isa death;
$311416 has death-date "" has confidence "high" isa death;
$360568 has confidence "high" isa death has death-date "1905-01-01";
$41103480 has surname "Newman" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female" has firstname "Eliza";
$49168 has middlename "" has confidence "high" has firstname "John" has birth-date "" has surname "Meyers" isa birth has gender "male";
$307216 has middlename "" has confidence "high" isa birth has gender "female" has surname "Niesz" has firstname "Elizabeth" has birth-date "1820-08-27";
$946192 has surname "Newman" has middlename "" has confidence "high" has firstname "John" isa birth has gender "male" has birth-date "circa 1803";
$573496 has firstname "Barbara" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female" has surname "Shafner";
$614456 has surname "Newman" has middlename "" has confidence "high" has birth-date "" isa birth has gender "male" has firstname "Henry";
$651320 has firstname "Andrew" has middlename "" has confidence "high" has birth-date "" isa birth has gender "male" has surname "Shafner";
$389168 has firstname "Barbara" has surname "Titus" has confidence "high" isa birth has middlename "Ellen" has gender "female" has birth-date "1850-09-18";
$954424 has firstname "Catherine" has middlename "" has confidence "high" isa birth has surname "Young" has gender "female" has birth-date "before 1798";
$462896 has birth-date "1798-04-09" has firstname "Mary" has middlename "" has confidence "high" isa birth has gender "female" has surname "Young";
$40984648 has surname "Newman" has confidence "high" has firstname "John" has birth-date "" isa birth has middlename "L." has gender "male";
$41013320 has firstname "Sarah" has surname "Hane" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female";
$41021512 has surname "Newman" has middlename "" has firstname "Lucinda" has confidence "high" has birth-date "" isa birth has gender "female";
$172088 has firstname "Mary" has middlename "" has confidence "high" isa birth has gender "female" has surname "Niesz" has birth-date "1824-05-29";
$41087048 has birth-date "1811-03-06" has surname "Newman" has middlename "" has confidence "high" isa birth has gender "male" has firstname "Henry";
$221240 has firstname "Byron" has middlename "" has confidence "high" has birth-date "" has surname "Culbertson" isa birth has gender "male";
$299064 has confidence "high" has birth-date "" isa birth has firstname "Ann" has gender "female" has surname "Niesz" has middlename "Eliza";
$323640 has firstname "Jacob" has confidence "high" has birth-date "1825-11-18" isa birth has gender "male" has middlename "J." has surname "Niesz";
$888880 has surname "Newman" has middlename "" has confidence "high" has birth-date "" isa birth has gender "male" has firstname "Peter";
$925744 has confidence "high" has firstname "Elam" has surname "Smith" has birth-date "" isa birth has gender "male" has middlename "G.";
$8256 has surname "Dudley" has confidence "high" has birth-date "" isa birth has gender "female" has firstname "Susan" has middlename "Josephine";
$81984 has firstname "Catherine" has birth-date "1824-10-20" has middlename "" has confidence "high" isa birth has gender "female" has surname "Niesz";
$135232 has firstname "Jacob" has middlename "" has confidence "high" has birth-date "" isa birth has gender "male" has surname "Young";
$172096 has firstname "Mary" has middlename "" has confidence "high" has birth-date "" isa birth has surname "Guthrie" has gender "female";
$458816 has firstname "Haman" has surname "Newman" has middlename "" has confidence "high" has birth-date "" isa birth has gender "male";
$41119784 has middlename "E." has firstname "Barbara" has surname "Newman" has confidence "high" has birth-date "" isa birth has gender "female";
$41193512 has surname "Newman" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female" has firstname "Amanda";
$467032 has firstname "Barbara" has middlename "" has confidence "high" isa birth has birth-date "1773-06-06" has gender "female" has surname "Herchelroth";
$499800 has middlename "" has confidence "high" has birth-date "" isa birth has gender "male" has firstname "George" has surname "Niesz";
$41056 has middlename "S." has confidence "high" has birth-date "" isa birth has gender "male" has firstname "Samuel" has surname "Bard";
$225376 has surname "Titus" has middlename "" has confidence "high" has birth-date "" has firstname "Timothy" isa birth has gender "male";
$155752 has surname "Newman" has middlename "" has confidence "high" has birth-date "" isa birth has gender "male" has firstname "Henry";
$815200 has surname "" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female" has firstname "Josephine";
$954464 has firstname "Barbara" has surname "Newman" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female";
$561272 has surname "" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female" has firstname "Elizabeth";
$40964096 has date "" isa wedding has confidence "high";
$663672 has firstname "Barbara" has birth-date "1833-04-08" has confidence "high" isa birth has middlename "Ellen" has gender "female" has surname "Niesz";
$692344 has middlename "" has confidence "high" has birth-date "" isa birth has gender "male" has firstname "Frederick" has surname "Shafner";
$41132032 isa wedding has confidence "high" has date "1854-05-04";
$725112 has middlename "" has confidence "high" has firstname "John" has birth-date "" isa birth has gender "male" has surname "Shafner";
$741496 has birth-date "1840-01-19" has firstname "Sarah" has confidence "high" isa birth has middlename "Ann" has gender "female" has surname "Niesz";
$757880 has middlename "" has confidence "high" has birth-date "" isa birth has gender "female" has firstname "Elizabeth" has surname "Shafner";
$843896 has birth-date "1829-09-12" has confidence "high" isa birth has gender "male" has firstname "George" has surname "Niesz" has middlename "W.";
$110712 has birth-date "1857-12-24" has firstname "William" has surname "Titus" has confidence "high" isa birth has gender "male" has middlename "Sanford";
$143480 has surname "Roush" has middlename "" has confidence "high" has birth-date "" isa birth has firstname "Delilah" has gender "female";
$180344 has firstname "Mary" has surname "Titus" has confidence "high" isa birth has middlename "Melissa" has gender "female" has birth-date "1847-08-12";
$122916904 has date "1874-12-09" isa wedding has confidence "high";
$122929192 isa wedding has confidence "high" has date "1829-10-29";
$122957864 has date "" isa wedding has confidence "high";
$364664 has birth-date "1822-05-28" has firstname "William" has middlename "" has confidence "high" isa birth has gender "male" has surname "Niesz";
$81932408 has date "1832-11-29" isa wedding has confidence "high";
$81993848 has date "" isa wedding has confidence "high";
$82108536 isa wedding has date "1845-10-21" has confidence "high";
$82223224 has date "" isa wedding has confidence "high";
$82247800 has date "1820-05-23" isa wedding has confidence "high";
$82260088 has date "1884-10-21" isa wedding has confidence "high";
$139424 has date "" isa wedding has confidence "high";
$192672 has date "" isa wedding has confidence "high";
$213152 has date "" isa wedding has confidence "high";
$270496 has date "" isa wedding has confidence "high";
$295072 has date "" isa wedding has confidence "high";
$16560 has birth-date "1774-08-02" has middlename "" has surname "Newman" has confidence "high" has firstname "John" isa birth has gender "male";
$581816 has firstname "Barbara" has surname "Newman" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female";
$635064 has confidence "high" has birth-date "1842-11-16" isa birth has gender "male" has firstname "Benjamin" has middlename "Franklin" has surname "Niesz";
$81965136 isa wedding has confidence "high" has date "1795 circa";
$82030672 has date "" isa wedding has confidence "high";
$266416 has middlename "" has surname "Weaver" has confidence "high" has birth-date "" isa birth has gender "female" has firstname "Elizabeth";
$458928 has surname "Newman" has middlename "" has confidence "high" isa birth has gender "male" has birth-date "1804 circa" has firstname "Lawrence";
$475312 has surname "Billings" has middlename "" has confidence "high" has firstname "Maggie" has birth-date "" isa birth has gender "female";
$499888 has firstname "Margaret" has surname "Newman" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female";
$676016 has surname "McGaughey" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female" has firstname "Isabelle";
$213176 has surname "Titus" has confidence "high" isa birth has middlename "Ann" has gender "female" has firstname "Amanda" has birth-date "1845-09-10";
$741552 has middlename "Kossuth" has confidence "high" has firstname "John" has birth-date "1836-11-22" isa birth has gender "male" has surname "Niesz";
$282808 has middlename "" has confidence "high" has birth-date "1798-01-02" has firstname "John" isa birth has gender "male" has surname "Niesz";
$41009336 has date "1844-11-21" isa wedding has confidence "high";
$4328 has surname "Newman" has middlename "" has confidence "high" has firstname "John" has birth-date "" isa birth has gender "male";
$65768 has firstname "Catherine" has surname "Newman" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female";
$20720 has date "" isa wedding has confidence "high";
$37104 has date "" isa wedding has confidence "high";
$114928 has date "" isa wedding has confidence "high";
$364792 has firstname "William" has surname "Titus" has confidence "high" isa birth has gender "male" has birth-date "1818-03-23" has middlename "Sanford";
$487672 has surname "" has firstname "Rosalie" has middlename "" has confidence "high" has birth-date "" isa birth has gender "female";
$4160 isa firstname val "Susan";
$77888 isa firstname val "Catherine";
$41001080 isa firstname val "Lucinda";
$41099384 isa firstname val "Eliza";
$561240 isa firstname val "Maggie";
$77840 isa firstname val "Samuel";
$864344 isa firstname val "Elam";
$499728 isa firstname val "George";
$552976 isa firstname val "Lawrence";
$663568 isa firstname val "Henry";
$704528 isa firstname val "Andrew";
$737296 isa firstname val "Benjamin";
$798736 isa firstname val "Isabelle";
$135264 isa firstname val "Jacob";
$376928 isa firstname val "Ann";
$397408 isa firstname val "Barbara";
$610400 isa firstname val "Margaret";
$704608 isa firstname val "Frederick";
$811104 isa firstname val "Josephine";
$12464 isa firstname val "John";
$532728 isa firstname val "Elizabeth";
$110640 isa firstname val "William";
$217264 isa firstname val "Byron";
$233648 isa firstname val "Amanda";
$254000 isa firstname val "Elizabeth";
$729272 isa firstname val "Peter";
$553008 isa firstname val "Rosalie";
$127160 isa firstname val "Mary";
$147576 isa firstname val "Delilah";
$229496 isa firstname val "Timothy";
$823344 isa firstname val "Sarah";
$446520 isa firstname val "Haman";
$41066616 val "1898-09-10" isa death-date;
$40976 val "1774-08-02" isa birth-date;
$421904 isa death-date val "1905-01-01";
$41107544 val "1811-03-06" isa birth-date;
$123056 val "1957-03-28" isa death-date;
$180272 val "1824-05-29" isa birth-date;
$766136 isa birth-date val "1829-09-12";
$278576 val "1820-08-27" isa birth-date;
$430128 val "1822-05-28" isa birth-date;
$450608 val "1868-03-15" isa death-date;
$12472 val "" isa birth-date;
$28728 val "1862-12-26" isa death-date;
$61496 isa death-date val "1900";
$123064 val "before 1798-10" isa death-date;
$135224 val "1847-08-12" isa birth-date;
$659632 isa birth-date val "1840-01-19";
$139320 val "1946-05-10" isa death-date;
$753712 isa birth-date val "1833-04-08";
$225464 val "1942-04-08" isa death-date;
$299192 val "1872-03-06" isa death-date;
$377016 isa birth-date val "1818-03-23";
$409656 isa birth-date val "1773-06-06";
$434360 val "1798-04-09" isa birth-date;
$454712 val "" isa death-date;
$471224 val "" isa birth-date;
$118848 val "1857-12-24" isa birth-date;
$254016 val "1891-12-08" isa death-date;
$438336 val "1868-10-28" isa death-date;
$806976 val "circa 1803" isa birth-date;
$553048 val "1804 circa" isa birth-date;
$704600 val "1842-11-16" isa birth-date;
$905304 isa birth-date val "1836-11-22";
$389208 val "1891-08" isa death-date;
$458840 val "1913" isa death-date;
$82016 val "1824-10-20" isa birth-date;
$274528 val "1845-09-10" isa birth-date;
$819448 val "1904-03-26" isa death-date;
$934008 val "before 1798" isa birth-date;
$16632 val "" isa death-date;
$303352 val "1798-01-02" isa birth-date;
$332024 isa birth-date val "1825-11-18";
$340088 val "1850-09-18" isa birth-date;
$344184 val "1933-01-10" isa death-date;
$41062648 isa person has identifier "Henry Newman";
$41099512 has identifier "Amanda Newman" isa person;
$4112 isa person has identifier "Susan Josephine Dudley";
$122896 isa person has identifier "William Sanford Titus Jr.";
$217104 isa person has identifier "Mary Guthrie";
$348176 has identifier "John Niesz" isa person;
$405520 has identifier "William Sanford Titus" isa person;
$843792 isa person has identifier "Josephine";
$4264 isa person has identifier "John Newman3";
$86184 isa person has identifier "Lucinda Newman";
$41046104 has identifier "Barbara E. Newman" isa person;
$548920 isa person has identifier "Elizabeth";
$81968 isa person has identifier "Samuel S. Bard";
$610360 isa person has identifier "Henry Newman2";
$618680 isa person has identifier "Frederick Shafner";
$196656 isa person has identifier "Timothy Titus";
$229424 isa person has identifier "Amanda Ann Titus";
$831544 isa person has identifier "Isabelle McGaughey";
$327856 isa person has identifier "Jacob J. Niesz";
$385200 has identifier "Mary Young" isa person;
$917560 isa person has identifier "John Kossuth Niesz";
$483376 has identifier "Haman Newman" isa person;
$524336 isa person has identifier "Maggie Billings";
$679984 isa person has identifier "Barbara Newman2";
$258104 has identifier "Elizabeth Weaver" isa person;
$757936 isa person has identifier "John Newman2";
$512184 isa person has identifier "Rosalie";
$41024 has identifier "John Meyers" isa person;
$184384 isa person has identifier "Mary Niesz";
$41078832 has identifier "Henry Newman3" isa person;
$335936 isa person has identifier "Barbara Ellen Titus";
$380992 has identifier "William Niesz" isa person;
$405568 isa person has identifier "Barbara Herchelroth";
$528448 isa person has identifier "Margaret Newman";
$557120 isa person has identifier "Barbara Shafner";
$643136 isa person has identifier "Benjamin Franklin Niesz";
$675904 isa person has identifier "Sarah Ann Niesz";
$708672 isa person has identifier "Peter Newman";
$749656 isa person has identifier "Elizabeth Shafner";
$942168 isa person has identifier "Barbara Newman";
$24664 has identifier "John Newman" isa person;
$40992808 isa person has identifier "John L. Newman";
$41037864 has identifier "Sarah Hane" isa person;
$41279528 has identifier "Eliza Newman" isa person;
$491608 has identifier "George Niesz" isa person;
$73824 isa person has identifier "Catherine Niesz";
$127072 isa person has identifier "Jacob Young";
$159840 isa person has identifier "Mary Melissa Titus";
$237664 isa person has identifier "Byron Culbertson";
$295008 isa person has identifier "Elizabeth Niesz";
$356448 isa person has identifier "Ann Eliza Niesz";
$90216 isa person has identifier "Catherine Newman";
$843872 isa person has identifier "George W. Niesz";
$602360 isa person has identifier "Andrew Shafner";
$659576 isa person has identifier "Barbara Ellen Niesz";
$708856 isa person has identifier "John Shafner";
$864376 isa person has identifier "Elam G. Smith";
$864504 isa person has identifier "Catherine Young";
$139384 isa person has identifier "Delilah Roush";
$483448 isa person has identifier "Lawrence Newman";
$53256 isa event-protagonist has event-role "parent" (protagonist: $385200, happening: $81984);
$65544 (protagonist: $548920, happening: $499888) isa event-protagonist has event-role "parent";
$114696 isa event-protagonist (protagonist: $348176, happening: $741496) has event-role "parent";
$118792 (protagonist: $385200, happening: $741496) isa event-protagonist has event-role "parent";
$122888 (protagonist: $41062648, happening: $65768) isa event-protagonist has event-role "parent";
$143368 (protagonist: $405568, happening: $458928) isa event-protagonist has event-role "parent";
$147464 isa event-protagonist (protagonist: $348176, happening: $323640) has event-role "parent";
$163848 (protagonist: $127072, happening: $954424) isa event-protagonist has event-role "parent";
$81936 has event-role "newborn" isa event-protagonist (protagonist: $81968, happening: $41056);
$94224 has event-role "deceased" isa event-protagonist (protagonist: $81968, happening: $69696);
$114704 (protagonist: $73824, happening: $110608) has event-role "deceased" isa event-protagonist;
$253968 has event-role "newborn" isa event-protagonist (protagonist: $196656, happening: $225376);
$290832 has event-role "newborn" (protagonist: $229424, happening: $213176) isa event-protagonist;
$368656 has event-role "deceased" (protagonist: $348176, happening: $286784) isa event-protagonist;
$438288 has event-role "newborn" (protagonist: $380992, happening: $364664) isa event-protagonist;
$454672 (protagonist: $380992, happening: $450648) has event-role "deceased" isa event-protagonist;
$471056 has event-role "newborn" isa event-protagonist (protagonist: $405568, happening: $467032);
$626704 has event-role "deceased" (protagonist: $548920, happening: $618592) isa event-protagonist;
$638992 has event-role "newborn" isa event-protagonist (protagonist: $557120, happening: $573496);
$40968296 isa event-protagonist (protagonist: $483448, happening: $41103480) has event-role "parent";
$40980584 isa event-protagonist has event-role "parent" (protagonist: $41037864, happening: $41119784);
$41070696 isa event-protagonist has event-role "parent" (protagonist: $385200, happening: $172088);
$41128040 (protagonist: $348176, happening: $843896) isa event-protagonist has event-role "parent";
$749584 has event-role "deceased" isa event-protagonist (protagonist: $643136, happening: $729184);
$757776 has event-role "newborn" (protagonist: $708856, happening: $725112) isa event-protagonist;
$41119848 (protagonist: $295008, happening: $110712) isa event-protagonist has event-role "parent";
$81985784 isa event-protagonist (protagonist: $618680, happening: $651320) has event-role "parent";
$82018552 isa event-protagonist has event-role "parent" (protagonist: $757936, happening: $499888);
$82022648 isa event-protagonist has event-role "parent" (protagonist: $348176, happening: $741552);
$82026744 (protagonist: $548920, happening: $458816) isa event-protagonist has event-role "parent";
$82030840 (protagonist: $831544, happening: $41021512) isa event-protagonist has event-role "parent";
$974864 has event-role "newborn" isa event-protagonist (protagonist: $864504, happening: $954424);
$40964176 (protagonist: $127072, happening: $462896) isa event-protagonist has event-role "parent";
$40972368 (protagonist: $491608, happening: $282808) isa event-protagonist has event-role "parent";
$41009232 isa event-protagonist has event-role "parent" (protagonist: $864504, happening: $757880);
$41017424 isa event-protagonist (protagonist: $483448, happening: $581816) has event-role "parent";
$41033808 isa event-protagonist has event-role "parent" (protagonist: $385200, happening: $663672);
$41070672 isa event-protagonist has event-role "parent" (protagonist: $385200, happening: $741552);
$41078864 isa event-protagonist (protagonist: $41037864, happening: $41193512) has event-role "parent";
$41115728 (protagonist: $548920, happening: $954464) isa event-protagonist has event-role "parent";
$41136208 isa event-protagonist has event-role "parent" (protagonist: $405568, happening: $954424);
$41152592 isa event-protagonist (protagonist: $385200, happening: $843896) has event-role "parent";
$41021528 has event-role "deceased" isa event-protagonist (protagonist: $41037864, happening: $41017432);
$41033816 (protagonist: $86184, happening: $41046088) has event-role "deceased" isa event-protagonist;
$41082968 has event-role "newborn" isa event-protagonist (protagonist: $90216, happening: $65768);
$41185368 has event-role "newborn" (protagonist: $41279528, happening: $41103480) isa event-protagonist;
$53296 has event-role "newborn" isa event-protagonist (protagonist: $24664, happening: $16560);
$65584 has event-role "newborn" (protagonist: $41024, happening: $49168) isa event-protagonist;
$630840 has event-role "deceased" isa event-protagonist (protagonist: $610360, happening: $590072);
$643128 has event-role "newborn" (protagonist: $679984, happening: $581816) isa event-protagonist;
$774200 has event-role "newborn" isa event-protagonist (protagonist: $675904, happening: $741496);
$835640 (protagonist: $831544, happening: $802904) has event-role "deceased" isa event-protagonist;
$516144 has event-role "deceased" isa event-protagonist (protagonist: $483448, happening: $491704);
$20536 has event-role "deceased" (protagonist: $4112, happening: $12536) isa event-protagonist;
$40968264 has event-role "newborn" (protagonist: $4264, happening: $4328) isa event-protagonist;
$41001032 has event-role "deceased" isa event-protagonist (protagonist: $40992808, happening: $40976632);
$41078856 (protagonist: $90216, happening: $110696) has event-role "deceased" isa event-protagonist;
$745520 has event-role "newborn" isa event-protagonist (protagonist: $659576, happening: $663672);
$376888 has event-role "deceased" isa event-protagonist (protagonist: $405520, happening: $360568);
$892976 has event-role "newborn" isa event-protagonist (protagonist: $708672, happening: $888880);
$438328 has event-role "newborn" (protagonist: $491608, happening: $499800) isa event-protagonist;
$933936 has event-role "newborn" isa event-protagonist (protagonist: $864376, happening: $925744);
$938032 has event-role "newborn" (protagonist: $917560, happening: $741552) isa event-protagonist;
$16448 has event-role "newborn" (protagonist: $4112, happening: $8256) isa event-protagonist;
$49216 has event-role "deceased" isa event-protagonist (protagonist: $41024, happening: $53496);
$40992816 has event-role "newborn" isa event-protagonist (protagonist: $40992808, happening: $40984648);
$41021488 has event-role "newborn" isa event-protagonist (protagonist: $41046104, happening: $41119784);
$143424 has event-role "newborn" (protagonist: $127072, happening: $135232) isa event-protagonist;
$217152 (protagonist: $196656, happening: $208952) has event-role "deceased" isa event-protagonist;
$262208 has event-role "newborn" isa event-protagonist (protagonist: $258104, happening: $266416);
$516160 has event-role "newborn" isa event-protagonist (protagonist: $512184, happening: $487672);
$544832 has event-role "newborn" (protagonist: $548920, happening: $561272) isa event-protagonist;
$606272 (protagonist: $602360, happening: $618744) has event-role "deceased" isa event-protagonist;
$786496 has event-role "deceased" isa event-protagonist (protagonist: $917560, happening: $933904);
$524376 has event-role "deceased" isa event-protagonist (protagonist: $491608, happening: $516112);
$585816 has event-role "deceased" isa event-protagonist (protagonist: $528448, happening: $610352);
$40964128 (protagonist: $348176, happening: $635064) isa event-protagonist has event-role "parent";
$40972320 isa event-protagonist has event-role "parent" (protagonist: $831544, happening: $41103480);
$40976416 (protagonist: $864504, happening: $725112) isa event-protagonist has event-role "parent";
$40984608 isa event-protagonist (protagonist: $41062648, happening: $41119784) has event-role "parent";
$41000992 isa event-protagonist has event-role "parent" (protagonist: $831544, happening: $581816);
$41054240 (protagonist: $348176, happening: $364664) isa event-protagonist has event-role "parent";
$41115680 isa event-protagonist (protagonist: $24664, happening: $41087048) has event-role "parent";
$921688 (protagonist: $757936, happening: $811072) has event-role "deceased" isa event-protagonist;
$966744 (protagonist: $942168, happening: $962648) has event-role "deceased" isa event-protagonist;
$139352 has event-role "deceased" (protagonist: $122896, happening: $77880) isa event-protagonist;
$147544 (protagonist: $139384, happening: $147632) has event-role "deceased" isa event-protagonist;
$41046056 has event-role "newborn" (protagonist: $41037864, happening: $41013320) isa event-protagonist;
$213080 has event-role "newborn" (protagonist: $184384, happening: $172088) isa event-protagonist;
$229464 has event-role "deceased" (protagonist: $184384, happening: $233720) isa event-protagonist;
$41091112 has event-role "newborn" (protagonist: $86184, happening: $41021512) isa event-protagonist;
$41156648 has event-role "deceased" isa event-protagonist (protagonist: $41046104, happening: $41029880);
$41177128 has event-role "newborn" (protagonist: $41062648, happening: $41087048) isa event-protagonist;
$376920 has event-role "newborn" isa event-protagonist (protagonist: $327856, happening: $323640);
$41222184 has event-role "deceased" (protagonist: $41099512, happening: $41091192) isa event-protagonist;
$41267240 (protagonist: $41078832, happening: $151720) has event-role "deceased" isa event-protagonist;
$401496 has event-role "newborn" isa event-protagonist (protagonist: $335936, happening: $389168);
$41324584 has event-role "deceased" isa event-protagonist (protagonist: $41279528, happening: $159976);
$479320 has event-role "deceased" isa event-protagonist (protagonist: $405568, happening: $426048);
$41000976 isa event-protagonist has event-role "parent" (protagonist: $348176, happening: $663672);
$41021456 (protagonist: $405568, happening: $946192) isa event-protagonist has event-role "parent";
$163936 has event-role "newborn" isa event-protagonist (protagonist: $159840, happening: $180344);
$41050128 (protagonist: $295008, happening: $213176) isa event-protagonist has event-role "parent";
$41058320 (protagonist: $405520, happening: $213176) isa event-protagonist has event-role "parent";
$41086992 isa event-protagonist has event-role "parent" (protagonist: $348176, happening: $172088);
$245856 has event-role "newborn" (protagonist: $237664, happening: $221240) isa event-protagonist;
$41099280 isa event-protagonist has event-role "parent" (protagonist: $41037864, happening: $40984648);
$282720 has event-role "deceased" (protagonist: $229424, happening: $237624) isa event-protagonist;
$315488 has event-role "newborn" isa event-protagonist (protagonist: $295008, happening: $307216);
$41168912 (protagonist: $385200, happening: $323640) isa event-protagonist has event-role "parent";
$41177104 (protagonist: $757936, happening: $954464) isa event-protagonist has event-role "parent";
$561248 has event-role "newborn" isa event-protagonist (protagonist: $524336, happening: $475312);
$573536 has event-role "deceased" isa event-protagonist (protagonist: $524336, happening: $483504);
$598112 (protagonist: $512184, happening: $589920) has event-role "deceased" isa event-protagonist;
$634976 (protagonist: $557120, happening: $655408) has event-role "deceased" isa event-protagonist;
$135272 has event-role "deceased" isa event-protagonist (protagonist: $41062648, happening: $41099336);
$696416 has event-role "deceased" isa event-protagonist (protagonist: $659576, happening: $610488);
$708704 has event-role "newborn" (protagonist: $618680, happening: $692344) isa event-protagonist;
$716896 has event-role "deceased" isa event-protagonist (protagonist: $618680, happening: $696408);
$766048 has event-role "deceased" isa event-protagonist (protagonist: $675904, happening: $663728);
$888928 has event-role "deceased" isa event-protagonist (protagonist: $864376, happening: $909328);
$630904 has event-role "newborn" isa event-protagonist (protagonist: $602360, happening: $651320);
$40968192 (protagonist: $405568, happening: $40964096) isa event-protagonist has event-role "spouse";
$40980480 isa event-protagonist (protagonist: $41037864, happening: $81932408) has event-role "spouse";
$41086976 isa event-protagonist (protagonist: $557120, happening: $192672) has event-role "spouse";
$761976 has event-role "newborn" isa event-protagonist (protagonist: $749656, happening: $757880);
$41111552 isa event-protagonist (protagonist: $618680, happening: $122957864) has event-role "spouse";
$819320 has event-role "deceased" isa event-protagonist (protagonist: $708672, happening: $798816);
$856184 has event-role "deceased" (protagonist: $843872, happening: $909360) isa event-protagonist;
$905336 has event-role "newborn" isa event-protagonist (protagonist: $757936, happening: $946192);
$123000 has event-role "newborn" isa event-protagonist (protagonist: $122896, happening: $110712);
$159864 has event-role "newborn" (protagonist: $139384, happening: $143480) isa event-protagonist;
$176248 has event-role "deceased" isa event-protagonist (protagonist: $127072, happening: $192528);
$209016 has event-role "newborn" isa event-protagonist (protagonist: $217104, happening: $172096);
$282744 has event-role "deceased" isa event-protagonist (protagonist: $295008, happening: $311384);
$331896 has event-role "deceased" (protagonist: $327856, happening: $393232) isa event-protagonist;
$479352 has event-role "deceased" isa event-protagonist (protagonist: $483376, happening: $446640);
$41111800 has event-role "newborn" isa event-protagonist (protagonist: $41099512, happening: $41193512);
$41005288 (protagonist: $483448, happening: $41021512) isa event-protagonist has event-role "parent";
$41021672 (protagonist: $295008, happening: $180344) isa event-protagonist has event-role "parent";
$41038056 (protagonist: $483448, happening: $155752) isa event-protagonist has event-role "parent";
$41050344 (protagonist: $41062648, happening: $41193512) isa event-protagonist has event-role "parent";
$41054440 (protagonist: $483448, happening: $4328) isa event-protagonist has event-role "parent";
$41087208 (protagonist: $41037864, happening: $65768) isa event-protagonist has event-role "parent";
$81936504 isa event-protagonist (protagonist: $41062648, happening: $81932408) has event-role "spouse";
$81961080 (protagonist: $229424, happening: $20720) isa event-protagonist has event-role "spouse";
$41099496 (protagonist: $348176, happening: $307216) isa event-protagonist has event-role "parent";
$41136360 (protagonist: $295008, happening: $389168) isa event-protagonist has event-role "parent";
$41144552 isa event-protagonist has event-role "parent" (protagonist: $405520, happening: $389168);
$41148648 isa event-protagonist has event-role "parent" (protagonist: $405520, happening: $110712);
$82002040 (protagonist: $757936, happening: $81993848) isa event-protagonist has event-role "spouse";
$82010232 (protagonist: $548920, happening: $81993848) isa event-protagonist has event-role "spouse";
$82022520 isa event-protagonist (protagonist: $41024, happening: $122916904) has event-role "spouse";
$82038904 isa event-protagonist (protagonist: $405568, happening: $81965136) has event-role "spouse";
$82067576 (protagonist: $831544, happening: $122929192) isa event-protagonist has event-role "spouse";
$82129016 isa event-protagonist has event-role "spouse" (protagonist: $327856, happening: $192672);
$82174072 isa event-protagonist has event-role "spouse" (protagonist: $708856, happening: $270496);
$82215032 isa event-protagonist (protagonist: $843792, happening: $295072) has event-role "spouse";
$110752 (protagonist: $380992, happening: $41009336) isa event-protagonist has event-role "spouse";
$155808 isa event-protagonist (protagonist: $512184, happening: $114928) has event-role "spouse";
$176288 (protagonist: $295008, happening: $82108536) isa event-protagonist has event-role "spouse";
$245920 isa event-protagonist (protagonist: $708672, happening: $82030672) has event-role "spouse";
$254112 isa event-protagonist has event-role "spouse" (protagonist: $41099512, happening: $82030672);
$303264 isa event-protagonist (protagonist: $184384, happening: $82223224) has event-role "spouse";
$307360 (protagonist: $81968, happening: $82223224) isa event-protagonist has event-role "spouse";
$319648 isa event-protagonist (protagonist: $348176, happening: $82247800) has event-role "spouse";
$327840 isa event-protagonist (protagonist: $385200, happening: $82247800) has event-role "spouse";
$348320 (protagonist: $122896, happening: $82260088) isa event-protagonist has event-role "spouse";
$32936 has event-role "deceased" isa event-protagonist (protagonist: $4264, happening: $40968440);
$143528 has event-role "newborn" (protagonist: $41078832, happening: $155752) isa event-protagonist;
$45232 has event-role "deceased" isa event-protagonist (protagonist: $24664, happening: $45072);
$229552 (protagonist: $237664, happening: $258144) has event-role "deceased" isa event-protagonist;
$745656 has event-role "deceased" isa event-protagonist (protagonist: $843792, happening: $839800);
$81985616 isa event-protagonist (protagonist: $483448, happening: $122929192) has event-role "spouse";
$81989712 (protagonist: $90216, happening: $139424) isa event-protagonist has event-role "spouse";
$81997904 (protagonist: $643136, happening: $114928) isa event-protagonist has event-role "spouse";
$82002000 (protagonist: $405520, happening: $82108536) isa event-protagonist has event-role "spouse";
$82018384 (protagonist: $864504, happening: $122957864) isa event-protagonist has event-role "spouse";
$299184 has event-role "newborn" (protagonist: $356448, happening: $299064) isa event-protagonist;
$835768 has event-role "deceased" (protagonist: $864504, happening: $966712) isa event-protagonist;
$82055248 (protagonist: $380992, happening: $41132032) isa event-protagonist has event-role "spouse";
$82075728 (protagonist: $843872, happening: $295072) isa event-protagonist has event-role "spouse";
$352432 has event-role "deceased" isa event-protagonist (protagonist: $335936, happening: $417888);
$409776 has event-role "deceased" (protagonist: $385200, happening: $442432) isa event-protagonist;
$438448 has event-role "newborn" (protagonist: $483376, happening: $458816) isa event-protagonist;
$512176 has event-role "newborn" isa event-protagonist (protagonist: $528448, happening: $499888);
$565424 has event-role "newborn" isa event-protagonist (protagonist: $610360, happening: $614456);
$626864 has event-role "newborn" (protagonist: $643136, happening: $635064) isa event-protagonist;
$143544 has event-role "deceased" (protagonist: $159840, happening: $139448) isa event-protagonist;
$164024 has event-role "deceased" isa event-protagonist (protagonist: $217104, happening: $229392);
$716976 has event-role "newborn" (protagonist: $843872, happening: $843896) isa event-protagonist;
$291000 has event-role "newborn" isa event-protagonist (protagonist: $348176, happening: $282808);
$323768 has event-role "deceased" isa event-protagonist (protagonist: $356448, happening: $311416);
$790704 has event-role "newborn" isa event-protagonist (protagonist: $942168, happening: $954464);
$41001144 isa event-protagonist (protagonist: $127072, happening: $81965136) has event-role "spouse";
$41029816 isa event-protagonist (protagonist: $139384, happening: $41009336) has event-role "spouse";
$41046200 (protagonist: $483376, happening: $139424) isa event-protagonist has event-role "spouse";
$81952808 (protagonist: $864504, happening: $651320) isa event-protagonist has event-role "parent";
$41091256 (protagonist: $675904, happening: $213152) isa event-protagonist has event-role "spouse";
$81989672 isa event-protagonist (protagonist: $831544, happening: $155752) has event-role "parent";
$82010152 (protagonist: $41062648, happening: $40984648) isa event-protagonist has event-role "parent";
$82034728 isa event-protagonist has event-role "parent" (protagonist: $196656, happening: $364792);
$81928240 (protagonist: $405568, happening: $462896) isa event-protagonist has event-role "parent";
$81932336 (protagonist: $258104, happening: $282808) isa event-protagonist has event-role "parent";
$81948720 isa event-protagonist has event-role "parent" (protagonist: $385200, happening: $635064);
$81965104 isa event-protagonist has event-role "parent" (protagonist: $618680, happening: $725112);
$81981488 (protagonist: $618680, happening: $757880) isa event-protagonist has event-role "parent";
$82026544 isa event-protagonist (protagonist: $405520, happening: $180344) has event-role "parent";
$82038832 isa event-protagonist has event-role "parent" (protagonist: $348176, happening: $81984);
$82059312 (protagonist: $24664, happening: $946192) isa event-protagonist has event-role "parent";
$82087984 (protagonist: $757936, happening: $458816) isa event-protagonist has event-role "parent";
$82128944 (protagonist: $385200, happening: $364664) isa event-protagonist has event-role "parent";
$82145328 isa event-protagonist (protagonist: $831544, happening: $4328) has event-role "parent";
$82169904 isa event-protagonist (protagonist: $864504, happening: $573496) has event-role "parent";
$82178096 (protagonist: $618680, happening: $573496) isa event-protagonist has event-role "parent";
$82186288 (protagonist: $217104, happening: $364792) isa event-protagonist has event-role "parent";
$82198576 (protagonist: $385200, happening: $307216) isa event-protagonist has event-role "parent";
$82206768 isa event-protagonist has event-role "parent" (protagonist: $757936, happening: $614456);
$82214960 isa event-protagonist (protagonist: $548920, happening: $614456) has event-role "parent";
$82235440 (protagonist: $24664, happening: $458928) isa event-protagonist has event-role "parent";
$82284592 (protagonist: $405568, happening: $41087048) isa event-protagonist has event-role "parent";
$40964264 isa event-protagonist (protagonist: $24664, happening: $40964096) has event-role "spouse";
$40988840 isa event-protagonist (protagonist: $237664, happening: $20720) has event-role "spouse";
$45296 (protagonist: $917560, happening: $37104) isa event-protagonist has event-role "spouse";
$53488 isa event-protagonist (protagonist: $524336, happening: $37104) has event-role "spouse";
$78064 (protagonist: $335936, happening: $122916904) isa event-protagonist has event-role "spouse";
$598264 (protagonist: $679984, happening: $708656) has event-role "deceased" isa event-protagonist;
$155888 isa event-protagonist (protagonist: $864376, happening: $213152) has event-role "spouse";
$176368 isa event-protagonist (protagonist: $356448, happening: $41132032) has event-role "spouse";
$217328 (protagonist: $4112, happening: $82260088) isa event-protagonist has event-role "spouse";
$725240 has event-role "deceased" isa event-protagonist (protagonist: $708856, happening: $761872);
$762104 has event-role "deceased" isa event-protagonist (protagonist: $749656, happening: $770136);
$766200 has event-role "newborn" isa event-protagonist (protagonist: $831544, happening: $676016);
$803064 has event-role "newborn" (protagonist: $843792, happening: $815200) isa event-protagonist;
$86264 has event-role "newborn" (protagonist: $73824, happening: $81984) isa event-protagonist;
$295160 has event-role "deceased" (protagonist: $258104, happening: $299128) isa event-protagonist;
$372984 has event-role "newborn" isa event-protagonist (protagonist: $405520, happening: $364792);
$401656 has event-role "newborn" isa event-protagonist (protagonist: $385200, happening: $462896);
$463096 has event-role "newborn" isa event-protagonist (protagonist: $483448, happening: $458928);
$122974248 isa event-protagonist has event-role "spouse" (protagonist: $73824, happening: $270496);
