insert

$parentsOfParentsAreGrandparents isa inference-rule
lhs
{(parent:$p, child: $gc) isa parentship;
(parent: $gp, child: $p) isa parentship;
}
rhs
{(grandparent: $gp, grandchild: $gc) isa grandparentship;};

#TODO: This requires the childrent to be different! (Possibly the parents, too if gender is not available)

$peopleWithSameParentsAreSiblings isa inference-rule
lhs
{(parent: $m, child: $x) isa parentship;
(parent: $m, child: $y) isa parentship;
(parent: $f, child: $x) isa parentship;
(parent: $f, child: $y) isa parentship;
$m has gender "female";
$f has gender "male";
$x != $y;
}
rhs
{(sibling1: $x, sibling2: $y) isa siblings;};

#TODO: Avoiding explicitly the cousins to be the same would be nice (siblings should take care of this, though)

$peopleWithSiblingsParentsAreCousins isa inference-rule
lhs
{
(parent: $p, child: $c1) isa parentship;
($p, $p2) isa siblings;
(parent: $p2, child: $c2) isa parentship;
$c1 != $c2;
}
rhs
{(cousin1: $c1, cousin2: $c2) isa cousins;};

$parentsOfSpousesAreInLaws isa inference-rule
lhs
{(spouse1: $x, spouse2: $y) isa marriage;
(parent: $il, child: $y) isa parentship;}
rhs
{(parent-in-law: $il, child-in-law: $x) isa in-laws;};

$parentsOfSpousesAreInLaws2 isa inference-rule
lhs
{(spouse1: $x, spouse2: $y) isa marriage;
(parent: $il, child: $x) isa parentship;}
rhs
{(parent-in-law: $il, child-in-law: $y) isa in-laws;};

#TODO: THIS IS HOW THE RULE SHOULD LOOK LIKE. FOR THE MOMENT I WILL USE TWO RULES INSTEAD
#$parentsOfSpousesAreInLaws isa inference-rule
#lhs
#{($r1: $x, $r2: $y) isa marriage;
#$r1 isa generic-spouse;
#$r2 isa generic-spouse;
#(parent: $il, child: $y) isa parentship;}
#rhs
#{(parent-in-law: $il, child-in-law: $x) isa in-laws;};
