insert

# TODO: materializing the relationships would make this much cleaner (genderized role would be added to the same relationship)

isa inference-rule
lhs
{(grandparent: $x, grandchild: $y) isa grandparentship;
$x has gender "female";
}
rhs
{(grandmother: $x) isa grandparentship;};

isa inference-rule
lhs
{(grandparent: $x, grandchild: $y) isa grandparentship;
$x has gender "male";
}
rhs
{(grandfather: $x) isa grandparentship;};

isa inference-rule
lhs
{(grandchild: $x, grandparent: $y) isa grandparentship;
$x has gender "male";
}
rhs
{(grandson: $x) isa grandparentship;};

isa inference-rule
lhs
{(grandchild: $x, grandparent: $y) isa grandparentship;
$x has gender "female";
}
rhs
{(granddaughter: $x) isa grandparentship;};

isa inference-rule
lhs
{(parent: $x, child: $y) isa parentship;
$x has gender "female";
}
rhs
{(mother: $x) isa parentship;};

isa inference-rule
lhs
{(parent: $x, child: $y) isa parentship;
$x has gender "male";
}
rhs
{(father: $x) isa parentship;};

isa inference-rule
lhs
{(child: $x, parent: $y) isa parentship;
$x has gender "female";
}
rhs
{(daughter: $x) isa parentship;};

isa inference-rule
lhs
{(child: $x, parent: $y) isa parentship;
$x has gender "male";
}
rhs
{(son: $x) isa parentship;};

isa inference-rule
lhs
{($x) isa marriage; $x has gender "female";}
rhs
{(wife: $x) isa marriage;};

isa inference-rule
lhs
{($x) isa marriage; $x has gender "male";}
rhs
{(husband: $x) isa marriage;};

# TODO: Genderize in-laws
isa inference-rule
lhs
{(parent-in-law: $x, child-in-law: $y) isa in-laws;
$x has gender "male";
}
rhs
{(father-in-law: $x) isa in-laws;};

isa inference-rule
lhs
{(parent-in-law: $x, child-in-law: $y) isa in-laws;
$x has gender "female";
}
rhs
{(mother-in-law: $x) isa in-laws;};

isa inference-rule
lhs
{(child-in-law: $x, parent-in-law: $y) isa in-laws;
$x has gender "male";
}
rhs
{(son-in-law: $x) isa in-laws;};

isa inference-rule
lhs
{(child-in-law: $x, parent-in-law: $y) isa in-laws;
$x has gender "female";
}
rhs
{(daughter-in-law: $x) isa in-laws;};
