java_library(
    name = "kryo-shaded",
    exports = [
        "//external:jar/com/esotericsoftware/kryo-shaded"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/objenesis:objenesis",
        ":minlog"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "minlog",
    exports = [
        "//external:jar/com/esotericsoftware/minlog"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


