insert

pokemon sub entity
    plays pokemon-with-type
    has pokedex-no
    has description
    has height
    has weight;

type-id sub resource datatype long;
pokedex-no sub resource datatype long;
description sub resource datatype string;
height sub resource datatype long;
weight sub resource datatype long;

pokemon-type sub entity
    has description
    has type-id
    plays type-of-pokemon;

has-type sub relation
    relates pokemon-with-type
    relates type-of-pokemon;
pokemon-with-type sub role;
type-of-pokemon sub role;
