const META_TYPE = "META_TYPE";
const ATTRIBUTE_TYPE = "ATTRIBUTE_TYPE";
const RELATIONSHIP_TYPE = "RELATIONSHIP_TYPE";
const ENTITY_TYPE = "ENTITY_TYPE";
const ENTITY = "ENTITY";
const ATTRIBUTE = "ATTRIBUTE";
const RELATIONSHIP = "RELATIONSHIP";
const ROLE = "ROLE";
const RULE = "RULE";

const SCHEMA_CONCEPTS = new Set([RULE, ROLE, ATTRIBUTE_TYPE, RELATIONSHIP_TYPE, ENTITY_TYPE]);
const TYPES = new Set([ATTRIBUTE_TYPE, RELATIONSHIP_TYPE, ENTITY_TYPE]);
const THINGS = new Set([ATTRIBUTE, RELATIONSHIP, ATTRIBUTE, ENTITY]);

module.exports = {
    baseType: {
        META_TYPE,
        ATTRIBUTE,
        ATTRIBUTE_TYPE,
        ROLE,
        RULE,
        RELATIONSHIP,
        RELATIONSHIP_TYPE,
        ENTITY,
        ENTITY_TYPE
    },
    set: {
        SCHEMA_CONCEPTS, TYPES, THINGS
    }
};
