java_library(
    name = "jets3t",
    exports = [
        "//external:jar/net/java/dev/jets3t/jets3t"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/jamesmurty/utils:java-xmlbuilder",
        "//dependencies/maven/artifacts/commons-codec:commons-codec",
        "//dependencies/maven/artifacts/commons-logging:commons-logging",
        "//dependencies/maven/artifacts/javax/activation:activation",
        "//dependencies/maven/artifacts/javax/mail:mail",
        "//dependencies/maven/artifacts/mx4j:mx4j",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpclient",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpcore",
        "//dependencies/maven/artifacts/org/bouncycastle:bcprov-jdk15on",
        "//dependencies/maven/artifacts/org/codehaus/jackson:jackson-core-asl",
        "//dependencies/maven/artifacts/org/codehaus/jackson:jackson-mapper-asl"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


