java_library(
    name = "jets3t",
    exports = [
        "//external:jar/net/java/dev/jets3t/jets3t"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/jamesmurty/utils:java_xmlbuilder",
        "//dependencies/maven/artifacts/commons_codec:commons_codec",
        "//dependencies/maven/artifacts/javax/activation:activation",
        "//dependencies/maven/artifacts/javax/mail:mail",
        "//dependencies/maven/artifacts/mx4j:mx4j",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpclient",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpcore",
        "//dependencies/maven/artifacts/org/bouncycastle:bcprov_jdk15on",
        "//dependencies/maven/artifacts/org/codehaus/jackson:jackson_core_asl",
        "//dependencies/maven/artifacts/org/codehaus/jackson:jackson_mapper_asl"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


