java_library(
    name = "error-prone-annotations",
    exports = [
        "//external:jar/com/google/errorprone/error-prone-annotations"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


