java_library(
    name = "caffeine",
    exports = [
        "//external:jar/com/github/ben-manes/caffeine/caffeine"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/errorprone:error-prone-annotations",
        "//dependencies/maven/artifacts/org/checkerframework:checker-qual"
    ],
    visibility = [
        "//visibility:public"
    ]
)


