java_library(
    name = "jnr-constants",
    exports = [
        "//external:jar/com/github/jnr/jnr-constants"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "jnr-posix",
    exports = [
        "//external:jar/com/github/jnr/jnr-posix"
    ],
    runtime_deps = [
        ":jnr-constants"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


