insert $a1 isa article has title "Italy’s tangled oil and gas referendum"
has uri "http://www.politico.eu/article/italy-referendum-oil-drilling-platforms-offshore-matteo-renzi-rigs-gas-renewables/" has subject "Italian Referendum";
insert $a2 isa article has title "Italy oil referendum a vote that Matteo Renzi does not want"
has uri "https://www.ft.com/content/20e47b6a-0244-11e6-9cc4-27926f2b110c" has subject "Italian Referendum";


insert $x isa company has name "BP";
insert $x isa company has name "Centrica";
insert $x isa company has name "Chevron";
insert $x isa company has name "China Petrochemical Corporation";
insert $x isa company has name "ENI";
insert $x isa company has name "Exxon Mobil";
insert $x isa company has name "Kuwait Energy Co";
insert $x isa company has name "Lukoil";
insert $x isa company has name "Qatargas";
insert $x isa company has name "Shell";
insert $x isa company has name "TOTAL";
insert $x isa company has name "YPF";
insert $x isa country has name "Afghanistan";
insert $x isa country has name "Albania";
insert $x isa country has name "Algeria";
insert $x isa country has name "Angola";
insert $x isa country has name "Angola/Congo Unitized Area";
insert $x isa country has name "Argentina";
insert $x isa country has name "Australia";
insert $x isa country has name "Austria";
insert $x isa country has name "Azerbaijan";
insert $x isa country has name "Bahrain";
insert $x isa country has name "Bangladesh";
insert $x isa country has name "Barbados";
insert $x isa country has name "Belarus";
insert $x isa country has name "Belize";
insert $x isa country has name "Benin";
insert $x isa country has name "Bolivia";
insert $x isa country has name "Bosnia and Herzegovina";
insert $x isa country has name "Botswana";
insert $x isa country has name "Brazil";
insert $x isa country has name "Brunei";
insert $x isa country has name "Bulgaria";
insert $x isa country has name "Cambodia";
insert $x isa country has name "Cameroon";
insert $x isa country has name "Canada";
insert $x isa country has name "Chad";
insert $x isa country has name "Chile";
insert $x isa country has name "China";
insert $x isa country has name "Colombia";
insert $x isa country has name "Congo";
insert $x isa country has name "Cote d\'Ivoire";
insert $x isa country has name "Croatia";
insert $x isa country has name "Cuba";
insert $x isa country has name "Cyprus";
insert $x isa country has name "Czech Republic";
insert $x isa country has name "Democratic Republic of Congo";
insert $x isa country has name "Denmark";
insert $x isa country has name "Divided Zone";
insert $x isa country has name "Ecuador";
insert $x isa country has name "Egypt";
insert $x isa country has name "Equatorial Guinea";
insert $x isa country has name "Ethiopia";
insert $x isa country has name "Falkland Islands";
insert $x isa country has name "Faroe Islands";
insert $x isa country has name "France";
insert $x isa country has name "French Guiana";
insert $x isa country has name "Gabon";
insert $x isa country has name "Georgia";
insert $x isa country has name "Germany";
insert $x isa country has name "Ghana";
insert $x isa country has name "Greece";
insert $x isa country has name "Guatemala";
insert $x isa country has name "Guinea";
insert $x isa country has name "Guinea-Bissau";
insert $x isa country has name "Guyana";
insert $x isa country has name "Hungary";
insert $x isa country has name "India";
insert $x isa country has name "Indonesia";
insert $x isa country has name "Iran";
insert $x isa country has name "Iraq";
insert $x isa country has name "Ireland";
insert $x isa country has name "Israel";
insert $x isa country has name "Italy";
insert $x isa country has name "Japan";
insert $x isa country has name "Jordan";
insert $x isa country has name "Kazakhstan";
insert $x isa country has name "Kenya";
insert $x isa country has name "Kuwait";
insert $x isa country has name "Kyrgyzstan";
insert $x isa country has name "Latvia";
insert $x isa country has name "Liberia";
insert $x isa country has name "Libya";
insert $x isa country has name "Libya/Tunisia JEZ";
insert $x isa country has name "Lithuania";
insert $x isa country has name "Madagascar";
insert $x isa country has name "Malaysia";
insert $x isa country has name "Malaysia/Thailand JDA";
insert $x isa country has name "Malta";
insert $x isa country has name "Mauritania";
insert $x isa country has name "Mexico";
insert $x isa country has name "Moldova";
insert $x isa country has name "Mongolia";
insert $x isa country has name "Morocco";
insert $x isa country has name "Mozambique";
insert $x isa country has name "Myanmar";
insert $x isa country has name "Namibia";
insert $x isa country has name "Netherlands";
insert $x isa country has name "New Zealand";
insert $x isa country has name "Niger";
insert $x isa country has name "Nigeria";
insert $x isa country has name "Nigeria/Sao Tome and Principe JDZ";
insert $x isa country has name "Norway";
insert $x isa country has name "Oman";
insert $x isa country has name "Pakistan";
insert $x isa country has name "Papua New Guinea";
insert $x isa country has name "Paraguay";
insert $x isa country has name "Peru";
insert $x isa country has name "Philippines";
insert $x isa country has name "Poland";
insert $x isa country has name "Portugal";
insert $x isa country has name "Qatar";
insert $x isa country has name "Romania";
insert $x isa country has name "Russia";
insert $x isa country has name "San Marino";
insert $x isa country has name "Saudi Arabia";
insert $x isa country has name "Senegal";
insert $x isa country has name "Serbia";
insert $x isa country has name "Sierra Leone";
insert $x isa country has name "Slovakia";
insert $x isa country has name "Slovenia";
insert $x isa country has name "Somalia";
insert $x isa country has name "South Africa";
insert $x isa country has name "South Korea";
insert $x isa country has name "South Sudan";
insert $x isa country has name "Spain";
insert $x isa country has name "Sri Lanka";
insert $x isa country has name "Sudan";
insert $x isa country has name "Suriname";
insert $x isa country has name "Sweden";
insert $x isa country has name "Switzerland";
insert $x isa country has name "Syria";
insert $x isa country has name "Taiwan";
insert $x isa country has name "Tajikistan";
insert $x isa country has name "Tanzania";
insert $x isa country has name "Thailand";
insert $x isa country has name "Timor Sea JPDA";
insert $x isa country has name "Trinidad and Tobago";
insert $x isa country has name "Tunisia";
insert $x isa country has name "Turkey";
insert $x isa country has name "Turkmenistan";
insert $x isa country has name "UAE - Abu Dhabi";
insert $x isa country has name "UAE - Ajman";
insert $x isa country has name "UAE - Dubai";
insert $x isa country has name "UAE - Ras al Khaimah";
insert $x isa country has name "UAE - Sharjah";
insert $x isa country has name "UAE - Umm al Qaiwain";
insert $x isa country has name "Uganda";
insert $x isa country has name "Ukraine";
insert $x isa country has name "United Kingdom";
insert $x isa country has name "United States";
insert $x isa country has name "Uruguay";
insert $x isa country has name "Uzbekistan";
insert $x isa country has name "Venezuela";
insert $x isa country has name "Vietnam";
insert $x isa country has name "Yemen";
insert $x isa region has name "C.I.S.";
insert $x isa region has name "Latin America";
insert $x isa region has name "North America";
insert $x isa region has name "Australasia";
insert $x isa region has name "Far East";
insert $x isa region has name "Europe";
insert $x isa region has name "Middle East";
insert $x isa region has name "Africa";


match $country isa country has name "Afghanistan"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Albania"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Algeria"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Angola"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Angola\/Congo Unitized Area"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Argentina"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Australia"; $region isa region has name "Australasia";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Austria"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Azerbaijan"; $region isa region has name "C.I.S.";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Bahrain"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Bangladesh"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Barbados"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Belarus"; $region isa region has name "C.I.S.";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Belize"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Benin"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Bolivia"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Bosnia and Herzegovina"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Botswana"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Brazil"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Brunei"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Bulgaria"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Cambodia"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Cameroon"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Canada"; $region isa region has name "North America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Chad"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Chile"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "China"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Colombia"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Congo"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Cote d\'Ivoire"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Croatia"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Cuba"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Cyprus"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Czech Republic"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Democratic Republic of Congo"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Denmark"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Divided Zone"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Ecuador"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Egypt"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Equatorial Guinea"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Ethiopia"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Falkland Islands"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Faroe Islands"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "France"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "French Guiana"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Gabon"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Georgia"; $region isa region has name "C.I.S.";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Germany"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Ghana"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Greece"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Guatemala"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Guinea"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Guinea-Bissau"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Guyana"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Hungary"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "India"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Indonesia"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Iran"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Iraq"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Ireland"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Israel"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Italy"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Japan"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Jordan"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Kazakhstan"; $region isa region has name "C.I.S.";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Kenya"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Kuwait"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Kyrgyzstan"; $region isa region has name "C.I.S.";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Latvia"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Liberia"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Libya"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Libya\/Tunisia JEZ"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Lithuania"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Madagascar"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Malaysia"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Malaysia\/Thailand JDA"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Malta"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Mauritania"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Mexico"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Moldova"; $region isa region has name "C.I.S.";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Mongolia"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Morocco"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Mozambique"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Myanmar"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Namibia"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Netherlands"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "New Zealand"; $region isa region has name "Australasia";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Niger"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Nigeria"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Nigeria\/Sao Tome and Principe JDZ"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Norway"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Oman"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Pakistan"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Papua New Guinea"; $region isa region has name "Australasia";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Paraguay"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Peru"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Philippines"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Poland"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Portugal"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Qatar"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Romania"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Russia"; $region isa region has name "C.I.S.";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "San Marino"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Saudi Arabia"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Senegal"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Serbia"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Sierra Leone"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Slovakia"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Slovenia"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Somalia"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "South Africa"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "South Korea"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "South Sudan"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Spain"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Sri Lanka"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Sudan"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Suriname"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Sweden"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Switzerland"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Syria"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Taiwan"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Tajikistan"; $region isa region has name "C.I.S.";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Tanzania"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Thailand"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Timor Sea JPDA"; $region isa region has name "Australasia";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Trinidad and Tobago"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Tunisia"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Turkey"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Turkmenistan"; $region isa region has name "C.I.S.";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "UAE - Abu Dhabi"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "UAE - Ajman"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "UAE - Dubai"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "UAE - Ras al Khaimah"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "UAE - Sharjah"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "UAE - Umm al Qaiwain"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Uganda"; $region isa region has name "Africa";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Ukraine"; $region isa region has name "C.I.S.";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "UK"; $region isa region has name "Europe";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "USA"; $region isa region has name "North America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Uruguay"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Uzbekistan"; $region isa region has name "C.I.S.";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Venezuela"; $region isa region has name "Latin America";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Vietnam"; $region isa region has name "Far East";
insert (located: $country, location: $region) isa located-in;
match $country isa country has name "Yemen"; $region isa region has name "Middle East";
insert (located: $country, location: $region) isa located-in;

insert $x0 isa oil-platform has platform-id "1" has distance-from-coast 5;
insert $x0 isa oil-platform has platform-id "2" has distance-from-coast 46;
insert $x0 isa oil-platform has platform-id "3" has distance-from-coast 42;
insert $x0 isa oil-platform has platform-id "4" has distance-from-coast 11;
insert $x0 isa oil-platform has platform-id "5" has distance-from-coast 18;
insert $x0 isa oil-platform has platform-id "6" has distance-from-coast 19;
insert $x0 isa oil-platform has platform-id "7" has distance-from-coast 40;
insert $x0 isa oil-platform has platform-id "8";
insert $x0 isa oil-platform has platform-id "9";
insert $x0 isa oil-platform has platform-id "10" has distance-from-coast 24;
insert $x0 isa oil-platform has platform-id "11";
insert $x0 isa oil-platform has platform-id "12" has distance-from-coast 45;
insert $x0 isa oil-platform has platform-id "13" has distance-from-coast 10;
insert $x0 isa oil-platform has platform-id "14" has distance-from-coast 2;
insert $x0 isa oil-platform has platform-id "15" has distance-from-coast 43;
insert $x0 isa oil-platform has platform-id "16" has distance-from-coast 6;
insert $x0 isa oil-platform has platform-id "17";
insert $x0 isa oil-platform has platform-id "18" has distance-from-coast 33;
insert $x0 isa oil-platform has platform-id "19";
insert $x0 isa oil-platform has platform-id "20";
insert $x0 isa oil-platform has platform-id "21" has distance-from-coast 43;
insert $x0 isa oil-platform has platform-id "22";
insert $x0 isa oil-platform has platform-id "23" has distance-from-coast 45;
insert $x0 isa oil-platform has platform-id "24" has distance-from-coast 4;
insert $x0 isa oil-platform has platform-id "25" has distance-from-coast 2;
insert $x0 isa oil-platform has platform-id "26";
insert $x0 isa oil-platform has platform-id "27" has distance-from-coast 5;
insert $x0 isa oil-platform has platform-id "28";
insert $x0 isa oil-platform has platform-id "29" has distance-from-coast 17;
insert $x0 isa oil-platform has platform-id "30";
insert $x0 isa oil-platform has platform-id "31";
insert $x0 isa oil-platform has platform-id "32" has distance-from-coast 38;
insert $x0 isa oil-platform has platform-id "33";
insert $x0 isa oil-platform has platform-id "34";
insert $x0 isa oil-platform has platform-id "35" has distance-from-coast 4;
insert $x0 isa oil-platform has platform-id "36";
insert $x0 isa oil-platform has platform-id "37";
insert $x0 isa oil-platform has platform-id "38" has distance-from-coast 42;
insert $x0 isa oil-platform has platform-id "39" has distance-from-coast 5;
insert $x0 isa oil-platform has platform-id "40";
insert $x0 isa oil-platform has platform-id "41" has distance-from-coast 17;
insert $x0 isa oil-platform has platform-id "42" has distance-from-coast 39;
insert $x0 isa oil-platform has platform-id "43" has distance-from-coast 37;
insert $x0 isa oil-platform has platform-id "44" has distance-from-coast 27;
insert $x0 isa oil-platform has platform-id "45" has distance-from-coast 45;
insert $x0 isa oil-platform has platform-id "46" has distance-from-coast 19;
insert $x0 isa oil-platform has platform-id "47" has distance-from-coast 6;
insert $x0 isa oil-platform has platform-id "48" has distance-from-coast 35;
insert $x0 isa oil-platform has platform-id "49";
insert $x0 isa oil-platform has platform-id "50";
insert $x0 isa oil-platform has platform-id "51";
insert $x0 isa oil-platform has platform-id "52";
insert $x0 isa oil-platform has platform-id "53";
insert $x0 isa oil-platform has platform-id "54";
insert $x0 isa oil-platform has platform-id "55" has distance-from-coast 2;
insert $x0 isa oil-platform has platform-id "56" has distance-from-coast 33;
insert $x0 isa oil-platform has platform-id "57" has distance-from-coast 10;
insert $x0 isa oil-platform has platform-id "58";
insert $x0 isa oil-platform has platform-id "59" has distance-from-coast 23;
insert $x0 isa oil-platform has platform-id "60";
insert $x0 isa oil-platform has platform-id "61" has distance-from-coast 44;
insert $x0 isa oil-platform has platform-id "62" has distance-from-coast 2;
insert $x0 isa oil-platform has platform-id "63" has distance-from-coast 3;
insert $x0 isa oil-platform has platform-id "64" has distance-from-coast 3;
insert $x0 isa oil-platform has platform-id "65";
insert $x0 isa oil-platform has platform-id "66" has distance-from-coast 12;
insert $x0 isa oil-platform has platform-id "67" has distance-from-coast 45;
insert $x0 isa oil-platform has platform-id "68" has distance-from-coast 14;
insert $x0 isa oil-platform has platform-id "69" has distance-from-coast 36;
insert $x0 isa oil-platform has platform-id "70";
insert $x0 isa oil-platform has platform-id "71" has distance-from-coast 26;
insert $x0 isa oil-platform has platform-id "72";
insert $x0 isa oil-platform has platform-id "73";
insert $x0 isa oil-platform has platform-id "74";
insert $x0 isa oil-platform has platform-id "75" has distance-from-coast 40;
insert $x0 isa oil-platform has platform-id "76" has distance-from-coast 4;
insert $x0 isa oil-platform has platform-id "77" has distance-from-coast 19;
insert $x0 isa oil-platform has platform-id "78" has distance-from-coast 21;
insert $x0 isa oil-platform has platform-id "79";
insert $x0 isa oil-platform has platform-id "80";
insert $x0 isa oil-platform has platform-id "81";
insert $x0 isa oil-platform has platform-id "82";
insert $x0 isa oil-platform has platform-id "83";
insert $x0 isa oil-platform has platform-id "84";
insert $x0 isa oil-platform has platform-id "85";
insert $x0 isa oil-platform has platform-id "86" has distance-from-coast 13;
insert $x0 isa oil-platform has platform-id "87";
insert $x0 isa oil-platform has platform-id "88";
insert $x0 isa oil-platform has platform-id "89" has distance-from-coast 11;
insert $x0 isa oil-platform has platform-id "90";
insert $x0 isa oil-platform has platform-id "91";
insert $x0 isa oil-platform has platform-id "92" has distance-from-coast 20;
insert $x0 isa oil-platform has platform-id "93" has distance-from-coast 41;
insert $x0 isa oil-platform has platform-id "94" has distance-from-coast 12;
insert $x0 isa oil-platform has platform-id "95" has distance-from-coast 41;
insert $x0 isa oil-platform has platform-id "96";
insert $x0 isa oil-platform has platform-id "97";
insert $x0 isa oil-platform has platform-id "98" has distance-from-coast 15;
insert $x0 isa oil-platform has platform-id "99" has distance-from-coast 23;
insert $x0 isa oil-platform has platform-id "100" has distance-from-coast 29;

match $company0 isa company has name "ENI"; $country0 isa country has name "Italy"; $platform0 isa oil-platform has platform-id "1";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "2"; $company0 isa company has name "TOTAL"; $country0 isa country has name "Niger";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "3"; $company0 isa company has name "YPF"; $country0 isa country has name "Afghanistan";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "4"; $company0 isa company has name "Lukoil"; $country0 isa country has name "Congo";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "5"; $company0 isa company has name "TOTAL"; $country0 isa country has name "Italy";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "6"; $company0 isa company has name "Shell"; $country0 isa country has name "Trinidad and Tobago";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Angola\/Congo Unitized Area"; $platform0 isa oil-platform has platform-id "7"; $company0 isa company has name "YPF";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Chevron"; $platform0 isa oil-platform has platform-id "8"; $country0 isa country has name "Uzbekistan";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Cyprus"; $platform0 isa oil-platform has platform-id "9"; $company0 isa company has name "Shell";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "South Korea"; $company0 isa company has name "Exxon Mobil"; $platform0 isa oil-platform has platform-id "10";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Lukoil"; $country0 isa country has name "UAE - Sharjah"; $platform0 isa oil-platform has platform-id "11";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Egypt"; $company0 isa company has name "Kuwait Energy Co"; $platform0 isa oil-platform has platform-id "12";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "13"; $country0 isa country has name "Albania"; $company0 isa company has name "China Petrochemical Corporation";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "14"; $company0 isa company has name "Qatargas"; $country0 isa country has name "Brazil";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Chile"; $company0 isa company has name "Shell"; $platform0 isa oil-platform has platform-id "15";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Chevron"; $country0 isa country has name "Germany"; $platform0 isa oil-platform has platform-id "16";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Exxon Mobil"; $country0 isa country has name "Cambodia"; $platform0 isa oil-platform has platform-id "17";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "China"; $platform0 isa oil-platform has platform-id "18"; $company0 isa company has name "China Petrochemical Corporation";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "19"; $country0 isa country has name "Philippines"; $company0 isa company has name "China Petrochemical Corporation";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "South Korea"; $company0 isa company has name "Centrica"; $platform0 isa oil-platform has platform-id "20";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Japan"; $company0 isa company has name "Chevron"; $platform0 isa oil-platform has platform-id "21";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "BP"; $platform0 isa oil-platform has platform-id "22"; $country0 isa country has name "Jordan";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Faroe Islands"; $company0 isa company has name "Centrica"; $platform0 isa oil-platform has platform-id "23";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "24"; $country0 isa country has name "Saudi Arabia"; $company0 isa company has name "BP";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "25"; $company0 isa company has name "Exxon Mobil"; $country0 isa country has name "Equatorial Guinea";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "26"; $company0 isa company has name "Centrica"; $country0 isa country has name "Senegal";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "27"; $company0 isa company has name "Centrica"; $country0 isa country has name "Georgia";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "28"; $company0 isa company has name "Shell"; $country0 isa country has name "Kazakhstan";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Papua New Guinea"; $platform0 isa oil-platform has platform-id "29"; $company0 isa company has name "China Petrochemical Corporation";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Qatargas"; $country0 isa country has name "Malaysia\/Thailand JDA"; $platform0 isa oil-platform has platform-id "30";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Portugal"; $company0 isa company has name "Centrica"; $platform0 isa oil-platform has platform-id "31";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Taiwan"; $company0 isa company has name "Exxon Mobil"; $platform0 isa oil-platform has platform-id "32";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Chevron"; $platform0 isa oil-platform has platform-id "33"; $country0 isa country has name "UAE - Ajman";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Lukoil"; $platform0 isa oil-platform has platform-id "34"; $country0 isa country has name "UAE - Ajman";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "35"; $company0 isa company has name "TOTAL"; $country0 isa country has name "Ghana";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Thailand"; $platform0 isa oil-platform has platform-id "36"; $company0 isa company has name "Qatargas";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "37"; $country0 isa country has name "Mozambique"; $company0 isa company has name "TOTAL";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "38"; $company0 isa company has name "Qatargas"; $country0 isa country has name "Timor Sea JPDA";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "39"; $company0 isa company has name "Shell"; $country0 isa country has name "Kazakhstan";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "BP"; $country0 isa country has name "USA"; $platform0 isa oil-platform has platform-id "40";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "USA"; $platform0 isa oil-platform has platform-id "41"; $company0 isa company has name "Kuwait Energy Co";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Qatargas"; $platform0 isa oil-platform has platform-id "42"; $country0 isa country has name "Uzbekistan";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "43"; $company0 isa company has name "Shell"; $country0 isa country has name "UK";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Guatemala"; $platform0 isa oil-platform has platform-id "44"; $company0 isa company has name "China Petrochemical Corporation";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Exxon Mobil"; $country0 isa country has name "Italy"; $platform0 isa oil-platform has platform-id "45";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "46"; $company0 isa company has name "Lukoil"; $country0 isa country has name "Italy";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "ENI"; $country0 isa country has name "Faroe Islands"; $platform0 isa oil-platform has platform-id "47";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "48"; $country0 isa country has name "Guinea"; $company0 isa company has name "Kuwait Energy Co";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "49"; $company0 isa company has name "TOTAL"; $country0 isa country has name "Uganda";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "50"; $company0 isa company has name "YPF"; $country0 isa country has name "United Kingdom";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "51"; $country0 isa country has name "Argentina"; $company0 isa company has name "Shell";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "52"; $country0 isa country has name "Algeria"; $company0 isa company has name "China Petrochemical Corporation";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "53"; $company0 isa company has name "BP"; $country0 isa country has name "USA";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "TOTAL"; $platform0 isa oil-platform has platform-id "54"; $country0 isa country has name "Kazakhstan";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Turkey"; $platform0 isa oil-platform has platform-id "55"; $company0 isa company has name "Shell";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Chile"; $company0 isa company has name "Lukoil"; $platform0 isa oil-platform has platform-id "56";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Guinea-Bissau"; $company0 isa company has name "Lukoil"; $platform0 isa oil-platform has platform-id "57";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "ENI"; $platform0 isa oil-platform has platform-id "58"; $country0 isa country has name "Libya\/Tunisia JEZ";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "59"; $country0 isa country has name "Canada"; $company0 isa company has name "China Petrochemical Corporation";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Spain"; $platform0 isa oil-platform has platform-id "60"; $company0 isa company has name "BP";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "61"; $company0 isa company has name "Lukoil"; $country0 isa country has name "Kuwait";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "62"; $country0 isa country has name "Guatemala"; $company0 isa company has name "TOTAL";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "63"; $company0 isa company has name "Qatargas"; $country0 isa country has name "Equatorial Guinea";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Chile"; $platform0 isa oil-platform has platform-id "64"; $company0 isa company has name "Centrica";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Qatargas"; $platform0 isa oil-platform has platform-id "65"; $country0 isa country has name "Nigeria";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "China"; $platform0 isa oil-platform has platform-id "66"; $company0 isa company has name "Shell";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Chevron"; $platform0 isa oil-platform has platform-id "67"; $country0 isa country has name "Italy";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Lukoil"; $platform0 isa oil-platform has platform-id "68"; $country0 isa country has name "USA";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "China"; $company0 isa company has name "Lukoil"; $platform0 isa oil-platform has platform-id "69";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "70"; $country0 isa country has name "Madagascar"; $company0 isa company has name "Kuwait Energy Co";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "71"; $company0 isa company has name "BP"; $country0 isa country has name "UAE - Dubai";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "72"; $country0 isa country has name "USA"; $company0 isa company has name "China Petrochemical Corporation";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "73"; $company0 isa company has name "TOTAL"; $country0 isa country has name "Iran";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "74"; $company0 isa company has name "ENI"; $country0 isa country has name "Chile";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Angola"; $company0 isa company has name "BP"; $platform0 isa oil-platform has platform-id "75";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Turkmenistan"; $company0 isa company has name "Exxon Mobil"; $platform0 isa oil-platform has platform-id "76";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Iraq"; $platform0 isa oil-platform has platform-id "77"; $company0 isa company has name "Shell";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Mauritania"; $platform0 isa oil-platform has platform-id "78"; $company0 isa company has name "BP";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Democratic Republic of Congo"; $company0 isa company has name "Exxon Mobil"; $platform0 isa oil-platform has platform-id "79";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "80"; $country0 isa country has name "Uganda"; $company0 isa company has name "Kuwait Energy Co";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Cyprus"; $company0 isa company has name "Exxon Mobil"; $platform0 isa oil-platform has platform-id "81";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Turkmenistan"; $platform0 isa oil-platform has platform-id "82"; $company0 isa company has name "Centrica";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Qatargas"; $platform0 isa oil-platform has platform-id "83"; $country0 isa country has name "Cuba";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Benin"; $company0 isa company has name "TOTAL"; $platform0 isa oil-platform has platform-id "84";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Thailand"; $company0 isa company has name "Lukoil"; $platform0 isa oil-platform has platform-id "85";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "86"; $country0 isa country has name "Papua New Guinea"; $company0 isa company has name "ENI";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "87"; $company0 isa company has name "Qatargas"; $country0 isa country has name "Kyrgyzstan";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Taiwan"; $company0 isa company has name "Exxon Mobil"; $platform0 isa oil-platform has platform-id "88";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Faroe Islands"; $platform0 isa oil-platform has platform-id "89"; $company0 isa company has name "TOTAL";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "90"; $company0 isa company has name "Lukoil"; $country0 isa country has name "Sweden";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Cote d\\\'Ivoire"; $company0 isa company has name "YPF"; $platform0 isa oil-platform has platform-id "91";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Qatargas"; $platform0 isa oil-platform has platform-id "92"; $country0 isa country has name "Trinidad and Tobago";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "93"; $company0 isa company has name "Shell"; $country0 isa country has name "Kazakhstan";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Qatargas"; $platform0 isa oil-platform has platform-id "94"; $country0 isa country has name "Falkland Islands";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "ENI"; $country0 isa country has name "Latvia"; $platform0 isa oil-platform has platform-id "95";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $country0 isa country has name "Moldova"; $platform0 isa oil-platform has platform-id "96"; $company0 isa company has name "Kuwait Energy Co";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "97"; $country0 isa country has name "Namibia"; $company0 isa company has name "Shell";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "98"; $company0 isa company has name "Shell"; $country0 isa country has name "Pakistan";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $platform0 isa oil-platform has platform-id "99"; $company0 isa company has name "TOTAL"; $country0 isa country has name "South Sudan";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;
match $company0 isa company has name "Chevron"; $country0 isa country has name "USA"; $platform0 isa oil-platform has platform-id "100";
insert (located: $platform0, location: $country0) isa located-in;
(owned: $platform0, owner: $company0) isa owns;

match $issuer0 isa company has name "BP";
insert $bond0 isa bond has name "okCertificate8778" has risk 0.503283885076;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "amazingBond1706" has risk 0.508623858707;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "inventedBond8032" has risk 0.62374233818;
(issuer: $issuer0, issued: $bond2) isa issues;
$bond3 isa bond has name "inventedInstrument5802" has risk 0.289354948221;
(issuer: $issuer0, issued: $bond3) isa issues;
match $issuer0 isa company has name "Centrica";
insert $bond0 isa bond has name "awesomeInstrument3661" has risk 0.343787354726;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "randomObligation7215" has risk 0.859966494549;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "superfluousBond5322" has risk 0.234927024099;
(issuer: $issuer0, issued: $bond2) isa issues;
match $issuer0 isa company has name "Chevron";
insert $bond0 isa bond has name "amazingCertificate7263" has risk 0.213561189745;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "inventedObligation6165" has risk 0.700242354622;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "amazingObligation5085" has risk 0.904592493286;
(issuer: $issuer0, issued: $bond2) isa issues;
match $issuer0 isa company has name "China Petrochemical Corporation";
insert $bond0 isa bond has name "averageInstrument6307" has risk 0.722522626183;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "okInstrument1179" has risk 0.180545300828;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "randomObligation5100" has risk 0.152744205495;
(issuer: $issuer0, issued: $bond2) isa issues;
$bond3 isa bond has name "superfluousCertificate2101" has risk 0.315888913215;
(issuer: $issuer0, issued: $bond3) isa issues;
match $issuer0 isa company has name "ENI";
insert $bond0 isa bond has name "superfluousCertificate6263" has risk 0.405559161416;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "awesomeCertificate5002" has risk 0.23110130454;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "averageBond3166" has risk 0.852381622478;
(issuer: $issuer0, issued: $bond2) isa issues;
$bond3 isa bond has name "inventedObligation5626" has risk 0.338009576189;
(issuer: $issuer0, issued: $bond3) isa issues;
match $issuer0 isa company has name "Exxon Mobil";
insert $bond0 isa bond has name "randomCertificate6011" has risk 0.630313078901;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "inventedCertificate9676" has risk 0.456801559052;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "awesomeObligation2564" has risk 0.566271203525;
(issuer: $issuer0, issued: $bond2) isa issues;
match $issuer0 isa company has name "Kuwait Energy Co";
insert $bond0 isa bond has name "inventedObligation2665" has risk 0.069688784361;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "okObligation9110" has risk 0.324065546196;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "awesomeObligation3316" has risk 0.403938068267;
(issuer: $issuer0, issued: $bond2) isa issues;
$bond3 isa bond has name "averageObligation1613" has risk 0.387646531355;
(issuer: $issuer0, issued: $bond3) isa issues;
match $issuer0 isa company has name "Lukoil";
insert $bond0 isa bond has name "awesomeInstrument5857" has risk 0.285420690773;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "inventedCertificate5710" has risk 0.548057717196;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "awesomeInstrument7990" has risk 0.919878840518;
(issuer: $issuer0, issued: $bond2) isa issues;
$bond3 isa bond has name "awesomeInstrument9424" has risk 0.989415534774;
(issuer: $issuer0, issued: $bond3) isa issues;
match $issuer0 isa company has name "Qatargas";
insert $bond0 isa bond has name "superfluousBond1989" has risk 0.072861960913;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "amazingCertificate4002" has risk 0.838769290217;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "averageObligation1793" has risk 0.511575413095;
(issuer: $issuer0, issued: $bond2) isa issues;
$bond3 isa bond has name "randomInstrument6356" has risk 0.941918474428;
(issuer: $issuer0, issued: $bond3) isa issues;
match $issuer0 isa company has name "Shell";
insert $bond0 isa bond has name "inventedInstrument6691" has risk 0.302556665187;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "superfluousBond3779" has risk 0.609499931374;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "inventedObligation3517" has risk 0.58286162587;
(issuer: $issuer0, issued: $bond2) isa issues;
$bond3 isa bond has name "superfluousInstrument7986" has risk 0.762749222182;
(issuer: $issuer0, issued: $bond3) isa issues;
match $issuer0 isa company has name "TOTAL";
insert $bond0 isa bond has name "amazingCertificate2250" has risk 0.680940388882;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "awesomeCertificate3672" has risk 0.17751921118;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "okObligation7602" has risk 0.334652969233;
(issuer: $issuer0, issued: $bond2) isa issues;
$bond3 isa bond has name "averageCertificate2015" has risk 0.920908634166;
(issuer: $issuer0, issued: $bond3) isa issues;
match $issuer0 isa company has name "YPF";
insert $bond0 isa bond has name "awesomeInstrument7640" has risk 0.963664081262;
(issuer: $issuer0, issued: $bond0) isa issues;
$bond1 isa bond has name "averageBond6043" has risk 0.445103158804;
(issuer: $issuer0, issued: $bond1) isa issues;
$bond2 isa bond has name "awesomeInstrument5212" has risk 0.930838605527;
(issuer: $issuer0, issued: $bond2) isa issues;
$bond3 isa bond has name "okObligation6673" has risk 0.993564997822;
(issuer: $issuer0, issued: $bond3) isa issues;