java_test(
    name = "grakn-tx-operation-exception-test",
    srcs = ["GraknTxOperationExceptionTest.java"],
    test_class = "ai.grakn.exception.GraknTxOperationExceptionTest",
    deps = [
        "//grakn-graql",
        "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library",
    ],
    size = "small"
)