java_library(
    name = "commons_configuration",
    exports = [
        "//external:jar/commons_configuration/commons_configuration"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/commons_lang:commons_lang",
        "//dependencies/maven/artifacts/commons_logging:commons_logging"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


