insert


#########################################
##########Language requirement###########
#########################################

"R1a" isa inference-rule,
lhs {match $x isa applicant;
$x has degreeOrigin 'US';
$x has TOEFL >499},
rhs {match $x has languageRequirement 'satisfied'};

"R1b" isa inference-rule,
lhs {match $x isa applicant;
$x has degreeOrigin 'nonUS' or $x has TOEFL <500},
rhs {match $x has languageRequirement 'unsatisfied'};

#########################################
##################Decision###############
#########################################

"R2" isa inference-rule,
lhs {match $x isa applicant;
$x has languageRequirement 'satisfied';
$x has transcript 'available'},
rhs {match $x has decisionType 'full'};

"R7" isa inference-rule,
lhs {match $x isa applicant;
$x has languageRequirement 'satisfied';
$x has transcript 'unavailable'},
rhs {match $x has decisionType 'conditional'};

#########################################
#############Conditional evaluation######
#########################################

"R3" isa inference-rule,
lhs {match $x isa applicant;
$x has GPR >3.29;
$x has specialHonours 'honour student'},
rhs {match $x has admissionStatus 'conditional'};

"R6" isa inference-rule,
lhs {match $x isa applicant;
$x has decisionType 'conditional';
$x has specialHonours 'none';
$x has GRE <1100},
rhs {match $x has admissionStatus 'wait for transcript'};

"R8" isa inference-rule,
lhs {match $x isa applicant;
$x has decisionType 'conditional';
$x has GPR <3.3},
rhs {match $x has admissionStatus 'wait for transcript'};

"R9" isa inference-rule,
lhs {match $x isa applicant;
$x has decisionType 'conditional';
$x has specialHonours 'none';
$x has GRE >1099},
rhs {match $x has admissionStatus 'conditional'};

#########################################
#########Admission denied#########
#########################################

"R5" isa inference-rule,
lhs {match $x isa applicant;
$x has priorGraduateWork 'none'},
rhs {match $x has considerGPR 'true'};

"RD1" isa inference-rule,
lhs {match $x isa applicant;
$x has priorGraduateWork 'completed';
$x has GPR >2.99},
rhs {match $x has considerGPR 'true'};

"R11" isa inference-rule,
lhs {match $x isa applicant;
$x has languageRequirement 'unsatisfied'},
rhs {match $x has admissionStatus 'denied'};

"R12" isa inference-rule,
lhs {match $x isa applicant;
$x has considerGPR 'true';$x has GPR <2.5},
rhs {match $x has admissionStatus 'denied'};

"RD2" isa inference-rule,
lhs {match $x isa applicant;
$x has priorGraduateWork 'completed';
$x has GPR <3.0},
rhs {match $x has admissionStatus 'denied'};

"RD3" isa inference-rule,
lhs {match $x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has GRE <900},
rhs {match $x has admissionStatus 'denied'};

"RD4" isa inference-rule,
lhs {match $x isa applicant;
$x has considerGPR 'true';
$x has specialHonours 'none';
$x has GPR >2.49;
$x has GRE <900},
rhs {match $x has admissionStatus 'denied'};

#########################################
##############Provisional admission##############
#########################################

"R4" isa inference-rule,
lhs {match $x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has specialHonours 'none';
$x has GRE >899;
$x has GRE <1100;
$x has vGRE <400},
rhs {match $x has admissionStatus 'provisional with English remediation'};

"RP1" isa inference-rule,
lhs {match $x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.99;
$x has specialHonours 'none';
$x has GRE >899;
$x has GRE <1100;
$x has vGRE >399},
rhs {match $x has admissionStatus 'provisional'};

"RP2" isa inference-rule,
lhs {match $x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has GPR <3.0;
$x has specialHonours 'none';
$x has GRE >899;
$x has vGRE <400},
rhs {match $x has admissionStatus 'provisional with English remediation'};

"RP3" isa inference-rule,
lhs {match $x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.49;
$x has GPR <3.0;
$x has GRE >899;
$x has vGRE <400},
rhs {match $x has admissionStatus 'provisional'};

##########################################
##############Admission accepted##############
##########################################

"R10" isa inference-rule,
lhs {match $x isa applicant;
$x has decisionType 'full';
$x has considerGPR 'true';
$x has GPR >2.49;
$x has specialHonours 'none';
$x has GRE >1099;
$x has vGRE >399},
rhs {match $x has admissionStatus 'full'};

"RA1" isa inference-rule,
lhs {match $x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.99;
$x has specialHonours !='none'},
rhs {match $x has admissionStatus 'full'};

"RA2" isa inference-rule,
lhs {match $x isa applicant;
$x has considerGPR 'true';
$x has GPR >2.99;
$x has specialHonours 'none';
$x has GRE >1099;
$x has vGRE <400},
rhs {match $x has admissionStatus 'admit at department\\'s discretion'};