insert


###################################################
####################Ontology######################
#################################################

"Person" isa entity-type;

"parent" isa role-type;
"child" isa role-type;
"Parent" isa relation-type, has-role parent, has-role child;
Person plays-role parent, plays-role child;

"ancestor" isa role-type;
"descendant" isa role-type;
"Ancestor" isa relation-type, has-role ancestor, has-role descendant;
Person plays-role ancestor, plays-role descendant;

####################################################
##################DATA#############################
####################################################

"a" isa Person;
"aa" isa Person;
"aaa" isa Person;
"aab" isa Person;
"aaaa" isa Person;
"ab" isa Person;
"c" isa Person;
"ca" isa Person;

(parent 'a', child 'aa') isa Parent;
(parent 'a', child 'ab') isa Parent;
(parent 'aa', child 'aaa') isa Parent;
(parent 'aa', child 'aab') isa Parent;
(parent 'aaa', child 'aaaa') isa Parent;
(parent 'c', child 'ca') isa Parent;

####################################################
##################RULES#############################
####################################################

"R1" isa inference-rule,
lhs {match
(parent $x, child $z) isa Parent;
(ancestor $z, descendant $y) isa Ancestor;
select $x, $y},
rhs {match
(ancestor $x, descendant $y) isa Ancestor};

"R2" isa inference-rule,
lhs {match
(parent $x, child $y) isa Parent},
rhs {match
(ancestor $x, descendant $y) isa Ancestor};