insert


###################################################
####################Ontology######################
#################################################

"Person" isa entity-type;

"friendA" isa role-type;
"friendB" isa role-type;
"Friend" isa relation-type, has-role friendA, has-role friendB;
Person plays-role friendA, plays-role friendB;

"parent" isa role-type;
"child" isa role-type;
"Parent" isa relation-type, has-role parent, has-role child;
Person plays-role parent, plays-role child;

"person" isa role-type;
"ancestor-friend" isa role-type;
"Ancestor-friend" isa relation-type, has-role person, has-role ancestor-friend;
Person plays-role person, plays-role ancestor-friend;

####################################################
##################DATA#############################
####################################################

"a" isa Person;
"b" isa Person;
"c" isa Person;
"d" isa Person;
"g" isa Person;

(parent: 'a', child: 'b') isa Parent;
(parent: 'b', child: 'c') isa Parent;
(friendA: 'a', friendB: 'g') isa Friend;
(friendA: 'c', friendB: 'd') isa Friend;

####################################################
##################RULES#############################
####################################################

"R1" isa inference-rule,
lhs {match
($x, $y) isa Friend;},
rhs {match
($x, $y) isa Ancestor-friend;};

"R2" isa inference-rule,
lhs {match
(parent: $x, child: $z) isa Parent;
(person: $z, ancestor-friend: $y) isa Ancestor-friend; select $x, $y},
rhs {match
(person: $x, ancestor-friend: $y) isa Ancestor-friend;};
