insert

"University of Cambridge" isa university;
"Mindmaps" isa company;
"Cambridge" isa city;
"London" isa city;
"UK" isa country;
"country-81" isa country, value "Italy";
"Europe" isa continent;
"Alice" isa person, value "Alice";
"Bob" isa person, value "Bob";
"age21" isa age, value 21;
"male" isa gender, value "male";
(person-resource-owner Bob, person-resource-value age21) isa person-resource;
(person-resource-owner Bob, person-resource-value "male") isa person-resource;
"Charlie" isa person, value "Charlie";
"Denis" isa person, value "Denis";
"Frank" isa person, value "Frank";
"Gary" isa person, value "Gary";
"Karl Fischer" isa person, value "Karl Fischer";
"forum1" isa forum;

(located-subject 'University of Cambridge', subject-location Cambridge) isa resides;
(located-subject 'Mindmaps', subject-location London) isa resides;
(member-location Cambridge, container-location UK) isa sublocate;
(member-location London, container-location UK) isa sublocate;
(member-location UK, container-location Europe) isa sublocate;
(moderator Bob, moderated forum1) isa moderates;

"Ennio Morricone" isa tag, value "Ennio_Morricone";
"John Wayne" isa tag, value "John_Wayne";
"Ozzy Osbourne" isa tag, value "Ozzy_Osbourne";
"Rising Force" isa tag, value "Rising_Force";
"Terry Pratchett" isa tag, value "Terry_Pratchett";
"H. G. Wells" isa tag, value "H._G._Wells";
"Oscar Wilde" isa tag, value "Oscar_Wilde";
"Johann Wolfgang von Goethe" isa tag, value "Johann_Wolfgang_von_Goethe";
"Writer" isa category, value "Writer";
(grouped-tag 'Terry Pratchett', tag-group Writer) isa grouping;
(grouped-tag 'H. G. Wells', tag-group Writer) isa grouping;
(grouped-tag 'Johann Wolfgang von Goethe', tag-group Writer) isa grouping;

"Johann_Sebastian_Bach" isa tag, value "Johann_Sebastian_Bach";
"Ludwig_van_Beethoven" isa tag, value "Ludwig_van_Beethoven";
"Wolfgang_Amadeus_Mozart" isa tag, value "Wolfgang_Amadeus_Mozart";

"Roger_Waters" isa tag, value "Roger_Waters";

(tagged-subject Alice, subject-tag 'H. G. Wells') isa tagging;
(tagged-subject Bob, subject-tag 'Ennio Morricone') isa tagging;
(tagged-subject Bob, subject-tag 'John Wayne') isa tagging;
(tagged-subject Denis, subject-tag 'Terry Pratchett') isa tagging;
(tagged-subject Denis, subject-tag 'Oscar Wilde') isa tagging;
(tagged-subject Frank, subject-tag 'Ludwig_van_Beethoven') isa tagging;

(tagged-subject Charlie, subject-tag 'Ozzy Osbourne') isa tagging;
(tagged-subject Charlie, subject-tag 'Rising Force') isa tagging;
(tagged-subject Gary, subject-tag 'Roger_Waters') isa tagging;

(tagged-subject 'Karl Fischer', subject-tag 'Ludwig_van_Beethoven') isa tagging;
(tagged-subject 'Karl Fischer', subject-tag 'Wolfgang_Amadeus_Mozart') isa tagging;
(tagged-subject 'Karl Fischer', subject-tag 'Johann Wolfgang von Goethe') isa tagging;