insert

# motorbike
$motorbike isa category, id "motorbike", value "motorbike";
$ducatti isa product, id "Ducatti-1299", value "Ducatti 1299";
(typed-product $ducatti, product-type $motorbike) isa typing;
$ducatti-min-age isa min-age, value 18;
(product-resource-owner $ducatti, product-resource-value $ducatti-min-age) isa product-resource;
$ducatti-gender isa gender, value "male";
(product-resource-owner $ducatti, product-resource-value $ducatti-gender) isa product-resource;
(product-made $ducatti, product-origin country-81) isa made-in;

# music
$cd isa category, id "cd", value "cd";
$theWall isa product, id "the-wall", value "Pink Floyd - The Wall";
(typed-product $theWall,product-type $cd) isa typing;
$blizzard isa product, id "blizzard-of-ozz", value "Ozzy Osbourne - Blizzard of Oz";
(typed-product $blizzard, product-type $cd) isa typing;
$nocturnes isa product, id "nocturnes", value "Chopin - Nocturnes";
(typed-product $nocturnes, product-type $cd) isa typing;

# movie
$movie isa category, id "movie", value "movie";
$goodBadUgly isa product, id "The-good-the-bad-the-ugly", value "The Good, the Bad and the Ugly";
(typed-product $goodBadUgly, product-type $movie) isa typing;
$godfather isa product, id "Godfather", value "Godfather";
(typed-product $godfather, product-type $movie) isa typing;
$dumb isa product, id "Dumb-and-dumber", value "Dumb and dumber";
(typed-product $dumb, product-type $movie) isa typing;

# book
$book isa category, id "book", value "book";
$dorianGray isa product, id "dorian-gray", value "The Picture of Dorian Gray";
(typed-product $dorianGray, product-type $book) isa typing;
$colourOfMagic isa product, id "colour-of-magic", value "The Colour of Magic";
(typed-product $colourOfMagic, product-type $book) isa typing;
$warOfWorlds isa product, id "war-of-the-worlds", value "The War of the Worlds";
(typed-product $warOfWorlds, product-type $book) isa typing;
$crime isa product, id "crime-and-punishment", value "Crime and Punishment";
(typed-product $crime, product-type $book) isa typing;
$farm isa product, id "animal-farm", value "Animal Farm";
(typed-product $farm, product-type $book) isa typing;
$alice isa product, id "adventures-in-wonderland", value "Alice's Adventures in Wonderland";
(typed-product $alice, product-type $book) isa typing;
$orientExpress isa product, id "orient-express", value "Murder on the Orient Express";
(typed-product $orientExpress, product-type $book) isa typing;
$fairy isa product, id "fairy-tales", value "Fairy Tales";
(typed-product $fairy, product-type $book) isa typing;
$jeeves isa product, id "my-man-jeeves", value "My Man Jeeves";
(typed-product $jeeves, product-type $book) isa typing;
$rings isa product, id "lord-of-the-rings", value "The Lord of the Rings";
(typed-product $rings, product-type $book) isa typing;
$harry isa product, id "harry-potter", value "Harry Potter";
(typed-product $harry, product-type $book) isa typing;
$sherlock isa product, id "sherlock-holmes", value "Stories of Sherlock Holmes";
(typed-product $sherlock, product-type $book) isa typing;
$forWhom isa product, id "for-whom-the-bell-tolls", value "For Whom the Bell Tolls";
(typed-product $forWhom, product-type $book) isa typing;
$miceAndMen isa product, id "of-mice-and-men", value "Of Mice and Men";
(typed-product $miceAndMen, product-type $book) isa typing;
$trial isa product, id "trial", value "The Trial";
(typed-product $trial, product-type $book) isa typing;
$faust isa product, id "faust", value "Faust";
(typed-product $faust, product-type $book) isa typing;


# paintings
$painting isa category, id "painting", value "painting";
$lesElephants isa product, id "les-elephants", value "Salvador Dali - Les Elephants";
(typed-product $lesElephants, product-type $painting) isa typing;
$waterLillies isa product, id "water-lillies", value "Claude Monet - The Water Lillies";
(typed-product $waterLillies, product-type $painting) isa typing;
$nightWatch isa product, id "night-watch", value "Rembrandt - The Night Watch";
(typed-product $nightWatch, product-type $painting) isa typing;
$monaLisa isa product, id "mona-lisa", value "Leonardo da Vinci - Mona Lisa";
(typed-product $monaLisa, product-type $painting) isa typing;
$raphael isa product, id "madonna-of-the-pinks", value "Raphael - The Madonna of the Pinks";
(typed-product $raphael, product-type $painting) isa typing;
$bacchus isa product, id "bacchus-and-ariadne", value "Titian - Bacchus and Ariadne";
(typed-product $bacchus, product-type $painting) isa typing;
$sunflowers isa product, id "sunflowers", value "Vincent van Gogh - Sunflowers";
(typed-product $sunflowers, product-type $painting) isa typing;
$universe isa product, id "controller-of-the-universe", value "Diego Rivera - Controller of the Universe";
(typed-product $universe, product-type $painting) isa typing;
$grayTree isa product, id "gray-tree", value "Piet Mondrian - Gray Tree";
(typed-product $grayTree, product-type $painting) isa typing;
$lastJudgement isa product, id "last-judgement", value "Michelangelo - The Last Judgement";
(typed-product $lastJudgement, product-type $painting) isa typing;

# instrument
$guitar isa category, id "guitar", value "guitar";
$stratocaster isa product, id "stratocaster", value "Fender Stratocaster";
(typed-product $stratocaster, product-type $guitar) isa typing;

# bands
"category-61" isa category, id "category-61", value "Band";
"category-115" isa category, id "category-115", value "MusicalArtist";

$beatles isa tag, id "beatles", value "The Beatles";
(grouped-tag $beatles,tag-group category-61) isa grouping;
$pinkFloyd isa tag, id "pink-floyd", value "Pink Floyd";
(grouped-tag $pinkFloyd,tag-group category-61) isa grouping;
$rollingStones isa tag, id "rolling-stones", value "Rolling Stones";
(grouped-tag $rollingStones,tag-group category-61) isa grouping;
$cream isa tag, id "cream", value "Cream";
(grouped-tag $cream,tag-group category-61) isa grouping;
$yardbirds isa tag, id "yardbirds", value "The Yardbirds";
(grouped-tag $yardbirds,tag-group category-61) isa grouping;
$simonAndGarfunkel isa tag, id "simon-and-garfunkel", value "Simon and Garfunkel";
(grouped-tag $simonAndGarfunkel,tag-group category-61) isa grouping;
$blackSabbath isa tag, id "black-sabbath", value "Black Sabbath";
(grouped-tag $blackSabbath,tag-group category-61) isa grouping;
$wailers isa tag, id "bob-marley-and-the-wailers", value "Bob Marley and the Wailers";
(grouped-tag $wailers,tag-group category-61) isa grouping;

$buckethead isa tag, id "buckethead", value "Buckethead";
(grouped-tag $buckethead,tag-group category-61) isa grouping;

$primus isa tag, id "primus", value "Primus";
(grouped-tag $primus, tag-group category-61) isa grouping;

$linkinPark isa tag, id "linkin-park", value "Linkin Park";
(grouped-tag $linkinPark, tag-group category-61) isa grouping;

$limpBizkit isa tag, id "limp-bizkit", value "Limp Bizkit";
(grouped-tag $limpBizkit, tag-group category-61) isa grouping;

$jimiHendrix isa tag, id "jimi-hendrix", value "Jimi Hendrix";
(grouped-tag $jimiHendrix, tag-group category-115) isa grouping;

$slash isa tag, id "slash", value "Slash";
(grouped-tag $slash, tag-group category-115) isa grouping;

$yngwie isa tag, id "yngwie-malmsteen", value "Yngwie Malmsteen";
(grouped-tag $yngwie, tag-group category-115) isa grouping;

$steveVai isa tag, id "steve-vai", value "Steve Vai";
(grouped-tag $steveVai, tag-group category-115) isa grouping;

$cacophony isa tag, id "cacophony", value "Cacophony";
(grouped-tag $cacophony, tag-group category-61) isa grouping;

$vanHalen isa tag, id "van-halen", value "van Halen";
(grouped-tag $vanHalen, tag-group category-61) isa grouping;

$metallica isa tag, id "metallica", value "Metallica";
(grouped-tag $metallica, tag-group category-61) isa grouping;

$megadeth isa tag, id "megadeth", value "Megadeth";
(grouped-tag $megadeth, tag-group category-61) isa grouping;

$slayer isa tag, id "slayer", value "Slayer";
(grouped-tag $slayer, tag-group category-61) isa grouping;

$pantera isa tag, id "pantera", value "Pantera";
(grouped-tag $pantera, tag-group category-61) isa grouping;

$superjoint isa tag, id "superjoint", value "Superjoint Ritual";
(grouped-tag $superjoint, tag-group category-61) isa grouping;

$ironMaiden isa tag, id "iron-maiden", value "Iron Maiden";
(grouped-tag $ironMaiden, tag-group category-61) isa grouping;

$judasPriest isa tag, id "judasPriest", value "Judas Priest";
(grouped-tag $judasPriest, tag-group category-61) isa grouping;

$thinLizzy isa tag, id "thin-lizzy", value "Thin Lizzy";
(grouped-tag $thinLizzy, tag-group category-61) isa grouping;

$ledZeppelin isa tag, id "led-zeppelin", value "Led Zeppelin";
(grouped-tag $ledZeppelin, tag-group category-61) isa grouping;

$deepPurple isa tag, id "deep-purple", value "Deep Purple";
(grouped-tag $deepPurple, tag-group category-61) isa grouping;

$queen isa tag, id "queen", value "Queen";
(grouped-tag $queen, tag-group category-61) isa grouping;

tag plays-role recommended-product;

