insert

"University of Cambridge" isa university;
"Mindmaps" isa company;
"Cambridge" isa city;
"London" isa city;
"UK" isa country;
"Italy" isa country;
"Europe" isa continent;
"Alice" isa person;
"Bob" isa person;
"Bob" has age 21, has gender "male";
"Charlie" isa person;
"Denis" isa person;
"Frank" isa person;
"Gary" isa person;
"Karl Fischer" isa person;
"forum1" isa forum;

(located-subject 'University of Cambridge', subject-location Cambridge) isa resides;
(located-subject 'Mindmaps', subject-location London) isa resides;
(member-location Cambridge, container-location UK) isa sublocate;
(member-location London, container-location UK) isa sublocate;
(member-location UK, container-location Europe) isa sublocate;
(moderator Bob, moderated forum1) isa moderates;

"Ennio Morricone" isa tag;
"John Wayne" isa tag;
"Ozzy Osbourne" isa tag;
"Rising Force" isa tag;
"Terry Pratchett" isa tag;
"H. G. Wells" isa tag;
"Oscar Wilde" isa tag;
"Johann Wolfgang von Goethe" isa tag;
"Writer" isa category;
(grouped-tag 'Terry Pratchett', tag-group Writer) isa grouping;
(grouped-tag 'H. G. Wells', tag-group Writer) isa grouping;
(grouped-tag 'Johann Wolfgang von Goethe', tag-group Writer) isa grouping;

"Johann Sebastian Bach" isa tag;
"Ludwig van Beethoven" isa tag;
"Wolfgang Amadeus Mozart" isa tag;

"Roger Waters" isa tag;

(tagged-subject Alice, subject-tag 'H. G. Wells') isa tagging;
(tagged-subject Bob, subject-tag 'Ennio Morricone') isa tagging;
(tagged-subject Bob, subject-tag 'John Wayne') isa tagging;
(tagged-subject Denis, subject-tag 'Terry Pratchett') isa tagging;
(tagged-subject Denis, subject-tag 'Oscar Wilde') isa tagging;
(tagged-subject Frank, subject-tag 'Ludwig van Beethoven') isa tagging;

(tagged-subject Charlie, subject-tag 'Ozzy Osbourne') isa tagging;
(tagged-subject Charlie, subject-tag 'Rising Force') isa tagging;
(tagged-subject Gary, subject-tag 'Roger Waters') isa tagging;

(tagged-subject 'Karl Fischer', subject-tag 'Ludwig van Beethoven') isa tagging;
(tagged-subject 'Karl Fischer', subject-tag 'Wolfgang Amadeus Mozart') isa tagging;
(tagged-subject 'Karl Fischer', subject-tag 'Johann Wolfgang von Goethe') isa tagging;