insert

"R1" isa inference-rule,
lhs {select $x, $z where
($x, $y) isa resides;
(member-location $y, container-location $z) isa sublocate},
rhs {select $x, $z where ($x, $z) isa resides};

# transitivity of sublocate
"R2" isa inference-rule,
lhs {select $x, $z where
(member-location $x, container-location $y) isa sublocate;
(member-location $y, container-location $z) isa sublocate},
rhs {select $x, $z where (member-location $x, container-location $z) isa sublocate};