insert

#transitivity of resides & sublocate
"R1" isa inference-rule,
lhs {match ($x, $y) isa resides;
(member-location $y, container-location $z) isa sublocate;
select $x, $z},
rhs {match ($x, $z) isa resides};

# transitivity of sublocate
"R2" isa inference-rule,
lhs {match
(member-location $x, container-location $y) isa sublocate;
(member-location $y, container-location $z) isa sublocate;
select $x, $z},
rhs {match (member-location $x, container-location $z) isa sublocate};

"R3" isa inference-rule,
lhs {match ($x, $y) isa moderates},
rhs {match ($x, $y) isa membership};

"R4" isa inference-rule,
lhs {match $x isa person;
$t1 isa tag;$t1 value 'Ennio_Morricone';
$t2 isa tag;$t2 value 'John_Wayne';
($x, $t1) isa tagging;
($x, $t2) isa tagging;
$y isa product;
$y value 'The Good, the Bad and the Ugly';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R5" isa inference-rule,
lhs {match $x isa person;
$t isa tag;{$t value 'Ozzy_Osbourne'} or {$t value 'Rising_Force'};
($x, $t) isa tagging;
$y isa product;
{$y value 'Ozzy Osbourne - Blizzard of Oz'} or {$y value 'Fender Stratocaster'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R6" isa inference-rule,
lhs {match $x isa person;
$x has gender 'male';$x has age >=18;
$y isa product;$y has min-age >=18;
$z isa country;$z value 'Italy';
($y, $z) isa made-in;
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R7" isa inference-rule,
lhs {match $x isa person;
$t isa tag;{$t value 'Ludwig_van_Beethoven'} or {$t value 'Johann_Sebastian_Bach'} or {$t value 'Wolfgang_Amadeus_Mozart'};
($x, $t) isa tagging;
$y isa product, value 'Chopin - Nocturnes';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R8" isa inference-rule,
lhs {match $x isa person;
$t isa tag;$t value 'Roger_Waters';
($x, $t) isa tagging;
$y isa product, value 'Pink Floyd - The Wall';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

###########################################
##################Writer->Book######################
#############################################

#"R9" isa inference-rule,
#lhs {select $x, $y where
#$x isa person;$t isa tag;
#($x, $t) isa tagging;
#$tt isa category;$tt value 'Writer';
#($t, $tt) isa grouping;
#$y isa product;
#$yt isa category;$yt value 'book';
#($y, $yt) isa typing},
#rhs {select $x, $y where
#($x, $y) isa recommendation};

"R10" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'H._G._Wells';
($x, $t) isa tagging;
$y isa product, value 'The War of the Worlds';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R11" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Fyodor_Dostoyevsky';
($x, $t) isa tagging;
$y isa product, value 'Crime and Punishment';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R12" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'George_Orwell';
($x, $t) isa tagging;
$y isa product, value 'Animal Farm';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R13" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Lewis_Carroll';
($x, $t) isa tagging;
$y isa product, value 'Alice\\'s Adventures in Wonderland';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R14" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Agatha_Christie';
($x, $t) isa tagging;
$y isa product, value 'Murder on the Orient Express';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R15" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Hans_Christian_Andersen';
($x, $t) isa tagging;
$y isa product, value 'Fairy Tales';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R16" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Terry_Pratchett';
($x, $t) isa tagging;
$y isa product, value 'The Colour of Magic';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R17" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'P._G._Wodehouse';
($x, $t) isa tagging;
$y isa product, value 'My Man Jeeves';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R18" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Oscar_Wilde';
($x, $t) isa tagging;
$y isa product, value 'The Picture of Dorian Gray';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R19" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'J._R._R._Tolkien';
($x, $t) isa tagging;
$y isa product, value 'The Lord of the Rings';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R20" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'J._K._Rowling';
($x, $t) isa tagging;
$y isa product, value 'Harry Potter';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R21" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Arthur_Conan_Doyle';
($x, $t) isa tagging;
$y isa product, value 'Stories of Sherlock Holmes';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R22" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Ernest_Hemingway';
($x, $t) isa tagging;
$y isa product, value 'For Whom the Bell Tolls';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R23" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'John_Steinbeck';
($x, $t) isa tagging;
$y isa product, value 'Of Mice and Men';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R24" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Franz_Kafka';
($x, $t) isa tagging;
$y isa product, value 'Stories of The Trial';
select $x, $y },
rhs {match ($x, $y) isa recommendation};

"R25" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Johann_Wolfgang_von_Goethe';
($x, $t) isa tagging;
$y isa product, value 'Faust';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

############################################
##############MusicalArtist->Band############
#############################################

"R26" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Ozzy_Osbourne';
($x, $t) isa tagging;
$y isa tag, value 'Black Sabbath',
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R27" isa inference-rule,
lhs {match $x isa person;
$t isa tag;{$t value 'Paul_McCartney'} or {$t value 'George_Harrison'};
($x, $t) isa tagging;
$y isa tag, value 'The Beatles';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R28" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Roger_Waters';
($x, $t) isa tagging;
$y isa tag, value 'Pink Floyd';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R29" isa inference-rule,
lhs {match x isa person;
$t isa tag, value 'Keith_Richards';
($x, $t) isa tagging;
$y isa tag, value 'Rolling Stones';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R30" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Paul_Simon';
($x, $t) isa tagging;
$y isa tag, value 'Simon and Garfunkel';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R31" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Eric_Clapton';
($x, $t) isa tagging;
$y isa tag;
{$y value 'Cream'} or {$y value 'The Yardbirds'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R32" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Bob_Marley';
($x, $t) isa tagging;
$y isa tag, value 'Bob Marley and the Wailers';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

############################################
##############Album->Band##################
#############################################

"R33" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Master_of_Puppets';
($x, $t) isa tagging;
$y isa tag;
{$y value 'Megadeth'} or {$y value 'Slayer'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R34" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Far_Beyond_Driven';
($x, $t) isa tagging;
$y isa tag;
{$y value 'Pantera'} or {$y value 'Superjoint Ritual'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R35" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Hybrid_Theory';
($x, $t) isa tagging;
$y isa tag;
{$y value 'Linkin Park'} or {$y value 'Limp Bizkit'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R36" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Powerslave';
($x, $t) isa tagging;
$y isa tag;
{$y value 'Iron Maiden'} or {$y value 'Judas Priest'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R37" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Enter_the_Chicken';
($x, $t) isa tagging;
$y isa tag;
{$y value 'Buckethead'} or {$y value 'Primus'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R38" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Rising_Force';
($x, $t) isa tagging;
$y isa tag;
{$y value 'Yngwie Malmsteen'} or {$y value 'Steve Vai'} or {$y value 'Cacophony'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R39" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Led_Zeppelin_IV';
($x, $t) isa tagging;
$y isa tag;
{$y value 'Led Zeppelin'} or {$y value 'Deep Purple'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

############################################
##############Song/Single->Band##################
#############################################

"R40" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'All_Along_the_Watchtower';
($x, $t) isa tagging;
$y isa tag, value 'Jimi Hendrix';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R41" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'These_Are_the_Days_of_Our_Lives';
($x, $t) isa tagging;
$y isa tag, value 'Queen';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R42" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Come_Together';
($x, $t) isa tagging;
$y isa tag, value 'The Beatles';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R43" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Smoke_on_the_Water';
($x, $t) isa tagging;
$y isa tag, value 'Deep Purple';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R44" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Immigrant_Song';
($x, $t) isa tagging;
$y isa tag, value 'Led Zeppelin';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

######################################################
##################Artist->Painting####################
#######################################################

"R45" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Claude_Monet';
($x, $t) isa tagging;
$y isa product, value 'Claude Monet - The Water Lillies';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R46" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Rembrandt';
($x, $t) isa tagging;
$y isa product, value 'Rembrandt - The Night Watch';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R47" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Leonardo_da_Vinci';
($x, $t) isa tagging;
$y isa product, value 'Leonardo da Vinci - Mona Lisa';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R48" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Raphael';
($x, $t) isa tagging;
$y isa product, value 'Raphael - The Madonna of the Pinks';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R49" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Titian';
($x, $t) isa tagging;
$y isa product, value 'Titian - Bacchus and Ariadne';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R50" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Vincent_van_Gogh';
($x, $t) isa tagging;
$y isa product, value 'Vincent van Gogh - Sunflowers';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R51" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Diego_Rivera';
($x, $t) isa tagging;
$y isa product, value 'Diego Rivera - Controller of the Universe';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R52" isa inference-rule,
lhs {match $x isa person;
$t isa tag, value 'Piet_Mondrian';
($x, $t) isa tagging;
$y isa product, value 'Piet Mondrian - Gray Tree';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R53" isa inference-rule,
lhs {match $x isa person;$t isa tag, value 'Michelangelo';
($x, $t) isa tagging;
$y isa product, value 'Michelangelo - The Last Judgement';
select $x, $y},
rhs {match ($x, $y) isa recommendation};
