insert


"R7" isa inference-rule,
lhs {match $x isa person;
$t isa tag;{$t value 'Ludwig_van_Beethoven'} or {$t value 'Johann_Sebastian_Bach'} or {$t value 'Wolfgang_Amadeus_Mozart'};
($x, $t) isa tagging;
$y isa product, value 'Chopin - Nocturnes';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R5" isa inference-rule,
lhs {match $x isa person;
$t isa tag;{$t value 'Ozzy_Osbourne'} or {$t value 'Rising_Force'};
($x, $t) isa tagging;
$y isa product;
{$y value 'Ozzy Osbourne - Blizzard of Oz'} or {$y value 'Fender Stratocaster'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

