insert 

entity isa entity-type, is-abstract;
product ako entity;
product-resource-owner isa role-type;
product-resource-value isa role-type;
product-resource isa relation-type, has-role product-resource-value, has-role product-resource-owner;
product plays-role product-resource-owner;

# product resources
min-age isa resource-type, datatype long, plays-role product-resource-value;
max-age isa resource-type, datatype long, plays-role product-resource-value;
gender isa resource-type, datatype string, plays-role product-resource-value;

product-made isa role-type;
product-origin isa role-type;
made-in isa relation-type, has-role product-origin, has-role product-made;
product plays-role product-made;

recommended-product isa role-type;
recommended-customer isa role-type;
recommendation isa relation-type, has-role recommended-product, has-role recommended-customer;
product plays-role recommended-product;

person isa entity-type;
person plays-role recommended-customer;

place ako entity;
place plays-role product-origin;

typed-product isa role-type;
product-type isa role-type;
typing isa relation-type, has-role typed-product, has-role product-type;
category isa entity-type, plays-role product-type;
product plays-role typed-product;