insert


"R6" isa inference-rule,
lhs {match $x isa person;
$x has gender 'male';$x has age >=18;
$y isa product;$y has min-age >=18;
$z isa country;$z id 'Italy';
($y, $z) isa made-in;
select $x, $y},
rhs {match ($x, $y) isa recommendation};

