insert

###################################################
####################Ontology######################
#################################################

"entity" isa entity-type;
"Human" ako entity;

"parent" isa role-type;
"child" isa role-type;
"Parent" isa relation-type, has-role parent, has-role child;
entity plays-role parent, plays-role child;

"SG-role-A" isa role-type;
"SG-role-B" isa role-type;
"SameGen" isa relation-type, has-role SG-role-A, has-role SG-role-B;
entity plays-role SG-role-A, plays-role SG-role-B;

####################################################
##################DATA#############################
####################################################

"a" isa entity;
"b" isa entity;
"c" isa entity;
"d" isa Human;
"e" isa entity;
"f" isa entity;
"g" isa entity;
"h" isa entity;

(parent: 'a', child: 'b') isa Parent;
(parent: 'a', child: 'c') isa Parent;
(parent: 'b', child: 'd') isa Parent;
(parent: 'c', child: 'd') isa Parent;
(parent: 'e', child: 'd') isa Parent;
(parent: 'f', child: 'e') isa Parent;

#Extra data
(parent: 'g', child: 'f') isa Parent;
(parent: 'h', child: 'g') isa Parent;

####################################################
##################RULES#############################
####################################################

"R1" isa inference-rule,
lhs {match
$x isa Human},
rhs {match
($x, $x) isa SameGen;};

"R2" isa inference-rule,
lhs {match
(parent: $x, child: $u) isa Parent;
($u, $v) isa SameGen;
(parent: $y, child: $v) isa Parent;
select $x, $y},
rhs {match
($x, $y) isa SameGen;};

