insert

#recommend Cabernet Sauvignion
"Alice" isa person, value "Alice";
Alice has preferred-context "aperitif";
Alice has preferred-sparklingness "non-sparkling";
Alice has preferred-body "full";
Alice has preferred-colour "red";

#recommend White Champagne
"Bob" isa person, value "Bob";
Bob has preferred-context "aperitif";
Bob has preferred-sparklingness "sparkling";
Bob has preferred-body "full";
Bob has preferred-colour "white";

#recommend Pinot Grigio
"Charlie" isa person, value "Charlie";
Charlie has preferred-context "entree";
Charlie has preferred-entree "white meat";
Charlie has preferred-colour "rose";

#recommend Busuioaca Romaneasca
"Denis" isa person, value "Denis";
Denis has preferred-context "entree";
Denis has preferred-entree "steak";
Denis has preferred-colour "rose";

#recommend Tamaioasa Romaneasca
"Eva" isa person, value "Eva";
Eva has preferred-context "aperitif";
Eva has preferred-body "full";
Eva has preferred-sparklingness "non-sparkling";
Eva has preferred-colour "white";

#recommend Riojo Blanco
"Frank" isa person, value "Frank";
Frank has preferred-context "entree";
Frank has preferred-entree "barbecue";
Frank has preferred-body "full";
Frank has preferred-sparklingness "non-sparkling";
Frank has preferred-colour "white";

#wines
"White Champagne" isa wine, value "White Champagne";
"Cabernet Sauvignion" isa wine, value "Cabernet Sauvignion";
"Tamaioasa Romaneasca" isa wine, value "Tamaioasa Romaneasca";
"Busuioaca Romaneasca" isa wine, value "Busuioaca Romaneasca";
"Pinot Noir" isa wine, value "Pinot Noir";
"Muscat Sec" isa wine, value "Muscat Sec";
"Pinot Grigio Rose" isa wine, value "Pinot Grigio Rose";
"Corbieres 2003" isa wine, value "Corbieres 2003";
"Chateau Agnel 2000" isa wine, value "Chateau Agnel 2000";
"Rosso di Sicilia 2004" isa wine, value "Rosso di Sicilia 2004";
"Riojo Blanco CVNE 2003" isa wine, value "Riojo Blanco CVNE 2003";
"Tamaioasa Regala" isa wine, value "Tamaioasa Regala";
"Riojo Tempranillo" isa wine, value "Riojo Tempranillo";
"Chianti" isa wine, value "Chianti";
"White Riesling" isa wine, value "White Riesling";
"Burgundy" isa wine, value "Burgundy";
"Chardonnay" isa wine, value "Chardonnay";
"Bordeaux Blanc" isa wine, value "Bordeaux Blanc";
"Feteasca Regala" isa wine, value "Feteasca Regala";
"Feteasca Roz" isa wine, value "Feteasca Roz";
"Feteasca Neagra" isa wine, value "Feteasca Neagra";
"Sauvignion Blanc" isa wine, value "Sauvignion Blanc";
