insert

"context-preference-owner" isa role-type;
"context-preference-value" isa role-type;
"context-preference" isa relation-type, has-role context-preference-owner, has-role context-preference-value;

"preferred-context" isa resource-type, datatype string;

"body-preference-owner" isa role-type;
"body-preference-value" isa role-type;
"body-preference" isa relation-type, has-role body-preference-owner, has-role body-preference-value;

"preferred-body" isa resource-type, datatype string;

"dryness-preference-owner" isa role-type;
"dryness-preference-value" isa role-type;
"dryness-preference" isa relation-type, has-role dryness-preference-owner, has-role dryness-preference-value;

"preferred-dryness" isa resource-type, datatype string;

"entree-preference-owner" isa role-type;
"entree-preference-value" isa role-type;
"entree-preference" isa relation-type, has-role entree-preference-owner, has-role entree-preference-value;

"preferred-entree" isa resource-type, datatype string;

"colour-preference-owner" isa role-type;
"colour-preference-value" isa role-type;
"colour-preference" isa relation-type, has-role colour-preference-owner, has-role colour-preference-value;

"preferred-colour" isa resource-type, datatype string;

"sparklingness-preference-owner" isa role-type;
"sparklingness-preference-value" isa role-type;
"sparkingness-preference" isa relation-type, has-role sparklingness-preference-owner, has-role sparklingness-preference-value;

"preferred-sparklingness" isa resource-type, datatype string;

"recommended-wine" isa role-type;
"recommendation-owner" isa role-type;
"wine-recommendation" isa relation-type, has-role recommended-wine, has-role recommendation-owner;

"recommended-generic-wine-type" isa resource-type, datatype string;

"person" isa entity-type;
person plays-role recommendation-owner;
person has-resource preferred-context;
person has-resource preferred-body;
person has-resource preferred-dryness;
person has-resource preferred-entree;
person has-resource preferred-colour;
person has-resource preferred-sparklingness;
person has-resource recommended-generic-wine-type;

"wine" isa entity-type;
wine plays-role recommended-wine;
