insert

model sub entity
    has name
    has year
    has description
    has price
    plays model-of-car;
make sub entity
    has name
    plays make-of-car;

name sub attribute datatype string;
year sub attribute datatype string;
description sub attribute datatype string;
price sub attribute datatype double;

make-and-model sub relationship, relates make-of-car, relates model-of-car;
make-of-car sub role;
model-of-car sub role;

