java_library(
    name = "paranamer",
    exports = [
        "//external:jar/com/thoughtworks/paranamer/paranamer"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


