java_library(
    name = "minlog",
    exports = [
        "//external:jar/com/esotericsoftware/minlog/minlog"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


