java_library(
    name = "uncommons-maths",
    exports = [
        "//external:jar/org/uncommons/maths/uncommons-maths"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


