java_test(
    name = "aggregate-query-impl-test",
    test_class = "ai.grakn.graql.internal.query.AggregateQueryImplTest",
    srcs = ["AggregateQueryImplTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)

java_test(
    name = "concept-map-test",
    test_class = "ai.grakn.graql.internal.query.ConceptMapTest",
    srcs = ["ConceptMapTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/org/mockito:mockito-core",
        "//grakn-graql"],
    size = "small"
)

java_test(
    name = "delete-query-impl-test",
    test_class = "ai.grakn.graql.internal.query.DeleteQueryImplTest",
    srcs = ["DeleteQueryImplTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//grakn-graql"],
    size = "small"
)

java_test(
    name = "insert-query-impl-test",
    test_class = "ai.grakn.graql.internal.query.InsertQueryImplTest",
    srcs = ["InsertQueryImplTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/org/mockito:mockito-core",
        "//grakn-graql"],
    size = "small"
)