java_library(
    name = "thrift_server",
    exports = [
        "//external:jar/com/thinkaurelius/thrift/thrift_server"
    ],
    runtime_deps = [
        "//dependencies/maven/com/lmax:disruptor",
        "//dependencies/maven/org/apache/thrift:libthrift",
        "//dependencies/maven/org/slf4j:slf4j_api"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


