java_library(
    name = "guice-servlet",
    exports = [
        "//external:jar/com/google/inject/extensions/guice-servlet"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


