
insert
  person sub entity
    plays-role person-with-address
    plays-role person-with-phone;

  address sub entity
    plays-role address-of-person
    plays-role address-with-street
    has-resource city;

  street-address sub entity
    plays-role street-of-address
    has-resource number
    has-resource street;

  phone-number sub entity
    plays-role phone-of-person
    has-resource location
    has-resource code;

  code sub resource datatype long;
  location sub resource datatype string;
  number sub resource datatype long;
  street sub resource datatype string;
  city sub resource datatype string;

  person-with-address sub role;
  address-of-person sub role;
  address-with-street sub role;
  street-of-address sub role;
  person-with-phone sub role;
  phone-of-person sub role;

  address-has-street sub relation has-role street-of-address has-role address-with-street;
  has-address sub relation has-role address-of-person has-role person-with-address;
  has-phone sub relation has-role phone-of-person has-role person-with-phone;


