insert
$person isa person;

$address isa address
  has city <address.city>;

$street isa street-address
   has street <address.streetAddress.street>
   has number <address.streetAddress.number>;

(address-with-street: $address, street-of-address: $street) isa address-has-street;

(person-with-address: $person, address-of-person: $address) isa has-address;

for ( <phoneNumber> ) do {
  $phone isa phone-number
    has location <location>
    has code <code>;

  (person-with-phone: $person, phone-of-person: $phone) isa has-phone;

}