insert 

# Primary Scheduled task entity.
scheduled-task sub entity;

# scheduled-task resources
status sub resource, datatype string;
status-change-time sub resource, datatype long;
status-change-by sub resource, datatype string;
task-class-name sub resource, datatype string;
created-by sub resource, datatype string;
executing-hostname sub resource, datatype string;
run-at sub resource, datatype long;
recurring sub resource, datatype boolean;
recur-interval sub resource, datatype long;
task-failure sub resource, datatype string;
stack-trace sub resource, datatype string;
task-exception sub resource, datatype string;
task-checkpoint sub resource, datatype string;
task-configuration sub resource, datatype string;

scheduled-task has-resource status,
               has-resource status-change-time,
               has-resource status-change-by,
               has-resource task-class-name,
               has-resource created-by,
               has-resource executing-hostname,
               has-resource run-at,
               has-resource recurring,
               has-resource recur-interval,
               has-resource stack-trace,
               has-resource task-exception,
               has-resource task-checkpoint
               has-resource task-configuration;

# Keep track of all keyspaces in system.
keyspace sub entity;
keyspace-name sub resource, datatype string;
keyspace has-resource keyspace-name;
keyspace has-key keyspace-name;

# Users
user sub entity;
user-name sub resource, datatype string;
user-password sub resource, datatype string;
user-first-name sub resource, datatype string;
user-last-name sub resource, datatype string;
user-email sub resource, datatype string;
user-is-admin sub resource, datatype boolean;
user has-key user-name;

user has-resource user-password,
	 has-resource user-first-name,
	 has-resource user-last-name,
	 has-resource user-email,
	 has-resource user-is-admin;
