insert 

# Primary Scheduled task entity.
scheduled-task isa entity;

# scheduled-task resources
status isa resource, datatype string;
status-change-time isa resource, datatype long;
status-change-by isa resource, datatype string;
task-class-name isa resource, datatype string;
created-by isa resource, datatype string;
executing-hostname isa resource, datatype string;
run-at isa resource, datatype long;
recurring isa resource, datatype boolean;
recur-interval isa resource, datatype long;
task-failure isa resource, datatype string;
stack-trace isa resource, datatype string;
task-exception isa resource, datatype string;
task-checkpoint isa resource, datatype string;
task-configuration isa resource, datatype string;

scheduled-task has-resource status,
               has-resource status-change-time,
               has-resource status-change-by,
               has-resource task-class-name,
               has-resource created-by,
               has-resource executing-hostname,
               has-resource run-at,
               has-resource recurring,
               has-resource recur-interval,
               has-resource stack-trace,
               has-resource task-exception,
               has-resource task-checkpoint
               has-resource task-configuration;

# Keep track of all keyspaces in system.
keyspace isa entity;
keyspace-name isa resource, datatype string;
keyspace has-resource keyspace-name;
keyspace has-key keyspace-name;

# Users
user isa entity;
user-name isa resource, datatype string;
user-password isa resource, datatype string;
user-first-name isa resource, datatype string;
user-last-name isa resource, datatype string;
user-email isa resource, datatype string;
user-is-admin isa resource, datatype boolean;
user has-key user-name;

user has-resource user-password,
	 has-resource user-first-name,
	 has-resource user-last-name,
	 has-resource user-email,
	 has-resource user-is-admin;
