insert 

# Primary Scheduled task entity.
scheduled-task isa entity-type;

# scheduled-task resources
status isa resource-type, datatype string;
status-change-time isa resource-type, datatype long;
status-change-by isa resource-type, datatype string;
task-class-name isa resource-type, datatype string;
created-by isa resource-type, datatype string;
engine-id isa resource-type, datatype string;
run-at isa resource-type, datatype long;
recurring isa resource-type, datatype boolean;
recur-interval isa resource-type, datatype long;
task-failure isa resource-type, datatype string;
stack-trace isa resource-type, datatype string;
task-exception isa resource-type, datatype string;
task-checkpoint isa resource-type, datatype string;
task-configuration isa resource-type, datatype string;

scheduled-task has-resource status,
               has-resource status-change-time,
               has-resource status-change-by,
               has-resource task-class-name,
               has-resource created-by,
               has-resource engine-id,
               has-resource run-at,
               has-resource recurring,
               has-resource recur-interval,
               has-resource stack-trace,
               has-resource task-exception,
               has-resource task-checkpoint
               has-resource task-configuration;

# Keep track of all keyspaces in system.
keyspace isa entity-type;
keyspace-name isa resource-type, datatype string;
keyspace has-resource keyspace-name;
keyspace key keyspace-name;

# Users
user isa entity-type;
user-name isa resource-type, datatype string;
user-password isa resource-type, datatype string;
user-first-name isa resource-type, datatype string;
user-last-name isa resource-type, datatype string;
user-email isa resource-type, datatype string;
user-is-admin isa resource-type, datatype boolean;
user key user-name;

user has-resource user-password,
	 has-resource user-first-name,
	 has-resource user-last-name,
	 has-resource user-email,
	 has-resource user-is-admin;
