java_library(
    name = "mockito-core",
    exports = [
        "//external:jar/org/mockito/mockito-core"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/net/bytebuddy:byte-buddy",
        "//dependencies/maven/artifacts/net/bytebuddy:byte-buddy-agent",
        "//dependencies/maven/artifacts/org/objenesis:objenesis"
    ],
    visibility = [
        "//visibility:public"
    ]
)


