java_library(
    name = "bcprov-jdk15on",
    exports = [
        "//external:jar/org/bouncycastle/bcprov-jdk15on"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


