java_library(
    name = "reflectasm-jar-shaded",
    exports = [
        "//external:jar/com/esotericsoftware/reflectasm/reflectasm-jar-shaded"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


