java_library(
    name = "reflectasm_jar_shaded",
    exports = [
        "//external:jar/com/esotericsoftware/reflectasm/reflectasm_jar_shaded"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


