java_library(
    name = "json-simple",
    exports = [
        "//external:jar/com/googlecode/json-simple/json-simple"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


