java_library(
    name = "mockito_core",
    exports = [
        "//external:jar/org/mockito/mockito_core"
    ],
    runtime_deps = [
        "//dependencies/maven/net/bytebuddy:byte_buddy",
        "//dependencies/maven/net/bytebuddy:byte_buddy_agent",
        "//dependencies/maven/org/objenesis:objenesis"
    ],
    visibility = [
        "//visibility:public"
    ]
)


