java_library(
    name = "instrumentation_api",
    exports = [
        "//external:jar/com/google/instrumentation/instrumentation_api"
    ],
    runtime_deps = [
        "//dependencies/maven/com/google/code/findbugs:jsr305",
        "//dependencies/maven/com/google/guava:guava"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


