filegroup(
    name = "cassandra-embedded",
    srcs = ["cassandra-embedded.yaml"],
    visibility = ["//visibility:public"]
)

filegroup(
    name = "logback-test",
    srcs = ["logback.xml"],
    visibility = ["//visibility:public"]
)

filegroup(
    name = "grakn-small-tx-cache",
    srcs = ["grakn-small-tx-cache.properties"],
    visibility = ["//visibility:public"]
)
