java_library(
    name = "org-abego-treelayout-core",
    exports = [
        "//external:jar/org/abego/treelayout/org-abego-treelayout-core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


