java_library(
    name = "elasticsearch_rest_client",
    exports = [
        "//external:jar/org/elasticsearch/client/elasticsearch_rest_client"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/commons_codec:commons_codec",
        "//dependencies/maven/artifacts/commons_logging:commons_logging",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpasyncclient",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpclient",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpcore",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpcore_nio"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


