java_library(
    name = "elasticsearch-rest-client",
    exports = [
        "//external:jar/org/elasticsearch/client/elasticsearch-rest-client"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/commons-codec:commons-codec",
        "//dependencies/maven/artifacts/commons-logging:commons-logging",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpasyncclient",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpclient",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpcore",
        "//dependencies/maven/artifacts/org/apache/httpcomponents:httpcore-nio"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


