const grpc = require("grpc");
const services = require("./autogenerated/SessionServiceProto");
const TxService = require("./TxService");

function Session(uri, keyspace, credentials) {
    this.keyspace = keyspace;
    this.credentials = credentials;
    this.stub = new services.SessionServiceClient(uri, grpc.credentials.createInsecure());
}

Session.prototype.createRemoteTx = async function create(txType) {
    const txService = new TxService(this.stub.transaction());
    await txService.openTx(this.keyspace, txType, this.credentials);
    return txService;
}

Session.prototype.close = function close() {
    grpc.closeClient(this.stub);
}

module.exports = Session;