define

name sub attribute,
  value string;

company-id sub attribute,
  value long;

company sub entity,
  key company-id,
  has name;

company-has-name sub rule,
when {
  $c2 isa company;
}, then {
  $c2 has name $n2; $n2 "the-company";
};
