java_library(
    name = "leveldbjni-all",
    exports = [
        "//external:jar/org/fusesource/leveldbjni/leveldbjni-all"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


