java_library(
    name = "guice",
    exports = [
        "//external:jar/com/google/inject/guice"
    ],
    runtime_deps = [
        "//dependencies/maven/aopalliance:aopalliance",
        "//dependencies/maven/javax/inject:javax_inject"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


