exports_files([
    "checkstyle-file-header-agpl.txt",
    "checkstyle-file-header-apache.txt",
    "checkstyle-suppressions.xml",
    "checkstyle.xml",
])

filegroup(
    name = "licenses",
    srcs = [
        "checkstyle-file-header-agpl.txt",
        "checkstyle-file-header-apache.txt",
    ],
    visibility = ["//visibility:public"]
)