java_library(
    name = "htrace-core",
    exports = [
        "//external:jar/org/apache/htrace/htrace-core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


