java_library(
    name = "htrace_core",
    exports = [
        "//external:jar/org/apache/htrace/htrace_core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


