java_library(
    name = "zt-exec",
    exports = [
        "//external:jar/org/zeroturnaround/zt-exec"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/slf4j:slf4j-api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


