# Queries:
# match (friend:$x, friend:$y) isa knows-trans;
# match (friend:$x, friend:$y) isa friends-sharing-interest-trans;
# match (trigger:$t, response:$r) isa friends-activity-propagation-trans;

define

#schema extension

knows sub knows-trans;

knows-trans sub relationship
	relates friend;

friends-sharing-interest sub friends-sharing-interest-trans
	relates friend;

friends-sharing-interest-trans sub relationship
	relates friend;

predecessor sub role;
successor sub role;

message-succession sub relationship
	relates predecessor
    relates successor;

trigger sub role;
response sub role;

friends-activity-propagation sub friends-activity-propagation-trans
	relates trigger
	relates response;

friends-activity-propagation-trans sub relationship
	relates trigger
	relates response;

