# The entities defined in the ldbc-snb benchmark
insert

# geographic entities
"place" sub entity
	key place-id
	has name
	has url
	plays region;

"city" sub place
	plays part;

"country" sub place
	plays whole
	plays part;

"continent" sub place
	plays whole;

# message board entities
"forum" sub entity
	key forum-id
	has title
	has creation-date
	plays container
	plays group
	plays moderated
	plays tagged;

"message" sub entity
	is-abstract
	key message-id
	has browser-used
	has creation-date
	has location-ip
	has content
	has length
	plays product
	plays tagged
	plays located
	plays like
	plays original;

"comment" sub message
	plays reply;

"post" sub message
	has language
	has image-file
	plays contained;

"tag" sub entity
	key tag-id
	has name
	has url
	plays interest
	plays topic
	plays instance;

"tag-class" sub entity
	key tag-class-id
	has name
	has url
	plays class
	plays subclass
	plays superclass;

# institutional entities
"organisation" sub entity
	key organisation-id
	has name
	has url
	plays located;

"company" sub organisation
	plays employer;

"university" sub organisation
	plays school;

# individuals
"person" sub entity
	key person-id
	has first-name
	has last-name
	has gender
	has birth-day
	has email
	has speaks
	has browser-used
	has location-ip
	has creation-date
	plays creator
	plays interested
	plays member
	plays moderator
	plays located
	plays friend
	plays admirer
	plays employee
	plays student;