# The resources as defined in the ldbc-snb benchmark
insert

# this is a proxy for the ID datatype that is unique per entity type
"ID" sub resource is-abstract datatype long;

# proxies for the character datatypes
"String" sub resource is-abstract regex /^(.{1,40})$/ datatype string;
"Long String" sub resource is-abstract regex /^(.{1,256})$/ datatype string;
"Text" sub resource is-abstract regex /^(.{1,2000})$/ datatype string;

# proxies for the date datatypes
# currently using epoch time not string + regex
# yyyy-mm-dd
#""Date"" sub resource is-abstract regex /^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/ datatype string;
"Date" sub resource is-abstract datatype date;
# yyyy-mm-ddTHH:MM:ss.sss+0000
#""Date"Time" sub resource is-abstract regex /^(19|20)\d\d-(0[1-9]|1[012])-([012]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)\+[0]{4}$/ datatype string;
"DateTime" sub resource is-abstract datatype date;

# proxy for all integers
"Integer" sub resource is-abstract datatype long;
"integer-32" sub Integer;
"integer-64" sub Integer;

# resources
"forum-id" sub ID;
"title" sub "Long String";
"creation-date" sub DateTime;
"message-id" sub ID;
"browser-used" sub String;
"location-ip" sub String;
"content" sub Text;
"length" sub integer-32;
"organisation-id" sub ID;
"name" sub "Long String";
"person-id" sub ID;
"first-name" sub String;
"last-name" sub String;
"gender" sub String;
"birth-day" sub "Date";
"email" sub "Long String";
"speaks" sub String;
"place-id" sub ID;
"language" sub String;
"image-file" sub String;
"tag-id" sub ID;
"tag-class-id" sub ID;
"url" sub Text;
"join-date" sub "Date";
"class-year" sub integer-32;
"work-from" sub integer-32;
