match
	$person isa person, has person-id @long(<"Person.id">);
	$comment isa comment, has message-id @long(<"Comment.id">);
insert
	(admirer: $person, like: $comment) isa likes
	has creation-date @date(<"creationDate">,"yyyy-MM-dd'T'HH:mm:ss.SSSZ");
