java_library(
    name = "checker-qual",
    exports = [
        "//external:jar/org/checkerframework/checker-qual"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


