java_library(
    name = "ant",
    exports = [
        "//external:jar/org/apache/ant/ant"
    ],
    runtime_deps = [
        ":ant-launcher"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "ant-launcher",
    exports = [
        "//external:jar/org/apache/ant/ant-launcher"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


