java_library(
    name = "ant",
    exports = [
        "//external:jar/org/apache/ant/ant"
    ],
    runtime_deps = [
        ":ant_launcher"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "ant_launcher",
    exports = [
        "//external:jar/org/apache/ant/ant_launcher"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


