java_library(
    name = "commons_logging",
    exports = [
        "//external:jar/commons_logging/commons_logging"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


