java_library(
    name = "dom4j",
    exports = [
        "//external:jar/dom4j/dom4j"
    ],
    runtime_deps = [
        "//dependencies/maven/xml_apis:xml_apis"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


