java_library(
    name = "j2objc-annotations",
    exports = [
        "//external:jar/com/google/j2objc/j2objc-annotations"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


