java_library(
    name = "jettison",
    exports = [
        "//external:jar/org/codehaus/jettison/jettison"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


