java_library(
    name = "scala_parser_combinators_2_11",
    exports = [
        "//external:jar/org/scala_lang/modules/scala_parser_combinators_2_11"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/scala_lang:scala_library"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "scala_xml_2_11",
    exports = [
        "//external:jar/org/scala_lang/modules/scala_xml_2_11"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/scala_lang:scala_library"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


