java_test(
    name = "match-base-test",
    test_class = "grakn.core.graql.internal.query.match.MatchBaseTest",
    srcs = ["MatchBaseTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//server"],
    size = "small"
)

java_test(
    name = "match-kb-test",
    test_class = "grakn.core.graql.internal.query.match.MatchKBTest",
    srcs = ["MatchKBTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/org/mockito:mockito-core",
        "//server"],
    size = "small"
)