java_library(
    name = "jetty",
    exports = [
        "//external:jar/org/mortbay/jetty/jetty"
    ],
    runtime_deps = [
        ":jetty-util"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "jetty-util",
    exports = [
        "//external:jar/org/mortbay/jetty/jetty-util"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


