java_library(
    name = "jetty-util",
    exports = [
        "//external:jar/org/mortbay/jetty/jetty-util"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


