java_test(
    name = "pattern-impl-test",
    test_class = "grakn.core.graql.query.pattern.PatternImplTest",
    srcs = ["PatternImplTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//server"],
    size = "small"
)