java_library(
    name = "java_xmlbuilder",
    exports = [
        "//external:jar/com/jamesmurty/utils/java_xmlbuilder"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/net/iharder:base64"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


