java_library(
    name = "mesos_jar_shaded_protobuf",
    exports = [
        "//external:jar/org/apache/mesos/mesos_jar_shaded_protobuf"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


