java_library(
    name = "junit",
    exports = [
        "//external:jar/junit/junit"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/hamcrest:hamcrest_core"
    ],
    visibility = [
        "//visibility:public"
    ]
)


