java_library(
    name = "scala-xml-2-11",
    exports = [
        "//external:jar/org/scala-lang/modules/scala-xml-2-11"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


