java_library(
    name = "scala-parser-combinators-2-11",
    exports = [
        "//external:jar/org/scala-lang/modules/scala-parser-combinators-2-11"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/scala-lang:scala-library"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "scala-xml-2-11",
    exports = [
        "//external:jar/org/scala-lang/modules/scala-xml-2-11"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


