java_library(
    name = "leveldbjni_all",
    exports = [
        "//external:jar/org/fusesource/leveldbjni/leveldbjni_all"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


