java_library(
    name = "javaruntype",
    exports = [
        "//external:jar/org/javaruntype/javaruntype"
    ],
    runtime_deps = [
        "//dependencies/maven/org/antlr:antlr_runtime"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


