java_library(
    name = "kryo",
    exports = [
        "//external:jar/com/esotericsoftware/kryo/kryo"
    ],
    runtime_deps = [
        "//dependencies/maven/com/esotericsoftware/minlog:minlog",
        "//dependencies/maven/com/esotericsoftware/reflectasm:reflectasm_jar_shaded",
        "//dependencies/maven/org/objenesis:objenesis"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


