java_library(
    name = "concurrent_trees",
    exports = [
        "//external:jar/com/googlecode/concurrent_trees/concurrent_trees"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


