package(default_visibility = ["//test/behaviour/resolution/framework/test:__subpackages__"])

filegroup(
    name = "complex_recursion",
    srcs = [
        "schema.gql",
        "data.gql",
    ],
)