define

currency sub attribute,
    value string;

country-name sub attribute,
    value string;

city-name sub attribute,
    value string;

transaction sub entity,
    has currency,
    plays locates_located;

locates sub relation,
    relates locates_location,
    relates locates_located;

location-hierarchy sub relation,
    relates location-hierarchy_superior,
    relates location-hierarchy_subordinate;

location sub entity,
    abstract,
    plays location-hierarchy_superior,
    plays location-hierarchy_subordinate;

country sub location,
    key country-name,
    has currency,
    plays locates_location;

city sub location,
    key city-name,
    plays locates_location;

locates-is-transitive sub rule,
when {
    $city isa city;
    $country isa country;
    $lh(location-hierarchy_superior: $country, location-hierarchy_subordinate: $city) isa location-hierarchy;
    $l1(locates_located: $transaction, locates_location: $city) isa locates;
}, then {
    (locates_located: $transaction, locates_location: $country) isa locates;
};

transaction-currency-is-that-of-the-country sub rule,
when {
    $transaction isa transaction;
    $locates(locates_located: $transaction, locates_location: $country) isa locates;
    $country isa country, has currency $currency;
}, then {
    $transaction has currency $currency;
};
