java_library(
    name = "json_simple",
    exports = [
        "//external:jar/com/googlecode/json_simple/json_simple"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


