java_library(
    name = "concurrentlinkedhashmap_lru",
    exports = [
        "//external:jar/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap_lru"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


