java_library(
    name = "commons-pool",
    exports = [
        "//external:jar/commons-pool/commons-pool"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


