java_library(
    name = "caffeine",
    exports = [
        "//external:jar/com/github/ben_manes/caffeine/caffeine"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


