java_library(
    name = "animal-sniffer-annotations",
    exports = [
        "//external:jar/org/codehaus/mojo/animal-sniffer-annotations"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


