define

pet sub entity
    has name
    has owner
    has sex
    has birth
    has death
    is-abstract;

cat sub pet;
dog sub pet;
snake sub pet;
hamster sub pet;
bird sub pet;

name sub attribute datatype string;
owner sub attribute datatype string;
sex sub attribute datatype string;
birth sub attribute datatype date;
death sub attribute datatype date;