java_test(
     name = "grakn-config-test",
     test_class = "grakn.core.common.config.test.ConfigTest",
     srcs = ["ConfigTest.java"],
     deps = ["//common/config:config", '//common/exception:exception'],
     resources = ["//server:conf/grakn.properties"],
     size = "small"
 )