java_library(
    name = "jcl-over-slf4j",
    exports = [
        "//external:jar/org/slf4j/jcl-over-slf4j"
    ],
    runtime_deps = [
        ":slf4j-api"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "jul-to-slf4j",
    exports = [
        "//external:jar/org/slf4j/jul-to-slf4j"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "log4j-over-slf4j",
    exports = [
        "//external:jar/org/slf4j/log4j-over-slf4j"
    ],
    runtime_deps = [
        ":slf4j-api"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "slf4j-api",
    exports = [
        "//external:jar/org/slf4j/slf4j-api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


