define
name sub attribute,
    value string;
is-liable sub attribute,
    value boolean;
company-id sub attribute,
    value long;
company sub entity,
    owns company-id @key,
    owns name,
    owns is-liable;
rule company-has-name:
when {
    $c1 isa company;
} then {
    $c1 has name $n1; $n1 "the-company";
};
rule company-is-liable:
when {
    $c2 isa company, has name $n2; $n2 "the-company";
} then {
    $c2 has is-liable $l2; $l2 true;
};