insert person sub entity, has identifier; identifier sub resource, datatype string;
insert spouse1 sub role; spouse2 sub role; person plays spouse1; person plays spouse2;
insert marriage sub relation, relates spouse1, relates spouse2, has date; date sub resource datatype string;
commit;

insert isa person, has identifier "Andrew Smith";
insert isa person, has identifier "Catherine Shaw";
insert isa person, has identifier "Paula Carter";
insert isa person, has identifier "Scott Jones";
commit;
match $s1 has identifier "Andrew Smith"; $s2 has identifier "Catherine Shaw"; insert (spouse1: $s1, spouse2: $s2) isa marriage has date "01-01-1980";
commit;
