java_library(
    name = "javax-servlet",
    exports = [
        "//external:jar/org/eclipse/jetty/orbit/javax-servlet"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


