java_library(
    name = "bigtable_hbase_1_0",
    exports = [
        "//external:jar/com/google/cloud/bigtable/bigtable_hbase_1_0"
    ],
    runtime_deps = [
        "//dependencies/maven/com/google/appengine:appengine_api_1_0_sdk",
        "//dependencies/maven/com/google/code/findbugs:jsr305",
        "//dependencies/maven/com/google/code/gson:gson",
        "//dependencies/maven/com/google/guava:guava",
        "//dependencies/maven/com/google/protobuf:protobuf_java",
        "//dependencies/maven/commons_cli:commons_cli",
        "//dependencies/maven/commons_codec:commons_codec",
        "//dependencies/maven/commons_collections:commons_collections",
        "//dependencies/maven/commons_lang:commons_lang",
        "//dependencies/maven/commons_logging:commons_logging",
        "//dependencies/maven/org/apache/hbase:hbase_annotations",
        "//dependencies/maven/org/apache/hbase:hbase_client",
        "//dependencies/maven/org/apache/hbase:hbase_common",
        "//dependencies/maven/org/apache/hbase:hbase_protocol",
        "//dependencies/maven/org/apache/httpcomponents:httpcore",
        "//dependencies/maven/org/slf4j:slf4j_api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


