java_library(
    name = "logback-classic",
    exports = [
        "//external:jar/ch/qos/logback/logback-classic"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/slf4j:slf4j-api",
        ":logback-core"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "logback-core",
    exports = [
        "//external:jar/ch/qos/logback/logback-core"
    ],
    visibility = [
        "//visibility:public"
    ]
)


