java_library(
    name = "logback_classic",
    exports = [
        "//external:jar/ch/qos/logback/logback_classic"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/slf4j:slf4j_api",
        ":logback_core"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "logback_core",
    exports = [
        "//external:jar/ch/qos/logback/logback_core"
    ],
    visibility = [
        "//visibility:public"
    ]
)


