insert

pokemon sub entity
    plays-role pokemon-with-type
    has-resource pokedex-no
    has-resource description
    has-resource height
    has-resource weight;

type-id sub resource datatype string;
pokedex-no sub resource datatype string;
description sub resource datatype string;
number sub resource datatype long;
height sub resource datatype long;
weight sub resource datatype long;

pokemon-type sub entity
    has-resource description
    has-resource type-id
    plays-role type-of-pokemon;

has-type sub relation
    has-role pokemon-with-type
    has-role type-of-pokemon;
pokemon-with-type sub role;
type-of-pokemon sub role;
