java_library(
    name = "org_apache_servicemix_bundles_commons_csv",
    exports = [
        "//external:jar/org/apache/servicemix/bundles/org_apache_servicemix_bundles_commons_csv"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


