java_library(
    name = "api_asn1_api",
    exports = [
        "//external:jar/org/apache/directory/api/api_asn1_api"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)



java_library(
    name = "api_util",
    exports = [
        "//external:jar/org/apache/directory/api/api_util"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


