from enum import Enum
import service.Session.autogenerated.Session_pb2 as SessionMessages

from Session import Session

class Grakn(object):

    def __init__(self):
        pass

    # stateless method
    def session(self, uri: str, keyspace: str):
        return Session(uri, keyspace)

    # TODO keyspace delete/retrieve


    class TxType(Enum):
        READ = SessionMessages.Transaction.Type.READ
        WRITE = SessionMessages.Transaction.Type.WRITE
        BATCH = SessionMessages.Transaction.Type.BATCH
        

    class DataType(Enum):
        STRING = SessionMessages.AttributeType.DATA_TYPE.STRING
        BOOLEAN = SessionMessages.AttributeType.DATA_TYPE.BOOLEAN
        INTEGER = SessionMessages.AttributeType.DATA_TYPE.INTEGER
        LONG = SessionMessages.AttributeType.DATA_TYPE.LONG
        FLOAT = SessionMessages.AttributeType.DATA_TYPE.FLOAT
        DOUBLE = SessionMessages.AttributeType.DATA_TYPE.DOUBLE
        DATE= SessionMessages.AttributeType.DATA_TYPE.DATE
