java_library(
    name = "pf4j",
    exports = [
        "//external:jar/ro/fortsoft/pf4j/pf4j"
    ],
    runtime_deps = [
        "//dependencies/maven/com/github/zafarkhaja:java_semver",
        "//dependencies/maven/org/slf4j:slf4j_api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


