java_library(
    name = "archaius_core",
    exports = [
        "//external:jar/com/netflix/archaius/archaius_core"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/commons_configuration:commons_configuration",
        "//dependencies/maven/artifacts/org/slf4j:slf4j_api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


