java_library(
    name = "archaius-core",
    exports = [
        "//external:jar/com/netflix/archaius/archaius-core"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/commons-configuration:commons-configuration",
        "//dependencies/maven/artifacts/org/slf4j:slf4j-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


