java_test(
    name = "chu-liu-edmonds-test",
    test_class = "grakn.core.graql.internal.gremlin.spanningtree.ChuLiuEdmondsTest",
    srcs = ["ChuLiuEdmondsTest.java"],
    deps = ["//server", "//dependencies/maven/artifacts/com/google/guava:guava"],
    size = "small"
)

java_test(
    name = "fibonacci-heap-test",
    test_class = "grakn.core.graql.internal.gremlin.spanningtree.datastructure.FibonacciHeapTest",
    srcs = ["datastructure/FibonacciHeapTest.java"],
    deps = ["//server", "//dependencies/maven/artifacts/com/google/guava:guava"],
    size = "small"
)

java_test(
    name = "fibonacci-queue-test",
    test_class = "grakn.core.graql.internal.gremlin.spanningtree.datastructure.FibonacciQueueTest",
    srcs = ["datastructure/FibonacciQueueTest.java"],
    deps = ["//server", "//dependencies/maven/artifacts/com/google/guava:guava"],
    size = "small"
)
