java_library(
    name = "protobuf-java",
    exports = [
        "//external:jar/com/google/protobuf/protobuf-java"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


