java_library(
    name = "commons-compress",
    exports = [
        "//external:jar/org/apache/commons/commons-compress"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "commons-crypto",
    exports = [
        "//external:jar/org/apache/commons/commons-crypto"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "commons-lang3",
    exports = [
        "//external:jar/org/apache/commons/commons-lang3"
    ],
    visibility = [
        "//visibility:public"
    ]
)



java_library(
    name = "commons-math3",
    exports = [
        "//external:jar/org/apache/commons/commons-math3"
    ],
    visibility = [
        "//visibility:public"
    ]
)


