java_library(
    name = "commons_compress",
    exports = [
        "//external:jar/org/apache/commons/commons_compress"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/tukaani:xz"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "commons_lang3",
    exports = [
        "//external:jar/org/apache/commons/commons_lang3"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "commons_math3",
    exports = [
        "//external:jar/org/apache/commons/commons_math3"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "commons_text",
    exports = [
        "//external:jar/org/apache/commons/commons_text"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


