define

someRole sub role;
anotherRole sub role;

newEntity sub entity;

someEntity sub entity,
    plays someRole,
    plays anotherRole,
    has resource;

anotherEntity sub entity,
    plays someRole,
    plays anotherRole,
    has resource;

someRelation sub relation,
    relates someRole,
    relates anotherRole,
    has resource;

#Resources
resource sub attribute, datatype string;

insert

#Data

$x isa someEntity, has resource 'resource';
$y isa anotherEntity;