define

###################################################
####################Schema######################
#################################################

start-vertex sub entity,
has index;
vertex sub entity,
has index;

coordinate sub role;
arc sub relation, relates coordinate;
vertex plays coordinate;
start-vertex plays coordinate;

path sub relation, relates coordinate;
vertex plays coordinate;
start-vertex plays coordinate;

index sub attribute, datatype string;

####################################################
##################RULES#############################
####################################################

rule-1
when {
($x, $y) isa arc;},
then {
($x, $y) isa path;};

rule-2
when {
($x, $z) isa path;
($z, $y) isa path;},
then {
($x, $y) isa path;};
