define

someEntity sub entity,
    plays resource-owner,
    has res-string,
    has res-double,
    has res-long,
    has res-boolean;


#Resources
res-string sub attribute, datatype string,
    plays resource-value;
res-double sub attribute, datatype double,
    plays resource-value;
res-long sub attribute, datatype long,
    plays resource-value;
res-boolean sub attribute, datatype boolean,
    plays resource-value;

resource-owner sub role;
resource-value sub role;

resource-relation sub relation,
    relates resource-owner,
    relates resource-value;

#Rules

rule-1 sub rule,
when {
    $x isa someEntity;
    $y 'value' isa res-string;
},
then {
    (resource-owner: $x, resource-value: $y) isa resource-relation;
};

rule-2 sub rule,
when {
    $x isa someEntity;
    $y 3.14 isa res-double;
},
then {
    (resource-owner: $x, resource-value: $y) isa resource-relation;
};

rule-3 sub rule,
when {
    $x isa someEntity;
    $y 123 isa res-long;
},
then {
    (resource-owner: $x, resource-value: $y) isa resource-relation;
};

rule-4 sub rule,
when {
    $x isa someEntity;
    $y 'true' isa res-boolean;
},
then {
    (resource-owner: $x, resource-value: $y) isa resource-relation;
};


insert
$x isa someEntity,
    has res-long 2000,
    has res-boolean true,
    has res-double 3.14,
    has res-string 'value';