define

#Roles

someRole sub role;
otherRole sub role;

#Entities

baseEntity sub entity,
    plays someRole,
    plays otherRole,
    has resource,
    has anotherResource;

someEntity sub baseEntity;
someOtherEntity sub baseEntity;
yetAnotherEntity sub baseEntity;

#Relations

someRelation sub relation,
    relates someRole,
    relates otherRole;

someRelationTrans sub relation,
    relates someRole,
    relates otherRole;

anotherRelation sub relation,
    relates someRole,
    relates otherRole;

yetAnotherRelation sub relation,
    relates someRole,
    relates otherRole;

derivedRelation sub relation,
    relates someRole,
    relates otherRole,
    has resource,
    has anotherResource;

anotherDerivedRelation sub relation,
    relates someRole,
    relates otherRole;


resource sub attribute, datatype string;
anotherResource sub attribute, datatype string;
yetAnotherResource sub attribute, datatype string;
derivedResource sub attribute, datatype string;
anotherDerivedResource sub attribute, datatype string;

simple-relation-rule
when {
(someRole: $x, otherRole: $y) isa someRelation;},
then {
(someRole: $x, otherRole: $y) isa derivedRelation;};

some-relation-equiv-rule
when {
(someRole: $x, otherRole: $y) isa someRelation;},
then {
(someRole: $x, otherRole: $y) isa someRelationTrans;};

transitivity-rule
when {
(someRole: $x, otherRole: $y) isa someRelationTrans;
(someRole: $y, otherRole: $z) isa someRelationTrans;},
then {
(someRole: $x, otherRole: $z) isa someRelationTrans;};

another-relation-rule
when {
(someRole: $x, otherRole: $y) isa anotherRelation;},
then {
(someRole: $x, otherRole: $y) isa anotherDerivedRelation;};

simple-resource-rule
when{
$x has resource $r;
},
then {
$x has derivedResource $r;
};

another-resource-rule
when{
$x has anotherResource $r;
},
then {
$x has anotherDerivedResource $r;
};

insert

$x isa someEntity, has resource 'someValue';
$z isa someEntity;
$c isa baseEntity;
$y isa someOtherEntity;
(someRole: $x, otherRole: $y) isa someRelation;
(someRole: $x, otherRole: $z) isa someRelation;
(someRole: $x, otherRole: $c) isa someRelation;
(someRole: $x, otherRole: $y) isa anotherRelation;
(someRole: $x, otherRole: $z) isa anotherRelation;
(someRole: $x, otherRole: $y) isa yetAnotherRelation;

$ar "someValue" isa anotherResource;
$ar2 "anotherValue" isa anotherResource;


