define

#Roles

# Role hierarchy
#
#                             role
#             /                 |                   \
#         role1               role2                 role3
#          |                     |                    |
#       subRole1             subRole2             subRole3
#

role1 sub role;
subRole1 sub role1;

role2 sub role;
subRole2 sub role2;

role3 sub role;
subRole3 sub role3;

#Entities
#simple vertical hierarchy

entity1 sub entity,
    plays role1;

anotherEntity1 sub entity,
    plays subRole1;

subEntity1 sub entity1,
    plays subRole1;

entity2 sub entity,
    plays role2;

anotherEntity2 sub entity,
    plays subRole2;

subEntity2 sub entity2,
    plays subRole2;

entity3 sub entity,
    plays role3;

anotherEntity3 sub entity,
    plays subRole3;

subEntity3 sub entity3,
    plays subRole3;

genericEntity sub entity,
    plays role1,
    plays role2,
    plays role3;

binary sub relation,
    relates role1,
    relates role2,
    relates subRole1,
    relates subRole2;

ternary sub relation,
    relates role1,
    relates role2,
    relates role3,
    relates subRole1,
    relates subRole2,
    relates subRole3;