java_library(
    name = "xbean_asm5_shaded",
    exports = [
        "//external:jar/org/apache/xbean/xbean_asm5_shaded"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


