java_library(
    name = "xbean-asm5-shaded",
    exports = [
        "//external:jar/org/apache/xbean/xbean-asm5-shaded"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


