java_library(
    name = "xercesImpl",
    exports = [
        "//external:jar/xerces/xercesImpl"
    ],
    runtime_deps = [
        "//dependencies/maven/xml_apis:xml_apis"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


