define

someRole sub role;
anotherRole sub role;

newEntity sub entity;

baseEntity sub entity,
    plays someRole,
    plays anotherRole,
    has resource-string,
    has resource-long,
    has resource-double,
    has resource-boolean,
    has resource-date;

someEntity sub baseEntity;
anotherEntity sub baseEntity;

someRelation sub relation,
    relates someRole,
    relates anotherRole,
    has resource-string;

#Resources
resource-string sub attribute, value string;
resource-long sub attribute, value long;
resource-double sub attribute, value double;
resource-boolean sub attribute, value boolean;
resource-date sub attribute, value date;

insert

#Data

$x isa someEntity, has resource-string 'resource';
$y isa anotherEntity;