java_library(
    name = "javax_servlet_api",
    exports = [
        "//external:jar/javax/servlet/javax_servlet_api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


