java_library(
    name = "javax-servlet-api",
    exports = [
        "//external:jar/javax/servlet/javax-servlet-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


