java_library(
    name = "hystrix-core",
    exports = [
        "//external:jar/com/netflix/hystrix/hystrix-core"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/netflix/archaius:archaius-core",
        "//dependencies/maven/artifacts/io/reactivex:rxjava",
        "//dependencies/maven/artifacts/org/hdrhistogram:HdrHistogram",
        "//dependencies/maven/artifacts/org/slf4j:slf4j-api"
    ],
    visibility = [
        "//visibility:public"
    ]
)


