java_library(
    name = "protocol",
    exports = [
        "//external:jar/grakn/core/protocol"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/com/google/protobuf:protobuf-java",
        "//dependencies/maven/artifacts/io/grpc:grpc-core",
        "//dependencies/maven/artifacts/io/grpc:grpc-protobuf",
        "//dependencies/maven/artifacts/io/grpc:grpc-stub"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


