java_library(
    name = "commons_httpclient",
    exports = [
        "//external:jar/commons_httpclient/commons_httpclient"
    ],
    runtime_deps = [
        "//dependencies/maven/commons_codec:commons_codec"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


