java_library(
    name = "annotations",
    exports = [
        "//external:jar/com/google/android/annotations"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


