java_library(
    name = "api-asn1-api",
    exports = [
        "//external:jar/org/apache/directory/api/api-asn1-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "api-util",
    exports = [
        "//external:jar/org/apache/directory/api/api-util"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


