java_library(
    name = "appengine-api-1-0-sdk",
    exports = [
        "//external:jar/com/google/appengine/appengine-api-1-0-sdk"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


