java_library(
    name = "appengine_api_1_0_sdk",
    exports = [
        "//external:jar/com/google/appengine/appengine_api_1_0_sdk"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


