java_library(
    name = "ognl",
    exports = [
        "//external:jar/ognl/ognl"
    ],
    runtime_deps = [
        "//dependencies/maven/javassist:javassist"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


