define
attribute-1 sub attribute, value string;
attribute-2 sub attribute, value string;
attribute-3 sub attribute, value string;
attribute-4 sub attribute, value string;
attribute-5 sub attribute, value string;

entity-1 sub entity, key attribute-1, has attribute-2, plays role-7, plays role-6;
entity-12 sub entity-1;

entity-2 sub entity, has attribute-1, has attribute-3, has attribute-5, plays role-1, plays role-2;
entity-6 sub entity-2, key attribute-2, plays role-5, plays role-6, plays role-1;
entity-5 sub entity-2, key attribute-2, plays role-6, plays role-1, plays role-5, abstract;
entity-11 sub entity-5, plays role-1, plays role-5, plays role-2;

relationship-1 sub relation, abstract;
relationship-2 sub relation, relates role-1, relates role-7;
relationship-4 sub relation, relates role-5, relates role-6;
relationship-5 sub relation, relates role-5, relates role-6;
relationship-8 sub relation, relates role-2, relates role-2;


rule-1 sub rule , when {
    (role-5: $var-7, role-6: $var-6) isa relationship-5;},
then {
    (role-5: $var-7, role-6: $var-6) isa relationship-4;};

rule-2 sub rule , when {
    (role-1: $var-7, role-7: $var-6) isa relationship-2;
    not {
    (role-5: $var-7, role-6: $var-8) isa relationship-5;};},
then {
    (role-5: $var-7, role-6: $var-6) isa relationship-4;};

extra-rule sub rule , when {
    (role-5: $var-7, role-6: $var-6) isa relationship-4;
    (role-5: $var-8, role-6: $var-7) isa relationship-4;},
then {
    (role-5: $var-8, role-6: $var-6) isa relationship-4;};

rule-6 sub rule , when {
    (role-2: $var-6, role-2: $var-7) isa relationship-8;},
then {
    (role-5: $var-7, role-6: $var-6) isa relationship-5;};




insert $var-12 isa entity-12, has attribute-1 "value-7", has attribute-2 "value-6";

match $var-15 isa entity-1,  has attribute-2 "value-6";
insert $var-16 isa entity-6, has attribute-1 "value-11", has attribute-2 "value-10", has attribute-5 "value-4";(role-1: $var-16, role-7: $var-15)  isa relationship-2;

match $var-725 isa entity-1,  has attribute-2 "value-6";$var-723 isa entity-6,  has attribute-2 "value-10";
insert $var-724 isa entity-11, has attribute-1 "value-473", has attribute-2 "value-472", has attribute-5 "value-4";(role-1: $var-724, role-7: $var-725)  isa relationship-2;(role-5: $var-724, role-6: $var-723)  isa relationship-5;

match $var-728 isa entity-1,  has attribute-2 "value-6";$var-726 isa entity-6,  has attribute-2 "value-10";
insert $var-727 isa entity-11, has attribute-1 "value-475", has attribute-2 "value-474", has attribute-5 "value-4";(role-1: $var-727, role-7: $var-728)  isa relationship-2;(role-5: $var-727, role-6: $var-726)  isa relationship-5;

match $var-731 isa entity-1,  has attribute-2 "value-6";$var-729 isa entity-6,  has attribute-2 "value-10";
insert $var-730 isa entity-11, has attribute-1 "value-477", has attribute-2 "value-476", has attribute-5 "value-4";(role-1: $var-730, role-7: $var-731)  isa relationship-2;(role-5: $var-730, role-6: $var-729)  isa relationship-5;

match $var-1540 isa entity-5,  has attribute-2 "value-476";$var-1539 isa entity-5,  has attribute-2 "value-474";
insert $var-1541 ( role-2: $var-1540 ,  role-2: $var-1539 ) isa relationship-8 ;