define
resource sub attribute, value string;

entity-1 sub entity, has resource, plays role-2, plays role-4;
entity-2 sub entity, has resource, plays role-1, plays role-3, plays role-4;
entity-3 sub entity, has resource, plays role-1, plays role-3, plays role-4, plays symmetric-role;

relation-2 sub relation, relates role-1, relates role-2;
relation-4 sub relation, relates role-3, relates role-4;
relation-5 sub relation, relates role-3, relates role-4;
symmetric-relation sub relation, relates symmetric-role;


rule-1 sub rule , when {
    (role-3: $x, role-4: $y) isa relation-5;},
then {
    (role-3: $x, role-4: $y) isa relation-4;};

rule-2 sub rule , when {
    (role-1: $x, role-2: $y) isa relation-2;
    not {
    (role-3: $x, role-4: $z) isa relation-5;};},
then {
    (role-3: $x, role-4: $y) isa relation-4;};

trans-rule sub rule , when {
    (role-3: $y, role-4: $z) isa relation-4;
    (role-3: $x, role-4: $y) isa relation-4;},
then {
    (role-3: $x, role-4: $z) isa relation-4;};

rule-3 sub rule , when {
    (symmetric-role: $x, symmetric-role: $y) isa symmetric-relation;},
then {
    (role-3: $y, role-4: $x) isa relation-5;};


insert
$d isa entity-1, has resource "d";
$e isa entity-2, has resource "e";

$a isa entity-3, has resource "a";
$b isa entity-3, has resource "b";
$c isa entity-3, has resource "c";

(role-1: $e, role-2: $d)  isa relation-2;
(role-1: $a, role-2: $d) isa relation-2;
(role-1: $b, role-2: $d)  isa relation-2;
(role-1: $c, role-2: $d) isa relation-2;

(role-3: $a, role-4: $e)  isa relation-5;
(role-3: $b, role-4: $e)  isa relation-5;
(role-3: $c, role-4: $e) isa relation-5;

(symmetric-role: $c, symmetric-role: $b ) isa symmetric-relation;