define

session sub entity,
    plays parent-session;
fault sub entity,
    plays relevant-fault,
    plays identified-fault,
    plays diagnosed-fault;
question sub entity,
    has response,
    plays identifying-question,
    plays question-logged,
    plays question-not-answered;

response sub attribute, value string;

reported-fault sub relation,
    relates relevant-fault,
    relates parent-session;

logged-question sub relation,
    relates question-logged,
    relates parent-session;

unanswered-question sub relation,
    relates question-not-answered,
    relates parent-session;

fault-identification sub relation,
    relates identifying-question,
    relates identified-fault;

diagnosis sub relation,
    relates diagnosed-fault,
    relates parent-session;


no-response-means-unanswered-question sub rule,
when {
    $ques isa question;
    (question-logged: $ques, parent-session: $ts) isa logged-question;
    not {
        $ques has response $r;
    };
}, then {
    (question-not-answered: $ques, parent-session: $ts) isa unanswered-question;
};

determined-fault sub rule,
when {
    (relevant-fault: $flt, parent-session: $ts) isa reported-fault;
    not {
        (question-not-answered: $ques, parent-session: $ts) isa unanswered-question;
        ($flt, $ques) isa fault-identification;
    };
}, then {
    (diagnosed-fault: $flt, parent-session: $ts) isa diagnosis;
};

insert
$sesh isa session;
$q1 isa question;
$q2 isa question;
$f1 isa fault;
$f2 isa fault;
(relevant-fault: $f1, parent-session: $sesh) isa reported-fault;
(relevant-fault: $f2, parent-session: $sesh) isa reported-fault;

(question-logged: $q1, parent-session: $sesh) isa logged-question;
(question-logged: $q2, parent-session: $sesh) isa logged-question;

(identified-fault: $f1, identifying-question: $q1) isa fault-identification;
(identified-fault: $f2, identifying-question: $q2) isa fault-identification;