define

#Roles

role1 sub role;
role2 sub role;


#Entities

entity1 sub entity,
    plays role1,
    plays role2;

entity2 sub entity,
    plays role1,
    plays role2;


#Relations

relation1 sub relation,
    relates role1,
    relates role2;

relation2 sub relation,
    relates role1,
    relates role2;

#Rules

rule-1 sub rule,
    when {
    	$x isa entity1;
    },
    then {
    	(role1:$x, role2:$x) isa relation1;
    };

rule-2 sub rule,
    when {
        (role1: $c, role2: $m) isa relation2;
        (role1: $m, role2: $op) isa relation1;
    },
    then {
        (role1: $c, role2: $op) isa relation1;
    };

insert

#Data

$a isa entity2;
$b isa entity1;
$c isa entity2;
(role1:$a, role2:$b) isa relation2;
(role1:$b, role2:$c) isa relation1;