define

#Entities

baseEntity sub entity;
subEntity sub baseEntity;
anotherBaseEntity sub entity;

#Rules

rule-1 sub rule,
    when {
    	$x isa anotherBaseEntity;
    },
    then {
    	$x isa subEntity;
    };

insert

#Data

$x isa anotherBaseEntity;