define

#Roles

role1 sub role;
role2 sub role;

#Entities

entity1 sub entity,
    plays role1,
    plays role2;

#Relations

reflexiveRelation sub relation,
    relates role1,
    relates role2;

uniquePairRelation sub relation,
    relates role1,
    relates role2;

#Rules

rule-1 sub rule,
    when {
    	$x isa entity1;
    	$y isa entity1;
    },
    then {
    	(role1:$x, role2:$y) isa reflexiveRelation;
    };

rule-2 sub rule,
    when {
    	$x isa entity1;
    	$y isa entity1;
    	$x != $y;
    },
    then {
    	(role1:$x, role2:$y) isa uniquePairRelation;
    };

insert

#Data

$x isa entity1;
$y isa entity1;
$z isa entity1;

