define

#Roles

friend sub role;

#Entities

person sub entity,
    plays friend;

#Relations

knows-trans sub relation,
    relates friend;

knows sub knows-trans,
    relates friend;

#Rules

rule0 sub rule,
    when {
        (friend:$x, friend:$y);
        (friend:$y, friend:$z);
    },
    then {
        (friend:$x, friend:$z) isa knows-trans;
    };

insert

#Data

$p1 isa person;
$p2 isa person;
$p3 isa person;
$p4 isa person;

(friend:$p1, friend:$p2) isa knows;
(friend:$p2, friend:$p3) isa knows;
(friend:$p3, friend:$p4) isa knows;

