define

#Roles

role1 sub role;
role2 sub role;

#Entities

entity1 sub entity,
    plays role1,
    plays role2;

#Relations

relation1 sub relation,
    relates role1,
    relates role2;

relation2 sub relation,
    relates role1,
    relates role2;

relation3 sub relation,
    relates role1,
    relates role2;

#Rules

rule-1 sub rule,
    when {
    	(role1:$x, role2:$y) isa relation1;
    	(role1:$y, role2:$z) isa relation1;
    },
    then {
    	(role1:$x, role2:$z) isa relation1;
    };

rule-2 sub rule,
    when {
    	(role1:$x, role2:$y) isa relation1;
    },
    then {
    	(role1:$x, role2:$y) isa relation2;
    };

rule-3 sub rule,
    when {
    	(role1:$x, role2:$y) isa relation3;
    },
    then {
    	(role1:$x, role2:$y) isa relation2;
    };

rule-4 sub rule,
    when {
    	(role1:$x, role2:$y) isa relation2;
    },
    then {
    	(role1:$x, role2:$y) isa relation3;
    };

insert

#Data

$x isa entity1;
$y isa entity1;

(role1:$x, role2:$x) isa relation1;
(role1:$x, role2:$y) isa relation1;