define

#Entities

baseEntity sub entity,
    plays baseRole;

baseRelation sub relation,
    relates baseRole;
subRelation sub baseRelation,
    relates baseRole;
subSubRelation sub subRelation,
    relates baseRole;

derivedRelation sub relation,
    relates baseRole;
directDerivedRelation sub derivedRelation,
    relates baseRole;

#Rules

relationRule sub rule,
    when {
        ($x) isa subRelation;
    },
    then {
        ($x) isa derivedRelation;
    };

directRelationRule sub rule,
    when {
        ($x) isa! subRelation;
    },
    then {
        ($x) isa directDerivedRelation;
    };

insert

#Data

$x isa baseEntity;
$y isa baseEntity;
$z isa baseEntity;

(baseRole: $x) isa baseRelation;
(baseRole: $y) isa subRelation;
(baseRole: $z) isa subSubRelation;