define

#Entities

baseEntity sub entity;
derivedEntity sub entity;

#Rules

rule-1 sub rule,
    when {
    	$x isa baseEntity;
    },
    then {
    	$x isa derivedEntity;
    };

insert

#Data

$x isa baseEntity;