insert

# Entities

person sub entity
	plays parent
	plays child
	plays spouse1
	plays spouse2

	has identifier
	has firstname
	has surname
	has middlename
	has picture
	has age
	has birth-date
	has death-date
	has gender;

# Resources

identifier sub resource datatype string;
firstname sub resource datatype string;
surname sub resource datatype string;
middlename sub resource datatype string;
picture sub resource datatype string;
age sub resource datatype long;
birth-date sub resource datatype string;
death-date sub resource datatype string;
gender sub resource datatype string;

# Roles and Relations

marriage sub relation
	relates spouse1
	relates spouse2
	has picture;

spouse1 sub role;
spouse2 sub role;

parentship sub relation
	relates parent
	relates child;

parent sub role;
child sub role;

## INFERRED

person 
	plays wife
	plays husband
	plays granddaughter
	plays grandson
	plays father-in-law
	plays mother-in-law
	plays daughter-in-law
	plays son-in-law
	plays son
	plays daughter
	plays sibling1
	plays sibling2
	plays grandparent
	plays grandchild
	plays cousin1
	plays cousin2
	plays child-in-law
	plays parent-in-law
	plays mother
	plays father
	plays grandmother
	plays grandfather;

marriage sub relation
	relates husband
	relates wife;

husband sub role;
wife sub role;

parentship sub relation
	relates mother
	relates father
	relates son
	relates daughter;

mother sub parent;
father sub parent;
son sub child;
daughter sub child;

siblings sub relation
	relates sibling1
	relates sibling2;

sibling sub role is-abstract;
sibling1 sub sibling;
sibling2 sub sibling;

grandparentship sub relation
	relates grandparent
	relates grandfather
	relates grandmother
	relates grandchild
	relates granddaughter
	relates grandson;

grandparent sub role;
grandfather sub grandparent;
grandmother sub grandparent;
grandchild sub role;
grandson sub grandchild;
granddaughter sub grandchild;

cousins sub relation
	relates cousin1
	relates cousin2;

cousin sub role is-abstract;
cousin1 sub cousin;
cousin2 sub cousin;

in-laws sub relation
	relates child-in-law
	relates son-in-law
	relates daughter-in-law
	relates parent-in-law
	relates mother-in-law
	relates father-in-law;

child-in-law sub role;
son-in-law sub child-in-law;
daughter-in-law sub child-in-law;
parent-in-law sub role;
mother-in-law sub parent-in-law;
father-in-law sub parent-in-law;



# DATA

$57472 isa person has firstname "Mary" has identifier "Mary Guthrie" has surname "Guthrie" has gender "female";
$86144 has surname "Dudley" isa person has identifier "Susan Josephine Dudley" has gender "female" has firstname "Susan" has middlename "Josephine";
$118912 has age 74 isa person has firstname "Margaret" has surname "Newman" has gender "female" has identifier "Margaret Newman";
$188544 isa person has firstname "Barbara" has birth-date "1833-04-08" has age 52 has identifier "Barbara Ellen Niesz" has gender "female" has middlename "Ellen" has surname "Niesz";
$32904 has birth-date "1774-08-02" has identifier "John Newman" isa person has surname "Newman" has death-date "1862-12-26" has firstname "John" has gender "male" has age 88;
$41096 isa person has surname "Newman" has gender "male" has firstname "Peter" has identifier "Peter Newman";
$41095248 has age 90 has middlename "S." isa person has gender "male" has firstname "Samuel" has identifier "Samuel S. Bard" has surname "Bard";
$41168976 isa person has identifier "Elizabeth Shafner" has gender "female" has surname "Shafner" has firstname "Elizabeth";
$41185360 has birth-date "1840-01-19" has firstname "Sarah" isa person has age 78 has middlename "Ann" has gender "female" has surname "Niesz" has identifier "Sarah Ann Niesz";
$41209936 has firstname "Rosalie" isa person has gender "female" has identifier "Rosalie";
$41291856 has surname "Roush" isa person has firstname "Delilah" has gender "female" has identifier "Delilah Roush";
$41324624 has age 76 has identifier "William Sanford Titus" isa person has firstname "William" has surname "Titus" has gender "male" has birth-date "1818-03-23" has death-date "1905-01-01" has middlename "Sanford";
$41349200 has firstname "Byron" isa person has surname "Culbertson" has identifier "Byron Culbertson" has gender "male";
$41361488 has death-date "1872-03-06" has age 74 has identifier "John Niesz" isa person has birth-date "1798-01-02" has firstname "John" has gender "male" has surname "Niesz";
$28840 has identifier "Barbara E. Newman" has middlename "E." isa person has firstname "Barbara" has surname "Newman" has gender "female";
$49320 has firstname "Ron" isa person has identifier "Ron Newman" has surname "Newman" has gender "male";
$8248 isa person has firstname "Barbara" has gender "female" has surname "Shafner" has identifier "Barbara Shafner";
$81976 isa person has identifier "Elizabeth" has gender "female" has firstname "Elizabeth";
$118840 isa person has identifier "Barbara Herchelroth" has firstname "Barbara" has age 93 has birth-date "1773-06-06" has gender "female" has death-date "1868-03-15" has surname "Herchelroth";
$41013448 has identifier "Eliza Newman" isa person has surname "Newman" has gender "female" has firstname "Eliza";
$184376 has firstname "Jacob" has death-date "before 1798-10" isa person has identifier "Jacob Young" has gender "male" has surname "Young";
$41025736 has identifier "Stephen Newman" isa person has firstname "Stephen" has surname "Newman" has gender "male";
$344120 isa person has identifier "Frederick Shafner" has gender "male" has firstname "Frederick" has surname "Shafner";
$458808 has identifier "Elizabeth Weaver" isa person has surname "Weaver" has gender "female" has firstname "Elizabeth";
$49344 isa person has surname "Newman" has identifier "Robert Newman" has gender "male" has birth-date "circa 1803" has firstname "Robert";
$53440 isa person has identifier "Ann Eliza Niesz" has firstname "Ann" has gender "female" has surname "Niesz" has middlename "Eliza";
$188608 has surname "Billings" isa person has firstname "Maggie" has identifier "Maggie Billings" has gender "female";
$319680 has age 74 has birth-date "1829-09-12" isa person has death-date "1904-03-26" has gender "male" has firstname "George" has surname "Niesz" has middlename "W." has identifier "George W. Niesz";
$356544 isa person has firstname "John" has gender "male" has identifier "John Shafner" has surname "Shafner" has age 22;
$4168 isa person has surname "Newman" has firstname "Lucinda" has gender "female" has identifier "Lucinda Newman";
$20552 has firstname "Sarah" has identifier "Sarah Hane" isa person has surname "Hane" has gender "female";
$40980536 has firstname "Catherine" isa person has surname "Newman" has gender "female" has identifier "Catherine Newman";
$40968224 has identifier "Amanda Newman" isa person has surname "Newman" has gender "female" has firstname "Amanda";
$40988704 isa person has identifier "John L. Newman" has surname "Newman" has firstname "John" has gender "male" has middlename "L.";
$41025568 has birth-date "1811-03-06" isa person has surname "Newman" has gender "male" has death-date "1898-09-10" has identifier "Henry Newman" has age 87 has firstname "Henry";
$119000 has death-date "1891-12-08" isa person has gender "female" has surname "Niesz" has age 71 has identifier "Elizabeth Niesz" has birth-date "1820-08-27" has firstname "Elizabeth";
$143576 isa person has firstname "Mary" has death-date "1946-05-10" has surname "Titus" has age 98 has gender "female" has middlename "Melissa" has identifier "Mary Melissa Titus" has birth-date "1847-08-12";
$237784 isa person has firstname "Mary" has age 83 has gender "female" has surname "Niesz" has birth-date "1824-05-29" has identifier "Mary Niesz";
$307416 has identifier "George Niesz" isa person has gender "male" has firstname "George" has surname "Niesz";
$8288 has identifier "Hermione Newman" isa person has firstname "Hermione" has surname "Newman" has gender "female";
$114784 isa person has firstname "Barbara" has identifier "Barbara Newman" has surname "Newman" has gender "female";
$233568 has birth-date "1798-04-09" has identifier "Mary Young" isa person has firstname "Mary" has death-date "1868-10-28" has gender "female" has surname "Young" has age 70;
$250080 isa person has surname "Newman" has identifier "Lawrence Newman" has gender "male" has age 82 has birth-date "1804 circa" has firstname "Lawrence";
$266336 isa person has identifier "Josephine" has gender "female" has firstname "Josephine";
$282848 isa person has birth-date "1842-11-16" has identifier "Benjamin Franklin Niesz" has gender "male" has firstname "Benjamin" has middlename "Franklin" has surname "Niesz";
$389216 has birth-date "1822-05-28" has age 91 has identifier "William Niesz" isa person has firstname "William" has gender "male" has death-date "1913" has surname "Niesz";
$40964120 has firstname "Jacob" isa person has birth-date "1825-11-18" has death-date "1891-08" has gender "male" has age 65 has middlename "J." has identifier "Jacob J. Niesz" has surname "Niesz";
$41119768 isa person has surname "Newman" has identifier "Harry Newman" has gender "male" has firstname "Harry";
$41127960 has identifier "Haman Newman" has firstname "Haman" isa person has surname "Newman" has gender "male";
$41316376 has age 76 has birth-date "1824-10-20" has firstname "Catherine" isa person has identifier "Catherine Niesz" has death-date "1900" has gender "female" has surname "Niesz" has picture "http:\/\/www.christliebfamilyassociation.com\/images\/CatherineNieszChristlieb.jpg";
$41320472 isa person has identifier "Andrew Shafner" has firstname "Andrew" has gender "male" has surname "Shafner";
$41340952 isa person has firstname "Barbara" has surname "Titus" has age 82 has identifier "Barbara Ellen Titus" has gender "female" has middlename "Ellen" has birth-date "1850-09-18" has death-date "1933-01-10";
$41406488 isa person has surname "Titus" has firstname "Timothy" has gender "male" has identifier "Timothy Titus";
$82040 has firstname "Catherine" isa person has identifier "Catherine Young" has surname "Young" has gender "female" has birth-date "before 1798";
$102520 isa person has firstname "Elam" has surname "Smith" has gender "male" has identifier "Elam G. Smith" has middlename "G.";
$135288 has identifier "John Meyers" isa person has surname "Meyers" has firstname "John" has gender "male";
$196728 has middlename "Kossuth" isa person has firstname "John" has birth-date "1836-11-22" has gender "male" has identifier "John Kossuth Niesz" has surname "Niesz";
$249976 has death-date "1942-04-08" isa person has age 96 has surname "Titus" has identifier "Amanda Ann Titus" has middlename "Ann" has gender "female" has birth-date "1845-09-10" has firstname "Amanda";
$295032 isa person has surname "McGaughey" has gender "female" has identifier "Isabelle McGaughey" has firstname "Isabelle";
$299128 has birth-date "1857-12-24" has death-date "1957-03-28" isa person has firstname "William" has surname "Titus" has age 99 has gender "male" has identifier "William Sanford Titus Jr." has middlename "Sanford";
$122888272 (parent: $41361488, child: $188544) isa parentship;
$122896464 (parent: $41361488, child: $319680) isa parentship;
$122908752 (parent: $119000, child: $249976) isa parentship;
$40984672 (parent: $233568, child: $188544) isa parentship;
$40964192 (parent: $344120, child: $8248) isa parentship;
$40964320 (parent: $41361488, child: $40964120) isa parentship;
$40980704 (parent: $233568, child: $389216) isa parentship;
$40984800 (parent: $41324624, child: $41340952) isa parentship;
$40992864 (parent: $184376, child: $82040) isa parentship;
$40997088 (parent: $41361488, child: $389216) isa parentship;
$41001056 (parent: $118840, child: $49344) isa parentship;
$41009248 isa parentship (parent: $295032, child: $4168);
$41013344 (parent: $81976, child: $118912) isa parentship;
$41017440 (parent: $41025568, child: $40988704) isa parentship;
$41021664 (parent: $41406488, child: $41324624) isa parentship;
$163848272 (parent: $250080, child: $41025736) isa parentship;
$163856464 (parent: $49344, child: $118912) isa parentship;
$163901520 (parent: $184376, child: $233568) isa parentship;
$163905616 (parent: $41025568, child: $40980536) isa parentship;
$163909712 (parent: $81976, child: $114784) isa parentship;
$163922000 (parent: $20552, child: $40980536) isa parentship;
$163926096 isa parentship (parent: $344120, child: $356544);
$8344 (parent: $233568, child: $119000) isa parentship;
$20632 (parent: $458808, child: $41361488) isa parentship;
$81924216 (parent: $119000, child: $143576) isa parentship;
$81944696 (parent: $233568, child: $319680) isa parentship;
$81948792 isa parentship (parent: $41361488, child: $119000);
$40980696 (parent: $233568, child: $237784) isa parentship;
$40984792 (parent: $233568, child: $41316376) isa parentship;
$40988888 (parent: $41361488, child: $41316376) isa parentship;
$40992984 (parent: $41324624, child: $299128) isa parentship;
$40997080 (parent: $41324624, child: $249976) isa parentship;
$41029848 (parent: $233568, child: $40964120) isa parentship;
$32944 (parent: $233568, child: $41185360) isa parentship;
$53424 (parent: $41361488, child: $196728) isa parentship;
$61616 (parent: $233568, child: $196728) isa parentship;
$40964288 isa parentship (parent: $233568, child: $282848);
$40968384 (parent: $344120, child: $41168976) isa parentship;
$40972480 (parent: $20552, child: $28840) isa parentship;
$40976576 (parent: $295032, child: $41025736) isa parentship;
$41005248 (parent: $118840, child: $250080) isa parentship;
$41025728 (parent: $82040, child: $41320472) isa parentship;
$4280 isa parentship (parent: $41361488, child: $237784);
$16568 (parent: $41324624, child: $143576) isa parentship;
$32952 (parent: $119000, child: $41340952) isa parentship;
$81932320 (parent: $41361488, child: $282848) isa parentship;
$81944608 (parent: $32904, child: $49344) isa parentship;
$81948704 (parent: $81976, child: $41127960) isa parentship;
$81965088 isa parentship (parent: $118840, child: $41025568);
$82010144 (parent: $295032, child: $49320) isa parentship;
$82014240 (parent: $41361488, child: $41185360) isa parentship;
$82026528 (parent: $250080, child: $49320) isa parentship;
$81932336 (parent: $118840, child: $233568) isa parentship;
$81940528 (parent: $82040, child: $41168976) isa parentship;
$81965104 (parent: $41025568, child: $28840) isa parentship;
$40964136 (parent: $32904, child: $41025568) isa parentship;
$40968232 (parent: $81976, child: $41119768) isa parentship;
$40972328 isa parentship (parent: $82040, child: $8248);
$40984616 (parent: $49344, child: $114784) isa parentship;
$40988712 (parent: $32904, child: $250080) isa parentship;
$40992808 (parent: $20552, child: $40968224) isa parentship;
$41001000 (parent: $49344, child: $41119768) isa parentship;
$41009192 (parent: $118840, child: $82040) isa parentship;
$41025576 (parent: $295032, child: $41013448) isa parentship;
$41029672 (parent: $250080, child: $41013448) isa parentship;
$28912 (parent: $344120, child: $41320472) isa parentship;
$4208 (parent: $119000, child: $299128) isa parentship;
$8304 (parent: $57472, child: $41324624) isa parentship;
$24816 (parent: $81976, child: $41096) isa parentship;
$37104 isa parentship (parent: $49344, child: $41127960);
$41200 isa parentship (parent: $250080, child: $4168);
$53488 (parent: $82040, child: $356544) isa parentship;
$61680 (parent: $250080, child: $8288) isa parentship;
$102640 (parent: $49344, child: $41096) isa parentship;
$78064 isa parentship (parent: $295032, child: $8288);
$86256 (parent: $20552, child: $40988704) isa parentship;
$94448 (parent: $41025568, child: $40968224) isa parentship;
$24824 (parent: $307416, child: $41361488) isa parentship;
$4096 (spouse2: $295032, spouse1: $250080) isa marriage;
$12288 (spouse2: $266336, spouse1: $319680) isa marriage;
$20480 has picture "http:\/\/2.bp.blogspot.com\/-AT7bLradHgU\/TsfF8VuBpaI\/AAAAAAAAADA\/uodQOYjQikE\/s1600\/willsusieanothercouplesm.jpg" (spouse2: $118840, spouse1: $32904) isa marriage;
$32768 (spouse2: $86144, spouse1: $299128) isa marriage;
$204816464 (spouse2: $356544, spouse1: $41316376) isa marriage;
$204824656 (spouse2: $41095248, spouse1: $237784) isa marriage;
$204828752 (spouse2: $41291856, spouse1: $389216) isa marriage;
$40980728 (spouse2: $81976, spouse1: $49344) isa marriage;
$40984728 (spouse2: $53440, spouse1: $389216) isa marriage;
$40992920 isa marriage (spouse2: $344120, spouse1: $82040);
$40997016 (spouse2: $41127960, spouse1: $40980536) isa marriage;
$81924296 (spouse2: $118840, spouse1: $184376) isa marriage;
$81932328 (spouse2: $41324624, spouse1: $119000) isa marriage;
$81952808 (spouse2: $188608, spouse1: $196728) isa marriage;
$81957064 (spouse2: $20552, spouse1: $41025568) isa marriage;
$122884216 (spouse2: $57472, spouse1: $41406488) isa marriage;
$40972456 (spouse2: $40964120, spouse1: $8248) isa marriage;
$40976552 (spouse2: $102520, spouse1: $41185360) isa marriage;
$40980648 (spouse2: $40968224, spouse1: $41096) isa marriage;
$40988840 (spouse2: $41349200, spouse1: $249976) isa marriage;
$81924152 (spouse2: $135288, spouse1: $41340952) isa marriage;
$81936440 (spouse2: $41209936, spouse1: $282848) isa marriage;

$81940536 (spouse2: $233568, spouse1: $41361488) has picture "http:\/\/1.bp.blogspot.com\/-Ty9Ox8v7LUw\/VKoGzIlsMII\/AAAAAAAAAZw\/UtkUvrujvBQ\/s1600\/johnandmary.jpg" isa marriage;

## RULES
#############################################################################
#                                                                           #
#     			Rules to add genderized basic relations		   		        #
#                                                                           # 
#############################################################################

$genderizeMarriages isa inference-rule
lhs
{(spouse1: $s1, spouse2: $s2) isa marriage;
$s1 has gender "male";
}
rhs
{(husband: $s1, wife: $s2) isa marriage;};

$genderizeMarriages2 isa inference-rule
lhs
{(spouse1: $s1, spouse2: $s2) isa marriage;
$s1 has gender "female";
}
rhs
{(husband: $s2, wife: $s1) isa marriage;};


$genderizeParentships1 isa inference-rule
lhs
{(parent: $p, child: $c) isa parentship;
$p has gender "male";
$c has gender "male";
}
rhs
{(father: $p, son: $c) isa parentship;};

$genderizeParentships2 isa inference-rule
lhs
{(parent: $p, child: $c) isa parentship;
$p has gender "male";
$c has gender "female";
}
rhs
{(father: $p, daughter: $c) isa parentship;};

$genderizeParentships3 isa inference-rule
lhs
{(parent: $p, child: $c) isa parentship;
$p has gender "female";
$c has gender "male";
}
rhs
{(mother: $p, son: $c) isa parentship;};

$genderizeParentships4 isa inference-rule
lhs
{(parent: $p, child: $c) isa parentship;
$p has gender "female";
$c has gender "female";
}
rhs
{(mother: $p, daughter: $c) isa parentship;};


#############################################################################
#                                                                           #
#     				Rules to add inferred  relations		   		        #
#                                                                           # 
#############################################################################


$grandParents1 isa inference-rule
lhs
{($p, son: $gc) isa parentship;
(father: $gp, $p) isa parentship;
}
rhs
{(grandfather: $gp, grandson: $gc) isa grandparentship;};

$grandParents2 isa inference-rule
lhs
{($p, daughter: $gc) isa parentship;
(father: $gp, $p) isa parentship;
}
rhs
{(grandfather: $gp, granddaughter: $gc) isa grandparentship;};

$grandParents3 isa inference-rule
lhs
{($p, daughter: $gc) isa parentship;
(mother: $gp, $p) isa parentship;
}
rhs
{(grandmother: $gp, granddaughter: $gc) isa grandparentship;};

$grandParents4 isa inference-rule
lhs
{($p, son: $gc) isa parentship;
(mother: $gp, $p) isa parentship;
}
rhs
{(grandmother: $gp, grandson: $gc) isa grandparentship;};


$peopleWithSameParentsAreSiblings isa inference-rule
lhs
{(mother: $m, $x) isa parentship;
(mother: $m, $y) isa parentship;
(father: $f, $x) isa parentship;
(father: $f, $y) isa parentship;
$x != $y;
}
rhs
{(sibling1: $x, sibling2: $y) isa siblings;};

$peopleWithSiblingsParentsAreCousins isa inference-rule
lhs
{
(parent: $p, child: $c1) isa parentship;
($p, $p2) isa siblings;
(parent: $p2, child: $c2) isa parentship;
}
rhs
{(cousin1: $c1, cousin2: $c2) isa cousins;};

$inLaws1 isa inference-rule
lhs
{(husband: $x, wife: $y) isa marriage;
(mother: $il, $y) isa parentship;}
rhs
{(mother-in-law: $il, son-in-law: $x) isa in-laws;};

$inLaws2 isa inference-rule
lhs
{(husband: $x, wife: $y) isa marriage;
(father: $il, $y) isa parentship;}
rhs
{(father-in-law: $il, son-in-law: $x) isa in-laws;};

$inLaws3 isa inference-rule
lhs
{(husband: $x, wife: $y) isa marriage;
(father: $il, child: $y) isa parentship;}
rhs
{(father-in-law: $il, daughter-in-law: $y) isa in-laws;};

$inLaws4 isa inference-rule
lhs
{(husband: $x, wife: $y) isa marriage;
(mother: $il, child: $y) isa parentship;}
rhs
{(mother-in-law: $il, daughter-in-law: $y) isa in-laws;};

#############################################################################
#                                                                           #
#     				Analytics ontology						   		        #
#                                                                           # 
#############################################################################

insert 
cluster sub entity
	has identifier
	has degree;
degree sub resource datatype long;
group sub role;
member sub role;
grouping sub relation relates group relates member;
cluster plays group;
person plays member;
marriage plays member;

#############################################################################
#                                                                           #
#     				Analytics data							   		        #
#                                                                           # 
#############################################################################

insert $x isa cluster has identifier "397400" has degree 1; 
insert $x isa cluster has identifier "123064" has degree 1; 
insert $x isa cluster has identifier "602200" has degree 1; 
insert $x isa cluster has identifier "499808" has degree 1; 
insert $x isa cluster has identifier "352400" has degree 1; 
insert $x isa cluster has identifier "143376" has degree 1; 
insert $x isa cluster has identifier "483416" has degree 1; 
insert $x isa cluster has identifier "303288" has degree 1; 
insert $x isa cluster has identifier "53312"  has degree 1; 
insert $x isa cluster has identifier "393360" has degree 1; 
insert $x isa cluster has identifier "225424" has degree 1; 
insert $x isa cluster has identifier "118800" has degree 1; 
insert $x isa cluster has identifier "635064" has degree 1; 
insert $x isa cluster has identifier "827576" has degree 1; 
insert $x isa cluster has identifier "696408" has degree 1; 
insert $x isa cluster has identifier "114784" has degree 1; 
insert $x isa cluster has identifier "262256" has degree 3; 
insert $x isa cluster has identifier "569408" has degree 3; 
insert $x isa cluster has identifier "970840" has degree 3; 
insert $x isa cluster has identifier "651448" has degree 3; 
insert $x isa cluster has identifier "573504" has degree 3; 
insert $x isa cluster has identifier "999512" has degree 3; 
insert $x isa cluster has identifier "78008"  has degree 3; 
insert $x isa cluster has identifier "635024" has degree 3; 
insert $x isa cluster has identifier "626832" has degree 3; 
insert $x isa cluster has identifier "995416" has degree 3; 
insert $x isa cluster has identifier "700512" has degree 3; 
insert $x isa cluster has identifier "82016"  has degree 3; 
insert $x isa cluster has identifier "798808" has degree 3; 
insert $x isa cluster has identifier "618640" has degree 3; 
insert $x isa cluster has identifier "843960" has degree 3; 
insert $x isa cluster has identifier "921784" has degree 3; 
insert $x isa cluster has identifier "610448" has degree 3; 
insert $x isa cluster has identifier "729272" has degree 3; 
insert $x isa cluster has identifier "979032" has degree 3; 
insert $x isa cluster has identifier "483344" has degree 5; 
insert $x isa cluster has identifier "983128" has degree 5;

match $xx has identifier "262256"; $yy has identifier "Peter Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "262256"; $yy has identifier "Amanda Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "569408"; $yy has identifier "Frederick Shafner";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "569408"; $yy has identifier "Catherine Young";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "970840"; $yy has identifier "Lawrence Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "970840"; $yy has identifier "Isabelle McGaughey";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "651448"; $yy has identifier "John Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "651448"; $yy has identifier "Mary Young";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "397400"; $yy has identifier "Elizabeth Weaver";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "573504"; $yy has identifier "Catherine Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "573504"; $yy has identifier "Haman Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "123064"; $yy has identifier "Barbara Ellen Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "999512"; $yy has identifier "Samuel S. Bard";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "999512"; $yy has identifier "Mary Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "602200"; $yy has identifier "George Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "499808"; $yy has identifier "John L. Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "78008" ; $yy has identifier "Susan Josephine Dudley";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "78008" ; $yy has identifier "William Sanford Titus Jr.";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "635024"; $yy has identifier "Sarah Ann Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "635024"; $yy has identifier "Elam G. Smith";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "352400"; $yy has identifier "Mary Melissa Titus";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "626832"; $yy has identifier "Sarah Hane";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "626832"; $yy has identifier "Henry Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "143376"; $yy has identifier "Stephen Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "483416"; $yy has identifier "Lucinda Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "995416"; $yy has identifier "Catherine Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "995416"; $yy has identifier "John Shafner";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "303288"; $yy has identifier "Ron Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "700512"; $yy has identifier "Rosalie";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "700512"; $yy has identifier "Benjamin Franklin Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "82016" ; $yy has identifier "Mary Guthrie";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "82016" ; $yy has identifier "Timothy Titus";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "798808"; $yy has identifier "Maggie Billings";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "798808"; $yy has identifier "John Kossuth Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "53312" ; $yy has identifier "Elizabeth Shafner";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "393360"; $yy has identifier "Hermione Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "618640"; $yy has identifier "William Sanford Titus";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "618640"; $yy has identifier "Elizabeth Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "225424"; $yy has identifier "Eliza Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "843960"; $yy has identifier "John Meyers";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "843960"; $yy has identifier "Barbara Ellen Titus";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "483344"; $yy has identifier "Delilah Roush";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "483344"; $yy has identifier "Ann Eliza Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "483344"; $yy has identifier "William Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "118800"; $yy has identifier "Barbara E. Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "635064"; $yy has identifier "Barbara Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "827576"; $yy has identifier "Andrew Shafner";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "921784"; $yy has identifier "Byron Culbertson";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "921784"; $yy has identifier "Amanda Ann Titus";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "696408"; $yy has identifier "Harry Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "983128"; $yy has identifier "Barbara Herchelroth";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "983128"; $yy has identifier "John Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "983128"; $yy has identifier "Jacob Young";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "114784"; $yy has identifier "Margaret Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "610448"; $yy has identifier "Elizabeth";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "610448"; $yy has identifier "Robert Newman";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "729272"; $yy has identifier "Barbara Shafner";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "729272"; $yy has identifier "Jacob J. Niesz";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "979032"; $yy has identifier "Josephine";
insert (group: $xx, member: $yy) isa grouping;
match $xx has identifier "979032"; $yy has identifier "George W. Niesz";
insert (group: $xx, member: $yy) isa grouping;

match $xx has identifier "569408"; $bb has identifier "Frederick Shafner"; $aa has identifier "Catherine Young"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "729272"; $bb has identifier "Jacob J. Niesz"; $aa has identifier "Barbara Shafner"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "979032"; $bb has identifier "George W. Niesz"; $aa has identifier "Josephine"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "610448"; $bb has identifier "Robert Newman"; $aa has identifier "Elizabeth"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "921784"; $bb has identifier "Byron Culbertson"; $aa has identifier "Amanda Ann Titus"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "78008" ; $bb has identifier "William Sanford Titus Jr."; $aa has identifier "Susan Josephine Dudley"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "618640"; $bb has identifier "Elizabeth Niesz"; $aa has identifier "William Sanford Titus"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "626832"; $bb has identifier "Henry Newman"; $aa has identifier "Sarah Hane"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "970840"; $bb has identifier "Isabelle McGaughey"; $aa has identifier "Lawrence Newman"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "983128"; $bb has identifier "John Newman"; $aa has identifier "Barbara Herchelroth"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "995416"; $bb has identifier "John Shafner"; $aa has identifier "Catherine Niesz"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "999512"; $bb has identifier "Mary Niesz"; $aa has identifier "Samuel S. Bard"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "798808"; $bb has identifier "John Kossuth Niesz"; $aa has identifier "Maggie Billings"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "82016" ; $bb has identifier "Mary Guthrie"; $aa has identifier "Timothy Titus"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "635024"; $bb has identifier "Sarah Ann Niesz"; $aa has identifier "Elam G. Smith"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "843960"; $bb has identifier "Barbara Ellen Titus"; $aa has identifier "John Meyers"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "700512"; $bb has identifier "Rosalie"; $aa has identifier "Benjamin Franklin Niesz"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "651448"; $bb has identifier "John Niesz"; $aa has identifier "Mary Young"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "483344"; $bb has identifier "Delilah Roush"; $aa has identifier "William Niesz"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "483344"; $bb has identifier "William Niesz"; $aa has identifier "Ann Eliza Niesz"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "573504"; $bb has identifier "Catherine Newman"; $aa has identifier "Haman Newman"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "983128"; $bb has identifier "Jacob Young"; $aa has identifier "Barbara Herchelroth"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;
match $xx has identifier "262256"; $bb has identifier "Peter Newman"; $aa has identifier "Amanda Newman"; $r ($aa, $bb) isa marriage;
insert (group: $xx, member: $r) isa grouping;

