insert
name sub resource
    datatype string;
age sub resource
	datatype long;
person sub entity;
person has name;
person has age;

$marko isa person;
$vadas isa person;
$josh isa person;
$peter isa person;
$marko has name "marko";
$vadas has name "vadas";
$josh has name "josh";
$peter has name "peter";
$marko has age 29;
$josh has age 32;
$vadas has age 27;
$peter has age 35;

weight sub resource
	datatype double;

knower sub role;
known-about sub role;

person plays knower;
person plays known-about;

knows sub relation
	relates knower
	relates known-about
	has weight;

(knower: $marko, known-about: $josh) isa knows has weight 1.0;
(knower: $marko, known-about: $vadas) isa knows has weight 0.5;

lang sub resource
	datatype string;
software sub entity;
software has name;
software has lang;

$lop isa software;
$ripple isa software;

$lop has name "lop";
$ripple has name "ripple";

$lop has lang "java";
$ripple has lang "java";

programmer sub role;
programmed sub role;

person plays programmer;
software plays programmed;

programming sub relation
	relates programmer
	relates programmed
	has weight;

(programmer: $marko, programmed: $lop) isa programming has weight 0.4;
(programmer: $peter, programmed: $lop) isa programming has weight 0.2;
(programmer: $josh, programmed: $lop) isa programming has weight 0.4;
(programmer: $josh, programmed: $ripple) isa programming has weight 1.0;