insert

pokemon sub entity
    plays ancestor
    plays descendant
    plays pokemon-with-type
    has name
    has pokedex-no
    has description
    has height
    has weight;

pokemon-type sub entity
    has name
    plays type-of-pokemon
    plays defending-type
    plays attacking-type;

name sub resource datatype string;
pokedex-no sub resource datatype long;
description sub resource datatype string;
height sub resource datatype double;
weight sub resource datatype double;

evolution sub relation
    relates ancestor
    relates descendant;
ancestor sub role;
descendant sub role;

has-type sub relation
    relates pokemon-with-type
    relates type-of-pokemon;
pokemon-with-type sub role;
type-of-pokemon sub role;

super-effective sub relation
    relates defending-type
    relates attacking-type;
defending-type sub role;
attacking-type sub role;


# Data retrieved from Pokeapi: $https://pokeapi.co/

$Bulbasaur isa pokemon
    has name 'Bulbasaur'
    has pokedex-no 1
    has description 'A strange seed was planted on its back at birth. The plant sprouts and grows with this POKéMON.'
    has height 7
    has weight 69;

(pokemon-with-type: $Bulbasaur, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Bulbasaur, type-of-pokemon: $grass) isa has-type;



$Ivysaur isa pokemon
    has name 'Ivysaur'
    has pokedex-no 2
    has description 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.'
    has height 10
    has weight 130;

(pokemon-with-type: $Ivysaur, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Ivysaur, type-of-pokemon: $grass) isa has-type;

(descendant: $Ivysaur, ancestor: $Bulbasaur) isa evolution;


$Venusaur isa pokemon
    has name 'Venusaur'
    has pokedex-no 3
    has description 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.'
    has height 20
    has weight 1000;

(pokemon-with-type: $Venusaur, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Venusaur, type-of-pokemon: $grass) isa has-type;

(descendant: $Venusaur, ancestor: $Ivysaur) isa evolution;


$Charmander isa pokemon
    has name 'Charmander'
    has pokedex-no 4
    has description 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.'
    has height 6
    has weight 85;

(pokemon-with-type: $Charmander, type-of-pokemon: $fire) isa has-type;



$Charmeleon isa pokemon
    has name 'Charmeleon'
    has pokedex-no 5
    has description 'When it swings its burning tail, it elevates the temperature to unbearably high levels.'
    has height 11
    has weight 190;

(pokemon-with-type: $Charmeleon, type-of-pokemon: $fire) isa has-type;

(descendant: $Charmeleon, ancestor: $Charmander) isa evolution;


$Charizard isa pokemon
    has name 'Charizard'
    has pokedex-no 6
    has description 'Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.'
    has height 17
    has weight 905;

(pokemon-with-type: $Charizard, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Charizard, type-of-pokemon: $fire) isa has-type;

(descendant: $Charizard, ancestor: $Charmeleon) isa evolution;


$Squirtle isa pokemon
    has name 'Squirtle'
    has pokedex-no 7
    has description 'After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.'
    has height 5
    has weight 90;

(pokemon-with-type: $Squirtle, type-of-pokemon: $water) isa has-type;



$Wartortle isa pokemon
    has name 'Wartortle'
    has pokedex-no 8
    has description 'Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.'
    has height 10
    has weight 225;

(pokemon-with-type: $Wartortle, type-of-pokemon: $water) isa has-type;

(descendant: $Wartortle, ancestor: $Squirtle) isa evolution;


$Blastoise isa pokemon
    has name 'Blastoise'
    has pokedex-no 9
    has description 'A brutal POKéMON with pressurized water jets on its shell. They are used for high speed tackles.'
    has height 16
    has weight 855;

(pokemon-with-type: $Blastoise, type-of-pokemon: $water) isa has-type;

(descendant: $Blastoise, ancestor: $Wartortle) isa evolution;


$Caterpie isa pokemon
    has name 'Caterpie'
    has pokedex-no 10
    has description 'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.'
    has height 3
    has weight 29;

(pokemon-with-type: $Caterpie, type-of-pokemon: $bug) isa has-type;



$Metapod isa pokemon
    has name 'Metapod'
    has pokedex-no 11
    has description 'This POKéMON is vulnerable to attack while its shell is soft, exposing its weak and tender body.'
    has height 7
    has weight 99;

(pokemon-with-type: $Metapod, type-of-pokemon: $bug) isa has-type;

(descendant: $Metapod, ancestor: $Caterpie) isa evolution;


$Butterfree isa pokemon
    has name 'Butterfree'
    has pokedex-no 12
    has description 'In battle, it flaps its wings at high speed to release highly toxic dust into the air.'
    has height 11
    has weight 320;

(pokemon-with-type: $Butterfree, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Butterfree, type-of-pokemon: $bug) isa has-type;

(descendant: $Butterfree, ancestor: $Metapod) isa evolution;


$Weedle isa pokemon
    has name 'Weedle'
    has pokedex-no 13
    has description 'Often found in forests, eating leaves. It has a sharp venomous stinger on its head.'
    has height 3
    has weight 32;

(pokemon-with-type: $Weedle, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Weedle, type-of-pokemon: $bug) isa has-type;



$Kakuna isa pokemon
    has name 'Kakuna'
    has pokedex-no 14
    has description 'Almost incapable of moving, this POKéMON can only harden its shell to protect itself from predators.'
    has height 6
    has weight 100;

(pokemon-with-type: $Kakuna, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Kakuna, type-of-pokemon: $bug) isa has-type;

(descendant: $Kakuna, ancestor: $Weedle) isa evolution;


$Beedrill isa pokemon
    has name 'Beedrill'
    has pokedex-no 15
    has description 'Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.'
    has height 10
    has weight 295;

(pokemon-with-type: $Beedrill, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Beedrill, type-of-pokemon: $bug) isa has-type;

(descendant: $Beedrill, ancestor: $Kakuna) isa evolution;


$Pidgey isa pokemon
    has name 'Pidgey'
    has pokedex-no 16
    has description 'A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.'
    has height 3
    has weight 18;

(pokemon-with-type: $Pidgey, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Pidgey, type-of-pokemon: $normal) isa has-type;



$Pidgeotto isa pokemon
    has name 'Pidgeotto'
    has pokedex-no 17
    has description 'Very protective of its sprawling territorial area, this POKéMON will fiercely peck at any intruder.'
    has height 11
    has weight 300;

(pokemon-with-type: $Pidgeotto, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Pidgeotto, type-of-pokemon: $normal) isa has-type;

(descendant: $Pidgeotto, ancestor: $Pidgey) isa evolution;


$Pidgeot isa pokemon
    has name 'Pidgeot'
    has pokedex-no 18
    has description 'When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP.'
    has height 15
    has weight 395;

(pokemon-with-type: $Pidgeot, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Pidgeot, type-of-pokemon: $normal) isa has-type;

(descendant: $Pidgeot, ancestor: $Pidgeotto) isa evolution;


$Rattata isa pokemon
    has name 'Rattata'
    has pokedex-no 19
    has description 'Bites anything when it attacks. Small and very quick, it is a common sight in many places.'
    has height 3
    has weight 35;

(pokemon-with-type: $Rattata, type-of-pokemon: $normal) isa has-type;



$Raticate isa pokemon
    has name 'Raticate'
    has pokedex-no 20
    has description 'It uses its whiskers to maintain its balance. It apparently slows down if they are cut off.'
    has height 7
    has weight 185;

(pokemon-with-type: $Raticate, type-of-pokemon: $normal) isa has-type;

(descendant: $Raticate, ancestor: $Rattata) isa evolution;


$Spearow isa pokemon
    has name 'Spearow'
    has pokedex-no 21
    has description 'Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.'
    has height 3
    has weight 20;

(pokemon-with-type: $Spearow, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Spearow, type-of-pokemon: $normal) isa has-type;



$Fearow isa pokemon
    has name 'Fearow'
    has pokedex-no 22
    has description 'With its huge and magnificent wings, it can keep aloft without ever having to land for rest.'
    has height 12
    has weight 380;

(pokemon-with-type: $Fearow, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Fearow, type-of-pokemon: $normal) isa has-type;

(descendant: $Fearow, ancestor: $Spearow) isa evolution;


$Ekans isa pokemon
    has name 'Ekans'
    has pokedex-no 23
    has description 'Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole.'
    has height 20
    has weight 69;

(pokemon-with-type: $Ekans, type-of-pokemon: $poison) isa has-type;



$Arbok isa pokemon
    has name 'Arbok'
    has pokedex-no 24
    has description 'It is rumored that the ferocious warning markings on its belly differ from area to area.'
    has height 35
    has weight 650;

(pokemon-with-type: $Arbok, type-of-pokemon: $poison) isa has-type;

(descendant: $Arbok, ancestor: $Ekans) isa evolution;


$Pikachu isa pokemon
    has name 'Pikachu'
    has pokedex-no 25
    has description 'When several of these POKéMON gather, their electricity could build and cause lightning storms.'
    has height 4
    has weight 60;

(pokemon-with-type: $Pikachu, type-of-pokemon: $electric) isa has-type;


$Raichu isa pokemon
    has name 'Raichu'
    has pokedex-no 26
    has description 'Its long tail serves as a ground to protect itself from its own high voltage power.'
    has height 8
    has weight 300;

(pokemon-with-type: $Raichu, type-of-pokemon: $electric) isa has-type;

(descendant: $Raichu, ancestor: $Pikachu) isa evolution;


$Sandshrew isa pokemon
    has name 'Sandshrew'
    has pokedex-no 27
    has description 'Burrows deep underground in arid locations far from water. It only emerges to hunt for food.'
    has height 6
    has weight 120;

(pokemon-with-type: $Sandshrew, type-of-pokemon: $ground) isa has-type;



$Sandslash isa pokemon
    has name 'Sandslash'
    has pokedex-no 28
    has description 'Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.'
    has height 10
    has weight 295;

(pokemon-with-type: $Sandslash, type-of-pokemon: $ground) isa has-type;

(descendant: $Sandslash, ancestor: $Sandshrew) isa evolution;


$Nidoran-F isa pokemon
    has name 'Nidoran-F'
    has pokedex-no 29
    has description 'Although small, its venomous barbs render this POKéMON dangerous. The female has smaller horns.'
    has height 4
    has weight 70;

(pokemon-with-type: $Nidoran-F, type-of-pokemon: $poison) isa has-type;



$Nidorina isa pokemon
    has name 'Nidorina'
    has pokedex-no 30
    has description "The female's horn develops slowly. Prefers physical attacks such as clawing and biting."
    has height 8
    has weight 200;

(pokemon-with-type: $Nidorina, type-of-pokemon: $poison) isa has-type;

(descendant: $Nidorina, ancestor: $Nidoran-F) isa evolution;


$Nidoqueen isa pokemon
    has name 'Nidoqueen'
    has pokedex-no 31
    has description 'Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.'
    has height 13
    has weight 600;

(pokemon-with-type: $Nidoqueen, type-of-pokemon: $ground) isa has-type;
(pokemon-with-type: $Nidoqueen, type-of-pokemon: $poison) isa has-type;

(descendant: $Nidoqueen, ancestor: $Nidorina) isa evolution;


$Nidoran-M isa pokemon
    has name 'Nidoran-M'
    has pokedex-no 32
    has description 'Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.'
    has height 5
    has weight 90;

(pokemon-with-type: $Nidoran-M, type-of-pokemon: $poison) isa has-type;



$Nidorino isa pokemon
    has name 'Nidorino'
    has pokedex-no 33
    has description 'An aggressive POKéMON that is quick to attack. The horn on its head secretes a powerful venom.'
    has height 9
    has weight 195;

(pokemon-with-type: $Nidorino, type-of-pokemon: $poison) isa has-type;

(descendant: $Nidorino, ancestor: $Nidoran-M) isa evolution;


$Nidoking isa pokemon
    has name 'Nidoking'
    has pokedex-no 34
    has description "It uses its powerful tail in battle to smash, constrict, then break the prey's bones."
    has height 14
    has weight 620;

(pokemon-with-type: $Nidoking, type-of-pokemon: $ground) isa has-type;
(pokemon-with-type: $Nidoking, type-of-pokemon: $poison) isa has-type;

(descendant: $Nidoking, ancestor: $Nidorino) isa evolution;


$Clefairy isa pokemon
    has name 'Clefairy'
    has pokedex-no 35
    has description 'Its magical and cute appeal has many admirers. It is rare and found only in certain areas.'
    has height 6
    has weight 75;

(pokemon-with-type: $Clefairy, type-of-pokemon: $fairy) isa has-type;


$Clefable isa pokemon
    has name 'Clefable'
    has pokedex-no 36
    has description 'A timid fairy POKéMON that is rarely seen. It will run and hide the moment it senses people.'
    has height 13
    has weight 400;

(pokemon-with-type: $Clefable, type-of-pokemon: $fairy) isa has-type;

(descendant: $Clefable, ancestor: $Clefairy) isa evolution;


$Vulpix isa pokemon
    has name 'Vulpix'
    has pokedex-no 37
    has description 'At the time of birth, it has just one tail. The tail splits from its tip as it grows older.'
    has height 6
    has weight 99;

(pokemon-with-type: $Vulpix, type-of-pokemon: $fire) isa has-type;



$Ninetales isa pokemon
    has name 'Ninetales'
    has pokedex-no 38
    has description 'Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.'
    has height 11
    has weight 199;

(pokemon-with-type: $Ninetales, type-of-pokemon: $fire) isa has-type;

(descendant: $Ninetales, ancestor: $Vulpix) isa evolution;


$Jigglypuff isa pokemon
    has name 'Jigglypuff'
    has pokedex-no 39
    has description 'When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.'
    has height 5
    has weight 55;

(pokemon-with-type: $Jigglypuff, type-of-pokemon: $fairy) isa has-type;
(pokemon-with-type: $Jigglypuff, type-of-pokemon: $normal) isa has-type;


$Wigglytuff isa pokemon
    has name 'Wigglytuff'
    has pokedex-no 40
    has description 'The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.'
    has height 10
    has weight 120;

(pokemon-with-type: $Wigglytuff, type-of-pokemon: $fairy) isa has-type;
(pokemon-with-type: $Wigglytuff, type-of-pokemon: $normal) isa has-type;

(descendant: $Wigglytuff, ancestor: $Jigglypuff) isa evolution;


$Zubat isa pokemon
    has name 'Zubat'
    has pokedex-no 41
    has description 'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.'
    has height 8
    has weight 75;

(pokemon-with-type: $Zubat, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Zubat, type-of-pokemon: $poison) isa has-type;



$Golbat isa pokemon
    has name 'Golbat'
    has pokedex-no 42
    has description 'Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.'
    has height 16
    has weight 550;

(pokemon-with-type: $Golbat, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Golbat, type-of-pokemon: $poison) isa has-type;

(descendant: $Golbat, ancestor: $Zubat) isa evolution;


$Oddish isa pokemon
    has name 'Oddish'
    has pokedex-no 43
    has description 'During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.'
    has height 5
    has weight 54;

(pokemon-with-type: $Oddish, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Oddish, type-of-pokemon: $grass) isa has-type;



$Gloom isa pokemon
    has name 'Gloom'
    has pokedex-no 44
    has description "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey."
    has height 8
    has weight 86;

(pokemon-with-type: $Gloom, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Gloom, type-of-pokemon: $grass) isa has-type;

(descendant: $Gloom, ancestor: $Oddish) isa evolution;


$Vileplume isa pokemon
    has name 'Vileplume'
    has pokedex-no 45
    has description 'The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.'
    has height 12
    has weight 186;

(pokemon-with-type: $Vileplume, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Vileplume, type-of-pokemon: $grass) isa has-type;

(descendant: $Vileplume, ancestor: $Gloom) isa evolution;


$Paras isa pokemon
    has name 'Paras'
    has pokedex-no 46
    has description 'Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.'
    has height 3
    has weight 54;

(pokemon-with-type: $Paras, type-of-pokemon: $grass) isa has-type;
(pokemon-with-type: $Paras, type-of-pokemon: $bug) isa has-type;



$Parasect isa pokemon
    has name 'Parasect'
    has pokedex-no 47
    has description 'A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.'
    has height 10
    has weight 295;

(pokemon-with-type: $Parasect, type-of-pokemon: $grass) isa has-type;
(pokemon-with-type: $Parasect, type-of-pokemon: $bug) isa has-type;

(descendant: $Parasect, ancestor: $Paras) isa evolution;


$Venonat isa pokemon
    has name 'Venonat'
    has pokedex-no 48
    has description 'Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.'
    has height 10
    has weight 300;

(pokemon-with-type: $Venonat, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Venonat, type-of-pokemon: $bug) isa has-type;



$Venomoth isa pokemon
    has name 'Venomoth'
    has pokedex-no 49
    has description 'The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.'
    has height 15
    has weight 125;

(pokemon-with-type: $Venomoth, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Venomoth, type-of-pokemon: $bug) isa has-type;

(descendant: $Venomoth, ancestor: $Venonat) isa evolution;


$Diglett isa pokemon
    has name 'Diglett'
    has pokedex-no 50
    has description 'Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.'
    has height 2
    has weight 8;

(pokemon-with-type: $Diglett, type-of-pokemon: $ground) isa has-type;



$Dugtrio isa pokemon
    has name 'Dugtrio'
    has pokedex-no 51
    has description 'A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground.'
    has height 7
    has weight 333;

(pokemon-with-type: $Dugtrio, type-of-pokemon: $ground) isa has-type;

(descendant: $Dugtrio, ancestor: $Diglett) isa evolution;


$Meowth isa pokemon
    has name 'Meowth'
    has pokedex-no 52
    has description 'Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.'
    has height 4
    has weight 42;

(pokemon-with-type: $Meowth, type-of-pokemon: $normal) isa has-type;



$Persian isa pokemon
    has name 'Persian'
    has pokedex-no 53
    has description 'Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.'
    has height 10
    has weight 320;

(pokemon-with-type: $Persian, type-of-pokemon: $normal) isa has-type;

(descendant: $Persian, ancestor: $Meowth) isa evolution;


$Psyduck isa pokemon
    has name 'Psyduck'
    has pokedex-no 54
    has description 'While lulling its enemies with its vacant look, this wily POKéMON will use psychokinetic powers.'
    has height 8
    has weight 196;

(pokemon-with-type: $Psyduck, type-of-pokemon: $water) isa has-type;



$Golduck isa pokemon
    has name 'Golduck'
    has pokedex-no 55
    has description 'Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.'
    has height 17
    has weight 766;

(pokemon-with-type: $Golduck, type-of-pokemon: $water) isa has-type;

(descendant: $Golduck, ancestor: $Psyduck) isa evolution;


$Mankey isa pokemon
    has name 'Mankey'
    has pokedex-no 56
    has description 'Extremely quick to anger. It could be docile one moment then thrashing away the next instant.'
    has height 5
    has weight 280;

(pokemon-with-type: $Mankey, type-of-pokemon: $fighting) isa has-type;



$Primeape isa pokemon
    has name 'Primeape'
    has pokedex-no 57
    has description 'Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.'
    has height 10
    has weight 320;

(pokemon-with-type: $Primeape, type-of-pokemon: $fighting) isa has-type;

(descendant: $Primeape, ancestor: $Mankey) isa evolution;


$Growlithe isa pokemon
    has name 'Growlithe'
    has pokedex-no 58
    has description 'Very protective of its territory. It will bark and bite to repel intruders from its space.'
    has height 7
    has weight 190;

(pokemon-with-type: $Growlithe, type-of-pokemon: $fire) isa has-type;



$Arcanine isa pokemon
    has name 'Arcanine'
    has pokedex-no 59
    has description 'A POKéMON that has been admired since the past for its beauty. It runs agilely as if on wings.'
    has height 19
    has weight 1550;

(pokemon-with-type: $Arcanine, type-of-pokemon: $fire) isa has-type;

(descendant: $Arcanine, ancestor: $Growlithe) isa evolution;


$Poliwag isa pokemon
    has name 'Poliwag'
    has pokedex-no 60
    has description 'Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.'
    has height 6
    has weight 124;

(pokemon-with-type: $Poliwag, type-of-pokemon: $water) isa has-type;



$Poliwhirl isa pokemon
    has name 'Poliwhirl'
    has pokedex-no 61
    has description 'Capable of living in or out of water. When out of water, it sweats to keep its body slimy.'
    has height 10
    has weight 200;

(pokemon-with-type: $Poliwhirl, type-of-pokemon: $water) isa has-type;

(descendant: $Poliwhirl, ancestor: $Poliwag) isa evolution;


$Poliwrath isa pokemon
    has name 'Poliwrath'
    has pokedex-no 62
    has description 'An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.'
    has height 13
    has weight 540;

(pokemon-with-type: $Poliwrath, type-of-pokemon: $fighting) isa has-type;
(pokemon-with-type: $Poliwrath, type-of-pokemon: $water) isa has-type;

(descendant: $Poliwrath, ancestor: $Poliwhirl) isa evolution;


$Abra isa pokemon
    has name 'Abra'
    has pokedex-no 63
    has description 'Using its ability to read minds, it will identify impending danger and TELEPORT to safety.'
    has height 9
    has weight 195;

(pokemon-with-type: $Abra, type-of-pokemon: $psychic) isa has-type;



$Kadabra isa pokemon
    has name 'Kadabra'
    has pokedex-no 64
    has description 'It emits special alpha waves from its body that induce headaches just by being close by.'
    has height 13
    has weight 565;

(pokemon-with-type: $Kadabra, type-of-pokemon: $psychic) isa has-type;

(descendant: $Kadabra, ancestor: $Abra) isa evolution;


$Alakazam isa pokemon
    has name 'Alakazam'
    has pokedex-no 65
    has description 'Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000.'
    has height 15
    has weight 480;

(pokemon-with-type: $Alakazam, type-of-pokemon: $psychic) isa has-type;

(descendant: $Alakazam, ancestor: $Kadabra) isa evolution;


$Machop isa pokemon
    has name 'Machop'
    has pokedex-no 66
    has description 'Loves to build its muscles. It trains in all styles of martial arts to become even stronger.'
    has height 8
    has weight 195;

(pokemon-with-type: $Machop, type-of-pokemon: $fighting) isa has-type;



$Machoke isa pokemon
    has name 'Machoke'
    has pokedex-no 67
    has description 'Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.'
    has height 15
    has weight 705;

(pokemon-with-type: $Machoke, type-of-pokemon: $fighting) isa has-type;

(descendant: $Machoke, ancestor: $Machop) isa evolution;


$Machamp isa pokemon
    has name 'Machamp'
    has pokedex-no 68
    has description 'Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.'
    has height 16
    has weight 1300;

(pokemon-with-type: $Machamp, type-of-pokemon: $fighting) isa has-type;

(descendant: $Machamp, ancestor: $Machoke) isa evolution;


$Bellsprout isa pokemon
    has name 'Bellsprout'
    has pokedex-no 69
    has description 'A carnivorous POKéMON that traps and eats bugs. It uses its root feet to soak up needed moisture.'
    has height 7
    has weight 40;

(pokemon-with-type: $Bellsprout, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Bellsprout, type-of-pokemon: $grass) isa has-type;



$Weepinbell isa pokemon
    has name 'Weepinbell'
    has pokedex-no 70
    has description 'It spits out POISONPOWDER to immobilize the enemy and then finishes it with a spray of ACID.'
    has height 10
    has weight 64;

(pokemon-with-type: $Weepinbell, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Weepinbell, type-of-pokemon: $grass) isa has-type;

(descendant: $Weepinbell, ancestor: $Bellsprout) isa evolution;


$Victreebel isa pokemon
    has name 'Victreebel'
    has pokedex-no 71
    has description 'Said to live in huge colonies deep in jungles, although no one has ever returned from there.'
    has height 17
    has weight 155;

(pokemon-with-type: $Victreebel, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Victreebel, type-of-pokemon: $grass) isa has-type;

(descendant: $Victreebel, ancestor: $Weepinbell) isa evolution;


$Tentacool isa pokemon
    has name 'Tentacool'
    has pokedex-no 72
    has description 'Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.'
    has height 9
    has weight 455;

(pokemon-with-type: $Tentacool, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Tentacool, type-of-pokemon: $water) isa has-type;



$Tentacruel isa pokemon
    has name 'Tentacruel'
    has pokedex-no 73
    has description 'The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.'
    has height 16
    has weight 550;

(pokemon-with-type: $Tentacruel, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Tentacruel, type-of-pokemon: $water) isa has-type;

(descendant: $Tentacruel, ancestor: $Tentacool) isa evolution;


$Geodude isa pokemon
    has name 'Geodude'
    has pokedex-no 74
    has description 'Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.'
    has height 4
    has weight 200;

(pokemon-with-type: $Geodude, type-of-pokemon: $ground) isa has-type;
(pokemon-with-type: $Geodude, type-of-pokemon: $rock) isa has-type;



$Graveler isa pokemon
    has name 'Graveler'
    has pokedex-no 75
    has description 'Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.'
    has height 10
    has weight 1050;

(pokemon-with-type: $Graveler, type-of-pokemon: $ground) isa has-type;
(pokemon-with-type: $Graveler, type-of-pokemon: $rock) isa has-type;

(descendant: $Graveler, ancestor: $Geodude) isa evolution;


$Golem isa pokemon
    has name 'Golem'
    has pokedex-no 76
    has description 'Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.'
    has height 14
    has weight 3000;

(pokemon-with-type: $Golem, type-of-pokemon: $ground) isa has-type;
(pokemon-with-type: $Golem, type-of-pokemon: $rock) isa has-type;

(descendant: $Golem, ancestor: $Graveler) isa evolution;


$Ponyta isa pokemon
    has name 'Ponyta'
    has pokedex-no 77
    has description 'Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.'
    has height 10
    has weight 300;

(pokemon-with-type: $Ponyta, type-of-pokemon: $fire) isa has-type;



$Rapidash isa pokemon
    has name 'Rapidash'
    has pokedex-no 78
    has description 'Very competitive, this POKéMON will chase anything that moves fast in the hopes of racing it.'
    has height 17
    has weight 950;

(pokemon-with-type: $Rapidash, type-of-pokemon: $fire) isa has-type;

(descendant: $Rapidash, ancestor: $Ponyta) isa evolution;


$Slowpoke isa pokemon
    has name 'Slowpoke'
    has pokedex-no 79
    has description 'Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.'
    has height 12
    has weight 360;

(pokemon-with-type: $Slowpoke, type-of-pokemon: $psychic) isa has-type;
(pokemon-with-type: $Slowpoke, type-of-pokemon: $water) isa has-type;



$Slowbro isa pokemon
    has name 'Slowbro'
    has pokedex-no 80
    has description "The SHELLDER that is latched onto SLOWPOKE's tail is said to feed on the host's left over scraps."
    has height 16
    has weight 785;

(pokemon-with-type: $Slowbro, type-of-pokemon: $psychic) isa has-type;
(pokemon-with-type: $Slowbro, type-of-pokemon: $water) isa has-type;

(descendant: $Slowbro, ancestor: $Slowpoke) isa evolution;


$Magnemite isa pokemon
    has name 'Magnemite'
    has pokedex-no 81
    has description 'Uses anti-gravity to stay suspended. Appears without warning and uses THUNDER WAVE and similar moves.'
    has height 3
    has weight 60;

(pokemon-with-type: $Magnemite, type-of-pokemon: $steel) isa has-type;
(pokemon-with-type: $Magnemite, type-of-pokemon: $electric) isa has-type;



$Magneton isa pokemon
    has name 'Magneton'
    has pokedex-no 82
    has description 'Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up.'
    has height 10
    has weight 600;

(pokemon-with-type: $Magneton, type-of-pokemon: $steel) isa has-type;
(pokemon-with-type: $Magneton, type-of-pokemon: $electric) isa has-type;

(descendant: $Magneton, ancestor: $Magnemite) isa evolution;


$Farfetchd isa pokemon
    has name 'Farfetchd'
    has pokedex-no 83
    has description 'The sprig of green onions it holds is its weapon. It is used much like a metal sword.'
    has height 8
    has weight 150;

(pokemon-with-type: $Farfetchd, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Farfetchd, type-of-pokemon: $normal) isa has-type;



$Doduo isa pokemon
    has name 'Doduo'
    has pokedex-no 84
    has description 'A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.'
    has height 14
    has weight 392;

(pokemon-with-type: $Doduo, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Doduo, type-of-pokemon: $normal) isa has-type;



$Dodrio isa pokemon
    has name 'Dodrio'
    has pokedex-no 85
    has description 'Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.'
    has height 18
    has weight 852;

(pokemon-with-type: $Dodrio, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Dodrio, type-of-pokemon: $normal) isa has-type;

(descendant: $Dodrio, ancestor: $Doduo) isa evolution;


$Seel isa pokemon
    has name 'Seel'
    has pokedex-no 86
    has description 'The protruding horn on its head is very hard. It is used for bashing through thick ice.'
    has height 11
    has weight 900;

(pokemon-with-type: $Seel, type-of-pokemon: $water) isa has-type;



$Dewgong isa pokemon
    has name 'Dewgong'
    has pokedex-no 87
    has description 'Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.'
    has height 17
    has weight 1200;

(pokemon-with-type: $Dewgong, type-of-pokemon: $ice) isa has-type;
(pokemon-with-type: $Dewgong, type-of-pokemon: $water) isa has-type;

(descendant: $Dewgong, ancestor: $Seel) isa evolution;


$Grimer isa pokemon
    has name 'Grimer'
    has pokedex-no 88
    has description 'Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.'
    has height 9
    has weight 300;

(pokemon-with-type: $Grimer, type-of-pokemon: $poison) isa has-type;



$Muk isa pokemon
    has name 'Muk'
    has pokedex-no 89
    has description 'Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.'
    has height 12
    has weight 300;

(pokemon-with-type: $Muk, type-of-pokemon: $poison) isa has-type;

(descendant: $Muk, ancestor: $Grimer) isa evolution;


$Shellder isa pokemon
    has name 'Shellder'
    has pokedex-no 90
    has description 'Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.'
    has height 3
    has weight 40;

(pokemon-with-type: $Shellder, type-of-pokemon: $water) isa has-type;



$Cloyster isa pokemon
    has name 'Cloyster'
    has pokedex-no 91
    has description 'When attacked, it launches its horns in quick volleys. Its innards have never been seen.'
    has height 15
    has weight 1325;

(pokemon-with-type: $Cloyster, type-of-pokemon: $ice) isa has-type;
(pokemon-with-type: $Cloyster, type-of-pokemon: $water) isa has-type;

(descendant: $Cloyster, ancestor: $Shellder) isa evolution;


$Gastly isa pokemon
    has name 'Gastly'
    has pokedex-no 92
    has description 'Almost invisible, this gaseous POKéMON cloaks the target and puts it to sleep without notice.'
    has height 13
    has weight 1;

(pokemon-with-type: $Gastly, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Gastly, type-of-pokemon: $ghost) isa has-type;



$Haunter isa pokemon
    has name 'Haunter'
    has pokedex-no 93
    has description 'Because of its ability to slip through block walls, it is said to be from another dimension.'
    has height 16
    has weight 1;

(pokemon-with-type: $Haunter, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Haunter, type-of-pokemon: $ghost) isa has-type;

(descendant: $Haunter, ancestor: $Gastly) isa evolution;


$Gengar isa pokemon
    has name 'Gengar'
    has pokedex-no 94
    has description 'Under a full moon, this POKéMON likes to mimic the shadows of people and laugh at their fright.'
    has height 15
    has weight 405;

(pokemon-with-type: $Gengar, type-of-pokemon: $poison) isa has-type;
(pokemon-with-type: $Gengar, type-of-pokemon: $ghost) isa has-type;

(descendant: $Gengar, ancestor: $Haunter) isa evolution;


$Onix isa pokemon
    has name 'Onix'
    has pokedex-no 95
    has description 'As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.'
    has height 88
    has weight 2100;

(pokemon-with-type: $Onix, type-of-pokemon: $ground) isa has-type;
(pokemon-with-type: $Onix, type-of-pokemon: $rock) isa has-type;



$Drowzee isa pokemon
    has name 'Drowzee'
    has pokedex-no 96
    has description 'Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.'
    has height 10
    has weight 324;

(pokemon-with-type: $Drowzee, type-of-pokemon: $psychic) isa has-type;



$Hypno isa pokemon
    has name 'Hypno'
    has pokedex-no 97
    has description 'When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION.'
    has height 16
    has weight 756;

(pokemon-with-type: $Hypno, type-of-pokemon: $psychic) isa has-type;

(descendant: $Hypno, ancestor: $Drowzee) isa evolution;


$Krabby isa pokemon
    has name 'Krabby'
    has pokedex-no 98
    has description 'Its pincers are not only powerful weapons, they are used for balance when walking sideways.'
    has height 4
    has weight 65;

(pokemon-with-type: $Krabby, type-of-pokemon: $water) isa has-type;



$Kingler isa pokemon
    has name 'Kingler'
    has pokedex-no 99
    has description 'The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.'
    has height 13
    has weight 600;

(pokemon-with-type: $Kingler, type-of-pokemon: $water) isa has-type;

(descendant: $Kingler, ancestor: $Krabby) isa evolution;


$Voltorb isa pokemon
    has name 'Voltorb'
    has pokedex-no 100
    has description 'Usually found in power plants. Easily mistaken for a POKé BALL, they have zapped many people.'
    has height 5
    has weight 104;

(pokemon-with-type: $Voltorb, type-of-pokemon: $electric) isa has-type;



$Electrode isa pokemon
    has name 'Electrode'
    has pokedex-no 101
    has description 'It stores electric energy under very high pressure. It often explodes with little or no provocation.'
    has height 12
    has weight 666;

(pokemon-with-type: $Electrode, type-of-pokemon: $electric) isa has-type;

(descendant: $Electrode, ancestor: $Voltorb) isa evolution;


$Exeggcute isa pokemon
    has name 'Exeggcute'
    has pokedex-no 102
    has description 'Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.'
    has height 4
    has weight 25;

(pokemon-with-type: $Exeggcute, type-of-pokemon: $psychic) isa has-type;
(pokemon-with-type: $Exeggcute, type-of-pokemon: $grass) isa has-type;



$Exeggutor isa pokemon
    has name 'Exeggutor'
    has pokedex-no 103
    has description 'Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE.'
    has height 20
    has weight 1200;

(pokemon-with-type: $Exeggutor, type-of-pokemon: $psychic) isa has-type;
(pokemon-with-type: $Exeggutor, type-of-pokemon: $grass) isa has-type;

(descendant: $Exeggutor, ancestor: $Exeggcute) isa evolution;


$Cubone isa pokemon
    has name 'Cubone'
    has pokedex-no 104
    has description "Because it never removes its skull helmet, no one has ever seen this POKéMON's real face."
    has height 4
    has weight 65;

(pokemon-with-type: $Cubone, type-of-pokemon: $ground) isa has-type;



$Marowak isa pokemon
    has name 'Marowak'
    has pokedex-no 105
    has description 'The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.'
    has height 10
    has weight 450;

(pokemon-with-type: $Marowak, type-of-pokemon: $ground) isa has-type;

(descendant: $Marowak, ancestor: $Cubone) isa evolution;


$Hitmonlee isa pokemon
    has name 'Hitmonlee'
    has pokedex-no 106
    has description 'When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.'
    has height 15
    has weight 498;

(pokemon-with-type: $Hitmonlee, type-of-pokemon: $fighting) isa has-type;


$Hitmonchan isa pokemon
    has name 'Hitmonchan'
    has pokedex-no 107
    has description 'While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.'
    has height 14
    has weight 502;

(pokemon-with-type: $Hitmonchan, type-of-pokemon: $fighting) isa has-type;


$Lickitung isa pokemon
    has name 'Lickitung'
    has pokedex-no 108
    has description "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies."
    has height 12
    has weight 655;

(pokemon-with-type: $Lickitung, type-of-pokemon: $normal) isa has-type;



$Koffing isa pokemon
    has name 'Koffing'
    has pokedex-no 109
    has description 'Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.'
    has height 6
    has weight 10;

(pokemon-with-type: $Koffing, type-of-pokemon: $poison) isa has-type;



$Weezing isa pokemon
    has name 'Weezing'
    has pokedex-no 110
    has description 'Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years.'
    has height 12
    has weight 95;

(pokemon-with-type: $Weezing, type-of-pokemon: $poison) isa has-type;

(descendant: $Weezing, ancestor: $Koffing) isa evolution;


$Rhyhorn isa pokemon
    has name 'Rhyhorn'
    has pokedex-no 111
    has description 'Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying.'
    has height 10
    has weight 1150;

(pokemon-with-type: $Rhyhorn, type-of-pokemon: $rock) isa has-type;
(pokemon-with-type: $Rhyhorn, type-of-pokemon: $ground) isa has-type;



$Rhydon isa pokemon
    has name 'Rhydon'
    has pokedex-no 112
    has description 'Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.'
    has height 19
    has weight 1200;

(pokemon-with-type: $Rhydon, type-of-pokemon: $rock) isa has-type;
(pokemon-with-type: $Rhydon, type-of-pokemon: $ground) isa has-type;

(descendant: $Rhydon, ancestor: $Rhyhorn) isa evolution;


$Chansey isa pokemon
    has name 'Chansey'
    has pokedex-no 113
    has description 'A rare and elusive POKéMON that is said to bring happiness to those who manage to get it.'
    has height 11
    has weight 346;

(pokemon-with-type: $Chansey, type-of-pokemon: $normal) isa has-type;


$Tangela isa pokemon
    has name 'Tangela'
    has pokedex-no 114
    has description 'The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks.'
    has height 10
    has weight 350;

(pokemon-with-type: $Tangela, type-of-pokemon: $grass) isa has-type;



$Kangaskhan isa pokemon
    has name 'Kangaskhan'
    has pokedex-no 115
    has description "The infant rarely ventures out of its mother's protective pouch until it is 3 years old."
    has height 22
    has weight 800;

(pokemon-with-type: $Kangaskhan, type-of-pokemon: $normal) isa has-type;



$Horsea isa pokemon
    has name 'Horsea'
    has pokedex-no 116
    has description 'Known to shoot down flying bugs with precision blasts of ink from the surface of the water.'
    has height 4
    has weight 80;

(pokemon-with-type: $Horsea, type-of-pokemon: $water) isa has-type;



$Seadra isa pokemon
    has name 'Seadra'
    has pokedex-no 117
    has description 'Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail.'
    has height 12
    has weight 250;

(pokemon-with-type: $Seadra, type-of-pokemon: $water) isa has-type;

(descendant: $Seadra, ancestor: $Horsea) isa evolution;


$Goldeen isa pokemon
    has name 'Goldeen'
    has pokedex-no 118
    has description 'Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.'
    has height 6
    has weight 150;

(pokemon-with-type: $Goldeen, type-of-pokemon: $water) isa has-type;



$Seaking isa pokemon
    has name 'Seaking'
    has pokedex-no 119
    has description 'In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.'
    has height 13
    has weight 390;

(pokemon-with-type: $Seaking, type-of-pokemon: $water) isa has-type;

(descendant: $Seaking, ancestor: $Goldeen) isa evolution;


$Staryu isa pokemon
    has name 'Staryu'
    has pokedex-no 120
    has description 'An enigmatic POKéMON that can effortlessly regenerate any appendage it loses in battle.'
    has height 8
    has weight 345;

(pokemon-with-type: $Staryu, type-of-pokemon: $water) isa has-type;



$Starmie isa pokemon
    has name 'Starmie'
    has pokedex-no 121
    has description 'Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.'
    has height 11
    has weight 800;

(pokemon-with-type: $Starmie, type-of-pokemon: $psychic) isa has-type;
(pokemon-with-type: $Starmie, type-of-pokemon: $water) isa has-type;

(descendant: $Starmie, ancestor: $Staryu) isa evolution;


$Mr-Mime isa pokemon
    has name 'Mr-Mime'
    has pokedex-no 122
    has description 'If interrupted while it is miming, it will slap around the offender with its broad hands.'
    has height 13
    has weight 545;

(pokemon-with-type: $Mr-Mime, type-of-pokemon: $fairy) isa has-type;
(pokemon-with-type: $Mr-Mime, type-of-pokemon: $psychic) isa has-type;


$Scyther isa pokemon
    has name 'Scyther'
    has pokedex-no 123
    has description 'With ninja-like agility and speed, it can create the illusion that there is more than one.'
    has height 15
    has weight 560;

(pokemon-with-type: $Scyther, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Scyther, type-of-pokemon: $bug) isa has-type;



$Jynx isa pokemon
    has name 'Jynx'
    has pokedex-no 124
    has description 'It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.'
    has height 14
    has weight 406;

(pokemon-with-type: $Jynx, type-of-pokemon: $psychic) isa has-type;
(pokemon-with-type: $Jynx, type-of-pokemon: $ice) isa has-type;


$Electabuzz isa pokemon
    has name 'Electabuzz'
    has pokedex-no 125
    has description 'Normally found near power plants, they can wander away and cause major blackouts in cities.'
    has height 11
    has weight 300;

(pokemon-with-type: $Electabuzz, type-of-pokemon: $electric) isa has-type;


$Magmar isa pokemon
    has name 'Magmar'
    has pokedex-no 126
    has description 'Its body always burns with an orange glow that enables it to hide perfectly among flames.'
    has height 13
    has weight 445;

(pokemon-with-type: $Magmar, type-of-pokemon: $fire) isa has-type;


$Pinsir isa pokemon
    has name 'Pinsir'
    has pokedex-no 127
    has description 'If it fails to crush the victim in its pincers, it will swing it around and toss it hard.'
    has height 15
    has weight 550;

(pokemon-with-type: $Pinsir, type-of-pokemon: $bug) isa has-type;



$Tauros isa pokemon
    has name 'Tauros'
    has pokedex-no 128
    has description 'When it targets an enemy, it charges furiously while whipping its body with its long tails.'
    has height 14
    has weight 884;

(pokemon-with-type: $Tauros, type-of-pokemon: $normal) isa has-type;



$Magikarp isa pokemon
    has name 'Magikarp'
    has pokedex-no 129
    has description 'In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.'
    has height 9
    has weight 100;

(pokemon-with-type: $Magikarp, type-of-pokemon: $water) isa has-type;



$Gyarados isa pokemon
    has name 'Gyarados'
    has pokedex-no 130
    has description 'Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.'
    has height 65
    has weight 2350;

(pokemon-with-type: $Gyarados, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Gyarados, type-of-pokemon: $water) isa has-type;

(descendant: $Gyarados, ancestor: $Magikarp) isa evolution;


$Lapras isa pokemon
    has name 'Lapras'
    has pokedex-no 131
    has description 'A POKéMON that has been overhunted almost to extinction. It can ferry people across the water.'
    has height 25
    has weight 2200;

(pokemon-with-type: $Lapras, type-of-pokemon: $ice) isa has-type;
(pokemon-with-type: $Lapras, type-of-pokemon: $water) isa has-type;



$Ditto isa pokemon
    has name 'Ditto'
    has pokedex-no 132
    has description "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy."
    has height 3
    has weight 40;

(pokemon-with-type: $Ditto, type-of-pokemon: $normal) isa has-type;



$Eevee isa pokemon
    has name 'Eevee'
    has pokedex-no 133
    has description 'Its genetic code is irregular. It may mutate if it is exposed to radiation from element STONEs.'
    has height 3
    has weight 65;

(pokemon-with-type: $Eevee, type-of-pokemon: $normal) isa has-type;



$Vaporeon isa pokemon
    has name 'Vaporeon'
    has pokedex-no 134
    has description "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's."
    has height 10
    has weight 290;

(pokemon-with-type: $Vaporeon, type-of-pokemon: $water) isa has-type;

(descendant: $Vaporeon, ancestor: $Eevee) isa evolution;


$Jolteon isa pokemon
    has name 'Jolteon'
    has pokedex-no 135
    has description 'It accumulates negative ions in the atmosphere to blast out 10000- volt lightning bolts.'
    has height 8
    has weight 245;

(pokemon-with-type: $Jolteon, type-of-pokemon: $electric) isa has-type;

(descendant: $Jolteon, ancestor: $Eevee) isa evolution;


$Flareon isa pokemon
    has name 'Flareon'
    has pokedex-no 136
    has description 'When storing thermal energy in its body, its temperature could soar to over 1600 degrees.'
    has height 9
    has weight 250;

(pokemon-with-type: $Flareon, type-of-pokemon: $fire) isa has-type;

(descendant: $Flareon, ancestor: $Eevee) isa evolution;


$Porygon isa pokemon
    has name 'Porygon'
    has pokedex-no 137
    has description 'A POKéMON that consists entirely of programming code. Capable of moving freely in cyberspace.'
    has height 8
    has weight 365;

(pokemon-with-type: $Porygon, type-of-pokemon: $normal) isa has-type;



$Omanyte isa pokemon
    has name 'Omanyte'
    has pokedex-no 138
    has description 'Although long extinct, in rare cases, it can be genetically resurrected from fossils.'
    has height 4
    has weight 75;

(pokemon-with-type: $Omanyte, type-of-pokemon: $water) isa has-type;
(pokemon-with-type: $Omanyte, type-of-pokemon: $rock) isa has-type;



$Omastar isa pokemon
    has name 'Omastar'
    has pokedex-no 139
    has description 'A prehistoric POKéMON that died out when its heavy shell made it impossible to catch prey.'
    has height 10
    has weight 350;

(pokemon-with-type: $Omastar, type-of-pokemon: $water) isa has-type;
(pokemon-with-type: $Omastar, type-of-pokemon: $rock) isa has-type;

(descendant: $Omastar, ancestor: $Omanyte) isa evolution;


$Kabuto isa pokemon
    has name 'Kabuto'
    has pokedex-no 140
    has description 'A POKéMON that was resurrected from a fossil found in what was once the ocean floor eons ago.'
    has height 5
    has weight 115;

(pokemon-with-type: $Kabuto, type-of-pokemon: $water) isa has-type;
(pokemon-with-type: $Kabuto, type-of-pokemon: $rock) isa has-type;



$Kabutops isa pokemon
    has name 'Kabutops'
    has pokedex-no 141
    has description 'Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids.'
    has height 13
    has weight 405;

(pokemon-with-type: $Kabutops, type-of-pokemon: $water) isa has-type;
(pokemon-with-type: $Kabutops, type-of-pokemon: $rock) isa has-type;

(descendant: $Kabutops, ancestor: $Kabuto) isa evolution;


$Aerodactyl isa pokemon
    has name 'Aerodactyl'
    has pokedex-no 142
    has description "A ferocious, prehistoric POKéMON that goes for the enemy's throat with its serrated saw-like fangs."
    has height 18
    has weight 590;

(pokemon-with-type: $Aerodactyl, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Aerodactyl, type-of-pokemon: $rock) isa has-type;



$Snorlax isa pokemon
    has name 'Snorlax'
    has pokedex-no 143
    has description 'Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.'
    has height 21
    has weight 4600;

(pokemon-with-type: $Snorlax, type-of-pokemon: $normal) isa has-type;


$Articuno isa pokemon
    has name 'Articuno'
    has pokedex-no 144
    has description 'A legendary bird POKéMON that is said to appear to doomed people who are lost in icy mountains.'
    has height 17
    has weight 554;

(pokemon-with-type: $Articuno, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Articuno, type-of-pokemon: $ice) isa has-type;



$Zapdos isa pokemon
    has name 'Zapdos'
    has pokedex-no 145
    has description 'A legendary bird POKéMON that is said to appear from clouds while dropping enormous lightning bolts.'
    has height 16
    has weight 526;

(pokemon-with-type: $Zapdos, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Zapdos, type-of-pokemon: $electric) isa has-type;



$Moltres isa pokemon
    has name 'Moltres'
    has pokedex-no 146
    has description 'Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.'
    has height 20
    has weight 600;

(pokemon-with-type: $Moltres, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Moltres, type-of-pokemon: $fire) isa has-type;



$Dratini isa pokemon
    has name 'Dratini'
    has pokedex-no 147
    has description 'Long considered a mythical POKéMON until recently when a small colony was found living underwater.'
    has height 18
    has weight 33;

(pokemon-with-type: $Dratini, type-of-pokemon: $dragon) isa has-type;



$Dragonair isa pokemon
    has name 'Dragonair'
    has pokedex-no 148
    has description 'A mystical POKéMON that exudes a gentle aura. Has the ability to change climate conditions.'
    has height 40
    has weight 165;

(pokemon-with-type: $Dragonair, type-of-pokemon: $dragon) isa has-type;

(descendant: $Dragonair, ancestor: $Dratini) isa evolution;


$Dragonite isa pokemon
    has name 'Dragonite'
    has pokedex-no 149
    has description 'An extremely rarely seen marine POKéMON. Its intelligence is said to match that of humans.'
    has height 22
    has weight 2100;

(pokemon-with-type: $Dragonite, type-of-pokemon: $flying) isa has-type;
(pokemon-with-type: $Dragonite, type-of-pokemon: $dragon) isa has-type;

(descendant: $Dragonite, ancestor: $Dragonair) isa evolution;


$Mewtwo isa pokemon
    has name 'Mewtwo'
    has pokedex-no 150
    has description 'It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.'
    has height 20
    has weight 1220;

(pokemon-with-type: $Mewtwo, type-of-pokemon: $psychic) isa has-type;



$Mew isa pokemon
    has name 'Mew'
    has pokedex-no 151
    has description 'So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.'
    has height 4
    has weight 40;

(pokemon-with-type: $Mew, type-of-pokemon: $psychic) isa has-type;


$normal isa pokemon-type, has name 'normal';

$fighting isa pokemon-type, has name 'fighting';
(defending-type: $normal, attacking-type: $fighting) isa super-effective;
(defending-type: $rock, attacking-type: $fighting) isa super-effective;
(defending-type: $steel, attacking-type: $fighting) isa super-effective;
(defending-type: $ice, attacking-type: $fighting) isa super-effective;
(defending-type: $dark, attacking-type: $fighting) isa super-effective;

$flying isa pokemon-type, has name 'flying';
(defending-type: $fighting, attacking-type: $flying) isa super-effective;
(defending-type: $bug, attacking-type: $flying) isa super-effective;
(defending-type: $grass, attacking-type: $flying) isa super-effective;

$poison isa pokemon-type, has name 'poison';
(defending-type: $grass, attacking-type: $poison) isa super-effective;
(defending-type: $fairy, attacking-type: $poison) isa super-effective;

$ground isa pokemon-type, has name 'ground';
(defending-type: $poison, attacking-type: $ground) isa super-effective;
(defending-type: $rock, attacking-type: $ground) isa super-effective;
(defending-type: $steel, attacking-type: $ground) isa super-effective;
(defending-type: $fire, attacking-type: $ground) isa super-effective;
(defending-type: $electric, attacking-type: $ground) isa super-effective;

$rock isa pokemon-type, has name 'rock';
(defending-type: $flying, attacking-type: $rock) isa super-effective;
(defending-type: $bug, attacking-type: $rock) isa super-effective;
(defending-type: $fire, attacking-type: $rock) isa super-effective;
(defending-type: $ice, attacking-type: $rock) isa super-effective;

$bug isa pokemon-type, has name 'bug';
(defending-type: $grass, attacking-type: $bug) isa super-effective;
(defending-type: $psychic, attacking-type: $bug) isa super-effective;
(defending-type: $dark, attacking-type: $bug) isa super-effective;

$ghost isa pokemon-type, has name 'ghost';
(defending-type: $ghost, attacking-type: $ghost) isa super-effective;
(defending-type: $psychic, attacking-type: $ghost) isa super-effective;

$steel isa pokemon-type, has name 'steel';
(defending-type: $rock, attacking-type: $steel) isa super-effective;
(defending-type: $ice, attacking-type: $steel) isa super-effective;
(defending-type: $fairy, attacking-type: $steel) isa super-effective;

$fire isa pokemon-type, has name 'fire';
(defending-type: $bug, attacking-type: $fire) isa super-effective;
(defending-type: $steel, attacking-type: $fire) isa super-effective;
(defending-type: $grass, attacking-type: $fire) isa super-effective;
(defending-type: $ice, attacking-type: $fire) isa super-effective;

$water isa pokemon-type, has name 'water';
(defending-type: $ground, attacking-type: $water) isa super-effective;
(defending-type: $rock, attacking-type: $water) isa super-effective;
(defending-type: $fire, attacking-type: $water) isa super-effective;

$grass isa pokemon-type, has name 'grass';
(defending-type: $ground, attacking-type: $grass) isa super-effective;
(defending-type: $rock, attacking-type: $grass) isa super-effective;
(defending-type: $water, attacking-type: $grass) isa super-effective;

$electric isa pokemon-type, has name 'electric';
(defending-type: $flying, attacking-type: $electric) isa super-effective;
(defending-type: $water, attacking-type: $electric) isa super-effective;

$psychic isa pokemon-type, has name 'psychic';
(defending-type: $fighting, attacking-type: $psychic) isa super-effective;
(defending-type: $poison, attacking-type: $psychic) isa super-effective;

$ice isa pokemon-type, has name 'ice';
(defending-type: $flying, attacking-type: $ice) isa super-effective;
(defending-type: $ground, attacking-type: $ice) isa super-effective;
(defending-type: $grass, attacking-type: $ice) isa super-effective;
(defending-type: $dragon, attacking-type: $ice) isa super-effective;

$dragon isa pokemon-type, has name 'dragon';
(defending-type: $dragon, attacking-type: $dragon) isa super-effective;

$dark isa pokemon-type, has name 'dark';
(defending-type: $ghost, attacking-type: $dark) isa super-effective;
(defending-type: $psychic, attacking-type: $dark) isa super-effective;

$fairy isa pokemon-type, has name 'fairy';
(defending-type: $fighting, attacking-type: $fairy) isa super-effective;
(defending-type: $dragon, attacking-type: $fairy) isa super-effective;
(defending-type: $dark, attacking-type: $fairy) isa super-effective;

$unknown isa pokemon-type, has name 'unknown';

$shadow isa pokemon-type, has name 'shadow';

