java_library(
    name = "jaxb_api",
    exports = [
        "//external:jar/javax/xml/bind/jaxb_api"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/javax/activation:activation",
        "//dependencies/maven/artifacts/javax/xml/stream:stax_api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


