java_library(
    name = "reflections",
    exports = [
        "//external:jar/org/reflections/reflections"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/dom4j:dom4j",
        "//dependencies/maven/artifacts/org/javassist:javassist"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


