java_library(
    name = "jcip-annotations",
    exports = [
        "//external:jar/net/jcip/jcip-annotations"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


