java_library(
    name = "jcip_annotations",
    exports = [
        "//external:jar/net/jcip/jcip_annotations"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


