java_library(
    name = "javax-inject",
    exports = [
        "//external:jar/javax/inject/javax-inject"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


