java_library(
    name = "javax_inject",
    exports = [
        "//external:jar/javax/inject/javax_inject"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


