java_library(
    name = "hibernate-validator",
    exports = [
        "//external:jar/org/hibernate/hibernate-validator"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/javax/validation:validation-api",
        "//dependencies/maven/artifacts/org/jboss/logging:jboss-logging"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


