java_library(
    name = "hibernate_validator",
    exports = [
        "//external:jar/org/hibernate/hibernate_validator"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/javax/validation:validation_api",
        "//dependencies/maven/artifacts/org/jboss/logging:jboss_logging"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


