test_suite(
    name = "test-end-to-end",
    tests = [
        "//test-end-to-end/distribution:grakn-graql-commands-e2e",
        "//test-end-to-end/distribution:grakn-graql-commands-with-a-running-grakn-e2e",
        "//test-end-to-end/client_java:client-java-e2e",
        "//test-end-to-end/attribute_deduplicator:attribute-deduplicator-e2e"
    ]
)