test_suite(
    name = "test-end-to-end",
    tests = [
        "//test-end-to-end/distribution:grakn-graql-commands-e2e",
        "//test-end-to-end/distribution:grakn-graql-commands-with-a-running-grakn-e2e",
        "//test-end-to-end/distribution:client-java-e2e",
    ]
)