
insert
  person sub entity
    plays person-with-address
    plays person-with-phone;

  address sub entity
    plays address-of-person
    plays address-with-street
    has city;

  street-address sub entity
    plays street-of-address
    has number
    has street;

  phone-number sub entity
    plays phone-of-person
    has location
    has code;

  code sub resource datatype long;
  location sub resource datatype string;
  number sub resource datatype long;
  street sub resource datatype string;
  city sub resource datatype string;

  person-with-address sub role;
  address-of-person sub role;
  address-with-street sub role;
  street-of-address sub role;
  person-with-phone sub role;
  phone-of-person sub role;

  address-has-street sub relation relates street-of-address relates address-with-street;
  has-address sub relation relates address-of-person relates person-with-address;
  has-phone sub relation relates phone-of-person relates person-with-phone;


