java_library(
    name = "RoaringBitmap",
    exports = [
        "//external:jar/org/roaringbitmap/RoaringBitmap"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


