define

inferMature sub rule
when {
$z isa cancer;
  $a isa stem-loop;
  (disease: $z, affected: $a);
  $b isa mature;
  (precursor: $a, matured: $b);
}
then {
  (disease: $z, affected: $b) isa interaction;
};

inferCancerDrug sub rule
when {
  (disease: $c, affected: $b);
  (targeting-mirna: $b, targeted-gene: $g);
  (influenced: $g, chemical: $d);
}
then {
  (target: $c, therapy: $d) isa treatment;
};

referencedTreatments sub rule
when {
  $cancer isa cancer;
  $sl isa stem-loop;
  (disease: $cancer, affected: $sl) isa interaction  has degree >= 4;
  $m isa mature;
  (precursor: $sl, matured: $m) isa mirna-precursor;
  $gene isa gene;
  (targeting-mirna: $m, targeted-gene: $gene) isa gene-target has degree >= 4;
  (influenced: $gene, chemical: $drug) isa action; $drug isa drug;
}
then {
  (target: $cancer, therapy: $drug) isa referenced-treatment;
};
