define

"article" sub entity
    plays publication
    has pmid
    has title
    has abstract;

"mirna" sub entity
    is-abstract
    plays sequence-in-genome
    plays affected
    plays targeting-mirna
    has accession-number
    has sequence
    has mirID;

"mature" sub mirna
    plays matured;

"stem-loop" sub mirna
    plays precursor;

"cancer" sub entity
    plays disease
    plays target
    has name;

"location" sub entity
    plays position
    has chromosome
    has species
    has starting-position
    has end-position
    has strand;

"gene" sub entity
    plays targeted-gene
    plays affected
    plays influenced
    has gene-symbol
    has entrez-gene-id;

"drug" sub entity
    has drug-name
    plays therapy
    plays chemical;

"action" sub relationship
    has action-type
    relates chemical
    relates influenced;
"influenced" sub role;
"chemical" sub role;


"interaction" sub relationship
    relates disease
    relates affected
    plays fact
    has degree;
"disease" sub role;
"affected" sub role;

"coordinate" sub relationship
    relates sequence-in-genome
    relates position;
"sequence-in-genome" sub role;
"position" sub role;

"reference" sub relationship
    relates fact
    relates publication;
"fact" sub role;
"publication" sub role;

"mirna-precursor" sub relationship
    relates precursor
    relates matured;
"precursor" sub role;
"matured" sub role;

"gene-target" sub relationship
    relates targeted-gene
    relates targeting-mirna
    plays fact
    has degree;
"targeted-gene" sub role;
"targeting-mirna" sub role;

"treatment" sub relationship
    relates target
    relates therapy;

"referenced-treatment" sub relationship
  relates target
  relates therapy;

"target" sub role;
"therapy" sub role;

"starting-position" sub attribute
    datatype string;
"end-position" sub attribute
    datatype string;
"sequence" sub attribute
    datatype string;

"species" sub attribute
    datatype string;

"chromosome" sub attribute
    datatype string;

"strand" sub attribute
    datatype string;

"accession-number" sub attribute
    datatype string;

"pmid" sub attribute
    datatype string;

"title" sub attribute
    datatype string;

"abstract" sub attribute
    datatype string;

"abstract" sub attribute
    datatype string;

"mirID" sub attribute
    datatype string;

"name" sub attribute
    datatype string;

"gene-symbol" sub attribute
    datatype string;

"entrez-gene-id" sub attribute
    datatype string;

"action-type" sub attribute
  datatype string;

"drug-name" sub attribute
    datatype string;

"degree" sub attribute
  datatype long;
