java_library(
    name = "reflections",
    exports = [
        "//external:jar/org/reflections/reflections"
    ],
    runtime_deps = [
        "//dependencies/maven/com/google/guava:guava",
        "//dependencies/maven/dom4j:dom4j",
        "//dependencies/maven/org/javassist:javassist"
    ],
    visibility = [
        "//dependencies/maven:__subpackages__"
    ]
)


