java_library(
    name = "jersey-guava",
    exports = [
        "//external:jar/org/glassfish/jersey/bundles/repackaged/jersey-guava"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


