java_library(
    name = "jackson_dataformat_yaml",
    exports = [
        "//external:jar/com/fasterxml/jackson/dataformat/jackson_dataformat_yaml"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/fasterxml/jackson/core:jackson_core",
        "//dependencies/maven/artifacts/org/yaml:snakeyaml"
    ],
    visibility = [
        "//visibility:public"
    ]
)


