java_library(
    name = "jackson-dataformat-yaml",
    exports = [
        "//external:jar/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/fasterxml/jackson/core:jackson-core",
        "//dependencies/maven/artifacts/org/yaml:snakeyaml"
    ],
    visibility = [
        "//visibility:public"
    ]
)


