java_test(
    name = "aggregate-query-impl-test",
    test_class = "grakn.core.graql.query.AggregateQueryTest",
    srcs = ["AggregateQueryTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//server"],
    size = "small"
)

java_test(
    name = "concept-map-test",
    test_class = "grakn.core.graql.query.ConceptMapTest",
    srcs = ["ConceptMapTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/org/mockito:mockito-core",
        "//server"],
    size = "small"
)

java_test(
    name = "delete-query-impl-test",
    test_class = "grakn.core.graql.query.DeleteQueryTest",
    srcs = ["DeleteQueryTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//server"],
    size = "small"
)

java_test(
    name = "insert-query-impl-test",
    test_class = "grakn.core.graql.query.InsertQueryImplTest",
    srcs = ["InsertQueryTest.java"],
    deps = [
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/org/mockito:mockito-core",
        "//server"],
    size = "small"
)