java_library(
    name = "javax-annotation-api",
    exports = [
        "//external:jar/javax/annotation/javax-annotation-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


