java_library(
    name = "javaruntype",
    exports = [
        "//external:jar/org/javaruntype/javaruntype"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/org/antlr:antlr-runtime"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


