java_test(
    name = "label-fragment-set-test",
    srcs = ["LabelFragmentSetTest.java"],
    test_class = "ai.grakn.graql.internal.gremlin.sets.LabelFragmentSetTest",
    deps = [
        "//grakn-graql",
        "//dependencies/maven/artifacts/org/apache/tinkerpop:gremlin-core",
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/org/mockito:mockito-core"
        ],
    size = "small"
)


java_test(
    name = "roleplayer-fragment-set-test",
    test_class = "ai.grakn.graql.internal.gremlin.sets.RolePlayerFragmentSetTest",
    srcs = ["RolePlayerFragmentSetTest.java"],
    deps = [
        "//dependencies/maven/artifacts/org/hamcrest:hamcrest-library",
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/org/mockito:mockito-core",
        "//grakn-graql"],
    size = "small"
)